#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-ZHULI-POOL
title=从ZHULI-POOL的角度分析市场(日内)
category=analyze

enable_bkzj_df=1

start=09:16:00

# 预先计算一下数据
# 这里选择了5日的主力 而不是3日的主力数据
if1=get_candi:BKZJ_ZHULI_2
if2=get_candi:bkzj.top
if3=strict_check_bkzj_file

try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 market-pull=01 by-bkzj=02 by-cdadan=04 ZHULI-POOL=07
no=91107

functions=analyze_by_bkzj

qianyan=从ZHULI-POOL的角度分析市场(日内)#\
(显然 市场中的主力题材池的表现 会直接影响资金是老题材 还是新题材 还是直接不做)#\
\n\
\n\
\n\
手工直接打开: sh/open/open_xls_list.sh candi:BKZJ_ZHULI_2#\
\n\
\n\
\n\
\n\

eva_quan={00:00:00,23:59:59}get_candi:BKZJ_ZHULI_2*append_xls,\
zhushi:显示一下基础的ZHULI-POOL数据,\
print_fenge,\
get_candi:BKZJ_ZHULI_2*stage:merge_left=0:zijin,\
zhushi:显示cdadan的实时数据 如果数据缺失 那么直接认为题材很弱,\
get_candi:BKZJ_ZHULI_2*stage:merge_left=0:zijin*\
stage:sort=sum2:zijin_sum:len=5[09:32:01,],\
zhushi:显示的BKZJ_ZHULI实时zijin-sum数据 如果数据缺失 那么直接认为题材很弱


# 更多内容 TODO:

