#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-inner-market-overall
title=关于分析实时/日内市场的一般论述
category=analyze

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 overall=00 inner-overall=01
no=91101

qianyan=本文给一下全市场实时分析数据的一般论述#\
\n\
对实时市场分析来说 有以下几个是最核心需要关注分析的: #\
如果市场处于特殊阶段(比如大波动 比如下跌期 比如市场超级低开也算) 是否脱离了特殊期#\
资金是延续还是切换(指在题材间的流动 是继续在旧题材还是去了新题材)\
(意味着需要关注前日的核心逻辑题材)#\
做多资金和做空资金是否分出了胜负#\
国家队主力是否在明显控盘 控盘意图是#\
\n\
------------ 上面是大局观 下面是细节 #\
涨停板 跌停板是否处于正常的区间#\
正常的题材竞争及其细节(锚定)->要求市场风险可控#\
大票小票的风格->要求市场风险可控#\
\n\
\n\
\n\
相关的知识点: #\
行情的定义: @engine/enum/hq_enum.py #\
\n\
\n\
\n\
没有明显思路时 无脑: #\
bkzj生成pool: sh/tips/run_template.sh bkzj_to_pool_none_silu #\
realtime-pool: sh/tips/run_template.sh realtime_pool_silu_none #\
查看市场实时数据: sh/template/run_template.sh market#\
随机打开index: python realtime/observe/index.py get#\
\n\
\n\
\n\
相关的模板: 



