#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-db31
title=从db31的视角来分析市场的状态(日内)
category=analyze

start=09:16:00

# 允许在计算计算结束后 加入到chain
try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 03=by-upstp 05=by-db31
no=91105

qianyan=从实时的db31数据来分析市场的状态(日内)#\
\n\
db31的几个作用:#\
1 判断超短票(一般是小票)是否强势 可以叠加市场的红盘数据进行对比#\
2 用作锚定+筛选版块池 #\
\n\
\n\
\n\
直接根据前排数据计算版块池: sh/eva/cli.sh db31 up7 --back pool_and_top#\
sh/eva/cli.sh db31 upstp --back pool_and_top#\
\n\
\n\
\n\
相关的模板:

eva_quan={00:00:00,23:59:59}db31->top.hist[09:23:00,],\
market:emotion.hist4[09:20:00,],\
db31->trend3.hist[09:22:00,],\
print_fenge,\
if db31->upstp*filter:max=15 then db31->upstp,back=append_xls2[09:23:00,],\
zhushi:直接计算涨停板的锚定数据

flush_quan={00:00:00,23:59:59}if db31->upstp*filter:min=3 \
then redu::db31->trend3[09:23:00,],\
zhushi:最基础的trend计算,\
if get_candi:redu*filter:max=8 and \
db31->upstp*filter:min=12 then redu::db31->top[09:24:00,],\
zhushi:本计算比较耗时 因此触发的条件比较苛刻,\
if get_candi:redu*filter:max=12 and db31->upstp*filter:min=3:max=15 \
then redu->top[09:24:00,]


