#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-market-by-db31
title=从db31股票池视角来分析市场的状态(日间)
category=analyze

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 50开头是by-codes类型 by-amount-codes=51 by-db31=52
no=91152

qianyan=从db31股票池视角来分析市场的状态(日间)#\
\n\
从db31股票池能够窥探到的市场状态包括:#\
1 db31的高度数据能够判断出超短资金当前偏向于高位还是低位#\
2 找到一个合适的db31子股票池数据用于分析题材逻辑(这个没有想好怎么做 有点复杂.. TODO:) #\
\n\
\n\
\n\
\n\
相关的模板: #\
从股票池分析市场的一般论述: \
sh/tips/run_template.sh analyze_cross_market_by_codes


############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}db31->trend3.days,\
db31->pos_high.days4,\
db31->shape_fenbu:test_pos_high,\
db31->shape_fenbu:test_trends_good,\
db31->shape_fenbu:amount.days4,\
zhushi:可以观察到db31中amount风格的变化


