#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-risk(market)-by-iggzj
title=从实时的ggzj(个股资金)数据来分析市场的风险
category=analyze

start=09:30:01
enable_bkzj_df=1
if=exist_ggzj

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 31=risk-by-iggzj
no=91131

qianyan=从实时的ggzj(个股资金)数据来分析市场的风险#\
\n\

eva_quan={00:00:00,23:59:59}market:emotion.hist4[09:20:00,],\
zhushi:感知一下基础的市场强度,\
xls:fenshi->stage:eva_detail:eva_type=ggzj*to_sum:col=zhuli.hist[09:35:00,]

eva_zao1={09:32:00,09:34:30}xls:iggzj.atzao1*eva:outxt:out=up->size:len=4,\
xls:iggzj.atzao1*eva:outxt:out=down->size:len=4,\
xls:fenshi->eva_detail:eva_type=ggzj.atzao1*to_sum:col=zhuli.cross5,\
xls:fenshi*eva.atzao1:ggzj:min_zhuli=0.3->eva_size:eva_type=rup.atzao1:min=2.5.days8

eva_zao2={09:36:00,09:39:00}xls:iggzj.atzao2*eva:outxt:out=up->size:len=4,\
xls:iggzj.atzao2*eva:outxt:out=down->size:len=4,\
xls:fenshi->eva_detail:eva_type=ggzj.atzao2*to_sum:col=zhuli.cross5,\
xls:fenshi*eva.atzao2:ggzj:min_zhuli=0.3->eva_size:eva_type=rup.atzao2:min=2.5.days8

eva_zao={09:41:00,09:44:00}xls:iggzj.atzao*eva:outxt:out=up->size:len=4,\
xls:iggzj.atzao*eva:outxt:out=down->size:len=4,\
xls:fenshi->eva_detail:eva_type=ggzj.atzao*to_sum:col=zhuli.cross5,\
xls:fenshi*eva.atzao:ggzj:min_zhuli=0.3->eva_size:eva_type=rup.atzao:min=2.5.days8
