#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-market-by-dlb2
title=从dlb2股票池视角来分析市场的状态(日内)
category=analyze

start=09:16:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 25开头是by-codes类型 by-dlb2=27
no=91127

# 参考@xx_xls_trend_fast.tips.properties

# 我可能自定义了一些dlb*xxx的子股票池 此时应该尽可能的找出来这些自定义数据 TODO:

qianyan=从dlb2股票池视角来分析市场的状态(日内)#\
\n\
首先是dlb2本身的走势数据,然后是用作锚定(可能) 然后还可能直接用作买点股票池 可谓一鱼三吃#\
本身的数据:#\
trend(hist) #\
涨停板 #\
跌停板 #\
opp/pull #\
rup3/rup5/rup7数据 #\
\n\
\n\
和db31的比较:#\
从等级上来说 dlb2和db31差不多 都是受资金关注度较高的股票池#\
但相比db31 dlb2的图形的延续性更好 振幅更宽 涨的话很可能连续涨 跌也是连续跌#\
\n\
\n\
\n\
一些命令: #\
更详细的trend数据: sh/tips/run_xls_template.sh dlb2 qp_trend_rank_alot #\
对头部数据进行分析: sh/codes/analyze_pool.sh dlb2*eva:btw:min=4:limit=20 #\
直接打开头部数据: sh/eva/cli.sh dlb2*eva:btw:min=2:limit=20 btw --open 1#\
\n\
\n\
\n\
\n\
\n\
相关的模板: #\
日间分析: sh/tips/run_template.sh analyze_cross_market_by_dlb2

eva_quan={00:00:00,23:59:59}dlb2->trend3.days4,\
dlb2->trend3.hist[09:25:00,],\
dlb2->btwed,\
dlb2->if2:rup3_alot.if,\
dlb2->if2:rup5_alot.if,\
dlb2->upstp,back=append_xls2,\
zhushi:涨停板分析,\
dlb2->opp_fenbu[09:31:00,09:45:00],\
if dlb2==rup5_alot.if then dlb2*eva:rup:min=3:limit=25->stage:trends_good,\
zhushi:如果有一定的强度 那么对前排数据做一下trends-good切割分析

flush_quan={00:00:00,23:59:59}stocks:dlb2_relative->trend3,\
stocks:dlb2_relative->trend3.hist[09:33:00,09:49:00]

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}

############################### 早盘时区
tips_zao={09:30:01,09:45:00}早盘时区:

eva_zao={09:30:01,09:45:00}dlb2->co:sort=abs:limit=20:asc=0*btw,\
zhushi:按照开盘的co-pchg进行绝对值排序

############################### 早盘时区
tips_zao2={09:38:01,09:45:00}早盘时区2(38分后):

eva_zao2={09:38:01,09:48:00}dlb2->npull:min=1.5:mode=m7,\
if dlb2->npull:min=1.5:mode=m7*alot then dlb2->npull:min=3.3:mode=m7


############################### 准盘中时区
tips_zpan={09:48:01,10:20:00}准盘中时区(48分后):

eva_zpan={09:48:01,10:20:00}dlb2->npull:min=1.5:mode=m7,\
dlb2->npull:min=1.5:mode=m10,\
dlb2->npull:min=1.5:mode=qt2

