#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-market-by-codes
title=从市场级别的股票池视角来分析市场的状态(日间)
category=analyze

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 50开头是by-codes类型 
no=91150

qianyan=从市场级别的股票池视角来分析市场的状态(日间)#\
\n\
在之前我的图形能力不够的时候 是做不到从市场级别的股票池\
来分析市场的 但现在我具备了这个能力 而显然 从股票池切入\
市场分析是必然正确的选择(因为市场的细节就隐藏在这些股票池中)#\
\n\
有以下股票池可以进行切入分析:#\
从头部amount入手 包括amount+trends-good,amount+trends-bad #\
从超短股票池入手 包括最强走势的超短 中位的超短 低位的超短#\
\n\
\n\
\n\
相关的模板: #\
从amounts数据入手分析: \
sh/tips/run_template.sh analyze_cross_market_by_amount_codes#\
从db31入手分析: \
sh/tips/run_template.sh analyze_cross_market_by_db31#\
从dlb2入手分析: \
sh/tips/run_template.sh analyze_cross_market_by_dlb2#\
(dlb2实现了日内版本): sh/tips/run_template.sh analyze_market_by_dlb2



