#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-ggzj2
title=从实时的ggzj(个股资金)数据来分析市场的状态(日内)(实现的第2个版本)
category=analyze

start=09:30:01
enable_bkzj_df=0
if=exist_ggzj

# 允许在计算计算结束后 加入到chain
try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 03=by-upstp 11=by-ggzj 112=by-ggzj(第二个实现版本)
no=911112

qianyan=从实时的ggzj(个股资金)数据来分析市场的状态(日内)#\
(第一个实现版本觉得效果不佳 再实现一个版本) #\
本实现中 注重根据ggzj的数据来判定市场的安全性与否 其次 才是用做锚定#\
\n\
\n\
数据很强的话 可以手工刷新: \
sh/flush_cli.sh redu::eva:ggzj2 eva_size:eva_type=rup3 --mode zao2#\
\n\
\n\
\n\
\n\
相关模板: #\
另一个版本: sh/tips/run_template.sh analyze_market_by_ggzj

eva_quan={00:00:00,23:59:59}market:emotion.hist4[09:20:00,],\
zhushi:感知一下基础的市场强度,\
print_fenge,\
xls:fenshi->ggzj:limit=40:asc=0*co,\
xls:fenshi->ggzj:min_zhuli=0.7:limit=20,back=append_xls2,\
zhushi:分析一下ggzj中的前排主力数据,\
if xls:fenshi->ggzj:limit=60*rup3*alot*filter:min=25 then \
xls:fenshi->ggzj:limit=60*rup3,back=append_xls2,\
zhushi:如果ggzj+rup3数据很好 那么进行分析,\
if xls:ggzj->ggzj2*filter:min=20 then \
xls:ggzj->ggzj2*btw:limit=20,back=append_xls2,\
zhushi:如果xls:ggzj的数据 同时在实时的ggzj数据中 那么进行分析



eva_zao={09:30:01,09:50:00}xls:fenshi*eva.atzao2:ggzj:min_zhuli=\
0.3->eva_size:eva_type=rup.atzao2:min=2.5.days8[09:35:00,09:40:00],\
zhushi:根据min_zhuli=0.3和rup3数据来判断市场强度,\
xls:fenshi*eva.atzao:ggzj:min_zhuli=0.5->eva_size:\
eva_type=rup.atzao:min=2.5.days8[09:41:00,09:45:00],\
zhushi:根据min_zhuli=0.5和rup3数据来判断市场强度
