#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-bkzj--overall
title=汇总一下对pool/xls/code的bkzj命令操作(前提是已经有了目标pool/xls/code)


# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 9代表bkzj 前3位是确定的
# 第4位和第5位数字组合代表了计算的类型 overall=00 
no=91900

qianyan=本文定位是仅做一下操作命令的汇总 #\
\n\
对单个pool的bkzj分析: sh/pool/analyze_bkzj.sh xx(支持盘前和实盘)#\
对单个xls/code的bkzj分析: sh/xls/analyze_bkzj.sh xx(支持盘前和实盘)#\
\n\
\n\
\n\
一些相关的其它模板: 



