#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-overall
title=分析一下题材的状态(日间和日内)
category=analyze

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 
no=91499

qianyan=本文尝试搞定掌控版块(已经指定了具体的版块)#\
\n\
\n\
\n\
当前还没有想好怎么实现 TODO: #\
\n\
\n\
相关的模板: #\
分析指定题材的日间/盘前状态: \
sh/tips/run_xls_template.sh xx analyze_xls_cross_state #\
分析指定题材的日间资金流动: \
sh/tips/run_xls_template.sh xx analyze_xls_cross_zijin



