#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-upstp
title=从实时的涨停板数据来分析市场的状态(日内)
category=analyze

enable_bkzj_df=0
start=09:16:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 03=by-upstp
no=91103

qianyan=从实时的涨停板数据来分析市场的状态(日内)#\
\n\
涨停板的几个作用:#\
涨停板(封板)数量能最直接的判断市场做多情绪 毕竟10% #\
涨停板的锚定作用: 反直觉的是 涨停板较少的时候 锚定作用越好 因为太多反而没有稀缺性 #\
和市场的红盘数据一齐看 能更准确的判断市场的整体情绪 #\
\n\
\n\
\n\
手工计算涨停板日间对比: python realtime/stage/cli.py get xls:fenshi upstp.cross #\
\n\
涨停风偏判定 #\
市值100: python realtime/stage/cli.py get shizhi100 days_upstp #\
市值200: python realtime/stage/cli.py get shizhi200 days_upstp #\
\n\
\n\
\n\
相关的模板: 

eva_quan={00:00:00,23:59:59}xls:fenshi->upstp.hist[09:24:00,],\
market:emotion.hist4[09:20:00,],\
print_fenge,\
if xls:fenshi*eva:upstp*filter:min=8 then \
xls:fenshi*eva:upstp->shape_fenbu:amount[09:24:00,],\
zhushi:做涨停板的amount风格分析,\
if xls:fenshi->upstp*filter:max=25 then \
xls:fenshi->upstp,back=append_xls2[09:24:00,],\
zhushi:对涨停板做分析 如果是小票风格 那么可以进一步从db31 日内首板来分析市场,\
if exist_bkzj then get_candi:bkzj.zhuli:limit=20[09:30:01,],\
if exist_bkzj then \
get_candi:bkzj.zhuli:limit=25*stage:sort=sum:zijin_sum:len=4[09:30:01,],\
zhushi:bkzj主力前排+几日的zijin-sum数据 丢失的数据视作新轮动的版块

flush_quan={00:00:00,23:59:59}if xls:fenshi->upstp*filter:min=12 then \
redu->stage:days_upstp[09:24:00,09:45:00],\
zhushi:市场涨停板>12的时候 计算redu+days-upstp的数据,\
if xls:fenshi->upstp*filter:min=18 then \
redu->upstp[09:45:01,]


############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: #\
竞价时区只能关注那些有辨识度的涨停板 比如:#\
超短的: sh/eva/cli.sh db31 upstp --back append_xls2 #\
大票的: sh/eva/cli.sh shizhi:min=400 upstp --back append_xls2

eva_jj={09:16:00,09:25:00}db31->if2:upstp,\
shizhi:min=400->if2:upstp


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区: #\
开盘时区只能关注那些有辨识度的涨停板 比如:#\
超短的: sh/eva/cli.sh db31 upstp --back append_xls2 #\
大票的: sh/eva/cli.sh shizhi:min=400 upstp --back append_xls2

eva_open={09:25:00,09:30:00}db31->if2:upstp,\
shizhi:min=400->if2:upstp,\
xls:fenshi->upstp.cross

############################### 早盘时区
tips_zao={09:30:01,09:45:00}早盘时区: #\
市值100的涨停板>2返回: $check_if(context,"shizhi100->upstp*filter:min=3") \
可以手工打开: sh/eva/cli.sh shizhi100 upstp --open 1 --back append_xls2#\
市值200的涨停板>2返回: $check_if(context,"shizhi200->upstp*filter:min=3") \
可以手工打开: sh/eva/cli.sh shizhi200 upstp --open 1 --back append_xls2#\
市值>500的涨停板>2返回: $check_if(context,"shizhi:min=500->upstp") \
可以手工打开: sh/eva/cli.sh shizhi:min=500 upstp --open 1 --back append_xls2

eva_zao={09:30:01,09:45:00}

############################### 早盘时区
tips_zao2={09:38:01,09:45:00}早盘时区2(38分后):

eva_zao2={09:38:01,09:48:00}


############################### 准盘中时区
tips_zpan={09:48:01,10:20:00}准盘中时区(48分后):

eva_zpan={09:48:01,10:20:00}


