#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-market-by-bkzj
title=从bkzj视角来分析市场的状态(日间)
category=analyze

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 by-bkzj=49 50开头是by-codes类型 by-amount-codes=51 by-db31=52
no=91149

qianyan=从bkzj视角来分析市场的状态(日间)#\
\n\
主要就是从市场的bkzj.cdadan数据来进行分析 #\
\n\
\n\
\n\
\n\
相关的模板: #\
从股票池分析市场的一般论述: \
sh/tips/run_template.sh analyze_cross_market_by_codes#\
\n\
\n\
相关的template数据:#\
open engine/observe/plan/template/xx_pool_bkzj.template.properties

# BKZJ_SUM_ABS_1版块池的内容补充一下 TODO:

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}get_candi:bkzj.cdadan:limit=22*\
stage:merge_left=0:sort=sum3:zijin_sum:can_has_empty=1,\
zhushi:给出大单数据的zijin-sum,\
get_candi:bkzj.czhuli:limit=22*stage:merge_left=0:sort=sum:zijin_sum:can_has_empty=1,\
zhushi:给出前排主力数据的zijin-sum,\
get_candi:BKZJ_ZHULI_2,\
zhushi:按照5日的zijin-sum数据进行挖掘的主线题材版块池 如果是轮动行情 \
那么这个数据不一定准,\
get_candi:BKZJ_HOT_3DAYS_1,\
zhushi:最近3日的主力资金流入数据最多的题材池


