#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-realtime-top
title=从实时的市场前排数据对市场进行暴力分析 适用于偏弱的行情
category=analyze

# 特定用于一些偏弱的/明显混沌的交易日通过最简单的实时前排(btw前排)的数据来进行市场分析
# 比如适合09-02这种市场开盘低开很多的交易日/也适合轮动行情交易日

start=09:19:01
enable_bkzj_df=0

# 允许在计算计算结束后 加入到chain
try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 03=by-upstp 11=by-ggzj 15=by-realtime-top
no=91115

qianyan=从实时的市场前排数据(包括涨停板 btw和ggzj前排)对市场进行暴力分析 \
适用于偏弱的行情 #\
(简单+暴力的数据分析 尽可能让事情变得简单) #\
(更加适合偏弱的/轮动的/弱混沌的行情 但震荡 强势行情也可以用) #\
\n\
\n\
注意1: 本模板在实际的计算中会使用10cm进行计算 如果要关注20cm 30cm 需要走其他模板 FIXME:#\
注意2: 本模板相当的计算依赖于ggzj API 需要确保对应的数据 #\
\n\
\n\
相关模板: #\
从ggzj API的视角分析: sh/tips/run_template.sh analyze_market_by_ggzj2 #\
涨停板视角分析: sh/tips/run_template.sh analyze_market_by_upstp

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区:

# 竞价部分的实现还需要优化  TODO:
eva_jj={09:16:00,09:25:00}if xls:fenshi->upstp*filter:max=25 then \
xls:fenshi->upstp,back=append_xls2,\
if shizhi:min=300->btw:min=4*filter:max=25 then \
shizhi:min=300->btw:min=4,back=append_xls2,\
if shizhi:max=300->btw:min=7*cc:not:xls:ggzj*filter:max=25 then \
shizhi:max=300->btw:min=7*cc:not:xls:ggzj,back=append_xls2

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}if xls:fenshi->upstp*filter:max=25 then \
xls:fenshi->upstp,back=append_xls2,\
if 30cm->btw:min=12 then 30cm->btw:min=12,back=append_xls2,\
if shizhi:max=300->btw:min=7*cc:not:xls:ggzj*filter:min=5:max=25 then \
shizhi:max=300->btw:min=7*cc:not:xls:ggzj,back=append_xls2,\
zhushi:市值小于300+非前日xls:ggzj数据+btw>7的票 还是有一定的价值的,\
if xls:fenshi->upstp*filter:min=13 then break,\
zhushi:如果涨停板很多 那么直接break,\
if xls:fenshi*eva:upstp*filter:max=10 and \
xls:fenshi->btw:min=7*cc:10cm*filter:max=25 then \
xls:fenshi->btw:min=7*cc:10cm,back=append_xls2,\
zhushi:对btw>7的分析 不过这里的前置条件较多 主要觉得开盘时区的btw7不准,\
if shizhi:min=300->btw:min=4*filter:min=5:max=25 then \
shizhi:min=300->btw:min=4,back=append_xls2,\
if shizhi:max=300->btw:min=7*cc:not:BK1633.bf*filter:min=5:max=25 then \
shizhi:max=300->btw:min=7*cc:not:BK1633.bf,back=append_xls2

############################### 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区

eva_zao1={09:30:01,09:45:00}if xls:fenshi->upstp*filter:min=50 then break,\
zhushi:如果实时涨停板直接爆表>50 那么不适合本tips计算 直接break,\
if xls:fenshi->upstp*filter:max=25 then \
xls:fenshi->upstp,back=append_xls2,\
zhushi:基础的涨停板分析,\
if exist_ggzj and xls:fenshi->upstp*ggzj*cc:shizhi:max=200*filter:min=4:max=35 then \
xls:fenshi->upstp*ggzj*cc:shizhi:max=200,back=append_xls2,\
zhushi:过滤出涨停板中的ggzj+shizhi<200的数据进行分析,\
if xls:fenshi*10cm->btw:min=7*rdown:max=2.5*cc:not:xls:ggzj*filter:max=35 then \
xls:fenshi*10cm->btw:min=7*rdown:max=2.5*cc:not:xls:ggzj,back=append_xls2,\
zhushi:10cm+非xls:ggzj数据+btw>7的票(一般都是新轮动个股) 还是有一定的价值的 暴力分析,\
if xls:fenshi*10cm->btw:min=7*rdown:max=2.5*filter:min=65 then break,\
zhushi:如果实时的up7数据爆炸 此时不适合根据头部数据进行分析 直接break,\
if exist_ggzj and xls:fenshi*10cm->btw:min=7:limit=50*ggzj*filter:min=12:max=45 then \
xls:fenshi*10cm->btw:min=7:limit=50*ggzj,back=append_xls2,\
zhushi:实时的btw>7+ggzj的数据量可控(不限制市值) 那么直接暴力分析,\
print_fenge,\
if exist_ggzj and xls:fenshi*10cm->ggzj:limit=60:min_zhuli=0*\
cc:shizhi:min=150*rup3*filter:max=40 then \
xls:fenshi*10cm->ggzj:limit=60:min_zhuli=0*cc:shizhi:min=150*rup3,back=append_xls2,\
zhushi:对实时ggzj前60+shizhi>150(非小市值)+rup3的数据进行分析,\
if exist_ggzj and xls:fenshi*10cm->ggzj:min_zhuli=0:limit=60*\
cc:shizhi:max=200*rup5*filter:min=12:max=45 then \
xls:fenshi*10cm->ggzj:min_zhuli=0:limit=60*cc:shizhi:max=200*rup5,back=append_xls2,\
zhushi:对实时ggzj前60+shizhi<200(中小市值)+rup5的数据进行分析


