#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-ggzj
title=从实时的ggzj(个股资金)数据来分析市场的状态(日内)
category=analyze

start=09:30:01
enable_bkzj_df=0
if=exist_ggzj

# 允许在计算计算结束后 加入到chain
try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 03=by-upstp 11=by-ggzj
no=91111

qianyan=从实时的ggzj(个股资金)数据来分析市场的状态(日内)#\
\n\
实时的个股资金API的数据是比较准的 甚至高过涨停板 因此本实现是非常重要和倚重的 #\
\n\
从ggzj API能够挖掘到的信息包括: #\
前排的涨停板数据可以分析市场的大票还是小票风格 #\
占比前排的数据 基本就可以视作确定性最高的数据 再计算一下btw trend数据 就能判定市场的强弱 #\
显然 还有题材池的锚定作用 #\
\n\
\n\
\n\
一些手工计算(正常情况下可以无脑计算的 只不过可能有些耗时被我写到了这里):#\
sh/eva/cli.sh xls:fenshi ggzj*upstp --open 1 --back pool_and_top#\
sh/eva/cli.sh shizhi:min=500 ggzj*rup:min=2:limit=30 --open 1 --back pool_and_top#\
sh/eva/cli.sh xls:fenshi ggzj:limit=15 --open 1 --back pool_and_top#\
\n\
\n\
\n\
相关的模板: #\
另一个版本: sh/tips/run_template.sh analyze_market_by_ggzj2

# xls:fenshi->ggzj:min_zhanbi=5*trend3,\
# zhushi:占比前排的btwed和trend3数据 能大体判断出市场的强弱,\

eva_quan={00:00:00,23:59:59}xls:fenshi->upstp.hist[09:24:00,],\
zhushi:市场的涨停板和红盘数 还是能大致感受市场的强度,\
market:emotion.hist4[09:20:00,],\
print_fenge,\
xls:fenshi->ggzj:min_zhanbi=5:sort=zhanbi:limit=100*btwed,\
zhushi:占比前排的btwed和trend3数据 能大体判断出市场的强弱,\
print_fenge,\
xls:fenshi->if2:eva-ggzj*upstp,\
if xls:fenshi->ggzj*upstp*filter:max=30 then \
xls:fenshi->ggzj*upstp,back=append_xls2,\
zhushi:分析一下ggzj+涨停板数据,\
xls:fenshi->ggzj:min_zhuli=1.1:limit=20,back=append_xls2,\
zhushi:分析一下ggzj中的前排主力数据,\
xls:fenshi->ggzj:min_zhuli=0.5:sort=zhanbi:min_zhanbi=5:limit=30,back=append_xls2,\
zhushi:分析一下ggzj中的前排top30占比数据,\
if exist_bkzj then get_candi:bkzj.zhuli:no_index=1:limit=15,\
print_fenge,\
shizhi:min=500->ggzj:min_zhuli=0.5:limit=25,back=append_xls2,\
zhushi:中大市值+ggzj按照前排主力排序的数据分析


