#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-market-by-dlb2
title=从dlb2股票池视角来分析市场的状态(日间)
category=analyze

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 50开头是by-codes类型 by-db31=52 by-dlb2=53
no=91153

qianyan=从dlb2股票池视角来分析市场的状态(日间)#\
\n\
从dlb2股票池能够窥探到的市场状态包括:#\
1 dlb2的高度数据能够判断出超短资金当前偏向于高位还是低位#\
2 找到一个合适的dlb2子股票池数据用于分析题材逻辑(这个没有想好怎么做 有点复杂.. TODO:) #\
\n\
\n\
和db31的比较:#\
从等级上来说 dlb2和db31差不多 都是受资金关注度较高的股票池#\
但相比db31 dlb2的图形的延续性更好 振幅更宽 涨的话很可能连续涨 跌也是连续跌#\
\n\
\n\
相关的模板: #\
从股票池分析市场的一般论述: \
sh/tips/run_template.sh analyze_cross_market_by_codes#\
通过db31来进行分析: sh/tips/run_template.sh analyze_cross_market_by_db31


############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

# dlb2->pos_high:len=8.days3,\
eva_plan={09:00:00,09:15:00}dlb2->jinji:limit=15,back=append_xls2,\
dlb2->trend3.days,\
dlb2->shape_fenbu:test_pos_high,\
dlb2->trends_good.day4,\
dlb2->shape_fenbu:test_trends_good,\
if dlb2*pc:trends_good4:len=4*filter:min=10:max=35 then \
dlb2*pc:trends_good4:len=4->get_codes,back=append_xls2,\
zhushi:数据合适的话 分析一下dlb2*pc:trends_good4:len=4,\
dlb2->shape_fenbu:amount.days4,\
zhushi:可以观察到dlb2中amount风格的变化,\
if dlb2*amount20*filter:min=10:max=35 then \
dlb2*amount20->get_codes,back=append_xls2,\
zhushi:数据合适的话 分析一下dlb2*amount20



