#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-overall
title=作为分析市场的导航
category=analyze

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 overall=00 
no=91100

qianyan=作为分析市场的导航#\
\n\
\n\
\n\
\n\
相关的模板: #\
日内市场分析的一般论述 ==> sh/tips/run_template.sh analyze_inner_market_overall#\
从市场级别的股票池视角来分析市场(日间状态) ==> \
sh/tips/run_template.sh analyze_cross_market_by_codes#\
从bkzj的视角来分析市场(日间) ==> \
sh/tips/run_template.sh analyze_cross_market_by_bkzj



