#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-trend
title=分析市场的实时走势
category=analyze

enable_bkzj_df=0
start=09:16:00

# 允许在计算计算结束后 加入到chain
try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 02=trend 03=by-upstp
no=91102

qianyan=分析市场的实时走势(日内)#\
\n\
主要包括的数据: #\
红盘家数 #\
涨停板hist #\
跌停板cross #\
小票代表(zhz2000)的数据#\
超短代表的数据 #\
bkzj #\
\n\
\n\
\n\
\n\
\n\
\n\
相关的模板: #\
从涨停板的视角分析市场 sh/tips/run_template.sh analyze_market_by_upstp

eva_quan={00:00:00,23:59:59}market:emotion.hist4[09:23:00,],\
market:amounts.cross7[09:26:00,],\
xls:fenshi->upstp.hist[09:33:00,],\
xls:fenshi->dstp.cross[09:22:00,],\
xls:zhz2000*eva:up2->btwed.hist[09:24:00,],\
xls:hs300->btwed.hist[09:24:00,],\
if db51->upstp*filter:min=5 then db51*eva:up2->btwed.hist[09:24:00,],\
if db102->upstp*filter:min=3 then db102*eva:up2->btwed.hist[09:24:00,],\
get_candi:bkzj.zhuli:limit=20[09:31:00,]

