#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-by-cdadan
title=从bkzj.cdadan的角度分析市场(日内)
category=analyze

enable_bkzj_df=1

start=09:16:00


# 预先计算一下数据
if1=get_candi:BKZJ_SUM_ABS_1
if2=get_candi:bkzj.top
if3=strict_check_bkzj_file

try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 
# 第4位和第5位数字组合代表了计算的类型
# no的说明 market-pull=01 by-bkzj=02 by-cdadan=04
no=91104

functions=analyze_by_bkzj

qianyan=从bkzj.cdadan的角度分析市场(日内)#\
(显然 市场中的核心题材池的表现 会直接影响资金是老题材 还是新题材 还是直接不做)#\
会分别从实时的cdadan 日间的cdadan(2个) 总计3类数据来进行分析#\
\n\
\n\
\n\
手工直接打开: sh/open/open_xls_list.sh bkzj.cdadan:limit=15#\
sh/open/open_xls_list.sh BKZJ_SUM_ABS_1:limit=20#\
\n\
\n\
\n\
\n\

#get_candi:BKZJ_SUM_ABS_1:limit=25*stage:sort=last:\
#merge_left=0:zijin_sum:len=4*stage:zijin[09:32:01,],\

eva_quan={00:00:00,23:59:59}get_candi:bkzj.cdadan,\
zhushi:显示一下基础的cdadan数据,\
get_candi:BKZJ_SUM_ABS_1,\
zhushi:显示一下基础的4日资金-sum数据,\
print_fenge,\
get_candi:bkzj.cdadan:limit=15*stage:merge_left=0:zijin,\
zhushi:显示cdadan的实时数据 如果数据缺失 那么直接认为题材很弱,\
get_candi:BKZJ_SUM_ABS_1:limit=25*stage:zijin[,09:32:00],\
zhushi:显示的BKZJ_SUM实时数据 如果数据缺失 那么直接认为题材很弱,\
get_candi:BKZJ_SUM_ABS_1:limit=25*stage:merge_left=0:zijin*\
stage:sort=sum2:zijin_sum:len=5[09:32:01,],\
zhushi:显示的BKZJ_SUM实时zijin-sum数据 如果数据缺失 那么直接认为题材很弱,\
print_fenge,\
get_candi:bkzj.zhuli:limit=25:min=2[09:31:00,],\
get_candi:bkzj.zhuli:limit=25:min=2*stage:zijin_sum:len=5[09:31:00,],\
zhushi:如果数据有丢失 结合实时主力数据很好 但日间数据丢失 那么认为此时强轮动


# 更多内容 TODO:

