#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-pull
title=作为分析市场的盘中pull
category=analyze

# 还是尽量不要走bkzj API
enable_bkzj_df=0

# 分析市场中的pull数据 TODO:
# 实现参考@sh//hq/market/market_pull_analyze.sh

start=09:38:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 7代表pull
# 第4位和第5位数字组合代表了计算的类型
# no的说明 market-pull=01
no=91701

qianyan=分析市场中的pull数据#\
实现参考@sh//hq/market/market_pull_analyze.sh #\
定位: 比较粗糙的判断是否存在明显的拉升行为(毕竟是全市场的数据) #\
\n\
\n\
\n\
会从以下数据进行分析: #\
1 直接计算pull数据(因为是全市场级别的计算 因此只能大致判断市场是否存在明显的波动) #\
2 市场的涨跌家数变化 #\
3 市场新增涨停板 #\
4 bkzj数据的挖掘 #\
5 热门题材的npull数据 #\
\n\
\n\
\n\
手工打开个大指数: python realtime/observe/index.py get#\
\n\
\n\
如果发现市场拉升爆炸了 那么: \
sh/tips/run_template.sh analyze_market_pull_baozha #\
从bkzj的视角来分析市场的pull: \
sh/tips/run_template.sh analyze_market_pull_by_bkzj 




eva_quan={00:00:00,23:59:59}if exist_t2_file:mode=m7 then \
xls:fenshi->if2:npull:mode=m7:min=2.2*baozha,\
zhushi:判断是否7分钟发生了明显的拉升,\
xls:fenshi->if2:npull:mode=qt:min=2.5*baozha[09:45:00,],\
zhushi:判断是否15分钟发生了明显的拉升,\
xls:fenshi->if2:npull:mode=qt:min=1.3*baozha[09:45:00,],\
zhushi:判断是否15分钟发生了明显的拉升(>1.3),\
market:emotion.hist5,\
if xls:fenshi->new_upstp*filter:min=3 then \
xls:fenshi->new_upstp*filter:max=25,back=append_xls2,\
zhushi:市场新增涨停的个股详情,\
print_fenge,\
if exist_bkzj,\
zhushi:判断是否存在本地bkzj数据 如果不存在 那么下面的计算全部失败,\
if exist_bkzj then get_candi:zhuli.pull:min=2:mode=qt,\
zhushi:如果存在bkzj数据 那么计算一下get_candi:zhuli.pull:min=2,\
if exist_bkzj then get_candi:bkzj.pull:min=1.1:mode=qt,\
zhushi:如果存在bkzj数据 那么计算一下get_candi:zijin.pull:min=1.1


