#
#Fri Feb 14 15:36:12 CST 2025
juben=baodie-hupan
title=暴跌开盘+明显护盘的临盘tips

qianyan=本文给出暴跌开盘+明显主力护盘的相关tips#\
暴跌开盘的定义: 至少跌70个点开盘#\
\n\
\n\
对于暴跌开盘日 一开盘主力80%的情况会护盘 此时有一些极为激进的资金会进场抢筹,\
但从买点的角度 因为瞬时的波动极大 因此我只能把视角尽量缩小 缩小到要么主力个股 \
要么盘前准备好的股票池#\
\n\
\n\
对于市场走势 因为是暴跌开盘 这里只存在些许的抄底机会 不可能预期主力能出多大的力量,\
很大概率只有开盘前20min这一波护盘 后面就没有了,\
因此暴跌+护盘日买点机会是比较少的 这个不要做不切实际的幻想#\
\n\
\n\
偷懒的话 可以直接关机睡觉/补觉了(如果错过一些买点 我也认了 机会很多 不急于某一天)#\
从其它资金的角度来看 想法也是一样的 就看你主力表演 其他资金也会选择关机睡觉的\
(因此很容易出现 时间到了10点后 指数不动了的情况 没人交易了)#\
\n\
本模板也许提供的不是最佳策略 但实盘的时候 想太多反而是累赘 认准某一个策略去执行\
某种程度上就是最佳实践了#\
\n\
走势的角度 可以关注一些市场的护盘表现 因此,#\
1 sh/open/open_xls_list.sh index:hp#\
2 sh/open/open_xls_list.sh index:dp



tips_plan={09:00:00,09:15:00}

tips_jj={09:16:00,09:25:00}


# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

tips_zao1={09:30:01,09:33:00}
