#
#Fri Feb 14 15:36:12 CST 2025
juben=tips
title=汇总一下一些有效的BK列表

# BK0535: https://chat.deepseek.com/a/chat/s/cec241a0-f0bb-4ed0-86c0-c7aafb4094aa

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 tips=99 bk_list=10
no=31010

qianyan=本文汇总一下一些有效的BK列表(可以选做股票池的) #\
\n\
\n\
BK0535:QFII重仓股(750+):合格的境外机构投资者(QFII)大量买入并持有某家A股上市公司的股票 #\
https://chat.deepseek.com/a/chat/s/cec241a0-f0bb-4ed0-86c0-c7aafb4094aa #\
BK1717:题材股(40~60): 每天都会更新 #\
BK1633:昨日高震幅(150~250): 每天都会更新 #\
BK0823:养老金(190+) #\
BK0501:次新股(100+) #\
BK0536:基金重仓(70+) #\
BK0821:MSCI中国(560+) 大阳线日特别适合做买点 #\
BK0568:深成500(500+) #\
\n\
BK1161:英伟达概念(64)


