#
#Fri Feb 14 15:36:12 CST 2025
juben=bkzj-to-pool-none-silu
title=没有明显思路时的一些tips

open_index=bkzj.cdadan:limit=12
enable_bkzj_df=1

if=get_candi:bkzj.top[09:25:00,]

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 1代表tips.properties 2代表bkzj-to-pool(gene) 前3位是确定的
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=71201

qianyan=本文给一下没有明显思路时的一些bkzj相关的tips #\
包括: #\
1 根据bkzj.index头部和尾部数据 大致给一下市场的所有题材的数据 #\
举个例子 bkzj.index>1的数据 如果有50个题材 那么肯定就清楚 这是一个普涨行情
\n\
\n\
\n\
相关的模板: 

################### 最开头的前序eva计算
eva_quan={00:00:00,23:59:59}get_candi:bkzj.cdadan:limit=15*\
stage:merge_left=0:zijin[09:20:00,10:00:00],\
zhushi:bkzj.cdadan的实时数据一定是市场中的重要数据 如果数据缺失 认为对应的题材很弱,\
get_candi:bkzj.cdadan:limit=15*stage:sort=sum:merge_left=0:zijin_sum:len=4[09:33:00,],\
zhushi:给出bkzj.cdadan的zijin-sum数据,\
print_fenge,\
get_candi:bkzj.zhuli:limit=20*stage:sort=sum:zijin_sum:len=4[09:33:00,],\
zhushi:给出实时bkzj.zhuli数据的zijin-sum数据,\
get_candi:bkzj.zhuli:asc=1:limit=20*stage:sort=sum:zijin_sum:len=4[09:33:00,],\
zhushi:给出实时bkzj.zhuli尾部数据的zijin-sum数据 如果这个数据非常差 \
那么说明资金在不断抛售 要注意风险了


############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}get_candi:bkzj.index:asc=0:min=1,\
if get_candi:bkzj.index:asc=0:min=1:limit=100*filter:min=60,\
zhushi:如果bkzj.index>1的数据量超过60 那么可以认为市场普涨

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}get_candi:bkzj.index:asc=0:min=1,\
if get_candi:bkzj.index:asc=0:min=0.8:limit=100*filter:min=60,\
zhushi:如果bkzj.index>1的数据量超过60 那么可以认为市场普涨,\
if get_candi:bkzj.index:asc=0:min=0.5:limit=120*filter:min=80,\
zhushi:如果bkzj.index>0.5的数据量超过80 那么可以认为市场普涨,\
get_candi:bkzj.index:asc=1:max=-0.8,\
zhushi:查看bkzj.index<-1的数据 因为API的问题 这个数据可能没那么准


############################### 早盘时区

tips_zao1={09:30:01,09:45:00}早盘时区:

eva_zao1={09:30:01,09:45:00}get_candi:bkzj.index:asc=0:min=1,\
if get_candi:bkzj.index:asc=0:min=0.7:limit=120*filter:min=100,\
zhushi:如果bkzj.index>0.7的数据量超过100 那么可以认为市场普涨 或者切换,\
if get_candi:bkzj.index:asc=0:min=1.2:limit=100*filter:min=60,\
zhushi:如果bkzj.index>1的数据量超过60 那么可以认为市场普涨,\
get_candi:bkzj.zhuli:min=18,\
zhushi:bkzj.zhuli>20的题材 一般认为确定性是比较高的,\
get_candi:bkzj.index:asc=1:max=-0.8,\
zhushi:查看bkzj.index<-1的数据 因为API的问题 这个数据可能没那么准,\
get_candi:bkzj.zhuli:asc=1:max=-25,\
zhushi:bkzj.zhuli<-30的题材 一般认为风险是比较高的



