#
#Fri Feb 14 15:36:12 CST 2025
juben=bkzj-to-pool-overall
title=根据实时的bkzj计算得出一些版块池的一般论述/汇总


# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 1代表tips.properties 2代表bkzj-to-pool(gene) 前3位是确定的
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=71200

qianyan=根据实时的bkzj计算得出一些版块池的一般论述/汇总(全是论述 没有计算) #\
\n\
一般来说 可以根据市场的行情走不同的分支实现 #\
weak行情: sh/hq/weak/bkzj_risk.sh #\
\n\
\n\
\n\
一些相关的其它模板: #\
1 没有明显好的思路/市场行情分支不明朗的时候 可以:\
sh/tips/run_template.sh bkzj_to_pool_none_silu



