#
#Fri Feb 14 15:36:12 CST 2025
juben=buyer-zijin-overall
title=根据市场主流资金的动作来制定买点策略tips

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 2代表define(定义) 1代表tips.properties 0代表资金行为(DefineNode)
# 第4位和第5位数字组合代表了计算的类型 overall=00 
no=21000

qianyan=本文给出根据市场主流资金的动作来制定买点策略tips#\
设计文章见<2026-07-01 状态图思路搞定上盘>#\
也可以: open data/article/20260701_zhuangtaitu-shangpan.txt#\
\n\
为什么选择从行情的角度 而不是资金流动的角度来设计买点策略?因为以震荡\
行情为例 资金依旧可以有不同的流动策略的 因此如果以行情为判断分支 准确度\
是不够的.#\
\n\
资金的具体定义可以:cat engine/enum/zijin_enum.py #\
这里简单列举:#\
1:PUDIE 普跌行情#\
2:BAOTUAN 资金报团在少量个股 对应弱震荡行情#\
3:BAOTUAN2 资金报团在少量题材 对应震荡行情#\
5:JIASU 资金在少量题材中打转 且非常激进 对应震荡行情#\
7:QIEHUAN 资金切换 一般这里黄白线分飞 对应震荡行情#\
8:PUZHANG = 8 普涨行情/资金无脑平铺 买点数量爆炸 #\
\n\
\n\
\n\
注意: 这里把资金的流向用作分支判定 因此需要找到办法/市场中的数据来\
临盘验证资金确实这样流动了(事实上有一定的难度)#\
\n\
\n\
相关的模板:





