#
#Fri Feb 14 15:36:12 CST 2025
juben=buyer-silu-huizong
title=汇总一下当前系统已经发生过的买点思路

functions=buyer_silu

qianyan=本文给出本系统已经发生过的买点思路,因为买点是一个连贯\
的动作 5分钟10分钟前的思路 也是有价值的思路数据 有的时候也能启发\
当前去寻找新的买点思路#\
更何况有一些数据是需要持续跟踪的 比如状态码为qianzai_buyer(潜在买点),\
genzong_chain(跟踪买点链路)的数据#\
因此 汇总系统发生过的买点思路非常的重要#\
\n\
\n\
如果要计算新的买点思路 可以:\
sh/tips/run_template.sh buyer_silu_new#\
\n\
一次性打开所有时间段/历史的买点的策略: sh/silu/generate_buyer.sh 


jcals_all={10:00:00,23:59:59}print_silu_recorder_info($day\
,"00:00:00","15:00:00")[10:00:00,]

tips_plan={09:00:00,09:15:00}

#################################### 竞价时区
tips_jj={09:16:00,09:25:00}

jcals_jj={09:16:00,09:25:00}print_silu_recorder_info($day\
,"00:00:00","09:25:00")[09:15:00,09:25:00]

#################################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

jcals_open={09:25:00,09:30:00}print_silu_recorder_info($day\
,"00:00:00","09:25:00")[09:25:00,09:30:00],\
print_silu_recorder_info($day,"09:25:01","09:30:00")[09:25:00,09:30:00]


#################################### 早盘时区
tips_zao1={09:30:01,09:45:00}

jcals_zao1={09:30:01,09:45:00}print_silu_recorder_info($day\
,"00:00:00","09:25:00")[09:30:01,09:45:00],\
print_silu_recorder_info($day,"09:25:01","09:30:00")[09:30:01,09:45:00],\
print_silu_recorder_info($day,"09:30:01","09:45:00")[09:30:01,09:45:00]

#################################### 早盘时区2
jcals_zao2={09:45:01,10:00:00}print_silu_recorder_info($day\
,"00:00:00","09:30:00")[09:45:01,10:00:00],\
print_silu_recorder_info($day,"09:30:01","09:45:00")[09:45:01,10:00:00],\
print_silu_recorder_info($day,"09:45:01","10:00:00")[09:45:01,10:00:00]





