juben=buyer-difficulty-overall
title=关于买点难度的一般论述

# 关于每天买点难度的论述	TODO:

# 其实从买点的链路思考就知道 每天的难度难在不同的环节
# 普涨的交易日买点数量爆炸 非常考验图形的准度
# 普跌日考验的是择时 以及能不能在非常有限的操作窗口内找到可以操作的标的

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 5代表论述
# 第4位和第5位数字组合代表了计算的类型 diffculty=04
no=81504

qianyan=本文给出买点难度的一般论述#\
\n\
买点难度分析一般可以从买点的chain链路来分析,但如果真的就这么分析 \
就会错失另外2个重要的要素: 当日买点数量的预估 市场行情#\
下面进行更多论述#\
\n\
显然 2个典型的买点链路: 市场->题材池->题材->切片买点 市场->切片池->切片->买点 \
各有各的难度 也就是每个链路部分都有难度#\
但其实这只是微观层面的难度 而宏观层面 稍微思考 就知道不同行情时有不同的难度: #\
普涨行情: #\
面对买点数量爆炸时 心态能不能稳住 看到某个题材rup3数据超过50的时候能不能不被吓到 #\
因为买点数量爆炸 极其考验瞬时找到可以操作的有辨识度的图形切片+准度图形能力 #\
\n\
普跌行情: #\
普跌日最考验的是择时 #\
第二考验的是 盘中极短的有限的操作窗口内 能不能找到可以介入的买点标的

# 更多内容?	TODO:
