#
#Fri Feb 14 15:36:12 CST 2025
juben=tips
title=汇总一下一些用做买点的市场级别codes列表

# 用做买点的codes的论述 TODO:

functions=build_pool
before_func=build_pool_codes(context,"list:BK1717,BK1633")[09:15:00,]

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 codes_list=11 buyer-codes-list=12
no=31012

qianyan=本文汇总一下一些用做买点的市场级别codes列表#\
(下面根据不同的行情来做分类) #\
\n\
机构主力主导的类型(适用强势交易日+震荡交易日做投机): #\
BK0535: QFII重仓股(750+) #\
BK0821: MSCI #\
BK0536: 基金重仓(60+) #\
BK1633: 前日高震幅 里面会有30%以上的主力主导的票 因此也归类在这里 #\
\n\
\n\
适合震荡日做的 #\
BK1633: 前日高震幅 因为有部分是前日的潜伏资金的票(30%) 所以最适合做震荡的 #\
db82/db62: 波动没那么大的超短 也是有市场的 #\
BK0535: 外资的投机资金 #\
db81_1*no30200*10cm: 强图形 没什么说的 #\
BK0823: 养老金 #\
xls:iggzj: 纯右侧图形 需要做2次加工计算 比如xls:iggzj+db81 \
xls:iggzj+no30200 xls:iggzj+某个题材#\
db31/db52/BK1717: 适合超短当日较强的情况 #\
\n\
\n\
适合普跌日的/市场极弱的 #\
xls:iggzj/xls:iggzj_pull: 这个没什么说的 提供了一定的确定性 #\
db81_1: 有些资金会去挖掘这种获利盘不多的超短票 #\
db32: 没什么说的 超短的抱团属性 但是风险也偏大

