#
#Fri Feb 14 15:36:12 CST 2025
juben=buyer-and-chain
title=chain实现过的所有buyer算子汇总

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 buyer-and-chain=42
no=31042

qianyan=本文给出chain实现过的所有buyer算子汇总 #\
\n\
[无脑计算(未知任何题材/股票)]: \
sh/chain/gene/run_xls_template.sh xx fast_buyer #\
\n\
[题材] #\
默认实现: sh/chain/gene/run_xls_template.sh xx xls_buyer_default #\
\n\
[切片] #\
数量爆炸(实际实现的一般 最好别用): sh/chain/gene/run_xls_template.sh xx buyer_alot #\
\n\
\n\
更多?

