#
#Fri Feb 14 15:36:12 CST 2025
juben=buyer
title=买点相关的临盘tips(默认)

qianyan=买点是一个宏大的问题 但仔细把买点拆分后 无非以下几个课题:#\
1 风险控制#\
2 择时#\
3 在1和2的基础上 要么做100切片买点 要么做题材买点 要么做切片+逻辑买点#\
\n\
且切记 临盘买点来说 最忌的就是脑子里杂念太多 思绪乱飞#\
\n\
本文下文的内容其实也能看出来 心理层面的稳定对我来说更加的重要



tips_plan={09:00:00,09:15:00}盘前的角度 没太多能做的 盘前更多的\
会做市场分析 大致的择时分析等等



tips_jj={09:16:00,09:25:00}竞价的时候 是博弈刚开始的时间 这个时区\
最忌讳的就是脑子里想的太多 因为竞价的时候不确定性是最高的 最忌讳这个时区\
对行情做太主观的判断 还是要冷静的等待开盘数据(除非竞价有明确的趋势)#\
\n\
也不是完全没东西可以做 可以通过bkzj数据看看有没有好的新题材上来#\
可以看看市场级别切片开的怎么样 实时头部数据的版块池分析#\
也可以看看市场核心题材的前排数据 比如加速数据等#\
\n\
但总的来说 别在竞价时区花费太多精力是没错的#\
\n\
不信邪的 可以随便去翻那些大波动的交易日 那些交易日中 竞价几乎毫无用处



# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}和竞价一样 其实开盘的时候 离收盘还有4个小时 \
这个时候也特别忌讳过于主观的去瞎赌 #\
永远要记住 市场有5000只票 有4个小时的博弈时间 不要心浮气躁 要看准行情先#\
\n\
从实际的角度 可以做以下事情:#\
1 先判断市场的风险 这个必定是第一位的 如果市场风险偏大 那么冷静的等待是最佳策略#\
2 判断市场主要的题材(如果存在的话) 有没有买点机会 毕竟合力题材是最佳选择#\
3 判断市场级别的股票池有没有买点机会 当然市场股票池本身的买点择时也很广 不用急于一时


tips_zao1={09:30:01,09:33:00}
