#
#Fri Feb 14 15:36:12 CST 2025
juben=caozuo-silu-overall
title=给出一下盘前/实盘操作的总体思路

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 tips=99 market-silu=17 caozuo-silu=18
no=31018


qianyan=本文给一下操作(其实就是如何应对市场+设计买点)的一般思路 #\
\n\
一些先验知识: #\
1 显然 行情是第一位的 不同的行情有大致的应对策略 最简单的 \
你不可能拿应对弱势行情的方法去对应一个普涨交易日 #\
2 在实盘的环境中 永远做不到全控市场 因此 只能把精力集中在有限的内容上 而且还不能犹豫#\
(要对抗这种有限确定性时自己心理的不安) #\
3 总体来说 有左侧买点(盘前有准备的)和右侧买点(纯靠临盘反应)的方式 \
但还是那句话 实盘只能选择其中一种 #\
\n\
\n\
基于上述的先验知识 可以先制定出以下方案: #\
1 判断行情 拿出基础的知识包: 这个是最基础的必备能力 必须要保证这部分的稳定性 #\
2 如果盘前有做过准备且大致符合行情 选择这个有过准备/预期的方案来做买点 #\
2.2 如果盘前准备的东西不符合行情 果断放弃 #\
2.3 如果盘前准备了东西 但因为比较混沌 不确定是否符合行情 可以放弃(要对自己的右侧能力有自信) #\
3 右侧买点 这个考验临盘的信息挖掘能力和瞬时图形买点能力 而且需要根据实时的行情选择激进or保守 #\
\n\
(注意到了吗 无论如何 盘前是否存在预期 是非常重要的选择逻辑分支的条件) #\
\n\
\n\
相关模板: 

