#
#Fri Feb 14 15:36:12 CST 2025
juben=codes-can-be-buyer-overall
title=判断某个指定的切片/股票池能否用作实时买点的一般性论述(没有指定具体的切片) 

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 1代表check-can-be-buyer 
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=81100

#3 随机性更大 #\ 
# 3 {还没想好如何和行情联动起来} #\
qianyan=本文解决一下判断某个指定的切片/股票池能否用作实时买点的一般性论述#\
\n\
\n\
\n\
判断某个切片能够用作买点有以下几个要素:#\
切片本身的rank: 显然权重越高 图形越好 越有机会#\
能否蹭到短链路买点: 比如市场低开高走 那么就有机会蹭到#\
切片本身的风控: 这个没什么好说的 也很重要#\
切片实时的图形结构 #\
\n\
其它更多? #\
\n\
\n\
一些相关的其它模板:



