#
#Fri Feb 14 15:36:12 CST 2025
juben=codes-can-be-maoding
title=判断某个指定的切片/股票池能否用作实时锚定数据的一般性论述 \
参考文章<2026-06-20 状态图思路解决判定股票池能否做为锚定股票池>

#3 随机性更大 #\ 
# 3 {还没想好如何和行情联动起来} #\
qianyan=本文解决一下判断某个指定的切片/股票池能否用作实时锚定数据的核心问题#\
(在实际的临盘场景中 我实际已经有了一个股票池[可能是盘前就看好的] 那么 \
其实我需要判断这个股票池是否适合用作锚定计算)#\
\n\
总体思路:按照状态跃迁的方式来进行判定 #\
参考文章<2026-06-20 状态图思路解决判定股票池能否做为锚定股票池> 也可以:\
open data/article/20260620_codes-can-be-maoding.txt#\
\n\
\n\
下面论述一下判断切片能否作锚定有一定的难度 #\
简单说 就是因为切片本身的属性/特征(一般的论述):#\
1 逻辑性小 #\
2 更碎片 #\
3 随机性很大#\
4 和行情的相关性没那么强：因为可能逆势 也可能坍塌成报团 #\
5 和过去几天的走势有一定的相关性 #\
\n\
\n\
当然 从锚定的角度 对一个切片其实有更高的要求 包括:#\
1 因为要做锚定 那么对切片本身的[重要度]是有要求的。纯监控的话 没有这个要求#\
2 由1可知用作锚定的股票池是有一定重要性的 那么 和过往交易日的走势的相关性 也会加强#\
3 由1可知 行情的比重也会加大。举个例子 如果当日是大票行情 \
而指定的这个切片也刚好是大票 那么锚定的效果也会更好(这是显然正确的)#\
\n\
\n\
\n\
那么 如果从状态图的角度来思考这个问题 先给出要素(最好有排序):#\
1 切片本身的权重: 这个很好理解 如果是一个极低权重的切片 那么从根基上就不具备\
作为锚定工具的基础#\
->但是要注意到这个量化起来有难度#\
2 切片过往几日的走势和实时的走势 共同组合形成的强度: 这个也很好理解 \
连续多日走强的切片 那么开盘允许一定程度的分歧 可以分歧后再走强。\
相比之下 一个过去几天没有表现的切片 那么当日必须只有前排个股 具备可能的锚定作用#\
3 和实时行情的联系。上面举过例子 如果实时的偏好 刚好是切片本身的属性 \
那么锚定效果更好。另外的例子 就是普跌日如果形成逆势 那么也具备一定的锚定作用 #\
\n\
注意到: 其实上面这3个要素其实只有2相对好量化#\
\n\
\n\
\n\
下面从实现的角度 来给出具体的方案: #\
1 如果能计算出切片的权重(假设这里克服了编码的困难) 那么根据切片的权重和实时的走势\
来共同判定能否用作锚定#\
2 在没有切片权重的情况下 根据“切片过往几日的走势和实时的走势 共同组合形成的强度”+\
判断切片不存在大幅风险 此时可用用作锚定#\
\n\
对于“切片过往几日的走势和实时的走势 共同组合形成的强度”稍作论述/举例:#\
1 近期连续走强 允许开盘弱分歧一下#\
2 近期一直不强 那么必须实盘很强 形成日间弱转强 才可以视作有效锚定#\
3 近期大波动+前日大跌 那么早盘必须至少头部有弱转强的迹象 才可以视作锚定#\
4 还可以有更多的例子 不再举例#\
注意:这种特征(前日走势+实时走势的组合)非常适合状态图实现#\
\n\
\n\
\n\
一些相关的其它模板:#\
从市场级别的锚定到版块池: sh/tips/run_template.sh maoding_to_pool #\
已经有切片了 做can-be-maoding的计算: \
sh/tips/run_xls_template.sh xx can_be_maoding #\
\n\
还没想好如何和行情联动起来 后续再来解决	TODO:



