#
#Fri Feb 14 15:36:12 CST 2025
juben=tips
title=汇总一下一些有效的市场级别codes列表

# BK0535: https://chat.deepseek.com/a/chat/s/cec241a0-f0bb-4ed0-86c0-c7aafb4094aa

functions=build_pool
before_func=build_pool_codes(context,"list:BK1717,BK1633")[09:15:00,]

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 tips=99 bk_list=10 codes_list=11
no=31011

qianyan=本文汇总一下一些有效的市场级别codes列表(可以选做买点股票池的) #\
\n\
\n\
[纯图形+早盘/全时段] #\
xls:ggzj:limit=120*trd:min=2*amount:limit=40 :可以用做市场情绪指标 适用于全时段 #\
xls:ggzj:limit=40 :可以用做市场情绪指标 #\
xls:fenshi*eva:ggzj:limit=40*eva:rup3 :实时的头部ggzj数据(这个数据不是很稳定) #\
BK1717 :题材股(40~60) #\
\n\
\n\
[纯图形+盘中] #\
xls:ggzj:limit=120 :可用做盘中pull的图形 #\
xls:zhz1000*10cm*no30200 :数据量不可控 一般在50~100 #\
db82 :没什么说的 8日2板的辨识度挺高的了 #\
db81_1*no30200*10cm :8日1板+基于箱体的辨识度 #\
\n\
\n\
\n\
\n\
[BK相关]#\
BK0535:QFII重仓股(750+):合格的境外机构投资者(QFII)大量买入并持有某家A股上市公司的股票 #\
https://chat.deepseek.com/a/chat/s/cec241a0-f0bb-4ed0-86c0-c7aafb4094aa #\
BK1717:题材股(40~60): 每天都会更新 #\
BK0823:养老金(190+) #\
BK0501:次新股(100+) #\
BK0536:基金重仓(60+) #\
\n\
\n\
相关模板: #\
对指定的股票池做简单分析: sh/tips/run_xls_template.sh xx analyze_cross_xls_by_shape


