#
#Fri Feb 14 15:36:12 CST 2025
juben=exist-pool-pull
title=分析市场是否存在题材的明显拉升(不走bkzj和ggzj)
category=analyze

# 还是尽量不要走bkzj API
enable_bkzj_df=0

# 分析市场中的pull数据 TODO:
# 实现参考@sh//hq/market/market_pull_analyze.sh

start=09:38:00

try_save_to_chain=1
chain_node=analyze_hq

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 1代表market 7代表pull
# 第4位和第5位数字组合代表了计算的类型
# no的说明 market-pull=01 exist-pool-pull=03
no=91703

qianyan=分析市场是否存在题材的明显拉升(不走bkzj和ggzj) #\
当前主要从以下几个分支进行计算: #\
redu题材池  => 这个是必存在的数据#\
config:pool  => 这个我实盘不一定会配置的 因此会先判空 #\
bkzj.top.atzao  => 这个只能在37分以后运行 #\
\n\
\n\

# 还没想好怎么实现 TODO:
# 不过基础思路是使用打开指数jpg来做兜底

eva_redu={00:00:00,23:59:59}print:热度版块池分支,\
open_index:redu,\
if get_candi:redu*filter:min=8 then break,\
zhushi:如果redu版块池数量过大 那么走到这里就直接终止计算\
 反正已经自动打开版块的jpg了,\
flush:redu->npulled:mode=qt,\
zhushi:直接计算热度题材池的pull数据

# config:pool分支
# 当前严格对config:pool的最大数量做了限制 因为再多的意义也不大 自己的脑子也反应不过来
eva_pool={00:00:00,23:59:59}print:config:pool分支 不一定配置了 所以会先判空,\
if get_candi:config:pool then open_index:config:pool,\
if not get_candi:config:pool*filter:min=2:max=6 then break,\
zhushi:如果没有配置config:pool或者配置的数量过大(当前最大限制为6) 那么终止计算,\
flush:config:pool->npulled:mode=qt,\
flush:config:pool::10cm->npulled:mode=qt

eva_bkzj_zao={09:37:00,}print:早盘的头部bkzj是可能\
迎来盘中2次拉升的 因此做成一个分支,\
if get_candi:bkzj.top.atzao2 then \
open_index:get_candi:bkzj.top.atzao2[09:36:00,09:41:00],\
if get_candi:bkzj.top.atzao then \
open_index:get_candi:bkzj.top.atzao:limit=15[09:41:30,]


flush_quan={00:00:00,23:59:59}


