#
#Fri Feb 14 15:36:12 CST 2025
juben=guzai
title=给出股灾行情的应对tips

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 2代表hangqing 见@engine/enum/tips_enum.py
# hq的定义见@engine/enum/hq_enum.py 
# 第4位和第5位数字组合代表了计算的类型 股灾=09
no=31209

qianyan=给出股灾行情的应对tips#\
\n\
结束股灾的2种方式: #\
1 跌停板清零  #\
2 虽然跌停板没有清零 但至少在减少+资金明显产生了一定的聚焦的赚钱效应(类似切换) #\
\n\
\n\
根据上面的思路 有: #\
1 监控跌停板的2连板 3连板 4连板的个股的走势 #\
2 监控市场的跌停板变化 #\
3 市场上rup3数据量足够好 也行




