#
#Fri Feb 14 15:36:12 CST 2025
juben=hangqing
title=给出各种行情的对应的模板的导航

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none/huizong
# 第4位和第5位数字组合代表了计算的类型 huizong=00 buyer=02 hangqing=03
no=31003

qianyan=根据行情来给出具体的模板文件#\
1 主力控盘的反弹日 ==> sh/tips/run_template.sh kongpan_fantan_buyer #\
2 弱势行情  	     ==> sh/tips/run_template.sh weak_buyer #\
3 普涨+高开行情	 ==> sh/tips/run_template.sh puzhang_gaokai #\
真普涨的行情		 ==> sh/tips/run_template.sh puzhang #\
4 震荡行情 		 ==> sh/tips/run_template.sh zhendang #\
5 切换行情		 ==> sh/tips/run_template.sh qiehuan

