#
#Fri Feb 14 15:36:12 CST 2025
juben=hq-buyer
title=根据行情快速选择买点方案的tips

qianyan=根据行情来给出买点方案是最基本的临盘买点方案了,那么本文来列出行情\
和对应的买点方案:#\
1 主力控盘的反弹日 ==> sh/tips/run_template.sh kongpan_fantan_buyer #\
2 弱势行情  	     ==> sh/tips/run_template.sh weak_buyer#\
\n\
\n\
如果对行情一无所知 只想根据前排数据来给出买点方案(其实大部分行情都适用) 那么:\
sh/tips/run_template.sh qianpai_buyer 


tips_jj={09:16:00,09:25:00}

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

tips_zao1={09:30:01,09:33:00}
