#
#Fri Feb 14 15:36:12 CST 2025
juben=hq-to-pool
title=根据行情生成pool的一般论述

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 1代表tips.properties 1代表hq-to-pool
# 第4位和第5位数字组合代表了计算的类型 overall=00 xls_sub=01 xls_sub_rank_alot=02
no=71100

qianyan=根据行情来生成版块池显然是最基本的思路 本文做一下一般论述#\
\n\
\n\
相关模板:#\
切换行情:  => sh/tips/run_template.sh hq_to_pool_qiehuan 



