#
#Fri Feb 14 15:36:12 CST 2025
juben=hq-to-pool
title=根据[切换]行情生成pool的一般论述

functions=hq_to_pool

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 1代表tips.properties 1代表hq-to-pool
# 第4位和第5位数字组合代表了计算的类型 overall=00 qiehuan=02
no=71102

qianyan=根据切换行情来生成版块池的tips#\
\n\
会从以下思路进行挖掘生成计算:#\
市场涨停板 #\
bkzj数据 #\
redu题材池挖掘(头部数据)(需要确保redu题材池的准度) #\
\n\
\n\
相关模板:#\
切换行情的tips(相关论述)(建议打开): sh/tips/run_template.sh qiehuan   

################### 最开头的前序eva计算
eva_quan={00:00:00,23:59:59}

# 打印一下当前配置文件中的所有版块池配置
jcals_quan={00:00:00,23:59:59}show_config_pools(),\
show_config_qpcs($day)

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区:

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区: #\
按照上面提到的来: #\
市场涨停板 #\
->当前涨停板的数据是否满足:xls:fenshi*upstp>20 返回: $check_if(context,\
"xls:fenshi->upstp*filter:min=20")#\
bkzj数据 #\
->一览bkzj数据: sh/tips/run_template.sh bkzj_to_pool_none_silu #\
redu题材池挖掘(头部数据)(需要确保redu题材池的准度) #\

eva_open={09:25:00,09:30:00}if xls:fenshi->upstp*filter:min=7:max=25 \
then xls:fenshi->upstp,back=append_xls2:redu,\
zhushi:分析一下涨停板,\
xls:fenshi->stage:upstp.hist

flush_open={09:25:00,09:30:00}redu->if2:rup7_alot.if,\
redu->if2:rup5_alot.if,\
redu->index

############################### 早盘时区

tips_zao1={09:30:01,09:45:00}早盘时区:




