#
#Fri Feb 14 15:36:12 CST 2025
juben=kongpan-fantan
title=主力控盘的反弹日的tips

qianyan=先给出主力控盘反弹日的准确定义: 即市场做多信心没那么足 \
因此需要主力带头控盘的反弹日 常常出现在:#\
1 外围大跌带动a股下跌然后外围企稳/反弹 此时外围的不确定下 市场做多信心不足 需要主力控盘#\
2 市场内生性的下跌/熊市持续一段时间后 市场从结构角度具备反弹能量 但需要主力带动#\
\n\
\n\
对于主力控盘的反弹日 有以下特征:#\
1 主力类型的股票池 比如大票 比如xxx板指 会比个股更强 因此会出买点#\
从这个角度 临盘去观察哪些指数比较强 然后做对应的套利 是一个基础策略#\
2 因为市场信心没那么足 如果高开 那么会先低走 然后盘中再走强#\
3 因为2 所以主力控盘的反弹日 会出盘中买点#\
4 尤其要注意午盘开盘的瞬间 因为有些资金后知后觉 会跑步入市的 所以其实11点到11点半\
这半小时 是适合做买点的


tips_plan={09:00:00,09:15:00}

tips_jj={09:16:00,09:25:00}

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

tips_zao1={09:30:01,09:33:00}
