#
#Fri Feb 14 15:36:12 CST 2025
juben=kongpan-fantan-buyer
title=给出[主力控盘的反弹日]的买点方案tips

qianyan=主力控盘反弹日的信息(比如准确定义) 见:\
open engine/observe/tips/template/kongpan_fantan.tips.properties#\
\n\
\n\
下面给出主力控盘反弹日的几个买点策略:#\
1 临盘从实时的主要市场指数中 找到强势的指数 然后做对应的指数套利#\
2 早盘观察题材的特征 有没有带头的题材 有的话做对应的题材买点#\
3 至于市场级别的股票池买点 也是必然存在的 但是逻辑性不如1和2 因此如果要做这类买点\
的话 那么优先选择权重更高的+图形更好的个股


tips_plan={09:00:00,09:15:00}


############################# 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区可以做以下操作:#\
1 打开市场主要指数 判断其中强势指数的数量 如果是普涨 那么暂时不做选择#\
买点的角度 其实做指数的etf也是可行的#\
python realtime/observe/index.py get --mode jj #\
sh/flush_cli.sh stocks:zhuli2 ruped --mode jj #\
sh/flush_cli.sh stocks:zhuli2 fronts_fenbu:jiasu --mode jj #\
2 观察主要的核心题材(前日大单): sh/open/open_xls_list.sh bkzj.dadan:limit=15#\
3 计算盘前准备好的切片池的数据 做观察: sh/flush_cli.sh qpc:plan trend3#\
sh/qpc/find_fronts.sh qpc:plan jiasu#\
sh/qpc/find_fronts.sh qpc:plan bsd



############################# 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:#\
1 市场核心指数套利: sh/flush_cli.sh stocks:zhuli2 trend3.hist#\
sh/flush_cli.sh stocks:zhuli2 fronts_fenbu:jiasu#\
sh/flush_cli.sh stocks:zhuli2 ruped#\
2 根据某个市场核心股票池做pool锚定分析: \
sh/codes/analyze_pool.sh xls:shenzhen*eva:btw:limit=20#\
3 前排题材池+头部amount直接计算数据: \
sh/flush_cli.sh config:top_amount::amount:limit=50 fronts_fenbu:jiasu#\
sh/pool/rup_alot.sh config:top_amount#\
\n\
\n\
买点的角度(别忘了本文开头说的 市场指数套利/题材买点/最后才是市场级切片买点):#\
1 直接qpc走起: sh/qpc/find_fronts.sh qpc:plan bsd --mode open

eva_open={09:25:00,09:30:00}xls:fenshi->trend3.hist,\
market:emotion.hist4,\
market:amounts.cross7[09:26:00,]



############################# 早盘时区
tips_zao1={09:30:01,09:33:00}



