#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=本tips给一下xls:ggzj的make plan(盘前)

# 参考@xx_xls_make_plan_overall.tips.properties 给出盘前的买点策略

# 写死时间戳
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan 所以前3位是固定的
# 股票池的plan 从数字65开始
# 第4位和第5位数字组合代表了计算的类型 overall=65 none=01  xls:ggzj=52
no=71052

functions=codes_shape
before_func=init_codes_no_if($day)

if=codes_no_recorder_inited

qianyan=本tips给一下xls:ggzj的make plan(盘前)#\
\n\
注意到xls:ggzj是实实在在的资金数据 因此分析题材的作用是必然要发挥的 #\
(但同时也要注意到 xls:ggzj天然对高权重的题材有倾斜 \
因此对挖掘轮动的/体量小的题材不友好 这个就和BKZJ_ZHULI_2原理类似)#\
\n\
手工计算的版块池分布: #\
sh/codes/qp/gene/by_xls.sh xls:ggzj:min_zhuli=0*10cm*trd:min=5 split_pool #\
新数据视角: sh/codes/qp/gene/by_xls.sh new:xls:ggzj split_pool #\
sh/codes/qp/gene/by_xls.sh new:len=3:xls:ggzj split_pool #\
sh/codes/qp/gene/by_xls.sh and:len=3:xls:ggzj split_pool #\
大成交视角: sh/codes/qp/gene/by_xls.sh xls:ggzj*amount:min=15 split_pool #\
\n\
\n\
\n\
\n\
\n\
注意:在下面计算出的股票池后 可以2次计算图形: \
sh/tips/run_xls_template.sh xx codes_make_plan_overall #\
\n\
其它思路?

tips_plan={09:00:00,09:15:00}xls:ggzj是否包含较多超短股票池: \
$check_if(context,"xls:ggzj*db61*filter:min=20"),\
如果是 那么生成一下超短切片池: sh/codes/qp/gene/by_xls.sh xls:ggzj basic_chaoduan

eva_plan={09:00:00,09:15:00}xls:ggzj*trd:min=5->size:len=4,\
xls:ggzj->stage:shape_fenbu:shizhi,\
xls:ggzj*tx:huoli->size:len=3,\
zhushi:获利盘+高震幅 如果数据量合适 是可以继续深挖or用做买点的,\
new:xls:ggzj->size:len=1,\
and1:xls:ggzj->size:len=1,\
xls:ggzj*BK1717->size:len=1,\
zhushi:题材股,\
xls:ggzj*BK0821->size:len=1,\
zhushi:MSCI,\
print_fenge,\
xls:ggzj*10cm*no30100->size:len=1,\
xls:ggzj*10cm*no30200->size:len=1,\
xls:ggzj*10cm*no40100->size:len=1


