#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=预期市场会走向弱势混沌(很弱 且很不确定)时的make plan

# 预期市场强分化 往往跟在大涨日 或者近期指数涨幅较大交易日之后 

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 yuqi-hot=09 yuqi-qfenhua=11 yuqi-rhundun
no=71012


qianyan=本tips尝试给出预期市场会走向弱势混沌时的make plan#\
\n\
市场弱势混沌常常出现在震荡行情 或者下跌行情 具体的表现包括: #\
1 市场整体进攻无力 指数可以红盘(如果是主力强行稳指数的话) #\
2 最好伴随缩量 #\
3 最好前日市场就处于这种萎靡 or 控盘的氛围中 那么后一日出现弱势混沌的概率就特别大 #\
\n\
注意: 要认知到弱势混沌的交易日买点数量是比平常更少的 没有信心的话完全可以战略性放弃 #\
注意: 弱势混沌交易日出现的概率大概是一周一次 要防范突然袭击 #\
\n\
\n\
资金有以下应对策略: #\
1 抱团在市场高权重个股 但不能确保下一日不会被兑现 #\
2 在近端超短票进行试错 #\
3 去新的日内热点试错 #\
4 盘中波动套利 #\
\n\
\n\
\n\
\n\
那么在这样的交易日 我怎么做交易日呢? 有以下思路: #\
1 近端超短进行试做 db31_new:len=3+日内图形良好 #\
sh/codes/qp/gene/by_xls.sh db31_new:len=3 sure_less_eva #\
2 保守的选择高权重小波动市场股票池的买点(这类股票池至少确定性是够的) \
比如 基金重仓BK0536,养老金BK0823 #\
sh/codes/qp/gene/by_xls.sh BK0823 sure_eva #\
3 盘中买点机会(当前这部分能力欠缺) #\
4 无脑的通过xls:fenshi*eva:ggzj:limit=40进行切入(最野蛮的策略 但也是可以的) #\
\n\
(上面没有提出题材的买点 因为对于弱势混沌日 除非早盘有\
非常确定的聚合的题材 否则题材很难有较强的赚钱效应) #\
(这也许让我不那么舒服 因为我心理层面对题材是有病态的依赖的 但理智告诉我 \
对买点来说 题材虽然很重要 但并不是全部 我还是要在心理层面学会在这样\
的交易日对题材和逻辑脱敏) #\
\n\
\n\
\n\
\n\
\n\
一些相关的其它模板: #\
通过bkzj挖掘市场核心题材池: sh/tips/run_template.sh analyze_cross_market_by_bkzj

# 感觉本文给出的解决方案还有明显的空间?			TODO:
