#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=预期市场强度会很高时的make plan

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 yuqi-hot=09 
no=71009


qianyan=本tips尝试给出预期市场强度很高的盘前生成操盘/买点计划的方案#\
\n\
这种市场强度高的预期是合理的 比如一般正常情况下周一的确定性是较高的\
(毕竟要给一周开个好头+周末利好刺激) 且其实出现的概率是比直觉来的要高的 \
至少一周有一天强势是合理的预期#\
而且这样的交易日盘前的工作会比平常来的更高 否则开盘以后各种脉冲 很容易搞乱心态#\
\n\
注意 如果实盘确实走了强势走势 那么就可以把实盘的精力专注于买点 不需要去关注市场的细节数据 #\
\n\
\n\
那么如何在这样的交易日做盘前计划呢? 本文就给出可选的思路(会有多种思路): #\
[题材切入]#\
热门题材(池)+辨识度子股票池 #\
热门题材(池)+权重个股 #\
\n\
[市场级别高权重股票池切入] #\
基金重仓BK0536(66只个股): sh/chain/gene/run_xls_template.sh BK0536 make_plan_core_codes#\
养老金BK0823(196只个股) #\
当然 实际对市场级别股票池的选择 还是要看实盘的强弱 走的强的 可以无脑选择 #\
\n\
[实时行情切入] #\
无脑的通过xls:fenshi*eva:ggzj:limit=40进行切入 也是可行的(熊市 \
震荡市可行的策略 强势行情同样适用) #\
\n\
\n\
一些相关的其它模板: #\
通过bkzj挖掘市场核心题材池: sh/tips/run_template.sh analyze_cross_market_by_bkzj

