#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=尝试给出盘前生成操盘/买点计划

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=71000


qianyan=本tips尝试给出盘前生成操盘/买点计划的一个方案#\
\n\
对于操盘/买点计划来说 至少要考虑以下几个要素: #\
预估市场风险: 谨记 无论在a股的主升 震荡 还是下跌周期 至少每周有一天的交易难度是很大的 #\
预估买点数量: 因为量化 主力的缘故 当前a股的买点数量上下波动很大 \
有些交易日买点能直接爆炸提升好几个数量级(不要因此被搞心态是重点) #\
->    实际上a股这点让我非常难过 行情好的时候 数量爆炸 混沌行情的时候 又会怀疑确定性不足\
买入就开始跌 行情差的时候 又担惊受怕 盘中快速拉升的时候 又信心不足觉得很难做买点#\
判定资金的大致去向(高低切 具体去的题材): #\
\n\
在做好上述的工作以后 然后还要给出具体的交易计划 否则自己很容易陷入到看盘的惯性中去 #\
另外 其实对操盘来说 对我来说 控制心态的稳定也非常的关键#\
\n\
\n\
在上述的事实之上(注意到其实是一个状态图) 如何生成操盘方案? #\
那么对一些特殊的分支 给出对应的tips文件实现是一个好的思路,那么具体有哪些分支? #\
买点数量爆炸: 必须作为单独分支 因为可能会影响到我的心态 #\
市场被明显控盘+走势不明 买点数量也不明: 也需要作为单独分支 因为这种不确定性高的交易日 \
自己容易信心不足 我需要进行特殊处理 #\
\n\
在上述的特殊分支外 是一些常见的分支 #\
缺 TODO: #\
\n\
\n\
一些好用的命令: #\
缺 TODO: #\
\n\
\n\
一些相关的其它模板: 

