#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=本tips给一下db62的make plan(盘前)

# db62的视角来分析市场

# 写死时间戳
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan 所以前3位是固定的
# 股票池的plan 从数字65开始
# 第4位和第5位数字组合代表了计算的类型 overall=65 none=01 db62=50 db32=51
no=71050

functions=codes_shape
before_func=init_codes_no_if($day)

if=codes_no_recorder_inited


qianyan=本tips给一下db62的make plan(盘前)#\
\n\
db62股票池 基本是能够代表超短情绪的股票池 因此本文的重点之一 就是分析市场的超短情绪#\
\n\
主要关注db62的细节数据 包括: #\
db62中的最高高度/最高板数据 #\
db62+CODES-BAN #\
db62的数量变化 #\
new:db62 #\
\n\
\n\
想知道一些具体的数据 可以: #\
sh/codes/qp/gene/by_xls.sh db62*db51.bf6 split_pool #\
sh/codes/qp/gene/by_xls.sh db62*db50.bf6 split_pool #\
sh/codes/qp/gene/by_xls.sh db62*amount:min=20 split_pool #\
\n\
\n\
\n\
其它思路?

tips_plan={09:00:00,09:15:00}

eva_plan={09:00:00,09:15:00}print:先看一下超短情绪指标数据,\
db62->stage:tidui,\
db62->stage:tidui.days4,\
db62*db31->stage:trends_sum:len=5.days5,\
db62*db43->size:len=4,\
db62*btw:max=3->stage:trends_sum:len=3.days4,\
zhushi:看一下差的数据,\
db62->stage:pos_sum:len=15,\
print_fenge,\
print:再看一些细节分布数据,\
db62->stage:shape_fenbu:amount,\
zhushi:成交额的细节数据,\
db62*duoban:len=6:min=3->size:len=1,\
zhushi:叠加3板,\
db32*db50.bf4->size:len=1,\
zhushi:新的3日2板,\
db62*db31_1->size:len=1,\
zhushi:6日2板叠加3日仅1板

