#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=盘前从近3天的热门题材来做盘前计划(仅支持盘前)

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 hot-3days-pool=17
no=71017

functions=build_pool
before_func=build_pool_codes(context,"BKZJ_HOT_3DAYS_1:limit=20")

qianyan=本tips尝试给出盘前从近3天的热门题材来做盘前计划#\
\n\
本tips的核心版块池是:BKZJ_HOT_3DAYS_1 当光靠这一个版块池是不够的 \
还会和其它版块池来共同判定 比如: #\
BKZJ_ZHULI_2(5日的主力题材池) #\
\n\
\n\
具体来说 包括下面的指标: #\
强势指标: trd:min=6->size:len=6 #\
图形指标: no30100,no40100 #\
结合市场高权重股票池来辅助判定 比如: shizhi500+trd6+amount:limit=40->append-xls #\
\n\
\n\
\n\
\n\
\n\
\n\
一些相关的其它模板: #\
通过bkzj挖掘市场核心题材池: sh/tips/run_template.sh analyze_cross_market_by_bkzj

eva_plan={09:00:00,09:15:00}get_candi:BKZJ_HOT_3DAYS_1,\
zhushi:给出基础数据,\
get_candi:BKZJ_HOT_3DAYS_1*BKZJ_ZHULI_2,\
zhushi:既是3日hot 又是5日主力 这个数据好的话 说明市场处于主升区间 \
这个数据差的话 市场处于强轮动,\
get_candi:BKZJ_HOT_3DAYS_1:limit=20*stage:merge_left=0:sort=size:size:len=1

# BKZJ_HOT_3DAYS_1:limit=15->if xx*filter:min=80 then xx*no30100->stage:trends_sum:len=3
# 也就是需要支持if xx then yy..		TODO:
#flush_plan={09:00:00,09:15:00}BKZJ_HOT_3DAYS_1:limit=15->size:len=1

