#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=本tips给一下BK0535(QFII重仓股)的make plan(盘前)

# 写死时间戳
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan 所以前3位是固定的
# 股票池的plan 从数字65开始
# 第4位和第5位数字组合代表了计算的类型 none=01  BK0535/QFII=53
no=71053

functions=codes_shape
before_func=init_codes_no_if($day),init_evas_no_if($day)

if=codes_no_recorder_inited


qianyan=本tips给一下BK0535(QFII重仓股)的make plan(盘前)#\
注意:本股票池的数据量是较大的(700+) 因此实际做买点的时候 必须取子股票池 #\
\n\
对于QFII这种大票 有2种通用的策略: #\
1 市场走阳线时 买点数量会相比平常暴涨 #\
2 正常的市场 作为一些稀有的保守的图形买点 或者近期有一定持续的市场关注度的票#\
\n\
一些组合: #\
QFII+BK1717: 题材股 #\
QFII+BK1633: 前日高震幅 #\
QFII+xls:ggzj 叠加ggzj 具备一定关注度的 #\
QFII+tx:huoli 获利盘 #\
MSCI+no30100 一定的辨识度 #\
MSCI+no30000 基础的xt图形 #\
\n\
\n\
如果上述图形依旧不能令我满意 试试: #\
BK0535*10cm*tx:drop10 #\
\n\
\n\
\n\
注意:在下面计算出的股票池后 可以2次计算图形: \
sh/tips/run_xls_template.sh xx codes_make_plan_overall #\
\n\
相关模板: 

# 思考: 要不要给出前日比较强的数据?

eva_plan={09:00:00,09:15:00}BK0535->trend3.days6,\
zhushi:对QFII来说 经常会出现相对长周期(5+)中会出现某一天走强,\
BK0535*trd:min=6*btw:min=2->size:len=6,\
zhushi:查看trd>6的数据 辅助上面的trend3数据来判断QFII的走势,\
print_fenge,\
print:上面是基本的走势数据 下面开始分析图形,\
if new:BK1717*filter:min=1 \
then BK0535*BK1717->size:len=1,\
zhushi:叠加题材股,\
if new:BK1633*filter:min=10 then BK0535*BK1633->size:len=1,\
zhushi:QFII叠加前日高震幅 可以视作有潜伏资金进入了QFII 可以用做买点股票池,\
BK0535*xls:ggzj->size:len=1,\
zhushi:叠加xls:ggzj,\
BK0535*BK0821->size:len=1,\
zhushi:叠加MSCI,\
BK0535*BK0821*no30000->size:len=1,\
BK0535*db51->size:len=1,\
BK0535*xls:zhz1000*no30000->size:len=1,\
BK0535*xls:zhz500*no30000->size:len=1,\
BK0535*tx:huoli->size:len=3,\
zhushi:叠加获利盘,\
print_fenge,\
print:更纯粹的图形,\
BK0535->size:len=1,\
BK0535*10cm*no30000->size:len=1,\
BK0535*10cm*no30100->size:len=1,\
BK0535*10cm*no30200->size:len=1,\
BK0535*10cm*no30401->size:len=1,\
BK0535*10cm*no40100->size:len=1,\
BK0535*10cm*no40001->size:len=1,\
zhushi:5日热度数据

flush_plan={09:00:00,09:15:00}if BK0535*trd:min=4*filter:min=25 then \
redu::BK0535*trd:min=3->size:len=1

# 在本文的最底端 加入一段收尾信息输出
jiewei=考虑根据本模板生成切片: \
sh/codes/qp/gene/by_tips.sh make_plan_QFII --time_str $time_str --action download

