#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=盘前从近3天的热门题材来做盘前计划(仅支持盘前)

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 hot-3days-pool=17
no=71017

functions=build_pool
before_func=build_pool_codes(context,"BKZJ_HOT_3DAYS_1:limit=20")

qianyan=本tips尝试给出盘前从近3天的热门题材来做盘前计划#\
\n\
本tips的核心版块池是:BKZJ_HOT_3DAYS_1 当光靠这一个版块池是不够的 \
还会和其它版块池来共同判定 比如: #\
BKZJ_ZHULI_2(5日的主力题材池) #\
\n\
\n\
具体来说 包括下面的指标: #\
强势指标: trd:min=6->size:len=6 #\
图形指标: no30100,no40100 #\
结合市场高权重股票池来辅助判定 比如: shizhi500+trd6+amount:limit=40->append-xls #\
\n\
\n\
\n\
\n\
\n\
\n\
一些相关的其它模板: #\
通过bkzj挖掘市场核心题材池: sh/tips/run_template.sh analyze_cross_market_by_bkzj

eva_plan={09:00:00,09:15:00}get_candi:BKZJ_HOT_3DAYS_1,\
zhushi:给出BKZJ-HOT-3DAYS的原始数据(按照sum3排序),\
get_candi:BKZJ_HOT_3DAYS_1*stage:zijin:mode=cross:min_zhuli=0,\
zhushi:给出BKZJ-HOT-3DAYS中前日收盘主力为正的数据(sum3排序)(一般来说 \
可以重点关注 因为延续性预期) 这个复合数据是近几天持续强势的题材 \
且如果这个数据很好的话 说明前日市场很强,\
print_fenge,\
get_candi:BKZJ_HOT_3DAYS_1*BKZJ_ZHULI_2,\
zhushi:既是3日hot 又是5日主力 这个数据好的话 说明市场处于主升区间 \
这个数据差的话 市场处于强轮动,\
get_candi:BKZJ_HOT_3DAYS_1*bkzj.cdadan:limit=20,\
zhushi:3日hot 又是大单版块池 这个数据好的话 说明至少市场没有大跌 但是如果\
这个数据太好的话 基本前一个交易日是反弹日 或者加速日 才会和大单统一(也许有一定风险),\
get_candi:bkzj.cdadan:limit=20*not:BKZJ_HOT_3DAYS_1*\
stage:zijin_sum:mode=cross:len=3:can_has_empty=1,\
zhushi:昨日收盘大单列表中不是3日hot的数据(按照大单绝对值排序)\
(这个题材池可能会轮动走强 如果前日大涨的话) \
如果主力为负且负很多 那么意义不是很大,\
get_candi:BKZJ_HOT_3DAYS_1:limit=20*stage:merge_left=1:sort=size:size:len=1,\
zhushi:给出基础的股票总数量并排序后返回,\
print_fenge,\
if exist_ggzj then xls:ggzj:limit=40*trd:min=4\
->get_codes,back=append_xls2:BKZJ_HOT_3DAYS_1:limit=20,\
zhushi:通过前日收盘的前排ggzj数据来判断题材池的准度 地位

# BKZJ_HOT_3DAYS_1:limit=15->if xx*filter:min=80 then xx*no30100->stage:trends_sum:len=3
# 也就是需要支持if xx then yy..		TODO:
#flush_plan={09:00:00,09:15:00}BKZJ_HOT_3DAYS_1:limit=15->size:len=1

