#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=本tips给一下db32的make plan(盘前)

# 参考@xx_xls_make_plan_overall.tips.properties 给出盘前的买点策略

# 写死时间戳
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan 所以前3位是固定的
# 股票池的plan 从数字65开始
# 第4位和第5位数字组合代表了计算的类型 overall=65 none=01  db32=51
no=71051

functions=codes_shape
before_func=init_codes_no_if($day)

if=codes_no_recorder_inited


qianyan=本tips给一下db32的make plan(盘前)#\
\n\
主要关注db32的细节数据 包括: #\
db32中的最高高度/最高板数据 #\
db32+CODES-BAN #\
db32的数量变化 #\
new:db32 #\
\n\
\n\
想知道一些具体的数据 可以: #\
sh/codes/qp/gene/by_xls.sh new:db32 split_pool #\
分析新数据: sh/codes/qp/gene/by_xls.sh db32*not:db81.bf3 split_pool #\
sh/codes/qp/gene/by_xls.sh db32*db81.bf3 split_pool #\
\n\
\n\
\n\
其它思路?

tips_plan={09:00:00,09:15:00}

eva_plan={09:00:00,09:15:00}db32->size:len=5,\
db32*duoban:len=5:limit=8->get_codes,\
zhushi:按照板的数量排序查看当前的市场超短高度,\
db32->stage:pos_sum:len=12,\
zhushi:查看最高板的数据,\
print_fenge,\
print:下面从db32的子股票池的视角来进行分析,\
db32*xls:ggzj->size:len=1,\
zhushi:叠加xls:ggzj的数据 这个数据越接近db32越好,\
db32*CODES_BAN->size:len=1,\
zhushi:db32+ban,\
new:len=2:db32->size:len=1,\
zhushi:新增的db32,\
db32*db81.bf3->size:len=1,\
zhushi:db32+之前已经有过涨停板(至少1板),\
db32*db102.bf3->size:len=1,\
zhushi:db32+之前已经有过涨停板(2板),\
db32*not:db81.bf3->size:len=1,\
zhushi:新冒出来的db32,\
print_fenge,\
if db32*filter:max=30 then db32->get_codes,back=append_xls2

