#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=盘前制定买点计划

# 其实本文的语义是盘前制定买点策略 可以归类到gene 可以归类到buyer 也可以归类到silu..
# 但还是取本名算了

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 buyer=90
no=71090

qianyan=有几个事实:#\
1 在大多数交易日买点策略的制定就是最重要的事情 #\
2 自己的能力足够丰富到能够应对各种行情(丰富的股票池带来的) #\
3 买点分成左侧和右侧 但尽管我现在能力很强 但如果想仅靠临盘的右侧能力 还是比较吃力 #\
4 在实际的市场中 市场具体的行情会圈出来一定的范围 就像考试一样 \
每一道题虽然可能有不同的解法 但这些解法也是受限制的 因为实时市场分析也是很必要的 #\
\n\
下面 我会在上述的几个事实之下 进行进一步阐述 #\
\n\
买点来源的基础分类: #\
题材类: 细分包括题材前排 题材+图形 题材+ggzj提供确定性 题材+盘中pull #\
股票池类: 细分包括前排超短 MSCI 股票池+题材 股票池+特定图形 股票池+ggzj 股票池+pull #\
(可选股票池大致分成超短 BK1633 MSCI xls:iggzj(_pull) 市值100 市值200 市值500)#\
(分类很多 单独写成文件 TODO:) #\
\n\
买点的不同择时: #\
左侧: (基于预测)先看好(准备好)题材或者股票池 实盘监控 等待买点出现做买点 #\
右侧: 完全不做预测 就根据实盘的内容做实盘跟随买点 #\
\n\
看起来根据不同的择时和买点来源 有非常多的排列组合 但注意到我一开始就论述了 \
每天可行的策略其实是由当日的行情圈定出来的范围所限制的 #\
\n\
那么根据上面的内容 有以下结论:#\
1 每天盘前还是要基于预期大致给出左侧股票池 (并且预期的准度越好 我临盘的操作也就越顺利)#\
2 实盘还是要做好实盘分析 毕竟实盘最大 然后根据实盘再来做左侧还是右侧#\
(看起来给出的结论都很显然 但其实自己之前没怎么想好) #\
\n\
虽然能做左侧买点是最好的 但其实在a股中 大部分情况下 都只能做右侧买点(65%占比以上) 包括: #\
1 市场极弱 包括黄线开盘就下挫的 暴跌开盘的 #\
2 市场不强的时候 资金明显聚焦在若干题材下的 此时题材的偏好超过了其它所有 #\
3 前日市场大涨 此时很难预测资金会去到哪个题材 只能做实盘右侧买点 #\
\n\
\n\
因为具体不同的行情时 如何做策略的内容太长 因此我会分别写在单独行情下的tips文件中 列举如下:#\
1 #\
\n\
\n\
相关模板: #\
打开codes 列表: sh/tips/run_template.sh buyer_codes_list #\
打开本日的手工hand买点文件: TODO:  #\
打开本日的周期调度的hand买点文件: TODO:

# TODO:


eva_plan={09:00:00,09:15:00}
