#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=预期市场会走向强分化时的make plan

# 预期市场强分化 往往跟在大涨日 或者近期指数涨幅较大交易日之后 

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan
# 第4位和第5位数字组合代表了计算的类型 overall=00 yuqi-hot=09 yuqi-qfenhua=11
no=71011


qianyan=本tips尝试给出预期市场会走向强分化时的make plan#\
\n\
市场走出强分化 一般出现在大涨后一日 或者近期指数涨幅较大交易日之后 #\
这种强分化的交易日 意味着近期热门题材内部的博弈难度很大(具体自己能不能应对要看具体的数据 不要硬来) \
此时资金有以下去处: #\
1 就在题材内部硬做 抱团或者高低切 但这类资金也非常聪明 势头不对立马跑路 \
因此选择这个时 要确保至少有一定数量的活口 #\
2 身段灵活的转身去新轮动的题材 不论这个题材是老登 还是黄金有色保险这种极小概率的品种 #\
3 选择辨识度极高的个股 我可以利用这类资金 通过诸如db81*no30200*10cm提供辨识度+实时ggzj提供确定性 来解决 #\
4 就等盘中的机会 #\
\n\
\n\
这种强分化的交易日 其实近期的热门题材反而是累赘 而这种交易日的特征也是很明显的 我不需要花过多的精力在市场 #\
\n\
\n\
\n\
那么如何在这样的交易日做交易/操盘计划呢? #\
下面给出可选的思路: #\
1 身段灵活的转身去新轮动的题材(考验我对这类题材的瞬时买点能力了) #\
2 上面提到的通过 图形提供辨识度+提供确定性(ggzj-eva或其它) #\
缺对应的chain		TODO: #\
sh/codes/qp/gene/by_xls.sh db81_1*no30200*10cm sure_less_eva #\
sh/codes/qp/gene/by_xls.sh db152*10cm basic_eva #\
3 转而选择保守的策略 去做高权重小波动市场股票池的买点(这类股票池至少确定性是够的) \
比如 基金重仓BK0536,养老金BK0823 #\
4 热门题材内部硬做 但买点延后 等盘中/准盘中的买点机会 #\
5 盘中买点机会(当前这部分能力欠缺) #\ 
6 无脑的通过xls:fenshi*eva:ggzj:limit=40进行切入(最野蛮的策略 但也是可以的) #\
\n\
\n\
通过上面的内容其实可以看到 对于强分化交易日 选择把买点延后 股票池尽量保守化是基本的策略 #\
\n\
\n\
\n\
一些相关的其它模板: #\
通过bkzj挖掘市场核心题材池: sh/tips/run_template.sh analyze_cross_market_by_bkzj

# 感觉本文给出的解决方案还有明显的空间?			TODO:
