#
#Fri Feb 14 15:36:12 CST 2025
juben=maoding-to-pool(切换)
title=关于[切换行情]下市场锚定->题材池(从实时的锚定数据计算得到题材 逻辑信息)的tips

qianyan=本文属于maoding-to-pool下切换行情时的特化论述,想看一下maoding-to-pool\
的一般论述: sh/tips/run_template.sh maoding_to_pool#\
\n\
切换行情一般意味着资金要抛弃近期形成大量资金的题材 进入新的题材 因此:#\
直接涨停板分析题材即可 且尽量必然避开近期的热门题材 #\
做bkzj的头部数据分析 同时也要避开/过滤掉近期的热门题材 #\
\n\
\n\
从技术的角度 切换行情下 那么对近期热门题材池的识别是非常重要的 最好在盘前就能做好#\
\n\
\n\
\n\
(仅用做记忆)一般默认场景下的一些锚定算子包括: #\
涨停板:  #\
bkzj的数据: #\
重头戏:市场核心个股/股票池的锚定数据: #\
\n\
\n\
\n\
一些相关的其它模板:

