#
#Fri Feb 14 15:36:12 CST 2025
juben=maoding-to-pool
title=关于市场锚定->题材池(从实时的锚定数据计算得到题材 逻辑信息)的一些论述 \
参考文章<2026-06-20 状态图思路解决锚定->题材(池)>

qianyan=本文解决一下实时锚定到版块池/逻辑的核心问题#\
实时锚定数据能提供巨大的确定性 因此几乎可以算做临盘最重要的数据了,因此虽然是\
maoding-to-pool,但其实本文主要侧重在maoding的部分#\
\n\
总体思路:按照状态跃迁的方式来进行判定 #\
参考文章<2026-06-20 状态图思路解决锚定->题材(池)> 也可以:\
open data/article/20260620_zhuangtaitu-maoding-to-pool.txt#\
\n\
\n\
下面给一下重点的内容:#\
1 行情是一个重要的要素(因为它能决定锚定算子的不同排序 显然不同交易日有\
不同的排序) -> 这也是为什么我会出不同行情的版本文件#\
2 涨停板: 是一个常用的锚定工具 #\
3 bkzj的数据: #\
4 重头戏: 市场核心个股/股票池的锚定数据#\
这部分内容同样很复杂 但大致也有以下思路: #\
近期高权重+走势好的股票池：#\
暴力的把热门题材的权重个股合并起来 视作一个整体股票池 然后实时前排的数据 #\
连板票：这个也不失为一个选择 但要求早盘迅速的走出极其强势的走势 #\
实时的走出超预期强度的高权重个股 比如2000亿市值的票 或者就暴力的实时市场\
成交前30的个股：不过这种票 很少会在开盘就立马走强#\
\n\
\n\
注意1: 时效性的排序 某些情况下的涨停板=市场核心股 > bkzj数据 > 涨停板数据 #\
注意2: 复杂度的排序 市场核心股 >> 涨停板分析 > bkzj数据分析(bkzj是最简单直接的数据了)#\
\n\
\n\
\n\
一些相关的其它模板(主要是按照不同的行情 我会给出不同的pool-to-maoding实现):#\
普涨行情:  => sh/tips/run_template.sh maoding_to_pool_puzhang #\
切换行情:  => sh/tips/run_template.sh maoding_to_pool_qiehuan #\
聚焦(震荡+一家独大)行情: => sh/tips/run_template.sh maoding_to_pool_jujiao #\
震荡行情: => sh/tips/run_template.sh maoding_to_pool_zhendang #\
弱势(普跌)行情: => sh/tips/run_template.sh maoding_to_pool_weak



