#
#Fri Feb 14 15:36:12 CST 2025
juben=maoding-to-pool(puzhang)
title=关于[普涨行情]下市场锚定->题材池(从实时的锚定数据计算得到题材 逻辑信息)的tips

qianyan=本文属于maoding-to-pool下普涨行情时的特化论述,想看一下maoding-to-pool\
的一般论述: sh/tips/run_template.sh maoding_to_pool#\
\n\
普涨行情时的锚定是相对简单的 甚至有点不那么重要 但出于心理层面的需求 \
还是给出具体的策略#\
(普涨行情买点太多了 逻辑也很多 甚至买点的时候 不那么需要逻辑信息 \
买点的角度:如果图形较好 直接判断一下是否属于risk数据就行)#\
(其实普涨行情时 就不需要逻辑啊 光图形+权重就够用)#\
\n\
策略1: #\
实时全市场头部成交额的top30做一下分析#\
\n\
策略2: #\
直接把热门题材的权重股作为整体 然后计算头部的数据进行题材分析即可#\
\n\
\n\
\n\
(仅用做记忆)一般默认场景下的一些锚定算子包括: #\
涨停板:  普涨行情下确实不好使?#\
	-> 还是有办法的 如果涨停板过多 可以: \
sh/template/run_template.sh maoding_upstp_alot_puzhang(当前未实现)#\
bkzj的数据: 普涨行情下 如果前排逻辑很多 那么也没什么作用 还不如risk数据有用#\
重头戏:市场核心个股/股票池的锚定数据: 普涨行情下 核心个股的锚定效果也会降低 \
更多起一个心理作用了 #\
\n\
\n\
\n\
一些相关的其它模板:

