#
#Fri Feb 14 15:36:12 CST 2025
juben=maoding-to-pool(聚焦)
title=关于[聚焦行情]下市场锚定->题材池(从实时的锚定数据计算得到题材 逻辑信息)的tips

qianyan=本文属于maoding-to-pool下聚焦行情时的特化论述,想看一下maoding-to-pool\
的一般论述: sh/tips/run_template.sh maoding_to_pool#\
\n\
聚焦行情=震荡+一家/2家独大行情  ->属于震荡行情中的一种特殊结构#\
\n\
对聚焦行情来说 逻辑的选择是简单的 即:具体的聚焦题材 因此聚焦行情下的主要工作就是\
判断一家独大的数据 简单说就是作一家独大分析就行了#\
具体有以下思路: #\
1 涨停板做一家独大分析 #\
2 市场前排大成交+实时走的很好的个股做一家独大分析 #\
3 bkzj数据是否形成一家独大结构 #\
\n\
\n\
\n\
一些相关的其它模板:

