#
#Fri Feb 14 15:36:12 CST 2025
juben=maoding-to-weak(弱势)
title=关于[弱势/普跌行情]下市场锚定->题材池(从实时的锚定数据计算得到题材 逻辑信息)的tips

qianyan=本文属于maoding-to-pool下弱势行情时的特化论述,想看一下maoding-to-pool\
的一般论述: sh/tips/run_template.sh maoding_to_pool#\
\n\
弱势行情也是适合锚定一显身手的行情,具体来说: #\
1 弱势行情有一个最有效的判定 就是对逆势数据的判定 但这个实战起来没有那么简单#\
2 开盘的涨停板分析(还要判断有没有形成聚焦) #\ 
3 bkzj的数据此时也比较有效 #\
4 暴力的把热门题材的权重个股合并起来 视作一个整体股票池 + 实时前排个股#\
\n\
\n\
注意: 弱势行情可能是0题材池的 此时买点坍塌到个股(不能排除这种可能)#\
\n\
\n\
\n\
(仅用做记忆)一般默认场景下的一些锚定算子包括: #\
涨停板:  #\
bkzj的数据: #\
重头戏:市场核心个股/股票池的锚定数据: #\
\n\
\n\
\n\
一些相关的其它模板:

