#
#Fri Feb 14 15:36:12 CST 2025
juben=maoding-to-pool(震荡)
title=关于[震荡行情]下市场锚定->题材池(从实时的锚定数据计算得到题材 逻辑信息)的tips

qianyan=本文属于maoding-to-pool下震荡行情时的特化论述,想看一下maoding-to-pool\
的一般论述: sh/tips/run_template.sh maoding_to_pool#\
注意:这里的震荡行情是排除了一家独大的情况的 那种情况 调用:\
sh/tips/run_template.sh maoding_to_pool_jujiao#\
\n\
震荡行情时最适合锚定工具一显身手的行情,可以: #\
1 涨停板分析 且聚焦在热门题材池做分析 无视不热门的题材.当然 允许日内有1~2个新轮动题材#\
2 近期高权重+走势好的股票池的头牌数据分析 #\
3 暴力的把热门题材的权重个股合并起来 视作一个整体股票池 + 实时前排个股#\
4 实时的走出超预期强度的高权重个股 比如2000亿市值的票 或者就暴力的实时市场成交前30的个股#\
\n\
注意: 震荡行情下 bkzj主要用作新题材的挖掘计算 不倚重它的题材选择功能#\
\n\
\n\
从技术的角度 震荡行情下 那么对近期热门题材池的识别是非常重要的 最好在盘前就能做好#\
\n\
\n\
\n\
(仅用做记忆)一般默认场景下的一些锚定算子包括: #\
涨停板:  #\
bkzj的数据: #\
重头戏:市场核心个股/股票池的锚定数据: #\
\n\
\n\
\n\
一些相关的其它模板:

