#
#Fri Feb 14 15:36:12 CST 2025
juben=zoushi
title=市场上一些重要股票池的论述tips

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 8代表codes
# 第4位和第5位数字组合代表了计算的类型 huizong=00 
no=31800

qianyan=市场上一些重要股票池的论述tips#\
\n\
\n\
包括: #\
db31#\
db102s#\
\n\
\n\
还没想好怎么实现	TODO:

tips_plan={09:00:00,09:15:00}


