#
#Fri Feb 14 15:36:12 CST 2025
juben=market
title=关于市场market的tips

enable_bkzj_df=0

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 market=00 zoushi=01
no=31000


qianyan=关于市场market的tips(提供一些导航和命令)#\
\n\
\n\
没有明显思路时 无脑: #\
bkzj生成pool: sh/tips/run_template.sh bkzj_to_pool_none_silu #\
realtime-pool: sh/tips/run_template.sh realtime_pool_silu_none #\
查看市场实时数据: sh/template/run_template.sh market#\
随机打开index: python realtime/observe/index.py get#\
\n\
\n\
\n\
从db31数据来分析市场(日间): sh/tips/run_template.sh analyze_cross_market_by_db31#\
\n\
\n\
\n\
相关模板: #\
分析市场的一般论述: sh/tips/run_template.sh analyze_market_overall #\
分析实时市场: sh/tips/run_template.sh analyze_inner_market_overall 

################### 最开头的前序eva计算
eva_quan={00:00:00,23:59:59}market:emotion.hist4[09:23:00,],\
xls:fenshi->stage:upstp.hist[09:33:00,],\
xls:fenshi->stage:dstp.hist[09:25:00,]
