#
#Fri Feb 14 15:36:12 CST 2025
juben=market-and-chain
title=chain实现过的所有market算子汇总

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 market-and-chain=40
no=31040

# TODO:

qianyan=本文给出chain实现过的所有market算子汇总 #\
\n\
市场行情:#\
[混沌] #\
sh/chain/gene/run_template.sh check_market_hundun #\
sh/chain/gene/run_template.sh handle_market_hundun #\
\n\
[轮动] #\
sh/chain/gene/run_template.sh check_market_rotate #\
\n\
[弱势行情] #\
sh/chain/gene/run_template.sh handle_market_bad #\
\n\
\n\
分析市场盘中存在的pull: sh/chain/gene/run_template.sh analyze_market_pull #\
\n\
\n\
更多?

