#
#Fri Feb 14 15:36:12 CST 2025
juben=market-silu-overall
title=给出一下分析/应对市场的思路的总体思路

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 tips=99 spec-codes-silu=15 market-silu=17
no=31017


qianyan=本文给出一下分析/应对市场的思路的总体思路 #\
\n\
分析市场绝对是操盘最重要的内容 但也绝非易事 这里原因也非常简单 \
市场中所包含的信息实在过多 非常容易陷入信息漩涡 #\
这种情况下 如何简单有效的找到分析市场的一扇窗口 \
做到管中窥豹就非常重要了 这也是本模板尝试做到的 #\
\n\
\n\
这里其实还有另一个非常重要点: 预期实盘的走势 \
这会直接决定是事半功倍 还是事倍功半 #\
很简单你费了半天功夫分析出了市场的强势题材 但日内市场走了一个\
纯轮动 那么功夫就白费了#\
\n\
\n\
那么 结合上面的内容 可以设计出以下方案: #\
1 对市场先做一个最基础的默认的分析 #\
2 判断当日最大几率的走势 #\
3 选择某个视角对市场进行分析 #\
(这个方案下 一般会有2个计算结果 是可以接受的工作量) #\
\n\
\n\
[几个常见可靠的最基础的默认分析] #\
sh/tips/run_template.sh make_plan_pool_hot_3days #\
sh/codes/qp/gene/by_xls.sh xls:ggzj:min_zhuli=0*tx:huoli split_pool#\
python strategy/cli.py get xls:ggzj:limit=40*not:xls:ggzj:limit=150.bf \
--back append_xls2#\
sh/codes/qp/gene/by_xls.sh db32*db80.bf3 split_pool #\
\n\
\n\
\n\
相关模板: 

