#
#Fri Feb 14 15:36:12 CST 2025
juben=master-xls
title=作为master题材相关的导航(未指定题材 纯导航/论述)

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 4代表xls
# 第4位和第5位数字组合代表了计算的类型 huizong=00 
no=31400


qianyan=本文作为掌控xls相关的导航#\
如果已经有了具体的题材: sh/tips/run_xls_template.sh xx master_xls #\
\n\
\n\
题材分析(日间): sh/tips/run_template.sh analyze_xls_overall #\
sh/tips/run_xls_template.sh xx xx_analyze_xls_cross_state #\
\n\
实时锚定: sh/tips/run_template.sh xls_maoding #\
sh/tips/run_xls_template.sh xx xls_maoding_overall #\
\n\
\n\
\n\
一些相关的其它模板: 



