#
#Fri Feb 14 15:36:12 CST 2025
juben=master-buyer
title=作为买点相关的导航

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 9代表master
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=81900

#3 随机性更大 #\ 
# 3 {还没想好如何和行情联动起来} #\
qianyan=本文作为买点相关的导航#\
\n\
\n\
短链路买点导航 ==> sh/tips/run_template.sh short_buyer_overall#\
\n\
\n\
\n\
一些相关的其它模板: #\
论述某个切片能否成为买点(没有指定具体的切片) \
==> sh/tips/run_template.sh codes_can_be_buyer_overall #\
买点的3选择 ==> sh/tips/run_template.sh three_options_buyer#\
对买点的分析,心态的分析等(tips) ==> sh/tips/run_template.sh buyer



