#
#Fri Feb 14 15:36:12 CST 2025
juben=overcome-anxiety(pool)
title=宣告解决了对版块池的焦虑问题

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 overcome-anxiety(pool)=33
no=31033

qianyan=之前我确实有很长一段时间对版块池有焦虑 但经过能力的提升后 我发现自己基本解决了 #\
\n\
解决版块池焦虑之:认识到不同的交易日强势的题材的数量不同 但即使如此 数量正常也不会很多 #\
\n\
解决版块池焦虑之:搞定了题材池源.其实无外乎近期的热门题材(通过日间bkzj 日间ggzj BK1633)和\
日内轮动题材(通过日内指标 比如涨停板 比如db31 比如ggzj 比如bkzj) #\
\n\
解决版块池焦虑之:认识到什么行情(市场热度 市场高度 市场所处周期)下 版块轮动大概率的演变规律 #\
\n\
解决版块池焦虑之:能够通过实盘的各项指标 比较准确的判断题材的状态 #\
\n\
\n\
那么这里我搞定了版块池源 实时版块状态监控 不同行情时版块池的演变规律 \
那么拥有了这几个能力后确实没有焦虑的必要了#\
\n\
\n\
\n\
\n\
\n\
\n\
一些相关模板(有用的工具): #\
判断版块池是否轮动(支持全时区): sh/tips/run_xls_template.sh xx is_pool_rotate


