#
#Fri Feb 14 15:36:12 CST 2025
juben=pool-and-chain
title=chain实现过的所有pool算子汇总

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 pool-and-chain=41
no=31041

qianyan=本文给出chain实现过的所有pool算子汇总 #\
\n\
快速分析: sh/chain/gene/run_xls_template.sh xx fast_analyze_pool #\
\n\
\n\
更多?

