#
#Fri Feb 14 15:36:12 CST 2025
juben=pull
title=汇总当前系统中和pull相关的工具

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 zoushi=01 pull=07
# 为什么要配置为07 因为@engine/enum/analyze_enum.py 中pull=7
no=31007

qianyan=当前系统中pull的工具包含:#\
1 分析全市场的pull(25s左右)  ==> sh//hq/market/market_pull_analyze.sh #\
2 计算bkzj的pull数据(当前存在一些性能问题) ==> sh/hq/bkzj_pull.sh #\
3 计算某个题材的pull数据	   ==> sh/hq/xls_pull_analyze.sh xyz #\
\n\
\n\
对盘中来说 等待是一门艺术 提问:我当前的系统 具备这种等待的艺术吗? TODO:#\
\n\
\n\
\n\
\n\
一些零碎的命令(未来可能要清理的):#\
判断市场是否bkzj-pull-alot:  sh/if/check_if.sh market_bkzj_pull_alot.if#\
\n\
\n\
\n\
相关模板: #\
关于pull的确定性论述: sh/tips/run_template.sh pull_sure#\
\n\
\n\
参考文章: #\
<2026-07-18 意识到盘中pull价值巨大+加强盘中pull动员>


