#
#Fri Feb 14 15:36:12 CST 2025
juben=pull
title=汇总当前系统中和pull相关的工具

qianyan=当前系统中pull的工具包含:#\
1 分析全市场的pull(25s左右)  ==> sh//hq/market/market_pull_analyze.sh #\
2 计算bkzj的pull数据(当前存在一些性能问题) ==> sh/hq/bkzj_pull.sh #\
3 计算某个题材的pull数据	   ==> sh/hq/xls_pull_analyze.sh xyz #\
\n\
\n\
\n\
一些零碎的命令(未来可能要清理的):#\
判断市场是否bkzj-pull-alot:  sh/if/check_if.sh market_bkzj_pull_alot.if


