#
#Fri Feb 14 15:36:12 CST 2025
juben=pull-sure
title=关于pull的确定性的一些论述

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 7代表pull
# 为什么7代表pull 因为@engine/enum/analyze_enum.py 中pull=7
# 第4位和第5位数字组合代表了计算的类型 sure=01
no=31701

qianyan=关于pull的确定性的一些论述:#\
\n\
首先 其实pull这个图形 一般来说就已经提供了一些确定性 除此外(按照重要性排序): #\
盘中指数的快速上行 ->需要具备实时监控分析能力#\
盘中题材指数的快速上行 ->需要具备实时监控挖掘分析能力#\
早盘明显有资金进入/有热度的题材 ->需要对早盘盘面做出分析 且对题材具备一定的分析能力#\
早盘市场呈现出的明显风格(某种切片走出超出过往交易日的强度) ->需要对早盘盘面做出分析#\
早盘关于涨停板的图形模仿 ->需要对早盘盘面做出分析#\
日间+日内的组合图形(左侧思路) #\
主动性个股的主动拉升 -> 需要找到目标可能的主动性个股股票池#\
\n\
发现了吗 其实盘中真的有很多地方能够提供确定性... #\
(但是 这些都建立在自己具备了对应的能力 比如盘中指数快速上行需要具备对市场的监控能力 等等)#\
\n\
\n\
\n\
\n\
相关模板: #\
\n\
\n\
参考文章: #\
<2026-07-18 意识到盘中pull价值巨大+加强盘中pull动员>


