#
#Fri Feb 14 15:36:12 CST 2025
juben=puzhang+gaokai
title=普涨+高开行情的相关tips

qianyan=本文给出普涨+高开行情(注意和平开后黄白齐升走成普涨行情的区别)\
时的一些tips(不仅仅给出临盘的操作 还给出对普涨+高开行情的思考)#\
\n\
首先 普涨+高开行情在a股是特殊的 理由主要有以下几个:#\
1 普涨+高开行情一般伴随着放量 那么充足的流动性下必然蕴藏着更多的机会(和风险)#\
	-> 也因为常常伴随着高开 会稍微对我造成一些冲击#\
2 普涨+高开行情会因为处于不同的节奏和结构 会产生不同的演变结构#\
\n\
\n\
来论述一下为什么经常普涨高开的时候 是陷阱#\
1 从心理学的角度 如果是处于底部箱体一段时间 然后突然高开 此时散户想的是 我终于可以\
上车了 但左侧资金想的是 终于有人来给我解盘了 因此这自然会演变成高开兑现的走势#\
一个典型的例子就是 2026-06-12#\
\n\
既然普涨高开是陷阱 那么自然有以下推论:#\
普涨后卖出的资金 是否日内继续买入其它题材 决定了这一次普涨的本质 #\
如果资金卖出后 不再买入 那么就是一个非常典型的高开低走 此时自然就不是一个普涨行情了#\
如果资金卖出后 继续买入其它题材 那么最终就变成:普涨+切换的行情(2026-06-12)#\
\n\
鉴于上面的分析 可知对于一个“真普涨日” 那么比较好的策略 其实是等准盘中/盘中的买点 #\
(其实就是当前切换行情来做就行 ->其实比切换还要难 因为普涨行情的日内eva更难)#\
\n\
\n\
当然 上面论述的是那种有一定风险的普涨日 如果是处于上升期周期的普涨 那么又是另一个故事#\
\n\
\n\
相关的模板:#\
1 普涨行情时的买点策略: sh/tips/run_template.sh puzhang_buyer #\
2 相似的切换行情的策略: sh/tips/run_template.sh qiehuan



########################### 盘前时区
tips_plan={09:00:00,09:15:00}


########################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区#\
1 确定一下确实高开: sh/flush_cli.sh stocks:zhuli2 if2:gaokai_alot.if #\
2 是否放量: sh/template/run_template.sh market #\
\n\
还是提醒一下 当成切换行情来做 而切换行情 竞价是[不建议]做买点的

flush_jj={09:16:00,09:25:00}


########################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


eva_open={09:25:00,09:30:00}


########################### 早盘时区
tips_zao1={09:30:01,09:45:00}



