#
#Fri Feb 14 15:36:12 CST 2025
juben=puzhang
title=真普涨行情(不是普涨后高开低走 也不是普涨+切换)的相关tips

qianyan=真普涨行情#\
对真普涨的行情来说 看起来买点数量很多 但其实反而对图形的准确度要求很高,\
因此不能因为普涨行情就放松 因为图形的精准度当前相对是我的弱势#\
-> 普涨行情图形精准度高的底层逻辑就是辨识度#\
-> 其实不光对图形精准度要求高 对实盘的操作的手速也有一定的要求#\
如果对于图形的精准度没那么自信 可以把买点时区延后 做准盘中or盘中时区#\
\n\
\n\
具体的买点策略角度:#\
1 普涨行情实盘就对头部的图形做模仿买点也是一个有效的策略 底层逻辑是量化对普涨\
行情的策略中图形的买点权重比平常更高#\
2 就直接做前排的个股 底层逻辑是普涨行情不论是散户 游资都会更激进 因此前排个股\
容错率比平常更高#\
3 真普涨行情 机构很可能会大量进货 此时就做核心题材的前排amount\
个股(20260615就是具体的例子 可以看当日的复盘)#\
\n\
相关的模板:#\
1 普涨+切换行情: sh/tips/run_template.sh puzhang_gaokai #\
2 普涨买点策略: sh/tips/run_template.sh puzhang_buyer #\
3 强震荡行情:  sh/tips/run_template.sh qzhendang_buyer 



########################### 盘前时区
tips_plan={09:00:00,09:15:00}


########################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区#\
1 确定一下确实高开: sh/flush_cli.sh stocks:zhuli2 if2:gaokai_alot.if #\
2 是否放量: sh/template/run_template.sh market #\
\n\

flush_jj={09:16:00,09:25:00}


########################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


eva_open={09:25:00,09:30:00}


########################### 早盘时区
tips_zao1={09:30:01,09:45:00}



