#
#Fri Feb 14 15:36:12 CST 2025
juben=qianpai-buyer
title=对行情一无所知的时候 根据前排数据来设计买点策略

qianyan=本文根据实时的前排数据来设计买点相关策略(不知道选择哪个切片的前提下)tips#\
注意:因为本文假设对行情一无所知 因此基本就是会尝试各种方向的思路 因此实际适用的\
场景还是挺广泛的#\
注意:本文中题材和市场股票池的占比各自一半一半 因此给出的tips也是一半一半#\
\n\
如果根据实时的数据获取到了一些信息 也可以转头去找对应行情的买点tips#\
\n\
\n\
实际自己一般会尝试的几个思路:#\
1 config:top_amount代表的题材 #\
2 qpc:plan代表的股票池 #\
3 一些市场实时数据 比如:xls:fenshi*eva:upstp*eva:up#\
\n\
\n\
相关的模板:#\
1 根据行情给出买点策略: sh/tips/run_template.sh hq_buyer #\
2 给出全买点相关的tips: sh/tips/run_template.sh buyer


########################### 盘前时区
tips_plan={09:00:00,09:15:00}


########################### 竞价时区
tips_jj={09:16:00,09:25:00}

flush_jj={09:16:00,09:25:00}


########################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:#\
从题材的思路:#\
1 直接计算最前排的数据: \
sh/flush_cli.sh config:top_amount::tx:quanzhong trend3 #\
sh/pool/rup_alot.sh config:top_amount #\
\n\
从切片池的思路:#\
\n\
从市场级别股票池的思路:#\
sh/codes/analyze_pool.sh xls:fenshi*eva:upstp*eva:up7 #\
sh/codes/analyze_pool.sh amount30*eva:btw:min=3:limit=20 

eva_open={09:25:00,09:30:00}market:emotion.hist4,\
market:amounts.cross7[09:26:00,]


########################### 早盘时区
tips_zao1={09:30:01,09:45:00}



