#
#Fri Feb 14 15:36:12 CST 2025
juben=qiehuan-tips
title=切换行情的版块池相关tips

qianyan=切换行情的定义: 题材间的强烈切换(主要)+风格的切换(小概率)#\
切换行情时的基本特征: #\
1 指数角度:黄白分岔 or 黄线大涨 or 白线大涨#\
2 题材角度:有涨有跌 尤其很多时候是前日热门/近期主线的报团瓦解(这也是本文的主要内容)#\
\n\
\n\
\n\
这里详细说一下从bkzj的前排数据判定切换行情的思路:#\
1 本日bkzj前排数据 但尝试获取前日收盘失败的 那么显然这是一个切换题材 具体的命令为:#\
python realtime/candi/cli.py get bkzj.zhuli*stage:not:zijin:mode=cross #\
2 本日bkzj前排数据 成功拿到了前日收盘数据 但前日id<0.7的#\
python realtime/candi/cli.py get bkzj.zhuli*stage:zijin:mode=cross:max_idx=0.7#\
3 还有一个简单的 直接打开bkzj.cdandan数据: #\
python realtime/candi/cli.py get bkzj.cdadan:limit=20*stage:merge_left=0:zijin#\
sh/open/open_xls_list.sh bkzj.cdadan:limit=20 



tips_plan={09:00:00,09:15:00}

tips_jj={09:16:00,09:25:00}对切换行情来说 竞价时区的价值有限 但前排的版块池数据\
还是有一定的作用 包括:#\
1 高开的题材的数据量: 这能大致判定是否有多个题材高开 这可能是切换行情的前奏#\
python realtime/candi/cli.py get bkzj.index:limit=70:min=0.3#\
2 前排题材中有没有新轮动的题材: #\
python realtime/candi/cli.py get bkzj.index:limit=20:min=0.8*append_xls#\
3 手工刷新一下高权重的题材数据: #\
sh/flush_cli.sh config:top_amount::amount:limit=50 trend3

##################################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}



##################################### 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区是切换行情比较重要的 因此要重视这个时区#\
1 依旧是市场指标第一位: sh/template/run_template.sh market --day $day #\
2 bkzj的数据第二位(分析市场题材): sh/hq/zhendang/bkzj_top.sh --day $day #\
3 刷新一下qpc(如果真的切换行情 那么数据可能很好 可能很差): sh/flush_cli.sh qpc:plan trend3#\
4 手工刷新一下高权重的题材数据: #\
sh/flush_cli.sh config:top_amount::amount:limit=50 trend3


##################################### 早盘时区2
tips_zao2={09:40:00,10:00:00}早盘时区2,对于一个切换行情 市场很可能迎来第二次变化#\
1 有没有快速走强的题材:#\
2 手工刷新qpc: sh/flush_cli.sh qpc:plan trend3.hist#\
3 手工直接打开前日的大单题材: sh/open/open_xls_list.sh bkzj.cdadan:limit=15#\
4 手工刷新一下高权重的题材数据: #\
sh/flush_cli.sh config:top_amount::amount:limit=50 trend3

