#
#Fri Feb 14 15:36:12 CST 2025
juben=qiehuan
title=切换行情的临盘tips

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 1代表hangqing
# hq的enum见@engine/enum/hq_enum.py 
# 第4位和第5位数字组合代表了计算的类型 02=qiehuan
no=31102

qianyan=首先要明确,切换行情是一个出现几率不大的行情,但比较容易出现在\
某段行情(不论是白线还是黄线 还是某几个题材筹码高度集中)的尾声阶段,\
也容易出现在前日大涨或大跌的后一日#\
其次 切换行情的特征是非常突出的: 必须要伴随大量的资金切换 那么#\
要么有很多的涨停板#\
要么黄白线形成大分岔#\
\n\
出现切换行情时 最关键的是找到市场的风格和题材去向 因为做多资金是不缺的\
因此本模板也会着重于对市场风格的判断和实时题材的分析#\
\n\
注意:#\
1 切换行情必然迎来巨震#\
2 切换行情时盘前准备的东西(包括题材和切片池)很可能会失效 要相信实盘的指标 \
而不是自己盘前定制的数据的指标#\
\n\
\n\
一些相关的其它模板:#\
1 切换行情时的题材模板: \
open engine/observe/tips/template/qiehuan_pool.tips.properties 



tips_plan={09:00:00,09:15:00}

tips_jj={09:16:00,09:25:00}对切换行情来说 竞价时区的价值也有限 \
不过可以关注一下盘前定义切片池的波动性#\
sh/flush_cli.sh qpc:plan if2:shake_alot.if #\
sh/flush_cli.sh qpc:plan if2:rup2_alot.if #\
sh/flush_cli.sh qpc:plan trend3.hist #\
sh/flush_cli.sh config:top_amount::amount:limit=50 if2:rup2_alot.if #\
sh/flush_cli.sh config:top_amount::amount:limit=50 trend3.hist #\
以及通过bkzj数据看看有没有新的题材出来#\
python realtime/candi/cli.py get bkzj.top:limit=40*append_xls


# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘的时候 可以关注以下数据#\
1 市场级别的指标(上面论述过最准确): sh/template/run_template.sh \
market --day $day #\
2 直接看bkzj数据: python realtime/candi/cli.py get bkzj.top:limit=40*append_xls#\
sh/hq/zhendang/bkzj_top.sh --mode open #\
3 市场核心题材的头部amount数据: sh/flush_cli.sh config:top_amount::amount20 \
trend3 --day $day #\
4 直接分析市场涨停板: sh/codes/analyze_pool.sh xls:fenshi*eva:upstp #\
5 直接打开前日大单的指数k线(有一定的滞后性不推荐): sh/open/open_xls_list.sh \
bkzj.cdadan:limit=15 --day $day#\
6 盘前定义切片池的shake数据计算: sh/flush_cli.sh qpc:plan if2:shake_alot.if #\
\n\
且注意: 切换行情必然迎来巨震 因此要现在心态上做好准备


tips_zao1={09:30:01,09:45:00}早盘时区是切换行情比较重要的 因此要重视这个时区#\
1 依旧是市场指标第一位: sh/template/run_template.sh market --day $day #\
2 bkzj的数据第二位(分析市场题材): sh/hq/zhendang/bkzj_top.sh --day $day #\
3 涨停板的数据(上文说过切换行情必然包含大量涨停板): python realtime/stage/cli.py \
get xls:fenshi upstp.hist #\
4 基于涨停板的数据做一下大小票的风格分析: python realtime/stage/cli.py \
get xls:fenshi*eva:upstp shape_fenbu:amount #\
5 可以刷新一下盘前定义的切片池: sh/flush_cli.sh qpc:plan trend3



