#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-rank-overall
title=给出切片/股票池的rank(权重)总体论述(因为没有指定切片 因此纯论述 0计算)

qianyan=本文论述一下切片/股票池的rank内容#\
具体的代码见@engine/caop/buyers/generate/rank_enum.py #\
\n\
当前一共定义了10个级别:#\
0:LOWEST  ==> 最低等级的切片池 基本只能随市场的波动而波动/甚至\
市场走强 它都不会走强 完全没有主动性#\
1:LOW  ==> 低等级的切片池 有一定概率随着市场的走强而走强#\
2:NONE  ==> 默认等级切片池 极大概率能随着市场 题材的走强而走强#\
3:ZHONGJIAN ==> 题材中的中间个股#\
4:ZHUDONG ==> 有一定主动性/辨识度的股票池#\
--------------- 5以上的rank 是相对较高的权重了(能达到等级5就不错了)#\
5:POOL_TOP  ==> 一般题材的头部股票池|市场热门题材中的次头部股票池#\
6:REDU_POOL_TOP  ==> 市场中的热门题材的头部股票池#\
--------------- 这个级别以上 出现的概率比较小 很少能落到这个区间#\
7:MARKET_CI  ==> 全市场次顶级的股票池 但是不能无视行情 也不能带动市场#\
8:TOP_POOL_TOP  ==> 市场中最顶级的题材中的头部股票池 有一定几率无视行情#\
9:MARKET_TOP  ==> 全市场最顶级的最有影响力的股票池 能无视市场行情 甚至能带动市场#\
\n\
\n\
简单总结: #\
1 等级6及以上的概率很小 当然等级0出现的概率也不大 因此大部分股票池基本会落在[1,5]#\
2 等级6指的市场中的热门题材的头部股票池#\
\n\
\n\
\n\
\n\
手工计算应该走哪个tips模板(根据rank找到tips模板):\
python engine/codes/trend/tips_decider.py get xx rank#\
\n\
相关的模板: 



