#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-sure-overall
title=给出切片/股票池的sure(确定性)总体论述(因为没有指定切片 因此纯论述 0计算)

qianyan=本文论述一下切片/股票池的sure内容#\
具体的代码见@engine/caop/buyers/generate/sure_enum.py #\
\n\
\n\
切片的确定性 本身应由日间走势+日内走势形成的状态图+切片的权重共同形成#\
当然 因为这种确定性不好准确定义 因此这里暂时只简单的分成1 2 3 4 4种简单等级#\
后续有更好 更准确的思路 再来做更多的细分划分 #\
\n\
0:LOWEST #\
1:LOW  #\
2:MID  #\
3:HIGH #\
4:TOP #\
\n\
\n\
\n\
相关的模板: #\
关于切片的rank(权重)的一般论述: sh/tips/run_template.sh qp_rank_overall#\



