#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-trend-overall
title=给出切片/股票池的trend(走势)总体论述(因为没有指定切片 因此纯论述 0计算)

qianyan=本文论述一下切片/股票池的trend内容#\
\n\
切片的trend是一个比较复杂的问题 因为切片本身是非常多样性的 包括最基础的切片的大小 \
逻辑性 也包括高级属性:切片的rank 切片的sure#\
本文当然做不到面面俱到 因此对问题做一个缩小 即本文不讨论大切片的trend问题#\
\n\
先来论述一下和切片的trend相关的几个核心要素:#\
切片的rank #\
切片的日间+日内形成的状态图 #\
切片的聚合性(如果是单一题材那么没有问题 如果是多个题材组合形成的 那么存疑)#\
	-> 为了简化讨论 默认切片具备较好的聚合型#\
\n\
而研究切片的trend的意义 其实最终还是为了买点 包括:#\
切片有没有风险 #\
切片的择时 #\
买点图形的选择 #\
\n\
而且认识到 上面提到的核心要素能够直接决定风险 择时和买点图形 举个例子 对于一个高权重\
的切片来说 是允许早盘是有一定的分歧的 此时不过影响到了择时和图形 #\
但相同情况下 如果是一个权重很低的切片 且早盘分歧 那么基本这个切片就需要淘汰掉了#\
\n\
(综上 切片的trend其实就是一个典型的状态图决策的信息 因此\
要从状态图的角度来思考trend 当然从代码的角度 我也要实现对应的状态图)#\
\n\
另外一个切片trend的意义: 是为了和日间trends 切片的rank一起共同决定切片的sure#\
(当然了 这个sure信息 其实最后还是为了买点)#\
\n\
\n\
\n\
相关的模板: #\
关于切片的rank(权重)的一般论述: sh/tips/run_template.sh qp_rank_overall#\
一无所知 无脑计算trend: sh/template/run_xls_template.sh xx trend#\
\n\
已经有了切片 #\
一般论述: sh/tips/run_xls_template.sh xx qp_trend_overall #\
有一定权重的rank的切片: sh/tips/run_xls_template.sh xx qp_trend_rank_alot



