#
#Fri Feb 14 15:36:12 CST 2025
juben=quedingxing
title=给出市场确定性相关的tips

qianyan=本文讨论一下市场的确定性#\
市场的确定性其实是a股中一个比较复杂 但又无比重要的内容,重要的原因\
是如果是一个确定性稀缺的行情下实际会在临盘时非常扰动我的心神,而另一点\
是确定性本身就是买点的逻辑基点#\
\n\
那么从哪里开始分析好呢?#\
周期的力量/k线的图形: 虽然看起来是玄学 但周期的力量绝对会影响市场 此时\
根据k线的图形能大致判断市场所处的周期 然后大致给出当日的预期#\
\n\
市场本身是资金行为 那么主导市场的资金力量会影响确定性 那么这个角度下,#\
1 扎堆/报团的资金会影响到市场 是继续加强 还是切换 最差的就是直接抛盘#\
    -> 这个角度下 对市场资金核心扎堆的地方要做好监控(需要我盘前做一些工作)#\
    -> 因为我左右不了资金的选择 我只能从右侧的角度来对资金进行监控#\
2 国家队的控盘: 国家队的控盘不光体现在日内的k线 其实从收盘时的主力资金\
的连续的行为 也能大致判断市场所处的阶段(进攻/盘整/刻意的下跌) 国家队的\
意志 绝对也是a股中不可忽视的力量#\
\n\
总结一下上面的内容 就是#\
1 先大致判断好市场的阶段(通过k线周期和主力资金连续多日数据)来给出预期#\
2 临盘对市场的核心资产(报团继续/切换/抛盘)和主力意志做好监控#\
	-> 注意这里报团包括了题材报团和少量个股报团#\
3 在1和2的基础上 再去判断资金的去向(如果是走报团要分辨报团的类型) 这本身\
属于技术层面的问题 重点考验临盘时的锚定能力了#\
\n\
当然 最省心的情况就是市场行情太好了 以至于不需要做确定性分析/确定性太充裕了#\
\n\
本文是统筹性质的文章,具体到每种不同的行情 那么有对应的tips文件 包括:#\
1 震荡(中性/强势)行情:#\
2 切换行情:#\
3 低开/弱震荡行情:


tips_plan={09:00:00,09:15:00}

tips_jj={09:16:00,09:25:00}

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

tips_zao1={09:30:01,09:33:00}
