#
#Fri Feb 14 15:36:12 CST 2025
juben=qzhendang-buyer
title=强震荡行情的买点相关tips

qianyan=对于强震荡行情来说 不应该在行情的验证上花费太多的精力\
因为强震荡行情买点数量非常多 需要全力来准备买点的工作#\
\n\
不过还是有一些事情需要注意:#\
1 对强震荡行情来说 买点最好提前: 因为强震荡行情其实是可以预期的 而如果买点择时\
还要参考临盘指标的话 那么必然会错过很多更低的买点#\
	-> 从这个角度 强震荡行情(和其他行情不同)的竞价和开盘时区 都是有价值的#\
2 即使是强震荡行情 也会有一定的偏好(大票小票 题材) 因此临盘需要快速判定市场偏好\
然后下手要快,因为强震荡行情不会等你#\
\n\
从具体策略上说 强震荡行情有以下多种选择:#\
1 实时走的好的指数的指数套利#\
2 盘前就配置的好的切片池 选择一个(最多2个 我没有能力做更多)做买点#\
3 题材买点也是可选项




tips_plan={09:00:00,09:15:00}

########################### 竞价时区
tips_jj={09:16:00,09:25:00}对强震荡行情来说 竞价时区就有很高的价值了#\
1 判断市场风格偏好: sh/flush_cli.sh qpc:plan fronts_fenbu:jiasu#\
sh/qpc/find_fronts.sh qpc:plan jiasu#\
2 找一些有辨识度的图形(也要注意到计算结果不如开盘的价值高): \
sh/qpc/find_fronts.sh qpc:plan bsd#\
3 直接查看有没有明显高开的指数: sh/open/open_xls_list.sh index 

flush_jj={09:16:00,09:25:00}if get_candi:qpc:plan then \
qpc:plan->trend3.hist[09:20:00,]#\
stocks:dapiao->trend3.hist[09:20:00,]


########################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}对强震荡行情来说 开盘时区几乎必然伴随\
大量买点 此时保持心理层面的稳定是更关键的事情#\
\n\
买点的角度 对于具体的股票池 买点被我写在了单独的qp-qzhendang-buyer.tips中#\
\n\
而对于切片池#\
判断切片的偏好(这里其实要求在竞价的时候就判定了): sh/flush_cli.sh qpc:plan \
fronts_fenbu:jiasu#\
sh/flush_cli.sh qpc:plan fronts_fenbu:jj_bad#\
\n\
直接查看有没有明显高开的指数: sh/open/open_xls_list.sh index#\
市场大票是否有买点机会: sh/flush_cli.sh stocks:dapiao trend3.hist#\
查看开盘时的bkzj数据: sh/hq/zhendang/bkzj_top.sh  


eva_open={09:25:00,09:30:00}xls:fenshi->trend3.hist



########################### 早盘时区
tips_zao1={09:30:01,09:45:00}



