#
#Fri Feb 14 15:36:12 CST 2025
juben=realtime-pool-silu-none
title=实盘没有明显思路时可以尝试的一些pool相关命令tips

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表no-need-xls 5代表qp-xls-sub 7代表builded
# 第4位和第5位数字组合代表了计算的类型 pool-silu=21
no=31021

qianyan=本文给出一些实盘没有明显思路时可以尝试的一些pool相关命令tips#\
包括: #\
1 前日bkzj cdadan版块池 绝对是可以观测市场行情的利器 #\
比如 直接做bkzj的实时数据监控: \
sh/tips/run_xls_template.sh bkzj.cdadan:limit=15 pool_tracing_bkzj #\
2 通过bkzj进行实时数据挖掘角度 #\
3 热门题材池的角度: #\
比如 直接计算rup-alot: sh/pool/rup_alot.sh redu #\
python realtime/stage/cli.py gets redu --sort success if2:rup5_alot.if 

tips_plan={09:00:00,09:15:00}


# ================================== 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区

# ================================== 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区


# ================================== 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区



