#
#Fri Feb 14 15:36:12 CST 2025
juben=remen-pool-tips
title=从[市场中的热门题材池]视角来操盘的相关tips

qianyan=热门题材的定义其实不需要我阐述: 资金扎堆/机构报团的题材#\
\n\
\n\
\n\
从bkzj的数据来寻找热门题材池的思路:#\
1 题材多次命中zijin-alot#\
2 昨天刚刚进入到热门题材行列的: 



tips_plan={09:00:00,09:15:00}盘前是最适合寻找热门题材池的时区#\
1 题材多次命中(4天3次)zijin-alot: python realtime/candi/cli.py get \
bkzj.cdadan:limit=30*stage2:if_size:min_size=3:if_zijin_alot.days4 --mode plan


tips_jj={09:16:00,09:25:00}

##################################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}



##################################### 早盘时区
tips_zao1={09:30:01,09:45:00}


##################################### 早盘时区2
tips_zao2={09:40:00,10:00:00}

