#
#Fri Feb 14 15:36:12 CST 2025
juben=safe
title=安全性相关的临盘tips

tips_plan={09:00:00,09:15:00}市场的安全性是一个比较复杂和高难度的问题#\
总体来说 市场的安全性由以下几个要素来构成#\
1 指数的位置 这个没什么好说的指数位置永远是有价值的#\
2 市场的黄白线的走势：这个也非常权威 代表量化和主力的意志 只不过有一定的滞后性#\
3 市场的核心题材(高位+大成交)的题材的走势#\
4 市场级别股票池的走势#\
5 市场涨停板的数据：这个也是比较细化的数据

tips_jj={09:16:00,09:25:00}对于大波动的交易日来说 竞价时区的有效价值不高#\
如果真要看一些数据 关注一下市场级别股票池的波动性 市场核心题材的波动性数据就够了


# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘的时候 可以关注以下数据#\
1 市场的量能和涨停板: sh/template/run_template.sh market --day $day #\
2 市场核心题材的头部amount数据: sh/flush_cli.sh config:top_amount::amount30 trend3 --day $day #\
3 市场级别切片池数据: sh/template/run_xls_template.sh amount30*tx:bsd trend --day $day #\
4 直接打开前日大单的指数k线(有较强滞后性不推荐): sh/open/open_xls_list.sh bkzj.cdadan:limit=15 --day $day


tips_zao1={09:30:01,09:33:00}
