#
#Fri Feb 14 15:36:12 CST 2025
juben=safe2
title=更细的临盘safe指标tips(注意 因为比较复杂 本模板下的指标并不能完全进行保证)

tips_plan={09:00:00,09:15:00}市场的安全性是一个比较复杂和高难度的问题#\
当前在safe tips中是存在很多的指标 但那些指标是比较粗糙的 因此本模板下实现更详细的指标 #\
并且会是主要以核心市场股票池的一些细分指标来判断是否safe

tips_jj={09:16:00,09:25:00}

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

tips_zao1={09:30:01,09:43:00}早盘是极其关键的时区 这里主要以amount30为基础来尝试判定#\
1 amount30的加速日间对比数据: python realtime/stage/cli.py get amount30*tx:bsd \
fronts_fenbu:jiasu.cross3 --day $day#\
python realtime/stage/cli.py get amount30*tx:bsd fronts_fenbu:jiasu.hist --day $day#\
2 amount30+trd2(走势好的个股的迅速走弱更能说明问题)的risk日间对比数据: python \
realtime/stage/cli.py get amount30*trd:min=0 risk_fenbu.cross --day $day #\
python realtime/stage/cli.py get amount30*trd:min=0 risk_fenbu.hist --day $day#\
3 最简单的直接计算amount30的数据: sh/template/run_xls_template.sh amount30*tx:bsd \
trend --day $day



