#
#Fri Feb 14 15:36:12 CST 2025
juben=short-buyer
title=关于短链路买点的一般论述

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 6代表short
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=81600


qianyan=关于短链路买点的一般论述#\
\n\
对于短链路来说 对行情的判断(进而找到买点思路/机会)是最重要的 也是最大的难点#\
一般有以下思路: #\
借助指数(盘中/准盘中)的拉升#\
\n\
\n\
\n\
\n\
一些相关的其它模板: 



