#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出BK0821(MSCI)实时强度很强时的思路

# 当MSCI强度很强的时候 走的特化分支

# no的赋值规则见@engine/enum/no_rule_enum.py 
# silu(第3位数字)的赋值规则见@engine/enum/silu_enum.py 
# 6代表silu 1代表tips.properties 9代表spec-codes 所以前3位是固定的
# 第4位和第5位数字组合代表了计算的类型  MSCI=07 MSCI-is-hot=072
no=619072

functions=codes_shape
before_func=init_codes_no_if($day),init_evas_no_if($day)

if=codes_no_recorder_inited

functions=codes_shape
before_func=init_codes_no_if($day),init_evas_no_if($day)

if=codes_no_recorder_inited

qianyan=本tips给出BK0821(MSCI)实时强度很强时的思路(盘前思路 \
临盘操作思路 股票池的属性分析) #\
\n\
\n\
总体思路 因为我已经开发出了@xx_silu_MSCI_sub.tips.properties \
所以可以借助切片来应对is-hot的情况 #\
具体来说: #\
叠加BK1633(高震幅): sh/tips/run_xls_template.sh BK0821*BK1633 silu_MSCI_sub#\
实时rup2: sh/tips/run_xls_template.sh BK0821*eva:rup2 silu_MSCI_sub#\
一定的箱体辨识度: sh/tips/run_xls_template.sh BK0821*no30100 silu_MSCI_sub#\
叠加实时ggzj: sh/tips/run_xls_template.sh BK0821*eva:ggzj2 silu_MSCI_sub#\
\n\
\n\
相关模板: #\
打开原始模板: sh/tips/run_template.sh silu_MSCI

tips_plan={09:00:00,09:15:00}盘前的实现直接复用: \
sh/tips/run_template.sh make_plan_MSCI    

eva_all={09:15:00,23:59:59}BK0821->trend3.days[09:22:00,],\
BK0821->trend3.hist[09:25:00,],\
BK0821*eva:rup2*eva:up0==split_pool.ana[09:22:00,],\
zhushi:版块池分析,\
BK0821->if2:rup2_alot.if[09:20:00,],\
BK0821->if2:rup3_alot.if[09:20:00,],\
BK0821->if2:rup5_alot.if[09:20:00,],\
BK0821*xls:ggzj->btwed,\
BK0821->eva-ggzj2*btwed[09:30:01,],\
BK0821->btw:limit=20:asc=0

