#
#Fri Feb 14 15:36:12 CST 2025
juben=tips
title=汇总一下一些spec-codes特殊市场级别的股票池的思路列表

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 tips=99 spec-codes-silu=10
no=31015

functions=build_pool
before_func=build_pool_codes(context,"list:BK1717,BK1633")[09:15:00,]

qianyan=本文汇总一下当前的特殊股票池的思路的导航 #\
\n\
\n\
BK0821:MSCI中国(560+) ==> sh/tips/run_template.sh silu_BK0821 (全时段)#\
BK1633:昨日高震幅(150~450): 每天都会更新 ==> sh/tips/run_template.sh silu_BK1633 


