#
#Fri Feb 14 15:36:12 CST 2025
juben=test
title=这是一个测试文件

tips_jj={09:16:00,09:25:00}这是竞价时区的信息
tips_jj2={09:16:00,09:25:00}竞价2
eva_jj={09:16:00,09:25:00}

tips_all={00:00:00,23:59:59}测试一下func的用法 $current_cid1($day)#\
然后是一个无效调用 $current_cid100($day)

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区的消息#\
开盘的时候需要关注什么呢

tips_zao1={09:30:01,09:33:00}开盘前3min

# 无效的tips 因为没有指定有效的时间戳
tips_blank={}
