#
#Fri Feb 14 15:36:12 CST 2025
juben=three-options-buyer
title=3种买点选择

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 5代表论述
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 
no=81500


qianyan=本文论述一下3种买点链路的选择#\
参考文章<2026-07-09 3个选择(买点链路)> #\
\n\
3种选择都是考虑了实战的可行性提出的 具体包括: #\
1 那么我要么从超短(最短 不是超短股票池)链路突破(指数抬升 图形极好) -> 标准的右侧买点思路#\
2 要么从市场级别的切片 can be buyer -> 相当于左侧买点的左侧切片 先有切片再临盘判断行不行#\
3 要么突破题材买点(已经根据实盘信息确定了题材)	-> 左侧+右侧混合买点思路#\
\n\
很容易想到的是 对于某个交易日来说 至少能命中其中一个选择 #\
\n\
\n\
\n\
\n\
\n\
一些相关的其它模板: 



