#
#Fri Feb 14 15:36:12 CST 2025
juben=tips
title=对当前所有的模板做一个系统汇总

qianyan=对当前所有的模板做一个系统汇总#\
1 对市场走势(注意和行情的区别)的汇总	 ==> sh/tips/run_template.sh zoushi #\
2 对买点的汇总     	  ==> sh/tips/run_template.sh buyer #\
3 对市场行情的汇总		  ==> sh/tips/run_template.sh hangqing #\
4 根据不同的行情选择买点 ==> sh/tips/run_template.sh hq_buyer #\
5 pull相关的汇总		  ==> sh/tips/run_template.sh pull#\
\n\
\n\
\n\
对题材相关的模板:#\
1 如果对题材一无所知 可以:  ==> sh/tips/run_xls_template.sh xx none_xls#\
2 关于题材状态的总体论述	==> sh/tips/run_template.sh xls_state #\
3 关于题材锚定的总体论述   ==> sh/tips/run_template.sh xls_maoding #\
4 给出题材最基本的信息 比如数据量 过去几天的bkzj数据等 ==> \
sh/tips/run_xls_template.sh xx basic_xls#\
\n\
\n\
\n\
锚定部分(锚定甚至是实盘最重要的数据了):#\
1 市场实时锚定->pool(逻辑) ==> sh/tips/run_template.sh maoding_to_pool#\
2 对指定切片能否用作锚定的一般论述 ==> \
sh/tips/run_template.sh codes_can_be_maoding#\
\n\
\n\
\n\
题材池相关:#\
1 掌控题材池的一般论述  ==> sh/tips/run_template.sh master_pool_overall#\
\n\
\n\
\n\
切片相关:#\
1 掌控切片的一般论述 ==> sh/tips/run_template.sh master_qp_overall#\
2 关于切片的rank(权重)的一般论述 ==> sh/tips/run_template.sh qp_rank_overall#\
3 关于切片的trend的一般论述 ==> sh/tips/run_template.sh qp_trend_overall



