#
#Fri Feb 14 15:36:12 CST 2025
juben=unknown_xintai
title=盘前确定性很低时的心态相关的tips

qianyan=在不确定极高的行情的时候 心态是对我来说考验最大的 因为我在心理层面\
对市场掌控力有变态级别的需求#\
\n\
那么怎么和这种不确定的行情相处呢?可以有以下思路:#\
1 加强不确定行情中的确定性挖掘 比如盘前加强对市场的逻辑梳理(通过对核心切片池\
的分析,对核心题材的日间数据分析) 加强临盘时对各种锚定数据的权重(比如临盘\
涨停板的分析)#\
	-> 这个思路其实就是在不确定强的行情的时候 硬钢 来加强确定性#\
2 把操作时区往后延 延后到准盘中和盘中 然后早盘多看少动+相信自己的盘中能力\
这要求我在准盘中和盘中依旧保持足够的精力和心力 注意力 (需要时刻提醒自己)#\
	-> 这个思路其实就是不硬钢 绕过高不确定性的时区


tips_plan={09:00:00,09:15:00}

############################## 竞价时区
tips_jj={09:16:00,09:25:00}对不确定性高的行情来说 竞价时区需要关注\
那些更高等级的确定性数据 比如涨停板 比如高权重个股的超预期强势数据 其他\
低权重的数据就可以无视了

eva_jj={09:16:00,09:25:00}



############################## 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区#\
在一个不确定的行情下 开盘时区的数据重要性是不高的 毕竟随时都能巨变 \
但也不是什么都不需要关注 可以关注一些极值的数据 比如:#\
1 市场核心票的头部top和底部risk数据: 至少能大致看出一点苗头#\
sh/flush_cli.sh qpc:plan fronts_fenbu:jj_bad #\
2 题材的角度 也是一样 也要关注题材中的头部和底部数据 看全指标是不够的#\
sh/flush_cli.sh config:top_amount::amount:limit=60 fronts_fenbu:jj_bad#\
3 可以从大票的角度 看看有没有突然走强的个股: sh/flush_cli.sh \
stocks:dapiao eva_size:eva_type=baov#\
sh/flush_cli.sh stocks:dapiao fronts_fenbu:jiasu#\
\n\
还是要提醒 #\
1 不确定行情下 开盘价值不高 保留精力给准盘中/盘中来战斗是必须要做到的#\
2 自己临盘对确定性需求很高 但在不确定的行情的时候 必须要压制自己的\
这种胡思乱想念头 更不能乱了方寸 安心等待市场的博弈

eva_open={09:25:00,09:30:00}

flush_open={09:25:00,09:30:00}


# 
############################## 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区#\
早盘时区市场的激烈博弈就开始了 此时可能会出现很多混乱的情况 比如:#\
1 整体指数不显山不漏水的 但其实题材发生剧烈的波动,#\
2 指数往下波动 但其实涨停板非常的健康#\
\n\
总之 为了应对这种高不确定 需要去关注更极端的数据 比如:#\
1 涨停板/跌停板数据是否健康 sh/template/run_template.sh market#\
2 市场核心股票池是否健康(关注极弱风控数据)#\
3 是否存在前排辨识度的题材: sh/hq/zhendang/bkzj_top.sh#\
\n\
如果市场出现投机/极端行情 心态千万不能乱#\
如果心态乱了 也要快速整理 收拾心情准备盘中的战斗  

eva_zao1={09:30:01,09:45:00}xls:fenshi->upstp.hist

flush_zao1={09:30:01,09:45:00}



