#
#Fri Feb 14 15:36:12 CST 2025
juben=upstp-to-pool
title=根据实时涨停板生成pool

start=09:16:00

try_save_to_chain=1
chain_node=analyze_hq

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 1代表tips.properties 1代表hq-to-pool
# 第4位和第5位数字组合代表了计算的类型 overall=00 upstp-to-pool=20
no=71120

qianyan=根据实时涨停板生成pool #\
\n\
当前设计了以下角度的涨停板: #\
1 全市场 #\
2 BK1633 #\
3 超短 #\
\n\
其实还可以有更多的角度 比如小票 大票 券商等....   TODO: #\
\n\
\n\
在拿到版块池以后 可以: \
sh/chain/gene/run_xls_template.sh xx fast_analyze_pool --time_str $time_str 



################### 最开头的前序eva计算
eva_normal={00:00:00,23:59:59}print:全市场涨停板可控的分支,\
if xls:fenshi->upstp*filter:min=40 then break,\
zhushi:如果实时涨停板太多 那么不走这个分支,\
xls:fenshi->upstp,back=append_xls2

eva_chaoduan={09:00:00,23:59:59}print:超短涨停板分支,\
db21->upstp*ban_size,back=append_xls2,\
if db51->upstp*filter:min=5 then db51->upstp*ban_size,back=append_xls2

eva_BK1633={09:00:00,23:59:59}print:BK1633涨停板分支,\
if new:BK1633*filter:max=10 then break,\
zhushi:做一下基础的BK1633校验,\
BK1633->upstp,back=append_xls2

