#
#Fri Feb 14 15:36:12 CST 2025
juben=weak-duikang
title=弱势行情的心理/操作的对抗tips

qianyan=弱势行情的时候 心理层面的对抗甚至是更重要的 而这个说起来容易做起来难,\
因此本模板会关注于如何实现对抗#\
\n\
注意:尽管需要做好心理层面的对抗 要保持信心 然而实盘的时候 也需要盘面上的积极信号\
来支撑 也就是需要现实来支撑 而不是蛮干



tips_plan={09:00:00,09:15:00}

############################## 竞价时区
tips_jj={09:16:00,09:25:00}对弱势行情来说 竞价时区就应该开始找盘面上的积极信号\
包括:#\
1 寻找qpc上的积极信号(且需要持续跟踪): sh/qpc/find_fronts.sh qpc:plan jiasu#\
2 寻找市场指数上又没有逆势走强的: sh/open/open_xls_list.sh index#\
\n\
注意: 要做好弱势行情的对抗 就需要在心理层面屏蔽掉那些走的极差的数据而去找积极的信号,\
否则很容易被干扰

eva_jj={09:16:00,09:25:00}


############################## 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

eva_open={09:25:00,09:30:00}

flush_open={09:25:00,09:30:00}




# 
############################## 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区是弱势行情比较重要的 甚至就是最重要的#\
1 找到切片池中相对更强的数据: sh/flush_cli.sh qpc:plan fronts_fenbu:jiasu#\
2 逆势涨停板分析: sh/codes/analyze_pool.sh xls:fenshi*eva:upstp#\
python realtime/stage/cli.py get xls:fenshi upstp.hist #\
3 有没有逆势的指数: python realtime/observe/index.py get#\
4 通过bkzj找到逆势题材(同时判定有没有一家独大结构): sh/hq/weak/bkzj_top.sh#\
\n\
还是要提醒 不要被盘面的下跌吓到 要把100%的精力都专注于寻找盘面上的机会上 


flush_zao1={09:30:01,09:45:00}

############################## 早盘时区2
tips_zao3={09:42:01,09:59:00}运行到接近准盘中的时区了 \
此时盘面可能会发生新变化 此时可以:#\
1 qpc中相对更强的切片: sh/flush_cli.sh qpc:plan trend3.hist#\
sh/flush_cli.sh qpc:plan fronts_fenbu:jiasu#\
2 寻找bkzj中有没有明显拉升的数据(仅45分以后): sh/hq/bkzj_pull.sh 


