#
#Fri Feb 14 15:36:12 CST 2025
juben=weak
title=弱势行情的临盘tips

qianyan=这里先定义一下什么是弱势(weak)行情#\
弱势行情这里只有2种:低开低走|平开低走(低开高走这里不算弱势行情)#\
\n\
对弱势行情来说 需要关注2个点:#\
1 尽量更早的准确判定市场弱势#\
2 更好的应对市场: 操作上+心理对抗上,#\
	-> 其实在弱势行情中 心理的对抗是特别重要的 能不能对抗市场环境 \
然后有心力进行操作 是比较关键的#\
	-> 临盘的时候 无论什么行情下保持心理的稳定都是非常关键的 尤其如果弱势的话#\
\n\
其实要认识到 无论多差的行情(除非市场真的崩了) 只要资金充沛 就不缺机会\
因此弱势行情的时候 更需要去找市场中逆势的题材/个股\
\n\
注意:本模板中很大的精力花在了确认weak上 应对的部分略有不足 可以考虑打开版本2: \
sh/tips/run_template.sh weak2#\
\n\
相关的其它模板:#\
1 对抗弱势行情: sh/tips/run_template.sh weak_duikang


tips_plan={09:00:00,09:15:00}

############################## 竞价时区
tips_jj={09:16:00,09:25:00}对弱势行情来说 竞价时区的价值相对是好的 \
正如前文说到的 我希望更早的准确判断市场是弱势 而竞价时区是有一定的数据能挖掘到的#\
\n\
比如:#\
1 市场的大体走势 python realtime/stage/cli.py get xls:fenshi trend3.hist#\
2 直接看10cm的最差的数据: python realtime/stage/cli.py get 10cm fronts_fenbu:jj_bad #\
3 直接看qpc:plan的弱势数据: sh/flush_cli.sh qpc:plan trend3.hist #\
sh/flush_cli.sh qpc:plan fronts_fenbu:jj_bad#\
4 直接打开前日大单的指数k线(有一定的滞后性不推荐): sh/open/open_xls_list.sh \
bkzj.cdadan:limit=15 

eva_jj={09:16:00,09:25:00}market:emotion.hist4[09:21:00,]


############################## 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘的时候 可以关注以下数据

eva_open={09:25:00,09:30:00}market:emotion.hist4

flush_open={09:25:00,09:30:00}if get_candi:qpc:plan then qpc:plan->trend3.hist




# 
############################## 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区是弱势行情比较重要的 \
因为很多时候是早盘快速走弱的(竞价开盘是看不出来的) 因此要重视这个时区#\
还是要啰嗦一句 弱势行情的时候 心理层面的对抗/信心的不灭是非常关键的#\
\n\
0 市场是第一指标: sh/template/run_template.sh market #\
1 直接关注bkzj的risk数据: sh/hq/weak/bkzj_risk.sh \n\
2 直接看qpc:plan的弱势数据: sh/flush_cli.sh qpc:plan trend3.hist#\
3 直接看市场小票的下跌数据: sh/flush_cli.sh stocks:xiaopiao trend3.hist#\
sh/flush_cli.sh stocks:xiaopiao::eva:btw:max=-2 if2:lianghua_drop_alot.if#\
\n\
\n\
然后是应对这个弱势 可以做的一些操作(上面说过 心理层面必须要做好对市场的对抗):#\
1 找到切片池中相对更强的数据: sh/flush_cli.sh qpc:plan fronts_fenbu:jiasu#\
2 逆势涨停板分析: sh/codes/analyze_pool.sh xls:fenshi*eva:upstp#\
3 有没有逆势的指数: python realtime/observe/index.py get#\
4 通过bkzj找到逆势题材(同时判定有没有一家独大结构): sh/hq/weak/bkzj_top.sh 


flush_zao1={09:30:01,09:45:00}if get_candi:qpc:plan then qpc:plan->if2:dstp,\
if get_candi:qpc:plan then qpc:plan->if2:lianghua_alot.if



