#
#Fri Feb 14 15:36:12 CST 2025
juben=weak-buyer
title=弱势行情的买点相关tips

qianyan=本文给出弱势行情时的买点相关策略(不知道选择哪个切片的前提下)tips#\
注意:弱势行情的时候 心态也特别的重要(行情差的时候很容易搞心态) 可以:\
sh/tips/run_template.sh weak_xintai#\
sh/tips/run_template.sh weak_duikang (对抗弱势行情 和本文的内容可以很好的协作)#\
\n\
\n\
下面给出弱势行情的大致买点策略:#\
1 寻找报团: 题材 or 报团个股 #\
2 寻找逆势力量: 也许存在我不知道的某个消息/逻辑能够推动个股逆势 或者纯图形非常好#\
3 耐心等盘中/等抄底#\
\n\
\n\
总的来说 弱势行情买点数量会明显减少 如果选择保守的策略 就等市场回暖or稳定下来#\
\n\
\n\
相关的模板:#\
1 指定切片后给出weak买点策略: sh/tips/run_xls_template.sh xx qp_weak_buyer



########################### 盘前时区
tips_plan={09:00:00,09:15:00}


# 缺逆势fronts?		TODO:
########################### 竞价时区
tips_jj={09:16:00,09:25:00}对一个弱势行情 竞价时区是有价值的 因为很多个股\
在竞价的时区就已经体现出逆势的特征了#\
1 直接刷新qpc: sh/qpc/find_fronts.sh qpc:plan bsd#\
sh/qpc/find_fronts.sh qpc:plan jiasu#\
sh/qpc/find_fronts.sh qpc:plan good (2/3日不错的图形)#\
sh/qpc/find_fronts.sh qpc:plan good5 (5日不错的图形 这个效果较好)#\
sh/flush_cli.sh qpc:plan eva_size:eva_type=jj_rzq:min=1.8#\
2 直接查看市场级别股票池的前排数据:\
sh/flush_cli.sh stocks:zhuli2 eva_size:eva_type=up2#\
3 有没有逆势强势的题材: \
sh/flush_cli.sh config:top_amount::amount:limit=50 trend3

flush_jj={09:16:00,09:25:00}


########################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


eva_open={09:25:00,09:30:00}


########################### 早盘时区
tips_zao1={09:30:01,09:45:00}



