#
#Fri Feb 14 15:36:12 CST 2025
juben=weak-xintai
title=弱势行情的心态(心理对抗)tips

qianyan=弱势行情的时候 心理层面的对抗甚至是更重要的 #\
虽然面对弱势行情 心理层面的对抗很重要 但还是要尊重盘面(需要盘面的事实证明)#\
\n\
为什么弱势行情依旧可以操作 底层逻辑是资金形成或大或小的报团,具体的形式:#\
1 抱团在某个题材/某几个题材#\
2 抱团在某些市场级别个股: 这个逻辑也是很硬的 毕竟个股的报团是通过多个交易日\
持续的走势来形成的#\
在极端情况下 可以认为只有极端的市场崩盘时 才不存在对抗策略#\
\n\
从这个角度 本模板下的目标就是去寻找盘面中那些报团的力量:题材or个股#\
\n\
\n\
且对自己的买点还是要保持基本的信心 也就是只要盘面上还有超过1000+红盘 \
就可以大胆的干(对自己的买点能力保持完全的自信)#\
当然 也要尊重盘面 不要意淫 #\
在保持自信的同时 也要尊重盘面 要做好两者的平衡



tips_plan={09:00:00,09:15:00}

############################## 竞价时区
tips_jj={09:16:00,09:25:00}

eva_jj={09:16:00,09:25:00}


############################## 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

eva_open={09:25:00,09:30:00}

flush_open={09:25:00,09:30:00}




# 
############################## 早盘时区
tips_zao1={09:30:01,09:45:00}


flush_zao1={09:30:01,09:45:00}

############################## 早盘时区2
tips_zao3={09:42:01,09:59:00}


