#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-cross-state-overall
title=关于题材日间状态的一般论述(没有指定具体的版块)
category=analyze


# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice/lunshu 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 zoushi=01 xls-cross-state=21
no=31021

qianyan=本文给出一下关于题材日间状态的一般论述#\
\n\
参考文章: <2026-07-12 状态图思路尝试解决题材的日间状态问题>#\
题材的日间状态主要包括以下: #\
rank：权重 #\
pos：绝对的位置高度(过去20个交易日来衡量) #\
trends：过去4/5个交易日的题材走势数据 #\
trend: 前一日的基本状态 #\
zijin: 前一日的资金的行为描述	#\
sure：确定性 #\
\n\
\n\
\n\
\n\
相关的模板: #\
已经有了具体的题材 分析日间状态: \
sh/tips/run_xls_template.sh xx analyze_xls_cross_state



