#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-maoding
title=关于题材锚定的一些论述/探讨 参考\
文章<2026-06-19 状态图思路解决题材锚定问题>

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 4代表xls
# 第4位和第5位数字组合代表了计算的类型 huizong=00 maoding=03
no=31403

qianyan=总体思路:按照状态跃迁的方式来审视题材锚定 #\
先阐述一些事实：#\
1 题材的锚定和题材过去几个交易日的走势的状态有关 #\
2 题材的锚定和市场的行情也强相关#\
3 正常行情下 比如震荡 普涨行情下 题材的锚定就是那几个标准的指标：\
涨停板 核心个股(可以是权重 也可以是弹性) bkzj流入数据 市场的竞争结果 \
20cm的锚定#\
4 特殊行情 比如弱势行情 能否形成逆势#\
\n\
\n\
那么根据上述事实 可以设计一下方案:#\
1 普涨行情下 主看核心个股的走势,bkzj流 次看市场竞争#\
2 震荡行情(相对复杂): #\
2.1 如果题材是过去几日多日资金流入的 那么这个题材的操作时区比其它更长 \
这个题材允许开盘先分歧 资金还是能把题材拉起来的 这是他的优势#\
2.2 除开1的情况 在一个震荡日 核心个股的走势 bkzj的流入数据+在市场中\
的竞争也是一个非常有效的指标 且这个情况其实是包含1的 \
因为谁规定说资金多日流入的题材不会早盘就确立竞争优势呢#\
3 切换行情: #\
4 聚焦行情: #\
5 弱势行情下 看题材能否形成逆势 看市场的竞争结果 #\
	-> 可以看到 这里是严格的以行情为第一要素的 #\
	-> 这么设计的话 会不会太看低题材的内生性? #\
\n\
\n\
一些相关的其它模板: #\
1 对指定题材的锚定的更多论述(论述为主 少量计算):\
sh/tips/run_xls_template.sh xx xls_maoding_overall


