#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-diwei
title=给出题材在市场中地位分析的论述(未指定题材 纯论述)

# no的赋值规则见@engine/enum/no_rule_enum.py 
# tips的赋值规则见@engine/enum/tips_enum.py 
# 3代表advice/tips 1代表tips.properties 4代表xls
# 第4位和第5位数字组合代表了计算的类型 huizong=00 diwei=02 
no=31402

qianyan=本文给出题材在市场中地位分析的论述(未指定题材 纯论述)#\
\n\
显然 题材在市场中的地位可以分成日间+日内 因此需要给出不同的实现模板#\
题材在市场中的地位 显然是需要比较出来的#\
(注意到 不同的交易日 适用的数据不同 道理很简单 举个例子 一个普涨的交易日 涨停板就没有辨识度了)#\
一般来说 有以下比较因素#\
市场涨停板不多的话 涨停板#\
超短票(db31)中的涨停板#\
大成交个股中的前排数据#\
bkzj数据#\
\n\
其他? #\
\n\
\n\
\n\
一些相关的其它模板: #\
已经有了具体的题材: sh/tips/run_xls_template.sh xx xls_diwei_default



