#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-state
title=关于题材状态的一些论述 参考\
文章<2026-06-18 解决逻辑能力问题之正确认识+承认逻辑能力不足带给我的困扰>

qianyan=总体思路:按照状态跃迁的方式来审视题材状态 #\
影响题材的状态跃迁的 有哪些因素呢？稍作思考 就知道：#\
1 题材前几个交易日的图形/走势：这是显然的 一个最近2个交易日主力资金大幅流入的题材 \
和一个最近2日没有主力资金流入的题材 显然是不同的 #\
2 交易日当日的行情：这也是显然的因子 一个普涨日能让猪都起飞 一个普跌日 则是另一个画面#\
	-> 前2个是最强的2个因子#\
	-> 这个甚至无法编码 但问题不是很大 因为这个要素我可以特殊处理：即直接手工输入#\
3 题材核心票(如果有的话)的当日走势：这个因子是我脑子想的 \
不确定能不能经受实际的数据的考验#\
4 题材在市场中的竞争位置 注意:这有个前提 就是震荡日/偏弱日 因为普涨日不需要竞争#\
5 题材早盘的走势：最弱的因子 如果是弱势行情走逆势 那么可能还有一定的权重#\
\n\
\n\
一些相关的其它模板:

