#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-codes-basic-shape
title=给出一些基础的图形
category=analyze

replace=builded

time_str=09:00:00

# 很多计算基于size-stager 在处理诸如new:BK1633(动态股票池)时可能会出bug 因此设置一下end at
end_at=14:59:59

# 核心函数通过加载获取
functions=analyze_cross_xls

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

if2=xx*filter:min=5:max=300

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 8代表shape
# 第4位和第5位数字组合代表了计算的类型
# no的说明 codes从30开始 baisc-shape=31
no=91831

qianyan=给出一些基础的图形 用做买点#\
\n\
\n\
\n\
\n\
相关的模板: 



tips_plan={09:00:00,09:15:00}生成一下对应的题材属性: \
sh/codes/qp/gene/by_xls.sh xx split_pool 

# 给出具体的计算	
eva_quan={00:00:00,14:59:59}if xx*simple_code then xx->trend3.days6,\
if xx*filter:max=80 then xx->stage:trends_sum:len=5,\
zhushi:计算一下基础的trends-sum,\
xx*tx:huoli->size:len=1,\
zhushi:基础的获利盘数据,\
xx*no30000->size:len=1,\
zhushi:最基础的箱体图形 一般用于基础判断题材的活跃度,\
xx*no30001->size:len=1,\
zhushi:最基础的宽箱体图形 一般用于no30000数量爆表的时候,\
xx*no30100->size:len=1,\
zhushi:5日辨识度箱体的数量+trends-sum数据 注意箱体的原始数量本身已经表示出了题材的热度,\
xx*no30200->size:len=1,\
zhushi:10日(2个周期)辨识度箱体的数量+trends-sum数据,\
xx*no30401->size:len=1,\
zhushi:5日多实体图形数量,\
xx*no30402->size:len=1,\
zhushi:10日多实体图形数量,\
xx*no40100->size:len=1,\
zhushi:10日(2个周期)热度图形的数量+trends-sum数据,\
print_fenge,\
xx*xls:ggzj->size:len=1,\
zhushi:给出股票池在前日收盘时的ggzj数据


