#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-codes-shape-xt-no
title=做一下股票池的xt图形分析(日间)
category=analyze

replace=xls

time_str=09:00:00

functions=no_shape

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 8代表shape
# 第4位和第5位数字组合代表了计算的类型
# no的说明 codes从30开始 yangxians=33 xt_no=37
no=91837

qianyan=做一下股票池的xt图形分析(日间)#\
注意本文的类型为xt_no 也就是说明本模板是strategy.no下包的对应模板 \
具体来说 本模板对应的包是@strategy/no/xt #\
\n\
\n\
下面进入正文 #\
首先是定位: #\
箱体图形是股票池的基础图形了 当前实现的只能说将将能用 不足之处在于: #\
1 缺少位置信息 #\
2 缺少good or bad信息 #\
3 图形特殊性不够 语义不够清晰 #\
综上 本模板实现的箱体图形 实战中只能用做大致过滤 还需要比如日内eva图形的辅助来实现买点 #\
(当然了 能够通过箱体作出初步筛选 已经不错)#\
\n\
\n\
箱体图形具体包含以下细分图形: #\
1 基础good shape(最基础的辨识度): sh/tips/run_xls_template.sh xx analyze_codes_shape_301 #\
2 长周期的xt: sh/tips/run_xls_template.sh xx analyze_codes_shape_302 #\
3 箱体缩小: sh/tips/run_xls_template.sh xx analyze_codes_shape_303 #\
\n\
\n\
\n\
更多内容? #\
\n\
\n\
相关的模板: #\
图形的一般论述: sh/tips/run_xls_template.sh xx analyze_codes_shape_overall

# 尝试读取statement文件
jcals_all={00:00:00,23:59:59}get_statement_msg_if("strategy.no.xt")


tips_quan={00:00:00,23:59:59}基础辨识度xt图形:xx*no30100的数据量是否超过80:\
$check_if(context,"xx*no30100*filter:min=80") 若超过: \
sh/tips/run_xls_template.sh xx analyze_codes_shape_301(支持日间+日内)#\
\n\
基础long-xt图形:xx*no30200的数据量是否超过80:\
$check_if(context,"xx*no30200*filter:min=80") 若超过: \
sh/tips/run_xls_template.sh xx analyze_codes_shape_302(支持日间+日内)#\
\n\
基础suo-xt图形:xx*no30300的数据量是否超过80:\
$check_if(context,"xx*no30300*filter:min=80") 若超过: \
sh/tips/run_xls_template.sh xx analyze_codes_shape_303(支持日间+日内)

eva_quan={00:00:00,23:59:59}if not xx*is_bk then xx->trend3.days,\
zhushi:对股票池的走势有一个基础印象,\
xx*no30100->get_codes,\
zhushi:基础辨识度箱体,\
xx*no30200->get_codes,\
zhushi:基础长周期箱体,\
xx*no30300->get_codes,\
zhushi:基础suo箱体



