#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-qp-none(切片信息全无的默认分支)
title=从状态图的思路分析一下给定[切片信息全无的默认分支]切片的日间属性
category=analyze

replace=xls
time_str=09:00:00
functions=analyze_qp

force_origin_code_type=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 xls_sub=01 xls_sub_rank_alot=02 none=3
no=91503

qianyan=本文从状态图的思路分析一下[切片信息全无的默认分支]切片的日间属性#\
如果想看一般论述: sh/tips/run_template.sh analyze_qp_overall#\
\n\
因为切片信息未知 那么本tips[只能]关注于切片自身的数据 并且尝试尽可能多的计算细节#\
\n\
\n\
\n\
相关的模板: #\
如果确定了切片本身的rank很高 那么: \
sh/tips/run_xls_template.sh xx analyze_qp_xls_sub_rank_alot


# 尝试从qp-recorder中读取切片的属性	
jcals_all={00:00:00,23:59:59}try_load_qp_info(context,code_type)

tip_plan={09:00:00,09:15:00}切片本身的数据:#\
trend3.days#\
切片高度的变化


eva_plan={09:00:00,09:15:00}xx->trend3.days4,\
if xx*simple_code then xx*trd:min=6->size:len=4,\
if xx*simple_code then xx*pos_pchg:min=22->size:len=4,\



