#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-pool-overall
title=分析一下题材池的状态(日间和日内)(已经指定了具体的版块)
category=analyze

replace=pool

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 3代表pool(analyze-pool)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 
no=91300

qianyan=本文汇总一下analyze题材池的一些具体操作#\
\n\
\n\
\n\
\n\
\n\
相关的模板: #\
[日间] #\
分析指定题材池的日间资金流动: \
sh/tips/run_xls_template.sh xx analyze_pool_cross_zijin #\
\n\
[日内] #\
缺



