#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-qp-xls-sub(xls-sub分支)
title=从状态图的思路分析一下给定[xls-sub类型]切片的日间属性
category=analyze

replace=xls_codes
time_str=09:00:00
functions=analyze_qp

force_origin_code_type=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 5代表qp(analyze-qp)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 xls_sub=01 xls_sub_rank_alot=02
no=91501

qianyan=本文从状态图的思路分析一下[xls-sub类型+rank不明]切片的日间属性#\
如果想看一般论述: sh/tips/run_template.sh analyze_qp_overall#\
\n\
对于xls-sub类型的切片来说 #\
1 本身的数据是重要的#\
2 但是本切片在对应题材的权重 排序也是重要的#\
3 对应题材的走势 也是重要的#\
因此会同时给出上述的所有数据 #\
\n\
\n\
\n\
相关的模板: #\
如果确定了切片本身的rank很高 那么: \
sh/tips/run_xls_template.sh xx analyze_qp_xls_sub_rank_alot


# 尝试从qp-recorder中读取切片的属性		TODO:
jcals_all={00:00:00,23:59:59}

tip_plan={09:00:00,09:15:00}切片本身的数据:#\
trend3.days#\
切片高度的变化:#\
\n\
切片在题材中的比重:#\
题材+amount40中有多少是属于切片的#\
题材+pos_pchg中有多少是属于切片的#\
\n\
题材本身的走势


eva_plan={09:00:00,09:15:00}xx->trend3.days4,\
if xx*simple_code then xx*trd:min=6->size:len=4,\
if xx*simple_code then xx*pos_pchg:min=22->size:len=4,\
print_fenge,\
xx*first*amount:limit=40->get_codes,back=append_xls:xx,\
zhushi:题材+amount40中有多少是属于切片的,\
xx*first*pos_pchg:limit=30->get_codes,back=append_xls:xx,\
zhushi:题材+pos_pchg中有多少是属于切片的,\
if xx*first==chaoduan_codes_alot.if then \
xx*first*db31->get_codes,back=append_xls:xx,\
zhushi:题材的超短中有多少属于切片的,\
print_fenge,\
xx*first->trend3.days4,\
xx*first*trd:min=6->size:len=4


