#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-qp
title=从状态图的思路分析一下给定切片的日间属性(会强制把时间设置为09:00:00)
category=analyze

replace=xls
time_str=09:00:00
functions=analyze_qp

# no的赋值规则见@engine/enum/no_rule_enum.py 
# no的说明 overall=00 xls_sub=01 xls_sub_rank_alot=02
# 9代表analyze 1代表tips.properties 5代表qp-xls-sub
# 第4位和第5位数字组合代表了计算的类型
no=91500

qianyan=本文从状态图的思路分析一下切片的日间属性 已经指定了切片 会进行计算#\
如果想看一般论述: sh/tips/run_template.sh analyze_qp_overall#\
\n\
会根据切片的实际类型 给出具体的建议#\
切片的几种基本类型:#\
1 xls+sub: #\
2 pool+sub: #\
3 builded(高权重): #\
4 builded(低权重): #\
会根据切片的类型走到不同的分支#\
\n\
\n\
切片的属性包括: #\
(参考@engine/recorder/ztt/qp_entity.py) #\
rank: 权重 #\
sure: 确定性 #\
pos: 整体的位置 #\
risk: 风险(会根据日内的走势调整这个状态) #\
itrend: 日内走势 #\
trends: 日间走势 #\
hq: 行情状态码 #\
\n\
\n\
\n\
手工计算应该走到哪个tips分支: python engine/codes/analyze/tips_decider.py get xx#\
\n\
\n\
相关的模板: #\
关于切片的rank(权重)的一般论述: sh/tips/run_template.sh qp_rank_overall#\
关于切片的确定性sure的一般论述: sh/tips/run_template.sh qp_sure_overall#\
\n\
切片属于xls-sub: sh/tips/run_xls_template.sh xx analyze_qp_xls_sub#\
xls-sub+rank-alot: sh/tips/run_xls_template.sh xx analyze_qp_xls_sub_rank_alot#\
切片信息未知: sh/tips/run_xls_template.sh xx analyze_qp_none

# 根据切片的属性 找到实际下一步应该走的tips分支
jcals_all={00:00:00,23:59:59}get_dispatch_tips(context,code_type)


