#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-overall
title=分析一下题材的状态(日间和日内)(已经指定了具体的版块)
category=analyze

replace=origin_xls

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 
no=91400

qianyan=本文汇总一下analyze题材的一些具体操作#\
\n\
\n\
\n\
\n\
\n\
相关的模板: #\
分析指定题材的日间资金流动: \
sh/tips/run_xls_template.sh xx analyze_xls_cross_zijin #\
分析题材的日间状态: sh/tips/run_xls_template.sh xx analyze_xls_cross_state#\
分析题材的地位: sh/tips/run_xls_template.sh xx analyze_xls_cross_rank#\
\n\
[日内] #\
题材的pull: sh/tips/run_xls_template.sh xx analyze_xls_pull_overall#\
\n\
\n\
关于题材日间状态的一般论述: sh/tips/run_template.sh xls_cross_state_overall



