#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-pull-overall
title=给一下xls-pull的分析的overall(一般论述)
category=analyze

replace=origin_xls
open_index=xx
start=09:38:00

# 还是尽量不要走bkzj API
enable_bkzj_df=0

functions=xls_pull

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 pull-overall=40
no=91440

qianyan=给一下xls-pull的分析的overall#\
\n\
其实题材的pull挺复杂的 因为题材的pull相关的要素很多 #\
稍微一想就能想到以下问题 #\
1 pull是一个连续的过程 那么题材日内已经有一定的pull了 会影响到后续的pull行为吗?#\
2 对大数据量题材来说 会存在题材中的部分个股pull 但其它个股跌的情况 此时视作?#\
3 题材的pull可能嵌入在市场的指数拉升中 此时pull是否有延续性?#\
(其实就是题材的波动是一个连贯的动态的过程 这就是复杂度来源) #\
\n\
\n\
那么我能做什么呢? #\
监控实时的pull 实时的题材指数 题材之前是不是已经有过pull #\
对一些分支还应该再单独再进行分析 比如pull数量属于爆炸 #\
\n\
\n\
具体的分析细节 我会写成另外的文件 因为写到这里的话 内容有点太多了 #\
\n\
\n\
相关的模板: 

# 还缺基于bkzj的分析	TODO:
# if exist_t2:mode=m7 then xx->npulled:mode=m7
eva_quan={00:00:00,23:59:59}xx->trend3.hist,\
xx->upstp.hist,\
xx->zijin.hist:size=4,\
print_fenge,\
if exist_t2:mode=m7 then xx->stage:if2:npull:mode=m7:min=1.2*alot,\
zhushi:仅存在min=7的数据时 才计算一下npull:mode=m7数据,\
if exist_t2:mode=qt then xx->stage:if2:npull:mode=qt:min=1.2*alot,\
zhushi:默认的判断 npull=qt的数据是否alot,\
if not exist_t2:mode=qt then xx->stage:if2:npull:mode=qt2:min=1.2*alot,\
zhushi:qt文件不存在时 尝试计算一下npull:mode=qt2,\
xx->npulled.hist

jcals_quan={00:00:00,23:59:59}if exist_t2:mode=m7 then \
analyze_pull_detail_by_size(context,code_type,"m7"),\
if exist_t2:mode=qt and xx->if2:npull:mode=qt:min=1.2*alot then \
analyze_pull_detail_num_alot(context,code_type,"qt")[09:47:00,]

