#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-cross-trends
title=分析一下题材的日间状态的trends(短期几日走势)数据(已经指定了具体的版块)
category=analyze

replace=origin_xls
enable_bkzj_df=0
open_index=xx

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02
no=91402

qianyan=本文给一下题材的最近几个交易日的走势分析#\
关于题材的日间状态的一般论述见: \
sh/tips/run_template.sh xls_cross_state_overall#\
\n\
题材最近几日的走势某种意义上是最重要的数据 因为: #\
资金是短视的 会追涨杀跌 而过去几日的走势直接决定了赚钱效应 获利盘 压力盘等数据#\
\n\
\n\
那么本文会具体给出以下数据:#\
bkzj的数据: 是最直接的数据 #\
全题材的trends数据 #\
全题材的头部成交个股的trends_good,trends_bad数据 #\
\n\
\n\
相关的模板: #\
从资金的角度进行分析: sh/tips/run_xls_template.sh xx analyze_xls_cross_zijin#\
分析一下题材的日间全状态: sh/tips/run_xls_template.sh xx analyze_xls_cross_state#\ 
\n\
\n\
关于题材日间状态的一般论述: sh/tips/run_template.sh xls_cross_state_overall


# 给出具体的计算	
eva_quan={00:00:00,23:59:59}xx->stage:zijin_sum,\
zhushi:bkzj数据,\
xx->stage:zijin.days4,\
print_fenge,\
xx->trend3.day4,\
xx*amount:limit=50->trend3.days,\
xx*amount:limit=50->trends_good.days3,\
xx*amount:limit=50->trends_bad.days3,\
xx*db31->trends_good.days3,\
zhushi:题材中的超短票的trends-good数据也挺重要的,\
print_fenge,\
xx*pos_pchg:limit=30->trend3,\
xx*pos_pchg:limit=30->shape_fenbu:test_trends_good,\
zhushi:题材中的前排高度的trends good数据,\
print_fenge,\
xx*amount:limit=20->amount*btw:asc=0
