#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-top-shape
title=从题材的头部图形数据来分析题材的日间状态
category=analyze

replace=xls
time_str=09:00:00

# 核心函数通过加载获取
functions=analyze_cross_xls

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# 思路:根据题材中的amount:limit=40+duanxt:limit=40的数据来分析题材的状态
# 参考@engine/observe/plan/template/xx_analyze_by_shape.template.properties

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 by-shape(basic)=09 by-top-shape=14
no=91414

qianyan=从题材的头部图形数据来分析题材的日间状态 #\
\n\
思考的点包括: #\
1 题材的强度 这个强度是决定题材能否在市场中竞争胜出的 #\
2 题材的获利盘的多少 太多的话 也有风险 #\
\n\
\n\
相关的模板: 

# 给出具体的计算       
eva_quan={00:00:00,14:59:59}xx*db81*tx:huoli_alot->size:len=1,\
xx*10cm*pos_pchg:len=12:min=18*tx:huoli->stage:trends_sum,\
xx*xls:ggzj:limit=50->trends_sum:len=3,\
zhushi:在前日收盘中的ggzj前排的数据 这个也挺重要,\
xx*db81->trend3.days4,\
xx*10cm*no30100->stage:trends_sum,\
print_fenge,\
if db32*filter:max=35 then db32->get_codes,back=append_xls2:xx,\
zhushi:db32数据量合适的话 简单判断地位

# 缺基于xls:amount的分析???   TODO:

