#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-shape-default
title=分析一下题材的图形(日间)的默认实现
category=analyze

replace=xls
time_str=09:00:00

# 指定类型=shape
operate_type=shape

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 8代表shape
# 第4位和第5位数字组合代表了计算的类型
# no的说明 xls从00开始 overall=00 default=01
no=91801

functions=codes_shape
before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

qianyan=本文汇总一下分析一下题材的图形(日间)(默认实现)#\
\n\
为什么要分析图形? #\
1 图形的分布状态能够给出切片的具体子股票池的辨识度数据#\
2 一般来说 图形的分布是随机 但如果某天某种图形突然很多 \
那么也就失去了辨识度 也一定程度上代表了走势具备相当程度的一致性#\
3 做为买点的基础(前置计算) #\
\n\
\n\
效果一般 最好不要使用 !!!! #\
\n\
\n\
相关的模板: #\
分析图形的overall: sh/tips/run_xls_template.sh xx analyze_xls_shape_overall #\
阳线分布数据(同时适用题材和切片): \
sh/tips/run_xls_template.sh xx analyze_codes_shape_yangxians

eva_quan={00:00:00,23:59:59}if xx*db31*alot then xx->if2:db31,\
zhushi:如果db31的数据满足alot 那么显示数据 如果数据超过60 那么建议做进一步的图形挖掘,\
if exist_ggzj and xx->ggzj*filter:min=10 then xx->ggzj*btwed,\
zhushi:如果存在前日的ggzj apply数据的话 稍微计算一下,\
print_fenge,\
if xx*10cm*duanxt32*alot2 then xx->if2:10cm*duanxt32,\
zhushi:显示短箱体的数据,\
if not xx*is_bk then xx*10cm->if2:duanxt32_and*alot2,\
zhushi:判断duanxt32-and数据(高辨识度)是否alot 若满足 可以基于这个数据做更多的挖掘,\
xx*10cm->if2:suo_xt:max=0.6*filter:min=10,\
zhushi:箱体suo的图形数据,\
print_fenge,\
xx*10cm->if2:no70701*filter:min=10,\
zhushi:2阳2阴图形,\
xx*10cm->if2:no70702*filter:min=10,\
zhushi:3阳1阴图形,\
xx*10cm->if2:no70703*filter:min=10,\
zhushi:1阳3阴图形,\
print_fenge,\
if not xx*is_bk then xx*10cm->trend3.days



