#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-zijin-shape
title=从题材的资金相关图形(xls:ggzj BK1633)数据来分析题材的日间状态
category=analyze

replace=xls
time_str=09:00:00

# 核心函数通过加载获取
functions=analyze_cross_xls

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

if2=new:BK1633*filter:min=10
if2_err_msg=BK1633更新失败? 尝试: python strategy/cli.py get BK1633 --ignore_cache 1

# 思路:根据题材中的amount:limit=40+duanxt:limit=40的数据来分析题材的状态
# 参考@engine/observe/plan/template/xx_analyze_by_shape.template.properties

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 by-shape(basic)=09 by-zijin-shape=15
no=91415

qianyan=从题材的资金相关图形(xls:ggzj BK1633)数据来分析题材的日间状态 #\
\n\
\n\
\n\
相关的模板: #\
另一个资金实现: sh/tips/run_xls_template.sh xx xx_analyze_xls_cross_zijin.tips.properties

# 给出具体的计算       
eva_quan={00:00:00,14:59:59}xx->stage:zijin.days5,\
xx*xls:ggzj->size:len=3,\
xx*xls:ggzj:min_zhuli=0->size:len=3,\
xx*xls:ggzj:limit=40->size:len=1,\
xx*xls:ggzj*tx:huoli->size:len=1,\
xx*BK1633->size:len=3,\
xx*BK1633*no30401->stage:trends_sum:len=5,\
zhushi:BK1633高震幅+5日实体强数据 这个数据是显示题材的强度,\
xx*BK1633*no30402->size:len=1,\
xx*new:BK1633->stage:trends_sum:len=3


