#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-core-shape
title=从题材的核心子股票池数据来分析题材的日间状态
category=analyze

replace=xls
time_str=09:00:00

# 核心函数通过加载获取
functions=analyze_cross_xls

# 思路:根据题材中的amount:limit=40+duanxt:limit=40的数据来分析题材的状态
# 参考@engine/observe/plan/template/xx_analyze_by_shape.template.properties

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 by-core-shape=10 cross-duanxt=11
no=91410


qianyan=本文从题材的核心子股票池数据来分析题材的日间状态#\
主要思路就是题材的前排amount 前排波动箱体 超短票#\
\n\
\n\
\n\
\n\
\n\
相关的模板: 


# 给出具体的计算	
eva_quan={00:00:00,23:59:59}xx*10cm->trend3.days6,\
zhushi:对题材的走势有一个基本印象,\
xx*10cm->stage:shape_fenbu:test_duan_xt:len=5,\
zhushi:对题材的波动有一个基础印象,\
xx->if2:10cm*duanxt:len=5:min=18,\
zhushi:计算一下基础的duanxt:len=5:min=18数量,\
xx*db31->size:len=3,\
zhushi:对题材的基础超短数据有一个基础印象,\
xx*amount:limit=30->btw*amount,\
zhushi:对题材的大成交票有一个基础印象

jcals_quan={00:00:00,23:59:59}analyze_core_shape(context,"xx*amount:limit=40"),\
if xx*10cm*duanxt:len=5:min=18*alot2*filter:max=60 then \
analyze_core_shape(context,"xx*10cm*duanxt:len=5:min=18"),\
zhushi:如果duanxt:len=5:min=18数量可控 进行分析,\
if xx*db41*filter:min=22:max=50 then \
analyze_core_shape(context,"xx*db31"),\
zhushi:如果超短票数量可控 那么进行分析

