#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze_zao
title=分析早盘的强度+进攻性+拉升强度

# 定位分析早盘的强度+进攻性+拉升强度

replace=xls
start=09:16:00

# 配置自动记录到chain recorder
try_save_to_chain=1
chain_node=analyze_codes

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 9代表analyze 1代表tips.properties 5代表qp
# 第4位和第5位数字组合代表了计算的类型
# no的说明 attack=11 zao=14
no=91514

qianyan=分析给定题材/股票池在早盘的具体eva表现 #\
\n\
\n\
关于个股图形的论述: <2026-10-10 再来论述图形的要素> #\
\n\
\n\
\n\
当前实现了对应的gene: sh/codes/qp/gene/by_xls.sh xx zao_eva --time_str $time_str 



eva_all={09:00:00,23:59:59}xx->btw_fenbu,\
xx->trend3.hist[09:20:00,],\
xx->btw:limit=15:asc=0[,09:30:00],\
zhushi:最基础的前排数据,\
xx->btw:limit=15:asc=0*co[09:30:01,],\
zhushi:最基础的前排数据,\
xx->if2:eva-minus_dis:min=4,\
zhushi:基础的minus dis数据 这个图形有可能是走强的图形(TODO:FIXME)

# 早盘的eva还需要继续大力的开发      TODO:

eva_jj={09:16:00,09:30:00}xx==analyze_zao.ana,\
zhushi:最基础的zao指标

eva_zao1={09:32:00,09:34:40}ixx==analyze_zao.ana,\
zhushi:最基础的zao指标

eva_zao2={09:36:00,09:39:30}xx==analyze_zao.ana,\
zhushi:最基础的zao指标

eva_zao3={09:41:30,09:44:30}xx==analyze_zao.ana,\
zhushi:最基础的zao指标
