#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze_attack
title=分析股票池的整体进攻性

replace=xls
start=09:16:00

# 配置自动记录到chain recorder
try_save_to_chain=1
chain_node=analyze_codes

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 9代表analyze 1代表tips.properties 5代表qp
# 第4位和第5位数字组合代表了计算的类型
# no的说明 attack=11
no=91511

qianyan=分析股票池的整体进攻性 #\
股票池的进攻性数据很有用 能够做为我选择激进策略 还是保守策略的依据(对买点来说太重要了) #\
\n\
具体包括以下指标: #\
1 和日间的纵向对比数据 通过analyze_attack.ana实现 #\
2 在up2/3中outxt>10的数据比例 #\
3 在outxt>6中 处于高位的数据的比例

eva_all={09:00:00,23:59:59}xx->up2*outxt:len=10*get_rate[,09:30:00],\
zhushi:核心指标1 在股价>2中 outxt>10的比例,\
xx->up3*outxt:len=10*get_rate[09:30:01,],\
zhushi:核心指标1 在股价>3中 outxt>10的比例,\
xx->outxt:len=6:out=up*wrap:pos_pchg:len=15:min=28*get_rate,\
zhushi:核心指标2 在outxt的数据中 高度达到28%的数据比例,\
xx->outxt:len=6:out=up*wrap:pos_pchg:len=15:min=21*get_rate,\
zhushi:核心指标3 在outxt的数据中 高度达到21%的数据比例,\
xx->outxt:len=6:out=up*max_pchg:len=5:min=15*get_rate,\
zhushi:核心指标4 在outxt的数据中 近5日涨幅超过15%的数据比例

# 注意: 当前的实现中 会不会漏掉近期涨幅在15%~21%的数据.... 但没有太好的办法?(比较要考虑计算性能)  TODO:

eva_jj={09:16:00,09:30:00}if xx*simple_codes then xx->trend3.days7,\
xx==analyze_attack.ana,\
zhushi:最基础的attack指标

eva_zao1={09:32:00,09:34:40}if xx*simple_codes then xx->trend3.days7,\
xx==analyze_attack.ana,\
zhushi:最基础的attack指标

eva_zao2={09:36:00,09:39:30}if xx*simple_codes then xx->trend3.days7,\
xx==analyze_attack.ana,\
zhushi:最基础的attack指标

eva_zao3={09:41:30,09:44:30}if xx*simple_codes then xx->trend3.days4,\
xx==analyze_attack.ana,\
zhushi:最基础的attack指标


