#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-pool-by-ggzj
title=通过实时ggzj的数据 来分析版块池
category=analyze

replace=pool

start=09:30:01

enable_bkzj_df=1

if=exist_ggzj

try_save_to_chain=1
chain_node=analyze_xls

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 3代表pool(analyze-pool)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 03=trend 05=by-ggzj
no=91305

qianyan=通过实时ggzj的数据 来分析版块池 #\
\n\

flush_quan={00:00:00,23:59:59}xx->stage:eva_detail:sort=sum_zhuli:eva_type=ggzj2*to_sum:col=zhuli,\
zhushi:直接计算实时的版块池的ggzj sum \
(注意ggzj数据是偏向大票的 因此如果是新轮动的题材又是黄线走强的话 这个数据会偏弱),\
if new:BK1633*filter:min=10 then xx::BK1633->if2:eva-ggzj2*rup2:sort=eva_size,\
zhushi:通过BK1633的数据来判断强度

eva_quan={00:00:00,23:59:59}xls:fenshi->ggzj:limit=40,back=append_xls2:xx,\
xls:fenshi->ggzj:limit=10,back=append_xls2:xx
