#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-pool-by-shape
title=从图形的视角来分析题材池(选择)
category=analyze

replace=pool
time_str=09:00:00

# 为了保证计算性能 数量做一个限制
if=get_candi:xx*filter:max=5

# 核心函数通过加载获取
functions=codes_shape

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# 思路:根据题材中的amount:limit=40+duanxt:limit=40的数据来分析题材的状态
# 参考@engine/observe/plan/template/xx_analyze_by_shape.template.properties

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 3代表pool(analyze-pool)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 by-shape=09 
no=91309

qianyan=本文从图形的视角来分析题材池(选择)#\
\n\
参与计算的指标包括 #\
basic chaoduan的分布数据 #\
trd6的日间变化数据 #\
basic xt的数量+对应的trends sum数据 #\
\n\
\n\
\n\
\n\
\n\
相关的模板: 


# 给出具体的计算	
flush_quan={00:00:00,23:59:59}xx->stage:fenbu2,\
xx::10cm*trd:min=6->size:len=8,\
zhushi:给出8天的数据 是希望能更准确的纵向评估强度,\
xx::10cm*no30100->stage:trends_sum:len=3,\
zhushi:5日辨识度箱体的数量+trends-sum数据 注意箱体的原始数量本身已经表示出了题材的热度,\
xx::10cm*no30200->stage:trends_sum:len=3,\
zhushi:10日(2个周期)辨识度箱体的数量+trends-sum数据

