#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-duanxt
title=从短箱体的视角来分析题材的日间状态
category=analyze

replace=xls
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 cross-duanxt=11
no=91411


qianyan=本文从短箱体(图形)的视角来分析题材的日间状态#\
\n\
对应题材来说 近5日的短箱体图形能够挖掘出的信息包括: #\
1 通过最简单的不同shake的数量 来分析近期的题材波动数据 #\
2 通过相对大箱体的trends-good,trends-bad数据 来分析近期的题材走势 #\
3 给出连续10个交易日 都是大波动的数据 可能会用作买点 #\
4 给出箱体波动变小的具体数据 可能会用作买点 #\
5 其他思路? #\
\n\
\n\
注意: 仅计算10cm的数据#\
20cm的数据可以收工: python realtime/stage/cli.py get xx*20cm trend3.day4 #\
\n\
\n\
\n\
\n\
相关的模板: #\
关于题材日间状态的一般论述: sh/tips/run_template.sh xls_cross_state_overall#\
计算题材的日间trends: sh/tips/run_xls_template.sh analyze_xls_cross_trends#\
\n\
分析某只个股的duan-xt: sh/codes/test_duan_xt.sh abc#\
\n\
\n\
本模板的实际效果一般 


# 给出具体的计算	
eva_quan={00:00:00,23:59:59}if not xx*is_bk then xx*10cm->trend3.days6,\
zhushi:对题材的走势有一个基本印象,\
xx*10cm->stage:shape_fenbu:test_duan_xt,\
zhushi:通过最简单的不同shake的数量 来分析近期的题材波动数据,\
xx*10cm->if2:duanxt32*alot2,\
zhushi:判断duanxt3-2数据是否alot,\
if not xx*is_bk then xx*10cm->if2:duanxt32_and*alot2,\
zhushi:判断duanxt32-and数据(高辨识度)是否alot 若满足 可以基于这个数据做更多的挖掘,\
print_fenge,\
if xx*10cm*duanxt32*alot2 then xx*10cm*duanxt32->shape_fenbu:test_trends_good,\
zhushi:如果宽箱体很多 那么计算一下trends-good数据 来分析近期的题材走势,\
if not xx*10cm*duanxt32*alot2 and xx*10cm*duanxt2*alot2 then \
xx*10cm*duanxt2->shape_fenbu:test_trends_good,\
zhushi:宽箱体不多 那么退而求其次计算duanxt2的trends good数据,\
if xx*10cm*duanxt32*alot2 then xx*10cm*duanxt32->shape_fenbu:test_trends_bad,\
zhushi:如果宽箱体很多 那么计算一下trends-bad数据 来分析近期的题材走势,\
print_fenge,\
xx*10cm*duanxt32_and->get_codes,\
zhushi:给出连续10个交易日 都是大波动的股票池数据 可能会用作买点,\
xx*10cm*suo_xt:max=0.6->get_codes,\
zhushi:给出箱体波动变小的具体数据 可能会用作买点

# 更多算子? 比如箱体波动放大的个股 TODO:

