#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-cross-state
title=分析一下题材的日间状态(已经指定了具体的版块)
category=analyze

replace=origin_xls
enable_bkzj_df=0
open_index=xx

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01
no=91401

qianyan=本文给一下题材的日间状态分析#\
关于题材的日间状态的一般论述见: \
sh/tips/run_template.sh xls_cross_state_overall#\
\n\
这里稍作论述 题材的日间状态以下数据是重要的: #\
rank: 权重(当然当市场资金很充沛的时候 很多题材都会有机会 此时rank就没那么重要) #\
pos: 绝对的位置高度(过去20个交易日来衡量->某种意义上题材的高度能代表在市场中的地位) #\
trends: 过去4/5个交易日的题材走势数据(对题材来说其实近期走势反而是最重要的 \
因此资金是短视的 会追涨杀跌 而过去几日的走势直接决定了赚钱效应 获利盘 压力盘等数据) #\
trend: 前一日的基本状态 #\
zijin: 前一日的资金的行为描述	#\
sure：确定性(或者说安全性) #\
\n\
\n\
\n\
\n\
相关的模板: #\
从资金的角度进行分析: sh/tips/run_xls_template.sh xx analyze_xls_cross_zijin#\
计算日间trends的详细数据: sh/tips/run_xls_template.sh xx analyze_xls_cross_trends#\
题材的rank(市场中的地位): sh/tips/run_xls_template.sh xx analyze_xls_cross_rank#\
\n\
\n\
关于题材日间状态的一般论述: sh/tips/run_template.sh xls_cross_state_overall



