#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-qp-big-builded(数据量偏大的builded的切片分支)
title=从状态图的思路分析一下给定[数据量偏大的builded]切片的日间属性
category=analyze

replace=xls
time_str=09:00:00
functions=analyze_qp

force_origin_code_type=1

# 9代表analyze 1代表tips.properties 5代表qp-xls-sub 7代表builded
# no的赋值规则见@engine/enum/no_rule_enum.py 
# no的说明 overall=00 xls_sub=01 
# xls_sub_rank_alot=02 none=3 rank_alot=4 big-builded=05
no=91705

# 确保非origin类型
if=not xx*has_origin
if2=xx*filter:min=60

qianyan=本文从状态图的思路分析一下[数据量偏大的builded]切片的日间属性#\
如果想看一般论述: sh/tips/run_template.sh analyze_qp_overall#\
\n\
对于这种数据量偏大的builded切片 会更多的挖掘其中的逻辑属性#\
\n\
\n\
对于有一定权重的切片 那么以下数据是重要的:#\
1 日间的trends数据,trd6数据 高度数据等#\
2 切片的逻辑/版块池数据 做非常多的挖掘逻辑等#\
\n\
\n\
\n\
相关的模板: 


# 尝试从qp-recorder中读取切片的属性	
jcals_all={00:00:00,23:59:59}try_load_qp_info(context,code_type)

tip_plan={09:00:00,09:15:00}切片本身的数据:#\
trend3.days#\
\n\
\n\
切片本身的逻辑分布数据:


eva_plan={09:00:00,09:15:00}xx->trend3.days4

# 下面的计算可能会相对耗时一点 但不管了
flush_plan={09:00:00,09:15:00}redu::xx->size:len=1



