#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-basic-shape
title=从题材的图形数据来分析题材的日间状态
category=analyze

replace=xls
#time_str=09:00:00

# 很多计算基于size-stager 在处理诸如new:BK1633(动态股票池)时可能会出bug 因此设置一下end at
end_at=14:59:59

# 核心函数通过加载获取
functions=codes_shape

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

if2=xx*filter:min=5

# 思路:根据题材中的amount:limit=40+duanxt:limit=40的数据来分析题材的状态
# 参考@engine/observe/plan/template/xx_analyze_by_shape.template.properties

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 by-shape(basic)=094
no=914094

qianyan=本文从题材的[最基础]图形数据来分析题材的日间状态#\
定位其实是偏向于判断题材的走势 是对题材有一个基础的印象 #\
\n\
\n\
\n\
\n\
\n\
相关的模板: #\
默认的图形分析: sh/tips/run_xls_template.sh xx analyze_cross_xls_by_shape #\
基于BK1633(昨日高震幅)的图形分析: \
sh/tips/run_xls_template.sh xx analyze_cross_xls_shape_of_BK1633 

tips_plan={09:00:00,09:15:00}本股票池是否是builded: \
$check_if(context,"xx*is_builded"),\
如果是 那么生成一下对应的题材属性: sh/codes/qp/gene/by_xls.sh xx split_pool #\
本股票池是否包含较多超短股票池: $check_if(context,"xx*db101*filter:min=40"),\
如果是 那么生成一下超短切片池: sh/codes/qp/gene/by_xls.sh xx basic_chaoduan

# 给出具体的计算	
eva_quan={00:00:00,14:59:59}if xx*simple_code then xx->trend3.days6,\
xx*10cm*tx:huoli->size:len=1,\
zhushi:基础的活力盘数据,\
xx*10cm*no30000->size:len=1,\
zhushi:最基础的箱体图形,\
xx*10cm*no30001->size:len=1,\
zhushi:最基础的宽箱体图形 一般用于no30000数量爆表的时候,\
xx*10cm*no30100->stage:trends_sum:len=3,\
zhushi:5日辨识度箱体的数量+trends-sum数据 注意箱体的原始数量本身已经表示出了题材的热度,\
xx*10cm*no30200->stage:trends_sum:len=3,\
zhushi:10日(2个周期)辨识度箱体的数量+trends-sum数据,\
xx*10cm*no40100->stage:trends_sum:len=3,\
zhushi:10日(2个周期)热度图形的数量+trends-sum数据,\
print_fenge,\
if xx*simple_code and exist_ggzj then xx*xls:ggzj->size:len=3,\
zhushi:给出股票池在前日收盘时的ggzj数据

