#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze_opp
title=分析股票池的早盘的opp数据强度

replace=xls
start=09:30:00

# 参考@xx_analyze_attack.tips.properties 给出早盘的opp详细分析

try_save_to_chain=1
chain_node=analyze_codes

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 9代表analyze 1代表tips.properties 5代表qp
# 第4位和第5位数字组合代表了计算的类型
# no的说明 attack=11 opp=12
no=91512

qianyan=分析股票池的早盘的opp数据强度


# 缺做成对应的gene            TODO:

eva_all={09:00:00,23:59:59}xx->stage:opp_fenbu,\
zhushi:基本的opp分布数据,\
xx->if2:eva-opp2*up0,\
zhushi:最基础的opp2+up0的数据,\
xx->if2*eva-opp3*bound50,\
zhushi:最基础的opp3+bound50数据,\
xx->stage:eva_detail:eva_type=opp2*sum_dis:min=7*get_rate,\
zhushi:opp2中符合sum-dis>7的比例 这个表示了一定程度的进攻性,\
xx->stage:eva_detail:eva_type=opp2*opp:min=4.5*get_rate,\
zhushi:opp2中符合opp>4.5的比例,\
xx->stage:eva_detail:eva_type=opp2*high5*get_rate,\
zhushi:opp2中符合high5的比例

eva_zao1={09:32:00,09:34:40}xx->stage:eva_size:mode=zao1:eva_type=opp2.cross,\
xx->stage:eva_size:mode=zao1:eva_type=opp3.cross,\
xx->stage:eva_detail:mode=zao1:eva_type=opp2*sum_dis:min=7*get_rate.cross

eva_zao2={09:36:00,09:39:30}xx->stage:eva_size:mode=zao2:eva_type=opp2.cross,\
xx->stage:eva_size:mode=zao2:eva_type=opp3.cross,\
xx->stage:eva_detail:mode=zao2:eva_type=opp2*sum_dis:min=7*get_rate.cross

eva_zao3={09:41:30,09:44:30}xx->stage:eva_size:mode=zao3:eva_type=opp2.cross,\
xx->stage:eva_size:mode=zao3:eva_type=opp3.cross,\
xx->stage:eva_detail:mode=zao3:eva_type=opp2*sum_dis:min=7*get_rate.cross


