#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-codes-shape-redu-no
title=做一下股票池的redu热度图形分析(日间)
category=analyze

# 实现参考@xx_analyze_codes_shape_xt_no.tips.properties

replace=xls

time_str=09:00:00

functions=no_shape

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 8代表shape
# 第4位和第5位数字组合代表了计算的类型
# no的说明 codes从30开始 yangxians=33 xt_no=37 redu_no=40
no=91840

qianyan=做一下股票池的redu图形分析(日间)#\
注意本文的类型为redu_no 也就是说明本模板是strategy.no下包的对应模板 \
具体来说 本模板对应的包是@strategy/no/redu #\
\n\
\n\
下面进入正文 #\
首先是定位: #\
热度图形是当前我优化的比较到位的图形了 主要我对热度的组成:高度 箱体宽度 \
股性都作出了综合的细节优化 因此从主观上我是比较看好本热度图形的 #\
\n\
\n\
热度图形具体包含以下细分图形: #\
1, 正常强度的热度 并且给出了高度为主 箱体宽度为主 dgx为主的3个主要细分的实现 #\
sh/tips/run_xls_template.sh xx analyze_codes_shape_401 #\
2, 以pos-high高位为第一特征的热度图形 #\
sh/tips/run_xls_template.sh xx analyze_codes_shape_407 #\
\n\
\n\
\n\
更多内容? #\
\n\
\n\
相关的模板: #\
图形的一般论述: sh/tips/run_xls_template.sh xx analyze_codes_shape_overall

# 尝试读取statement文件
jcals_all={00:00:00,23:59:59}get_statement_msg_if("strategy.no.redu")


tips_quan={00:00:00,23:59:59}正常强度热度图形:xx*no40100的数据量是否超过100:\
$check_if(context,"xx*no40100*filter:min=100") 若超过: \
sh/tips/run_xls_template.sh xx analyze_codes_shape_401(支持日间+日内)#\
\n\
以pos-high高位为第一特征的热度图形:xx*no40701的数据量是否超过40:\
$check_if(context,"xx*no40701*filter:min=40") 若超过: \
sh/tips/run_xls_template.sh xx analyze_codes_shape_407(支持日间+日内)

eva_quan={00:00:00,23:59:59}if not xx*is_bk then xx->trend3.days,\
zhushi:对股票池的走势有一个基础印象,\
xx*no40100->get_codes,\
zhushi:正常强度的热度,\
if xx*no40100*filter:min=50 then xx*no40102->get_codes,\
zhushi:正常强度+箱体宽度为主要特征的图形数量,\
if xx*no40100*filter:min=50 then xx*no40103->get_codes,\
zhushi:正常强度+股性为主要特征的图形数量(当前40103似乎有计算问题?FIXME),\
xx*no40701->get_codes,\
zhushi:以pos-high高位为第一特征的热度图形

