#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-shape
title=从题材的图形数据来分析题材的日间状态
category=analyze

replace=xls
time_str=09:00:00

# 对数据量提出一个基础的要求
if=xx*filter:min=40

# 核心函数通过加载获取
functions=codes_shape

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# 思路:根据题材中的amount:limit=40+duanxt:limit=40的数据来分析题材的状态
# 参考@engine/observe/plan/template/xx_analyze_by_shape.template.properties

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 by-shape=09 
no=91409

if=
if_err_msg=

qianyan=本文从题材的图形数据来分析题材的日间状态#\
(主要的思路还是当作潜在的买点股票池来做)#\
\n\
参与计算的指标包括 #\
basic chaoduan的分布数据 #\
trd6的日间变化数据 #\
basic xt的数量+对应的trends sum数据 #\
\n\
\n\
\n\
\n\
\n\
相关的模板: 


# 给出具体的计算	
eva_quan={00:00:00,23:59:59}xx*first->stage:fenbu2,\
if not xx*is_bk then xx*10cm*trd:min=6->size:len=8,\
zhushi:给出8天的数据 是希望能更准确的纵向评估强度,\
xx*10cm*no30100->stage:trends_sum:len=3,\
zhushi:5日辨识度箱体的数量+trends-sum数据 注意箱体的原始数量本身已经表示出了题材的热度,\
xx*10cm*no30200->stage:trends_sum:len=3,\
zhushi:10日(2个周期)辨识度箱体的数量+trends-sum数据,\
print_fenge,\
if exist_ggzj then xx->ggzj2*rup3,\
zhushi:给出股票池在前日收盘时的ggzj数据

