#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-shape-overall
title=分析一下题材的图形(日间)(已经指定了具体的版块)
category=analyze

replace=xls

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 8代表shape
# 第4位和第5位数字组合代表了计算的类型
# no的说明 xls从00开始 overall=00 
no=91800

qianyan=本文汇总一下分析一下题材的图形(日间)的相关操作#\
\n\
为什么要分析图形? #\
1 图形的分布状态能够给出切片的具体子股票池的辨识度数据#\
2 一般来说 图形的分布是随机 但如果某天某种图形突然很多 \
那么也就失去了辨识度 也一定程度上代表了走势具备相当程度的一致性#\
3 做为买点的基础(前置计算) #\
\n\
\n\
\n\
\n\
相关的模板: #\
阳线分布数据(同时适用题材和切片): sh/tips/run_xls_template.sh xx analyze_codes_shape_yangxians



