#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-cross-rank
title=分析一下题材的在市场中的rank(日间)数据(已经指定了具体的版块)
category=analyze

replace=origin_xls
enable_bkzj_df=0
open_index=xx

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 cross-rank=03
no=91403

qianyan=分析一下题材的在市场中的rank(日间)数据#\
题材在市场中的地位 其实可以从资金的视角来看 一般有以下几个角色: #\
(参考@engine/enum/rank_enum.py)#\
资金持续投入的绝对主线: 这个分支下吸收尽可能多的资金就是它的唯一目标 \
分析就从这个特征入手 #\
资金近期切入的新贵: 这个分支的话 最好题材打出短期的赚钱效应且是低位 \
那么可以根据这2个特征来进行分析 #\
资金因为避险需求介入的题材: 这个分支的话 越低越好 越大票越好 #\
资金在一个混沌阶段市场做的尝试: 这个分支的话 只有零星的赚钱效应 #\
\n\
\n\
\n\
具体可以通过以下几个数据来判断: #\
题材中的最大成交股票池的数据(在全市场中的比较数据)和近期走势 #\
连板票的数据 最高高度的数据(虽然当前连板票的地位下降了很多 但也还可以看做一个监控指标)#\
题材的资金活跃度(通过bkzj的近几日数据可以获得)#\
\n\
\n\
\n\
\n\
相关的模板: #\
分析一下题材的日间全状态: sh/tips/run_xls_template.sh xx analyze_xls_cross_state#\ 
\n\
\n\
关于题材日间状态的一般论述: sh/tips/run_template.sh xls_cross_state_overall


# 给出具体的计算	TODO: 当前还没有想好怎么实现
eva_quan={00:00:00,23:59:59}
