#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-cross-zijin
title=给出题材的基于日间bkzj数据进行相关分析

replace=origin_xls
enable_bkzj_df=0
open_index=xx

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 cross-zijin=07
no=91407

qianyan=给出题材的基于日间bkzj数据进行相关分析#\
\n\
\n\
\n\
一些相关的模板:#\
1 如果是热门题材(有一些定制的信息挖掘逻辑) ==> \
sh/tips/run_xls_template.sh xx remen_xls #\
2 对题材做bkzj更多的挖掘逻辑: sh/plan/run_xls_template.sh xx bkzj


################################ 全时段
# 
eva_quan={00:00:00,23:59:59}xx->stage:zijin_sum,\
xx->stage:zijin.days5,\
xx->stage:if_zijin_alot1.days5,\
zhushi:给出题材的5日是否zijin-alot判断分析,\
if get_candi:xx then get_candi:xx*stage:zijin*find_bk*bkzj.cdadan:limit=30,\
zhushi:判断题材对应的bkzj数据是否在前日大单前30,\
if not get_candi:xx then get_candi:list:xx*stage:zijin*find_bk*bkzj.cdadan:limit=30,\
zhushi:判断题材对应的bkzj数据是否在前日大单前30




tips_plan={09:00:00,09:15:00}盘前时区

eva_plan={09:00:00,09:15:00}


