#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-qp-xls-sub-rank-alot(xls-sub分支)
title=从状态图的思路分析一下给定[xls-sub类型+rank-alot]切片的日间属性
category=analyze

replace=xls_codes
time_str=09:00:00
functions=analyze_qp

force_origin_code_type=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# no的说明 overall=00 xls_sub=01 xls_sub_rank_alot=02
# 9代表analyze 1代表tips.properties 5代表qp-xls-sub
# 第4位和第5位数字组合代表了计算的类型
no=91502

qianyan=本文从状态图的思路分析一下[xls-sub类型+rank-alot]切片的日间属性#\
如果想看一般论述: sh/tips/run_template.sh analyze_qp_overall#\
\n\
对于xls-sub类型+rank-alot的切片来说 #\
1 因为权重较高 那么本身的数据是最重要的 除非出现大的利空 或者盘面\
出现明显的切换 否则一般都是安全的#\
2 默认切片在对应的题材中权重很高 但还是给一下数据证明#\
3 对应题材的走势 不是很重要 但也要看一眼#\
4 但是对应题材在市场中的地位 是挺重要的(只是这个不好量化)#\
\n\
\n\
虽然切片属于题材中权重股 但也不代表绝对安全 不能迷信(尤其如果本身\
题材在市场中没什么竞争力的话)#\
\n\
\n\
\n\
相关的模板: #\
对analyze-qp的一般计算: sh/tips/run_xls_template.sh xx analyze_qp


# 根据切片的属性 找到实际下一步应该走的tips分支
jcals_all={00:00:00,23:59:59}

tip_plan={09:00:00,09:15:00}切片本身的数据:#\
trend3.days#\
切片高度的变化:#\
\n\
切片在题材中的比重:#\
题材+amount40中有多少是属于切片的#\
题材+pos_pchg中有多少是属于切片的#\
\n\
题材本身的走势


eva_plan={09:00:00,09:15:00}xx->trend3.days4,\
if xx*simple_code then xx*trd:min=6->size:len=4,\
if xx*simple_code then xx*pos_pchg:min=22->size:len=4,\
print_fenge,\
xx*first*amount:limit=40->get_codes,back=append_xls:xx,\
zhushi:题材+amount40中有多少是属于切片的,\
xx*first*pos_pchg:limit=30->get_codes,back=append_xls:xx,\
zhushi:题材+pos_pchg中有多少是属于切片的,\
if xx*first==chaoduan_codes_alot.if then \
xx*first*db31->get_codes,back=append_xls:xx,\
zhushi:题材的超短中有多少属于切片的,\
print_fenge,\
xx*first->trend3.days4,\
xx*first*trd:min=6->size:len=4


