#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-by-ggzj
title=从个股资金的角度来分析题材(日内)(已经指定了具体的版块)
category=analyze

replace=xls
enable_bkzj_df=0
open_index=xx

start=09:30:01

# 只有存在对应的ggzj-BKxxx文件时 才会执行本模板计算
if=xx*filter:min=1 and xx->exist_ggzj

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 数字>50说明是日内的分析 52=by-ggzj
no=91452

qianyan=从个股资金的角度来分析题材#\
\n\
个股资金的数据是比较准的 那么通过个股能获取哪些信息呢?#\
头部数据的风格可以分析题材的风格是大票还是小票#\
结合trend3的数据 能大致判断题材的真实走势#\
通过市场的ggzj的API 判断当前题材在市场中的地位 #\
其他? #\
\n\
\n\
\n\
相关的模板: 


# 给出具体的计算	
eva_quan={00:00:00,23:59:59}xx->stage:zijin.hist[09:31:00,],\
zhushi:题材的bkzj总体数据,\
xx->trend3.hist,\
zhushi:题材的trend的hist数据 对题材大体走势有一个初步印象,\
xx->if2:rup3_alot.if,\
zhushi:对rup3数据有一个基础概念,\
print_fenge,\
xx->upstp*ggzj,\
zhushi:看一下涨停板的ggzj数据,\
xx->ggzj:min_zhuli=0.5:limit=20*info,\
zhushi:题材资金前排个股 可以判断题材的大票小票风格,\
xx->ggzj:min_zhanbi=5:limit=20*btwed,\
zhushi:结合题材的trend3.hist数据 能比较准确的判断题材的走势,\
xx->ggzj:sort=zhanbi:min_zhanbi=5:limit=25*btw,\
zhushi:按照占比排序的前排的数据,\
xx*amount:limit=40->ggzj*btwed,\
zhushi:题材中权重的数据的表现,\
print_fenge,\
if exist_ggzj then xls:fenshi->ggzj:min_zhuli=1:limit=30,\
back=append_xls:xx,\
zhushi:判断当前题材在市场中的地位

