#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-pool-by-bkzj
title=通过实时bkzj的数据 来分析版块池
category=analyze

replace=pool

start=09:30:01

enable_bkzj_df=1

if=exist_bkzj

try_save_to_chain=1
chain_node=analyze_xls

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 3代表pool(analyze-pool)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 03=trend 05=by-ggzj 06=by-bkzj
no=91306

qianyan=通过实时bkzj的数据 来分析版块池 #\
\n\

flush_quan={00:00:00,23:59:59}xx->stage:zijin

eva_quan={00:00:00,23:59:59}get_candi:xx*stage:zijin,\
get_candi:xx*to_bk*bkzj.zhuli:limit=40,\
get_candi:xx*to_bk*bkzj.idx:limit=20,\
get_candi:bkzj.zhuli:limit=30*append_xls,\
get_candi:bkzj.idx:limit=20*append_xls
