#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-codes-shape-yangxians
title=分析一下切片的阳线相关图形(日间)
category=analyze

replace=xls

time_str=09:00:00

functions=codes_shape
before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 8代表shape
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 yangxians=03
no=91803

qianyan=分析一下切片的阳线相关图形(日间)#\
\n\
注意: 一般来说 图形的分布是随机 但如果某天某种图形突然很多 \
那么也就失去了辨识度 也一定程度上代表了走势具备相当程度的一致性#\
\n\
\n\
主要包括以下数据:#\
3阳1阴: 一般这个数据量是比较小的 #\
2阳2阴: 一般这个数据量是适量的 也是我的主力图形 #\
1阳3阴: 一般这个数据量也是比较小的 #\
\n\
\n\
相关的模板: #\
图形的一般论述: sh/tips/run_xls_template.sh xx analyze_codes_shape_overall

eva_quan={00:00:00,23:59:59}xx*no70701->get_codes,\
zhushi:3阳1阴,\
xx*no70702->get_codes,\
zhushi:2阳2阴,\
xx*no70703->get_codes,\
zhushi:1阳3阴


