juben=analyze-cross-xls-by-basic-shape
title=从xls:ggzj的视角分析题材(图形)

category=analyze

replace=xls

# 核心函数通过加载获取
functions=codes_shape

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# 判断本日的BK1633和前日的数据是否雷同(网站是否更新了新数据)
if2=xls:ggzj*filter:min=100

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 cross-state=01 cross-trends=02 by-BK1633=12 by-xls-ggzj
no=91413

qianyan=从xls:ggzj的视角分析题材(图形)

eva_quan={00:00:00,14:59:59}xx*xls:ggzj->size:len=4,\
xx*xls:ggzj:limit=40->size:len=4,\
zhushi:处于ggzj前排的数据的变化,\
if xx*xls:ggzj:limit=40*filter:min=5 then xx->ggzj2:limit=40*btw,\
zhushi:查看一下前日处于ggzj前排的具体数据,\
xx*new:xls:ggzj->size:len=1,\
xx*and:len=1:xls:ggzj->size:len=1
