#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-qp-rank-alot(具备一定权重的切片分支)
title=从状态图的思路分析一下给定[具备一定权重]切片的日间属性
category=analyze

replace=xls
time_str=09:00:00
functions=analyze_qp

force_origin_code_type=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 5代表qp(analyze-qp)
# no的说明 overall=00 xls_sub=01 
# xls_sub_rank_alot=02 none=3 rank_alot=4
no=91504

# 做一个数据量的最大限制
if=xx*filter:max=150

qianyan=本文从状态图的思路分析一下[具备一定权重]切片的日间属性#\
如果想看一般论述: sh/tips/run_template.sh analyze_qp_overall#\
\n\
注意:本tips实现没有对切片的数据量做约束,因此可能偏大或偏小#\
\n\
\n\
对于有一定权重的切片 那么以下数据是重要的:#\
1 日间的trends数据,trd6数据 高度数据等#\
2 切片本身在市场中的位置 到底能达到什么高度#\
3 切片的逻辑/版块池数据 有没有一家独大等#\
\n\
\n\
\n\
相关的模板: 


# 尝试从qp-recorder中读取切片的属性	
jcals_all={00:00:00,23:59:59}try_load_qp_info(context,code_type)

tip_plan={09:00:00,09:15:00}切片本身的数据:#\
trend3.days#\
\n\
切片在市场中的位置:(不大容易?)(暂时没想好怎么做)#\
\n\
切片本身的逻辑分布数据:#\
切片的check_if(xx*filter:max=40):$check_if(context,"xx*filter:max=40"),\
此时可以进行pool分析: sh/codes/analyze_pool.sh xx --mode plan


eva_plan={09:00:00,09:15:00}xx->trend3.days4,\
if xx*simple_code then xx*trd:min=6->size:len=4,\
if xx*simple_code then xx*pos_pchg:min=22->size:len=4,\

flush_plan={09:00:00,09:15:00}if not xx*has_origin and \
xx*filter:min=45 then redu::xx->size:len=1



