#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-cross-xls-by-ggzj2
title=从个股资金的角度来分析题材(日间)(已经指定了具体的版块)
category=analyze

replace=xls
enable_bkzj_df=0

time_str=09:00:00
if=xx*filter:min=1 and exist_ggzj

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5 6位数字组合代表了计算的类型 06=by-ggzj 062=by-ggzj2
no=914062

qianyan=从个股资金的角度(ggzj2 API)(全市场的ggzj数据)来分析题材#\
\n\
个股资金的数据是比较准的 那么通过个股能获取哪些信息呢?#\
头部数据的风格可以分析题材的风格是大票还是小票#\
结合trend3的数据 能大致判断题材的真实走势#\
通过市场的ggzj的API 判断当前题材在市场中的地位 #\
其他? #\
\n\
\n\
\n\
相关的模板: 


# 给出具体的计算	
eva_quan={00:00:00,23:59:59}xx->zijin,\
if not xx*is_bk then xx->stage:zijin.days,\
zhushi:题材的bkzj总体数据,\
if not xx*is_bk then xx->trend3.days,\
zhushi:题材的trend的days数据 对题材大体走势有一个初步印象,\
print_fenge,\
xx->upstp*ggzj2,\
zhushi:看一下涨停板的ggzj数据,\
xx->ggzj:min_zhuli=0.5:limit=20*info,\
zhushi:题材资金前排个股 可以判断题材的大票小票风格,\
xx->ggzj:min_zhanbi=5:limit=20*btwed,\
zhushi:结合题材的trend3.hist数据 能比较准确的判断题材的走势,\
xx->ggzj:sort=zhanbi:min_zhanbi=5:limit=25*btw:asc=0,\
zhushi:按照占比排序的前排的数据,\
xx*amount:limit=40->ggzj2*btwed,\
zhushi:题材中权重的数据的表现,\
print_fenge,\
xx->ggzj2:limit=60,\
zhushi:在市场中的地位 以ggzj的收盘前60数据作为判定标准


