#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-xls-rup-alot
title=题材满足rup alot时的分析(日内)(已经指定了具体的版块)
category=analyze

replace=origin_xls
enable_bkzj_df=0

start=09:20:01

# 做最基础的rup2条件判定
if=xx->if2:rup2_alot.if

try_save_to_chain=1

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 数字>50说明是日内的分析 52=by-ggzj rup-alot=61
no=91461

qianyan=题材满足rup alot时的分析(日内)#\
\n\
主要包含2个内容: #\
rup数据的信息显示: 包括rup2 rup3 rup5#\
风格的判定: 大票小票 成交额等#\
\n\
\n\
\n\
简单说明买点思路: 当满足rup3的时候 说明题材非常强 此时日间图形就是第一权重了#\
(当然 最好在xx*eva:rup3的前提下进行计算 因为题材都这么强了 对应的个股没有动静 就说明弱了)#\
\n\
\n\
相关的模板: #\
计算一下基础的超短图形: sh/codes/qp/gene/by_xls.sh xx basic_chaoduan

# rup3爆炸的时候 说明仅仅一个rup3图形是不够用的 需要再叠加更多的eva来进行辅助 比如newhigh,比如qushi-up	TODO:

# 给出具体的计算	
eva_quan={00:00:00,23:59:59}xx->stage:zijin.hist[09:31:00,],\
zhushi:题材的bkzj总体数据,\
xx->trend3.hist,\
zhushi:题材的trend的hist数据 对题材大体走势有一个初步印象,\
xx->trend3.days,\
if exist_ggzj then xx->ggzj2*btwed,\
print_fenge,\
xx->if2:rup2_alot.if,\
xx->if2:rup3_alot.if,\
xx->if2:eva-rup3*baozha2*filter:min=50,\
zhushi:判断是否满足rup3 爆炸,\
print_fenge,\
if xx->if2:rup3_alot.if then xx*eva:rup3->stage:shape_fenbu:amount,\
zhushi:成交额分析,\
if xx->if2:rup3_alot.if then xx*eva:rup3->stage:shape_fenbu:shizhi,\
zhushi:市值分析


