#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-pool-cross-zijin
title=从资金的视角(bkzj,ggzj)对题材池进行分析(仅日间)

replace=pool
enable_bkzj_df=0

try_save_to_chain=1
chain_node=analyze_pool

# 写死时间
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 3代表pool
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 cross-zijin=07
no=91307

qianyan=从资金的视角(bkzj,ggzj)对题材池进行分析#\
\n\
\n\
\n\
一些相关的模板:


################################ 全时段
# 

eva_quan={00:00:00,23:59:59}get_candi:xx*stage:sort=sum:zijin_sum:can_has_empty=1,\
get_candi:xx*stage:zijin,\
print_fenge,\
xls:ggzj:limit=40->get_codes,back=append_xls2:xx

# xx->stage:zijin,\
# xx::xls:ggzj:limit=60*not:xls:ggzj:limit=150.bf->size:len=1,\
# zhushi:新进入到xls:ggzj前60的数据
flush_quan={00:00:00,23:59:59}xx::xls:ggzj->stage:trends_sum:len=3,\
xx::xls:ggzj*tx:huoli->size:len=1,\
xx::xls:ggzj:limit=40->size:len=1



