#
#Fri Feb 14 15:36:12 CST 2025
juben=basic-xls
title=给出题材的基础信息 包括题材的数据量 过去几日的bkzj数据等

replace=origin_xls
enable_bkzj_df=0
open_index=xx

qianyan=给出题材的基础信息 用于给出一些大致的思路#\
\n\
\n\
\n\
一些相关的模板:#\
1 如果是热门题材(有一些定制的信息挖掘逻辑) ==> \
sh/tips/run_xls_template.sh xx remen_xls


################################ 全时段
eva_quan={00:00:00,23:59:59}xx->stage:zijin.days5,\
xx->stage:if_zijin_alot1.days5,\
xx->stage:upstp.days5,\
xx->stage:eva_size:eva_type=trd:min=5.days5,\
xx->stage:trend3.days5,\
if xx*amount30*alot,\
zhushi:判断是否amount30满足alot,\
if xx*amount20*baozha,\
zhushi:判断是否amount20满足baozha,\
xx*amount:limit=12->get_codes,\
zhushi:给出题材中前10大成交的股票池数据,\
if xx*amount30*alot then \
xx*amount30*pc:yuanli_two123->stage:size:len=4,\
zhushi:如果amount30 alot 那么计算一下amount30+yuanli的数据

# 缺核心股票池的计算数据		TODO:

