#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=拿到一个指定的未知的股票池时 如何进行分析+make plan(盘前) 

# 参考@xx_xls_make_plan_overall.tips.properties 给出盘前的买点策略

replace=builded

# 写死时间戳
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan 所以前3位是固定的
# 股票池的plan 从数字65开始
# 第4位和第5位数字组合代表了计算的类型 overall=65 none=01 
no=71065

functions=codes_shape
before_func=init_codes_no_if($day)

if=codes_no_recorder_inited

qianyan=本tips解决的问题是:拿到一个未知股票池时 如何[在盘前]进行分析+make plan#\
\n\
其实对于切片来说 最本质的工作 还是分析图形/图形后面代表的属性 包括: #\
切片的波动性 #\
切片池的大票小票属性 最好过滤出一些数据#\
builded类型 自然也有题材分类属性(注意:xls+sub,pool+sub无需计算) #\
\n\
其它思路?

tips_plan={09:00:00,09:15:00}本股票池是否是xls-sub或者pool-sub: \
$check_if(context,"xx*xls_codes or xx*pool_codes"),\
如果不是 那么生成一下对应的题材属性: sh/codes/qp/gene/by_xls.sh xx split_pool #\
本股票池是否包含较多超短股票池: $check_if(context,"xx*db101*filter:min=20"),\
如果是 那么生成一下超短切片池: sh/codes/qp/gene/by_xls.sh xx basic_chaoduan

eva_plan={09:00:00,09:15:00}xx->stage:shape_fenbu:shizhi,\
xx*xls:ggzj->size:len=1,\
xx*tover:min=5->size:len=1,\
xx*tover:min=3->size:len=1,\
xx*amount:min=3->size:len=1,\
xx*no30100->size:len=1,\
xx*no30200->size:len=1,\
xx*no40100->size:len=1,\
xx*BK1717->size:len=1,\
zhushi:题材股,\
xx*BK0821->size:len=1,\
zhushi:MSCI,\
xx*BK1633->size:len=1,\
zhushi:昨日高震幅


