#
#Fri Feb 14 15:36:12 CST 2025
juben=codes-can-be-buyer-by-eva
title=根据切片的实时eva表现来判定能否做买点(已经指定了来具体的切片) 

# 根据实时的eva(btw-good,co,dis-good)表现来判断能否做买点

replace=builded
start=09:16:00
force_origin_code_type=1

# 太小的数据量的话... 本策略会失效 因此设置一下最基础的数量校验
if=xx*filter:min=10

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 1代表check-can-be-buyer 
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 qp-by-eva=04
no=81104

functions=qp_trend

#3 随机性更大 #\ 
# 3 {还没想好如何和行情联动起来} #\
qianyan=本文解决一下根据切片的实时eva表现来判定能否做买点(纯从图形角度判定)#\
\n\
思路: #\
1 如果有涨停板 加分#\
2 根据实时的btw-good-eva的数量来判定 #\
3 根据实时的dis-good-eva的数量来判定 #\
\n\
\n\
注意 也会稍微判定一下风险 也就是底部的数据(当前未实现 TODO:) #\
\n\
\n\
(要不要考虑日间图形?	TODO:) #\
\n\
\n\
一些相关的其它模板:

eva_quan={00:00:00,23:59:59}

jcals_all={00:00:00,23:59:59}try_load_qp_info(context,code_type)

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}xx->if2:has_upstp0,\
xx->if2:eva-btw:min=-2*ma_dis:min=2,\
zhushi:竞价时区对个股的图形限制放宽一点


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}xx->if2:has_upstp0,\
xx->if2:eva-btw:min=-2*ma_dis:min=2*filter:min=5,\
zhushi:开盘时区对个股的图形限制放宽一点 设置最小数量=5,\
xx->if2:eva-btw_good*filter:min=5,\
zhushi:开盘时区对个股的图形限制放宽一点(btw-good) 设置最小数量=5,\
xx->if2:eva-ma_dis:min=2*filter:min=5,\
zhushi:开盘时区对个股的图形限制放宽一点(ma-dis) 设置最小数量=5,\
xx->if2:eva-wrap:trd_sum:len=4:min=3*btw:min=-2*filter:min=5,\
zhushi:开盘时区对个股的图形限制放宽一点(trd-sum:len=4) 设置最小数量=5,\
print_fenge,\
xx->btw:limit=12,\
zhushi:给出实时btw排序前12(不过滤负数)

############################### 早盘时区

tips_zao1={09:30:01,09:50:00}早盘时区:

eva_zao1={09:30:01,09:50:00}xx->if2:has_upstp0,\
zhushi:如果有涨停板 加分项,\
xx->if2:eva-opp:min=2*bound40*filter:min=5,\
zhushi:给出个股冲高的数据(opp+bound40) 最小值小一点=5 \
因为冲高的数据代表不了什么 可以回落的(回落也代表不了什么),\
xx->if2:eva-btw:min=-2*ma_dis:min=2*filter:min=10,\
zhushi:早盘时区对个股的图形 设置最小数量=10,\
xx->if2:eva-btw_good*filter:min=10,\
zhushi:早盘时区对个股的图形(btw-good) 设置最小数量=10,\
xx->if2:eva-ma_dis:min=2*filter:min=10,\
zhushi:早盘时区对个股的图形(ma-dis) 设置最小数量=10,\
xx->if2:eva-wrap:trd_sum:len=4:min=3*btw:min=-2*filter:min=5,\
zhushi:早盘时区对个股的图形(trd-sum:len=4) 设置最小数量=10,\
print_fenge,\
xx->bound40*btw:limit=12,\
zhushi:给出实时btw排序前12(不过滤负数)


