#
#Fri Feb 14 15:36:12 CST 2025
juben=can_be_maoding
title=给定一个切片/股票池 判断能否用作实时锚定(计算为主 论述为辅)

replace=builded
enable_bkzj_df=0

# 注意: 本锚定是我最看重的工具 因此要好好做,不要怕复杂 越复杂越好	TODO:

# 比如 普跌日如果形成逆势 那么也具备一定的锚定作用\ 
qianyan=本文做一下切片能否用作锚定判定 注意:因为这个问题其实很复杂 因此论述\
部分被我放在了其它地方 想看可以:sh/tips/run_template.sh codes_can_be_maoding#\
\n\
这里给出一般的结论 判断依据主要包括:#\
1 切片本身的权重(量化有一定的难度) #\
-> 虽然有难度 但这个可以在盘前就计算好 #\
2 切片过往几日的走势和实时的走势 共同组合形成的强度: #\
3 和实时行情的联系(有点复杂): 比如市场实时的偏好 刚好是切片本身的属性 那么锚定效果更好#\
\n\
\n\
从实现的角度 来给出具体的方案: #\
1 如果能计算出切片的权重(假设这里克服了编码的困难) 那么根据切片的权重和实时的走势\
来共同判定能否用作锚定#\
2 在没有切片权重的情况下 根据“切片过往几日的走势和实时的走势 共同组合形成的强度”+\
判断切片不存在大幅风险 此时可用用作锚定#\
\n\
\n\
对于“切片过往几日的走势和实时的走势 共同组合形成的强度”稍作论述/举例:#\
1 近期连续走强 允许开盘弱分歧一下#\
2 近期一直不强 那么必须实盘很强 形成日间弱转强 才可以视作有效锚定#\
3 近期大波动+前日大跌 那么早盘必须至少头部有弱转强的迹象 才可以视作锚定#\
4 还可以有更多的例子 不再举例#\
注意:这种特征(前日走势+实时走势的组合)非常适合状态图实现#\
->实现起来没那么难 只要实现"过去几日的强度"+"实时的强度"+"实时的风控" 即可#\
\n\
\n\
\n\
相关的模板: #\
1 判断切片能否作锚定的一般论述: sh/tips/run_template.sh codes_can_be_maoding#\
2 ?

################### 最开头的前序eva计算
eva_quan={00:00:00,23:59:59}xx->trend3.days



############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}

############################### 早盘时区

tips_zao1={09:30:01,09:45:00}早盘时区:

eva_zao1={09:30:01,09:45:00}



