#
#Fri Feb 14 15:36:12 CST 2025
juben=is-pool-rotate
title=从各个角度判断题材是否轮动/轮动程度强度

replace=pool
enable_bkzj_df=0

try_save_to_chain=1
chain_node=analyze_pool

# 核心函数通过加载获取
functions=analyze_cross_xls

before_func=init_codes_no_if($day)
if=codes_no_recorder_inited

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 3代表pool
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 cross-zijin=07 is-pool-rotate=21
no=91321

qianyan=从各个角度判断题材是否轮动/轮动程度强度(支持全时区)#\
(会给出很多细致的数据 比如no30401这种细节图形数据)#\
\n\
\n\
\n\
一些相关的模板:


################################ 全时段
# 

eva_quan={00:00:00,23:59:59}get_candi:xx*stage:sort=sum3:zijin_\
sum:mode=cross:can_has_empty=1,\
zhushi:最基础的bkzj+3日数据 按照sum3排序 如果数据很好 \
那么(必然不是)轮动题材 数据缺失时轮动概率很高,\
get_candi:xx*stage:zijin:mode=cross,\
zhushi:最基础的前日收盘数据 如果数据非常好 那么也(必然不是)轮动数据,\
print_fenge,\
xls:ggzj:limit=40->get_codes,back=append_xls2:xx,\
zhushi:前日的ggzj的前排数据 这个数据太好的话 也必然不是轮动数据

# xx->stage:zijin,\
# xx::xls:ggzj:limit=60*not:xls:ggzj:limit=150.bf->size:len=1,\
# zhushi:新进入到xls:ggzj前60的数据
# if not new:BK1633*filter:min=1 then break,\
# zhushi:如果更新动态版块池BK1633失败 那么终止计算,\

flush_quan={00:00:00,23:59:59}xx::xls:ggzj->stage:trends_sum:len=3:sort=sum,\
zhushi:首先如果个股数量很多 就代表资金介入很深了 其次trends-sum数据很好的话 那么也不是轮动,\
xx::xls:ggzj:limit=40->size:len=3:sort=sum,\
zhushi:在前排ggzj的数量 本身也能代表在市场中的权重,\
xx::no30401->stage:trends_sum:len=5:sort=sum,\
zhushi:30401号图形是dst图形 这个数量如果很多 本身就能代表资金的介入程度,\
xx::10cm*trd:min=6->size:len=4:sort=size,\
zhushi:10cm的trd>6的数据 也是直观的资金获利数据 不过这个数据的\
准度没那么高 因为完全可以在题材内部不同个股拉升6%,\
if new:BK1633*filter:min=1 then xx::BK1633->stage:trends_sum:len=5:sort=sum,\
zhushi:首先如果个股数量很多 就代表资金介入很深了 其次trends-sum数据很好的话 那么也不是轮动



