#
#Fri Feb 14 15:36:12 CST 2025
juben=master-xls-overall
title=作为master题材相关的导航
category=analyze

replace=origin_xls

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 master=99
no=91499

qianyan=本文作为掌控xls相关的导航#\
\n\
\n\
题材分析(日间): sh/tips/run_xls_template.sh xx xx_analyze_xls_cross_state #\
\n\
实时锚定(日内): sh/tips/run_xls_template.sh xx xls_maoding_overall #\
\n\
实时监控(日内): sh/tips/run_xls_template.sh xx xls_trend_default #\ 
快速监控(判断能不能买入): sh/tips/run_xls_template.sh xx xls_trend_fast #\
\n\
\n\
\n\
\n\
一些相关的其它模板: 



