#
#Fri Feb 14 15:36:12 CST 2025
juben=master-qp-overall
title=给出掌控切片的总体论述(纯论述 0计算)

replace=xls

qianyan=本文做为一些切片分析的引导文章#\
对切片的size change分析: sh/codes/analyze_size_change.sh xx #\
对切片做pool分布分析(同时支持盘前和实盘): \
sh/codes/analyze_pool.sh xx #\
对切片做头部数据分析(仅支持实盘不支持盘前): sh/codes/analyze_top.sh xx#\
对切片做pos-high分布分析: sh/codes/test_pos_high.sh xx#\
根据切片的类型(pool+sub,xls+sub)做实时的分析(仅支持实盘)(效果有限): \
sh/codes/analyze_codes.sh xx#\
\n\
\n\
\n\
相关的模板: #\
关于切片的rank(权重)的一般论述: sh/tips/run_template.sh qp_rank_overall#\
关于切片的确定性sure的一般论述: sh/tips/run_template.sh qp_sure_overall#\
\n\
对切片进行analyze分析: sh/tips/run_xls_template.sh xx analyze_qp #\
对切片进行监控trend: sh/tips/run_xls_template.sh xx qp_trend_overall



