#
#Fri Feb 14 15:36:12 CST 2025
juben=master-xls-overall
title=作为master题材相关的导航
category=analyze

replace=xls

# 直接手工指定本模板的operate字符串
operate_type=master

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall=00 master=99
no=91499

# 当前还缺题材的日间子股票池图形的分析: TODO: #\
qianyan=本文作为掌控xls相关的导航#\
\n\
\n\
[日间]#\
*从个股资金(ggzj)的角度进行分析: sh/tips/run_xls_template.sh xx analyze_cross_xls_by_ggzj#\
全市场API版本: sh/tips/run_xls_template.sh xx analyze_cross_xls_by_ggzj2#\
题材分析(日间): sh/tips/run_xls_template.sh xx analyze_xls_cross_state #\
日间走势核心实现: sh/tips/run_xls_template.sh xx analyze_xls_cross_trends #\
从短xt的图形数据进行分析: sh/tips/run_xls_template.sh xx analyze_cross_xls_by_duanxt#\
从题材的核心子股票池分析: \
sh/tips/run_xls_template.sh xx analyze_cross_xls_by_core_shape#\
\n\
[纯图形分析(日间)]#\
一般论述: sh/tips/run_xls_template.sh xx analyze_xls_shape_overall#\
\n\
\n\
[日内]#\
实时锚定(日内): sh/tips/run_xls_template.sh xx xls_maoding_overall #\
题材在市场中的地位(日内): sh/tips/run_xls_template.sh xx xls_diwei_default #\
\n\
快速监控(判断能不能买入): sh/tips/run_xls_template.sh xx xls_trend_fast #\
实时监控(日内): sh/tips/run_xls_template.sh xx xls_trend_default #\
通过ggzj数据来分析日内(条件允许的话 尽量使用这个): \
sh/tips/run_xls_template.sh xx analyze_xls_by_ggzj #\
如果题材强度够: sh/tips/run_xls_template.sh xx analyze_xls_rup_alot #\
\n\
\n\
\n\
\n\
一些相关的其它模板: 



