#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-master-pool
title=给出掌控题材池的相关tips(指定了题材 一半论述 一半计算)

replace=pool
enable_bkzj_df=0

qianyan=本文给一下掌控题材池(也就是已经有了题材池)的相关tips#\
更一般的论述间(这里非常简略): sh/tips/run_xls_template.sh xx master_pool_overall#\
\n\
给出一般的master pool的过程: #\
1 题材池的内生性/主动性计算/评估(如果不好量化的话) #\
2 对题材池内的老大做特别监控 #\
-> 那么题材池当前的老大是? #\
3 题材池间的竞争/监控 包括核心数据和整体数据 #\
4 最后是通过题材池的合并数据的前排数据 来做一个锚定计算#\
\n\
\n\
相关的模板: #\
关于掌控题材池的一般论述: sh/tips/run_xls_template.sh xx master_pool_overall #\
掌控[市场最顶级的核心]题材池: sh/tips/run_xls_template.sh xx master_pool_core


# 计算一下基础特征
flush_quan={00:00:00,23:59:59}if get_candi:xx*filter:max=4 then \
xx::subs.atplan:toubu->size:len=1[,09:24:59],\
zhushi:预计算一下subs:toubu

eva_quan={00:00:00,23:59:59}get_candi:xx*stage2:if2:\
cross_days_zijin_dafu_liuru,\
zhushi:计算一下是否满足标准的4天2日主力资金大幅流入

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: #\
给出一些题材池的日间数据 包括:#\
1 前日trd>4的数据 #\
2 trend3.days数据 #\
3 题材池内核心股票池的数据

flush_plan={09:00:00,09:15:00}xx::trd:min=5->size:len=2,\
xx->trend3.days3,\
xx::amount:limit=30->trend3,\
zhushi:计算一下题材池中的核心股在前日的表现,\
xx->if:amount_codes_alot.if,\
zhushi:判断题材池中是否满足amount-codes-alot,\
xx->if:chaoduan_codes_alot.if,\
zhushi:判断题材池中是否满足chaoduan-codes-alot

############################### 竞价时区
tips_jj={09:15:00,09:25:00}竞价时区:#\
对题材池来说 竞价时区已经有价值了 包括可以稍微一窥头部 核心 风险 强度等数据#\
头部数据包括: #\
涨停板: sh/flush_cli.sh xx if2:has_upstp.if #\
up5的数据: sh/flush_cli.sh xx up5 #\
核心股: sh/flush_cli.sh xx::subs.atplan:toubu trend3 #\
风险: sh/flush_cli.sh xx dstp info #\
\n\
直接打开jpg: sh/open/open_xls_list.sh xx

flush_jj={09:15:00,09:25:00}xx->trend3[09:20:00,],\
zhushi:注意 竞价时区的数据稍微看看就好 准确性不那么高的,\
xx->if:has_upstp.if[09:22:00,]

eva_jj={09:15:00,09:25:00}xx*amount:limit=100->btwed[09:20:00,],\
if xx*amount:limit=100->up3*filter:min=5 then \
xx*amount:limit=100->up3,back=append_xls2:xx[09:22:00,],\
zhushi:如果题材池的前排数据较好 那么做一下版块池分析

