#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-master-pool-overall
title=给出掌控题材池的总体论述(指定了题材 论述为主 少量计算)

replace=pool
enable_bkzj_df=0

qianyan=本文给一下掌控题材池(也就是已经有了题材池)的一些论述#\
更一般的论述 可以: sh/tips/run_template.sh master_pool_overall#\
\n\
先给出一些基本事实: #\
1 显然 题材池本身的特征是排在第一位的: 具体的特征包括: \
在市场中的地位(主动性) bkzj资金占比 大票占比 超短占比等#\
主动性计算包括: #\
bkzj分析: sh/pool/analyze_duori_zijin.sh xx #\
2 题材池本身的内部紧密程度 当然本文默认题材池是很紧密的/已经归类好的#\
3 题材池中的老大的表现至关重要 当然了老大不行的时候 老二能接替老大也行#\
4 和行情的联系度: 取决于题材池本身的主动性高低 简单说成反比 \
也就是题材池越重要 那么行情越无关紧要#\
\n\
\n\
论述一下锚定 #\
1 根据文章<2026-06-24 讨论一下锚定是不是伪命题> 认为一般情况下 可以\
暂时忘掉个股的锚定 此时 需要关注题材的头部数据(也就是通过头部数据来\
当作锚定 而不是某只个股) 和 全体数据->即做好监控#\
2 只有明显的数据的时候 可以视作锚定 比如有效的has upstp#\
3 关于题材间的竞争 可以把实时的题材池的数据合并起来 然后统一计算这个\
数据集中的前排数据 来做一个横向竞争#\
\n\
\n\
经过上面的论述 可知 掌控一个题材池 可以按照下面的步骤走:#\
1 题材池的内生性/主动性计算/评估(如果不好量化的话) #\
2 对题材池内的老大做特别监控 #\
-> 那么题材池当前的老大是? #\
3 题材池间的竞争/监控 包括核心数据和整体数据 #\
4 最后是通过题材池的合并数据的前排数据 来做一个锚定计算#\
\n\
\n\
相关的模板: #\
关于掌控题材池的一般论述: sh/tips/run_template.sh master_pool_overall #\
默认的掌控题材池实现(一半计算一半论述): \
sh/tips/run_xls_template.sh xx master_pool 



# 计算一下基础特征
flush_quan={00:00:00,23:59:59}if db32*filter:min=15:max=40 then \
xx::db32->size:len=1,\
zhushi:如果市场中的db32数量较多 那么进行计算,\
if amount:limit=50*trd:min=2*filter:min=20:max=40 then \
xx::amount:min=30:limit=30*trd:min=2->size:len=1,\
zhushi:如果前一日市场的大成交很好 那么进行计算,\
xx::subs.atplan:toubu->size:len=1[,14:59:59],\
zhushi:预计算一下subs:toubu

eva_quan={00:00:00,23:59:59}get_candi:xx*stage2:if2:\
cross_days_zijin_dafu_liuru,\
zhushi:计算一下是否满足标准的4天2日主力资金大幅流入,\
get_candi:xx*stage2:zijin:mode=cross,\
zhushi:给出基础的前日bkzj收盘数据





