#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-master-pool-core
title=给出掌控[市场最核心]题材池(数量限制<=3)的相关tips(指定了题材 一半论述 一半计算)

replace=pool
enable_bkzj_df=0
category=master

if=get_candi:xx*filter:min=1:max=4

qianyan=本文给一下掌控[市场最核心]题材池的相关tips#\
注意因为是最核心的题材池 因此会计算的特别的细致#\
更一般的论述间(这里非常简略): sh/tips/run_xls_template.sh xx master_pool_overall#\
\n\
给出一般的master pool的过程: #\
1 题材池的内生性/主动性计算/评估(如果不好量化的话) #\
2 对题材池内的老大做特别监控 #\
-> 那么题材池当前的老大是? #\
3 题材池间的竞争/监控 包括核心数据和整体数据 #\
4 最后是通过题材池的合并数据的前排数据 来做一个锚定计算#\
\n\
\n\
相关的模板: #\
关于掌控题材池的一般论述: sh/tips/run_xls_template.sh xx master_pool_overall


# 计算一下基础特征
flush_quan={00:00:00,23:59:59}xx::subs.atplan:toubu->size:len=1[,09:24:59],\
zhushi:预计算一下subs:toubu,\
xx->stage:top_amount:num=100:mode=cross[,09:24:59]

eva_quan={00:00:00,23:59:59}get_candi:xx*stage2:if2:\
cross_days_zijin_dafu_liuru[,09:24:59],\
zhushi:计算一下是否满足标准的4天2日主力资金大幅流入

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}amount:limit=40->get_codes,back=append_xls:xx,\
zhushi:确认一下市场前排成交个股中 大多数属于本题材池,\
if db43*filter:min=10 then db43->get_codes,back=append_xls:xx,\
zhushi:确认一下市场前排超短个股中 大多数属于本题材池

flush_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:15:00,09:25:00}竞价时区:#\
对核心题材池来说 竞价时区已经有价值了 包括可以稍微一窥头部 核心 风险 强度等数据#\
核心题材池合并的前排大成交个股数据直接查看: sh/eva/cli.sh xx*amount:limit=30 btw#\
快速刷新题材池的核心trend数据: sh/flush_cli.sh xx::amount:limit=20 trend3#\
直接打开jpg: sh/open/open_xls_list.sh xx

flush_jj={09:15:00,09:25:00}xx::amount:limit=20->trend3[09:20:00,],\
zhushi:快速刷新题材池的核心trend数据,\
xx->if:has_upstp0.if[09:22:00,]

eva_jj={09:15:00,09:25:00}if xx*amount:limit=50->up2*filter:min=5 then \
xx*amount:limit=50->up2,back=append_xls:xx,\
zhushi:查看题材池合并的数据的前排数据的append-xls分析

############################### 开盘时区
tips_open={09:25:01,09:30:00}开盘时区:#\
对开盘数据来说 这个时区是用于确定题材池绝对强度和相对强度(在市场中的位置)的重要时区,\
因此要同时给出绝对数据和相对数据#\
\n\
相对强度:#\
1 市场前50成交额+实时走的可以的数据的占比数据: \
sh/eva/cli.sh amount:limit=50 up2 --back append_xls:xx #\
2 全市场涨停板占比: \
sh/eva/cli.sh xls:fenshi upstp*up7 --back append_xls:xx #\
\n\
\n\
绝对强度:#\
核心题材池合并的前排大成交个股数据直接查看: sh/eva/cli.sh xx*amount:limit=30 btw#\
sh/flush_cli.sh xx::amount:limit=20 trend3 #\
直接打开jpg: sh/open/open_xls_list.sh xx #\
\n\
\n\
注意:因为是核心题材池 因此要格外关注老大的走势!!!!

eva_open={09:25:01,09:30:00}xx*amount:limit=30->btw:asc=0,\
xls:fenshi->up2*amount:limit=15,back=append_xls:xx[09:26:00,],\
zhushi:全市场的up2数据中的前排amount的题材池数据占比分析,\
if db32*filter:min=15 then db32->up5,back=append_xls:xx,\
zhushi:全市场的db32的实时前排数据中的题材池数据占比分析

flush_open={09:25:01,09:30:00}xx->if2:has_upstp0.if,\
xx::subs.atplan:toubu->trend3,\
xx->trend3,\
zhushi:注意这个全题材的trend数据可能不准 因为可能坍塌到核心个股



