#
#Fri Feb 14 15:36:12 CST 2025
juben=none-xls
title=对题材/切片一无所知时的临盘tips

replace=xls

qianyan=本文给一下当给出一个一无所知的题材时 如何进行下手#\
有以下几个角度可以尝试:#\
1 trend: 包括盘中的波动数据 是否突然上拉等 #\
2 锚定/前排数据: 包括对锚定 前排数据的题材分析等 #\
3 从买点的角度 可以分成"有理智的图形"和"没有理性的硬做"#\
有理智的图形 就是复杂的有逻辑性的状态图图形#\
没有理性的硬做: 直接把实时的图形硬做 包括前排的shake 前排的btw 前排的amount等#\
-> 下面的不同时区都会按照这几个内容来做#\
\n\
有没有更多的思路?#\
\n\
相关的模板:


tips_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:16:00,09:25:00}对于切片来说 竞价时区是有价值的 \
比如trend和图形都大有可为#\
trend相关:#\
1 sh/template/run_xls_template.sh xx trend #\
sh/xls/analyze_hangqing.sh xx #\
和过去交易日的对比: python realtime/stage/cli.py get xx trend3.cross #\
\n\
锚定/前排数据:#\
sh/eva/cli.sh xx btw:min=-2*ma_dis:min=2*btw:limit=20 --back append_xls2#\
sh/eva/cli.sh xx up5 --back append_xls2#\
sh/xls/maoding.sh xx (要求是原始类型的xls)#\
\n\
买点的角度:#\
1 直接分析图形: sh/qpc/find_fronts.sh xx bsd #\
2 喜欢的jj-rzq: sh/buyer/run_simple_eva.sh xx jj_rzq:min=2 info --mode open#\
sh/buyer/run_simple_eva.sh xx jj_xt:min=3 info #\
3 暴力点 直接把前排数据拉出来 反正我跟踪能力强(最直接and有效的思路了): \
sh/eva/cli.sh xx btw:min=-2*ma_dis:min=2*btw:limit=20 --mode open

eva_jj={09:16:00,09:25:00}xx->trend3.hist[09:20:00,],\
xx->btwed,\
xx->btw:limit=15:asc=0

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区 很多操作可以复用竞价时区#\
trend3相关: 没什么补充的 复用竞价即可#\
\n\
锚定/前排数据: 同样 复用竞价#\
\n\
买点的角度: 复用竞价#\
可以看看有没有baov的数据: sh/buyer/run_simple_eva.sh xx baov info

eva_open={09:25:00,09:30:00}xx->trend3.hist,\
xx->btwed,\
xx->btw:limit=15:asc=0,\
xx->amount:limit=10


############################### 早盘时区

tips_zao1={09:30:01,09:33:00}
