#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-show-chain
title=打印某个chain id对应的信息

replace=chain_id
category=tracing

# 判断一下chain id是否真的存在于数据库
if=xx->exist_in_rec

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 5代表tracing 1代表tips.properties 8代表chain
# 第4位和第5位数字组合代表了计算的类型 show=01
no=51801

functions=chain

qianyan=本文打印一下指定id(chain)在数据库中的计算#\
\n\
具体会打印以下信息: #\
1 数据库中id的所有数据 #\
2 如果这个id能够找到code-type,那么再计算一下对应的code-type的数据 #\
\n\
\n\
\n\
相关的模板: 

jcals_all={00:00:00,23:59:59}show_id_msg_in_rec(context,id),\
may_show_qp_info_by_query_id(context,id)


