#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-pool-tracing-none
title=给出指定版块池的bkzj-tracing(跟踪bkzj)论述(默认实现)\
(指定了版块池 一半论述 一半计算)

replace=pool
enable_bkzj_df=1
category=tracing

if=get_candi:xx*is_bk
if2=get_candi:bkzj.top[09:20:00,]

start=09:20:00

open_index=xx

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 5代表tracing 1代表tips.properties 1代表pool
# 第4位和第5位数字组合代表了计算的类型 bkzj=21
no=51121

qianyan=本文给一下版块池的bkzj-tracing(跟踪bkzj)计算#\
\n\
\n\
\n\
相关的模板: 

eva_quan={00:00:00,23:59:59}get_candi:xx,\
zhushi:给出版块池的原始数据,\
get_candi:xx*stage:merge_left=0:zijin[09:22:00,],\
zhushi:给出版块池的实时数据 如果数据不存在 那么可以默认这个题材的bkzj数据很差,\
get_candi:xx*stage:zijin_sum:len=4[09:33:00,]


############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}

