#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-qp-trend-overall
title=给出切片/股票池的trend(走势)总体论述(指定了切片 论述为主 少量计算)

replace=xls
enable_bkzj_df=0
force_origin_code_type=1
functions=qp_trend

category=tracing

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 4代表trend 1代表tips.properties 5代表qp-xls-sub 7代表builded
# 第4位和第5位数字组合代表了计算的类型 overall=00 xls_sub=01 xls_sub_rank_alot=02
no=41700

qianyan=本文给一下切片/股票池的trend(走势)的一些论述#\
更一般的论述 可以: sh/tips/run_template.sh qp_trend_overall#\
\n\
\n\
手工计算应该走哪个tips模板(根据rank找到tips模板):\
python engine/codes/trend/tips_decider.py get xx rank#\
\n\
\n\
相关的模板: #\
关于切片trend的一般论述: sh/tips/run_template.sh qp_trend_overall #\
默认的切片(未知切片信息)trend实现(一半计算一半论述): \
sh/tips/run_xls_template.sh xx qp_trend_none #\
切片本身有一定的权重(rank-alot): \
sh/tips/run_xls_template.sh xx qp_trend_rank_alot #\
有一定权重的rank的切片: sh/tips/run_xls_template.sh xx qp_trend_rank_alot#\
市场最顶级的rank的切片: sh/tips/run_xls_template.sh xx qp_trend_rank_top#\
权重不多的rank的切片: sh/tips/run_xls_template.sh xx qp_trend_rank_some#\
\n\
\n\
关于权重rank的一般论述: sh/tips/run_template.sh qp_rank_overall

eva_quan={00:00:00,23:59:59}xx->trend3.days[,09:24:59]

# 判断一下最终会走到哪个tips
jcals_all={00:00:00,23:59:59}get_dispatch_tips(context,code_type)




