#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-weak-buyer
title=弱势行情时的买点相关的tips

replace=xls

qianyan=给出一下弱势行情时的切片的买点策略#\
对于一个弱势行情的切片来说 永远先需要考虑 买点的安全性来源: #\
是切片本身形成了报团?#\
切片本身走出了逆势/超预期的强度?#\
还是来自于对应的题材的强度?#\
\n\
不要慌张 临盘先搞清楚安全性的问题再来做买点 4个小时呢 不急于一时#\
\n\
其实能够确定安全性的话 买点反而是简单的 无非是以下几种的一种:#\
1 纯逆势#\
2 5日图形形态good#\
3 2日图形形态good#\
\n\
这里再给出一些相关的模板:#\
1 弱势行情的总体买点思路: sh/tips/run_template.sh weak_buyer #\
2 弱势行情时的心态对抗: sh/tips/run_template.sh weak_duikang


############################# 盘前时区:
tips_plan={09:00:00,09:15:00}盘前的时候 可以先关注一下切片本身的数据,包括:#\
1 切片近期的强度#\
2 切片的题材和逻辑信息 比如是否一家独大 哪些题材占据主要的成分: \
sh/codes/analyze_pool.sh xx --day $day --mode plan

############################# 竞价时区:
tips_jj={09:16:00,09:25:00}弱势行情的时候 竞价的时候 就已经构成可以筛选的图形了#\
1 直接按照图形来:\
sh/codes/fronts/find_fronts.sh xx good5 #\
sh/codes/fronts/find_fronts.sh xx good #\
sh/codes/fronts/find_fronts.sh xx bsd #\
2 股票池前排数据是否符合一家独大: \
sh/codes/analyze_pool.sh xx*eva:btw:min=2:limit=20 #\
3 风控某种角度上也不能完全抛弃: \
sh/codes/fronts/find_fronts.sh xx jj_bad

############################# 开盘时区:
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


############################# 开盘时区:
tips_zao1={09:30:01,09:33:00}







