#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-buyer
title=根据切片的特征(?)快速选择买点方案的tips

replace=xls

qianyan=根据切片的特征来给出买点方案是最基本的临盘买点方案了,那么本文来列出特征\
和对应的买点方案:#\
1 市场核心高权重切片+根据强度判定买点 ==> \
sh/tips/run_xls_template.sh xx qp_core_buyer#\
2 未知切片特征/不存在明显的切片特征时 ==> \
sh/tips/run_xls_template.sh xx qp_none_buyer#\
3 已知切片的行情时给出买点方案 ==> \
sh/tips/run_xls_template.sh xx qp_hq_buyer#\
4 未知切片强度,根据切片的实时强度实时计算然后给出买点方案 ==> \
sh/tips/run_xls_template.sh xx qp_realtime_hq_buyer#\
\n\
什么都不想 直接硬做 试试这个 ==> sh/tips/run_xls_template.sh xx none_xls#\
sh/tips/run_xls_template.sh xx yingzuo_buyer


# 既然是按照切片的特征来选择买点方案 那么自动计算一下切片的特征? TODO:

