#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-qp-trend-none(xls-sub分支)
title=给出[xls-sub类型]切片的trend(走势)论述

replace=xls
enable_bkzj_df=0
force_origin_code_type=1

category=tracing

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 4代表trend 1代表tips.properties 5代表qp-xls-sub 7代表builded
# 第4位和第5位数字组合代表了计算的类型 overall=00 none=01 xls-sub=02
no=41502

qianyan=本文给一下[xls-sub类型+rank不明]切片的trend(走势)的论述和计算#\
更一般的论述 可以: sh/tips/run_template.sh qp_trend_overall#\
\n\
\n\
对于xls-sub类型的切片来说 #\
1 本身的数据是重要的#\
2 但是本切片在对应题材的权重 排序也是重要的#\
3 对应题材的走势 也是重要的#\
因此会同时给出上述的所有数据 #\
\n\
\n\
\n\
\n\
相关的模板: #\
关于切片trend的一般论述: sh/tips/run_template.sh qp_trend_overall #\
默认的切片trend实现(一半计算一半论述): \
sh/tips/run_xls_template.sh xx qp_trend_none #\
切片本身有一定的权重(rank-alot): \
sh/tips/run_xls_template.sh xx qp_trend_rank_alot #\
\n\
关于切片的rank(权重)的一般论述: sh/tips/run_template.sh qp_rank_overall


eva_quan={00:00:00,23:59:59}

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:#\
切片本身的走势:#\
\n\
切片对应的题材的走势:#\
\n\
题材前排个股中切片的占比:

eva_open={09:25:00,09:30:00}xx->trend3.cross,\
xx->trend3.hist,\
xx->btw:limit=12:asc=0,\
zhushi:就给出最直接的前排数据,\
print_fenge,\
xx*first->trend3.cross,\
xx*first->if2:has_upstp.if,\
xx*first->stage:zijin,\
print_fenge,\
xx*first->btw:min=0:limit=20,back=append_xls:xx,\
zhushi:给出全题材btw前排数据中切片的占比数据

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_zao={09:30:01,09:45:00}早盘时区:#\
切片本身的走势:#\
\n\
切片对应的题材的走势:#\
\n\
题材前排个股中切片的占比:

eva_zao={09:30:01,09:45:00}xx->trend3.cross,\
xx->trend3.hist,\
xx->btw:limit=12:asc=0,\
zhushi:就给出最直接的前排数据,\
print_fenge,\
xx*first->trend3.cross,\
xx*first->trend3.hist,\
xx*first->if2:has_upstp.if,\
xx*first->stage:zijin,\
print_fenge,\
xx*first->btw:min=0:limit=20,back=append_xls:xx,\
zhushi:给出全题材btw前排数据中切片的占比数据,\
xx*first->amount:limit=20,back=append_xls:xx

