#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-dabodong-buyer
title=切片买点相关的{大波动行情}的临盘tips

replace=xls

qianyan=对大波动行情来说 尤其是竞价时区就呈现明显的大波动的时候 \
对我来说 买点倒是其次 最大的考验是心态能否保持稳定。#\
从底层逻辑来看 大波动要么说明指数不稳定 要么说明某些题材进行剧烈的切换 \
无论是哪一种 其实把买点稍微延后(一点) 先把情况看明白了 再做买点比较稳妥


tips_plan={09:00:00,09:15:00}对大波动行情来说 盘前的时候 最好关注一下题材的数据#\
sh/codes/analyze_pool.sh xx --day $day --mode plan

tips_jj={09:16:00,09:25:00}竞价的时候 大波动的话 需要关注以下信息#\
1 总体来说 是向上波动 还是向下波动: sh/template/run_xls_template.sh xx trend#\
sh/buyer/run_qp_template.sh xx shake_alot info --day $day#\
2 对极大波动的数据 可以做一个数据分析: sh/codes/analyze_pool.sh \
xx*eva:jj_xt:min=4:limit=20 --day $day#\
\n\
还是要说 对大波动行情来说 先把行情看明白更重要 要相信自己盘中的买点能力


# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


tips_zao1={09:30:01,09:33:00}
