#
#Fri Feb 14 15:36:12 CST 2025
juben=qzhendang-buyer
title=在(判定为强震荡行情)的前提下给出股票池买点相关的临盘tips

replace=xls

qianyan=强震荡行情的一些特征:#\
1 买点很多#\
2 买点尽量提前: 因为竞价和开盘时区很重要 #\
\n\
详见: open engine/observe/tips/template/qzhendang_buyer.tips.properties


tips_plan={09:00:00,09:15:00}

############################## 竞价时区
tips_jj={09:16:00,09:25:00}对强震荡行情来说 \
竞价时区已经极具价值,大有可为#\
1 判定股票池的头部和尾部数据: sh/codes/fronts/find_fronts.sh xx jiasu#\
sh/codes/fronts/find_fronts.sh xx jj_bad#\
sh/codes/fronts/find_fronts.sh xx bsd#\
2 确认股票池的强势: python realtime/stage/cli.py get xx fronts_fenbu:jiasu.cross#\
\n\
对股票池的头部数据进行版块池分析: sh/codes/analyze_pool.sh xx*eva:btw:min=2:limit=20

eva_jj={09:16:00,09:25:00}xx->trend3.hist[09:22:00,],\
xx->caop:find_fronts:bsd[09:22:00,],\
xx->if2:shake_alot.if[09:20:00,],\
zhushi:判断是否shake alot,\
xx->if2:rup2_alot.if[09:21:00,],\
zhushi:判断是否rup2-alot,\
xx->if2:has_upstp0.if[09:23:00,],\
zhushi:判断是否存在涨停板


############################## 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


# 注意下面的 xx->if2:eva-jj_rzq:min=1.8*alot2 中的[eva-]
eva_open={09:25:00,09:30:00}xx->trend3.hist,\
xx->caop:find_fronts:bsd,\
xx->if2:shake_alot.if,\
zhushi:判断是否shake alot,\
xx->if2:rup2_alot.if,\
zhushi:判断是否rup2-alot,\
xx->if2:has_upstp0.if,\
zhushi:判断是否存在涨停板,\
xx->if2:eva-jj_rzq:min=1.8*alot2,\
zhushi:判断是否竞价弱转强alot



############################## 早盘时区
tips_zao1={09:30:01,09:33:00}

eva_zao1={09:30:01,09:45:00}
