#
#Fri Feb 14 15:36:12 CST 2025
juben=qp-none-buyer
title=切片买点相关的临盘tips(默认)

replace=xls

qianyan=对切片买点来说 永远要先思考这个切片的确定性来源于哪里#\
是来自本身强度明显超过了往期?#\
是来自对应题材的确定性?#\
是来自指数层面的普涨?#\
只有清楚的知道了确定性来源 才能临盘的时候更加的冷静和确定#\
\n\
除了确定性以外 盘前也可以大致判定一下切片的择时 开盘 早盘 盘中?


tips_plan={09:00:00,09:15:00}盘前的时候 可以先关注一下切片本身的数据,包括:#\
1 切片近期的强度#\
2 切片的题材和逻辑信息 比如是否一家独大 哪些题材占据主要的成分: \
sh/codes/analyze_pool.sh xx --day $day --mode plan

tips_jj={09:16:00,09:25:00}竞价的时候 需要关注以下信息#\
1 本身的大致走势 大致强度和波动性#\
2 对头部的数据保持关注 不论是本身有没有可能当作买点 还有其中的逻辑信息

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}


tips_zao1={09:30:01,09:33:00}
