#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-qp-trend-rank-alot
title=给出[较高权重]切片/股票池的trend(走势)论述(指定了切片 一半论述 一半计算)

replace=xls
enable_bkzj_df=0
force_origin_code_type=1

qianyan=本文给一下[较高权重]切片/股票池的trend(走势)的论述和计算#\
更一般的论述 可以: sh/tips/run_template.sh qp_trend_overall#\
\n\
\n\
对于高权重(重要题材+重要个股)的切片 它的走势主要由以下要素影响:#\
1 日间走势+日内走势形成的组合走势/状态图 #\
2 这类切片可能形成坍塌/报团 因此只需要头部数据安全就行 #\
3 因为没有重要到能够无视市场行情 因此:最好不要出现跌停板+最好还是看一下对应题材的走势#\
下文会主要根据这些思路来进行判断#\
\n\
\n\
\n\
\n\
相关的模板: #\
关于切片trend的一般论述: sh/tips/run_template.sh qp_trend_overall #\
默认的切片trend实现(一半计算一半论述): \
sh/tips/run_xls_template.sh xx qp_trend_none #\
切片本身有一定的权重(rank-alot): \
sh/tips/run_xls_template.sh xx qp_trend_rank_alot #\
\n\
关于切片的rank(权重)的一般论述: sh/tips/run_template.sh qp_rank_overall


eva_quan={00:00:00,23:59:59}

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: #\
确认一下切片的权重 比如资金数据 #\
计算一下切片的trend3.days数据

eva_plan={09:00:00,09:15:00}xx*first->stage:zijin.days5,\
zhushi:计算一下资金流入数据,\
xx*first->if2:cross_days_zijin_dafu_liuru.if,\
zhushi:判断一下是否多日流入,\
xx->trend3.days5,\
xx*first->trend3.days3

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: #\
严格按照上面提到的: #\
1 日间走势+日内走势形成的组合走势/状态图(如果本身波动偏大 那么就关注日内数据即可) #\
python realtime/stage/cli.py get xx trend3.cross #\
2 这类切片可能形成坍塌/报团 因此只需要头部数据安全就行 #\
python realtime/stage/cli.py get xx fronts_fenbu:jiasu.cross #\
python realtime/stage/cli.py get xx fronts_fenbu:good.cross #\
3 因为没有重要到能够无视市场行情 因此:最好不要出现跌停板+最好还是看一下对应题材的走势

eva_jj={09:16:00,09:25:00}xx->trend3.days5[09:21:00,],\
xx*first->trend3.days3[09:21:00,],\
xx->trend3.hist[09:22:00,]


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:#\
可以完全照抄竞价时区的操作即可#\
python realtime/stage/cli.py get xx fronts_fenbu:jiasu.cross 

eva_open={09:25:00,09:30:00}xx->trend3.days5,\
xx->trend3.cross4,\
xx*first->trend3.days3,\
xx->trend3.hist[09:22:00,],\
xx->if2:has_upstp0.if,\
if xx->dstp,\
zhushi:判断有没有跌停板,\
xx->if2:rup2_alot.if,\
xx->stage:zijin,\
xx->btw:limit=10:asc=0

############################### 早盘时区

tips_zao1={09:30:01,09:45:00}早盘时区:#\
python realtime/stage/cli.py get xx fronts_fenbu:jiasu.cross3 #\
python realtime/stage/cli.py get xx fronts_fenbu:good.cross3 #\
sh/eva/cli.sh xx btw:limit=15 --open 1

eva_zao1={09:30:01,09:45:00}xx->trend3.cross4,\
xx*first->trend3.days3,\
xx->trend3.hist,\
xx->if2:has_upstp0.if,\
if xx->dstp,\
zhushi:判断有没有跌停板,\
xx->if2:rup2_alot.if,\
xx->stage:zijin,\
xx->btw:limit=10:asc=0,\
xx->co:limit=10:asc=0,\
xx->stage:opp_fenbu



