#
#Fri Feb 14 15:36:12 CST 2025
juben=remen-xls
title=给出热门题材的临盘tips

replace=origin_xls

qianyan=这里先准确定义一下热门题材: 资金持续扎堆的 or 新进入资金视角的题材

################################ 盘前时区

tips_plan={09:00:00,09:15:00}盘前时区是最好的判定输入的题材是否是\
热门题材的时区:#\
1 从bkzj的角度: python realtime/candi/cli.py get \
list:xx*stage2:if_size:min_size=1:if_zijin_alot.days4 --mode plan#\
python realtime/stage/cli.py get xx zijin.days4 --mode plan#\
2 直接从资金(题材内的大成交)角度: python realtime/stage/cli.py get \
xx*amount:min=5:limit=80*pos_pchg:min=16 size:len=6 --mode plan#\
3 直接看涨停板的数据: python realtime/stage/cli.py get \
xx*CODES_BAN size:len=6 --mode plan#\
4 查看trd4的数据: python realtime/stage/cli.py get \
xx*trd:min=4.4 size:len=6 --mode plan#\
5 计算梯队数据(虽然不知道现在这种超短数据还有没有用):python \
realtime/stage/cli.py get xx ban_total --mode plan#\
6 在市场前50成交的占比数据: python realtime/stage/cli.py get \
amount:limit=60*xx size:len=8 --mode plan

eva_plan={09:00:00,09:15:00}xx->trend3.days6

################################ 竞价时区

tips_jj={09:16:00,09:25:00}

####### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}
eva_open={09:25:00,09:30:00}


####### 早盘时区
tips_zao1={09:30:01,09:33:00}
eva_zao1={09:30:01,09:45:00}
