#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出out-xt这个特别的eva的对于题材/股票池的视角
replace=xls

enable_bkzj_df=0

# 对outxt-eva的细分类型做一个论述+实际计算
# 细分类型见@eva/tuxing/outxts_1.py

# no的赋值规则见@engine/enum/no_rule_enum.py 
# silu(第3位数字)的赋值规则见@engine/enum/silu_enum.py 
# 6代表silu 1代表tips.properties 8代表spec-eva 所以前3位是固定的
# 第4位和第5位数字组合代表了计算的类型 outxt=04
no=61804

qianyan=本tips包含两个部分 论述outxt这个eva视角的重要性+实时的具体数据 #\
\n\
注意: outxt图形本身比较适合市场环境较好 资金做多意愿较强的环境 否则还是建议inxt-eva #\
注意2: outxt图形尤其tx:outxt 本身已经有一定的筛选力度了的(这也是为什么我这么看重) #\
\n\
\n\
[outxt-eva本身的语义和分类] #\
当前我在@eva/tuxing/outxts_1.py 中我定义了4个基本算子: #\
tx:outxt1 => 最基础的几乎不限制的eva #\
tx:outxt2 => 对箱体的宽度做一般的限制 #\
tx:outxt3 => 箱体宽度较高 #\
tx:outxt11 => 箱体最严格的限制 扁箱体 #\
\n\
首先 从语义上来说 outtx eva代表了一个题材本身进攻的意愿 #\
那么最简单的 资金一般来说 会从箱体宽度最高开始进攻 然后一般宽度 然后最后溢出到扁箱体 #\
\n\
但对于a股来说 还有一些其它规律 #\
1 如果热度很高/过热 那么资金内部也会考虑高低切 此时扁箱体的优先级会提高 #\
2 对盘中 准盘中时区来说 扁箱体的优先级较高 因为这些喜欢盘中的资金也是鸡贼的资金 \
和图形本身也很契合了 #\
\n\
\n\
\n\
[和其它eva的组合] #\
还没有想好  TODO:  #\
\n\
\n\
对应的gene qp: sh/codes/qp/gene/by_xls.sh xx outxt_eva --time_str $time_str 

eva_all={09:18:00,23:59:59}xx->size:len=1,\
xx->if2:eva-tx:outxt1,\
xx->if2:eva-tx:outxt2,\
xx->if2:eva-tx:outxt3,\
xx->if2:eva-tx:outxt11

