#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出xls:iggzj的操作思路(盘前思路 临盘操作思路 股票池的属性分析)
replace=xls

enable_bkzj_df=1

# 参考@silu_BK1633.tips.properties

# 必须是xls:iggzj的子股票池
if2=xx->has_codes_str:xls:iggzj
if3=xx->one_code and xx*filter:min=10

start=09:30:01

# no的赋值规则见@engine/enum/no_rule_enum.py 
# silu(第3位数字)的赋值规则见@engine/enum/silu_enum.py 
# 6代表silu 1代表tips.properties 9代表spec-codes 所以前3位是固定的
# 第4位和第5位数字组合代表了计算的类型 xls:iggzj=11 xls:iggzj-sub=12
no=61911

functions=codes_shape
before_func=init_codes_no_if($day),init_evas_no_if($day)

if=codes_no_recorder_inited

qianyan=本tips给一下xx的思路(盘前思路 临盘操作思路 股票池的属性分析)#\
\n\
对于xls:iggzj来说 是可以同时用做版块池/逻辑梳理和买点的 本文也会分别做这两个方面的工作 #\
当然 不同的行情下 侧重点不同 一些规律: #\
1 对于大涨后一日的分化预期来说 此时很难形成题材买点 因此这个时候应该侧重在\
买点(甚至可以直接无视题材逻辑 因为会有惯性上冲) #\
2 对于某天行情爆炸的时候 此时买点会爆炸 那么侧重在逻辑梳理 \
实在要做买点则需要走细分再细分的图形 比如叠加MSCI #\
3 更多规律暂时不赘述 #\
\n\
\n\
[版块池分析] #\
sh/codes/qp/gene/by_xls.sh xx split_pool #\
sh/codes/qp/gene/by_xls.sh xx:min_zhuli=0.3:limit=50 split_pool #\
sh/codes/qp/gene/by_xls.sh xx:min_zhuli=0*db50 split_pool #\
python strategy/cli.py get xls:iggzj.atzao1:limit=15 --back append_xls2 #\
sh/eva/cli.sh xx:limit=18 rup2 --back append_xls2 #\
\n\
\n\
一些图形组合: #\
xls:iggzj*BK1717(题材股) #\
xls:iggzj*BK0821(MSCI) 叠加了权重的数据 也是不错的 #\
xls:iggzj*shizhi:min=400 叠加中大市值 #\
xls:iggzj*shizhi200 叠加中市值 这个市值规避了太大波动的小票 也规避了波动太小的大票 优质#\
xls:iggzj*10cm*not:no30100 偏轮动的图形 #\
xls:iggzj*not:tx:huoli 获利盘不多的图形 也是备选股票池 #\
\n\
\n\
\n\
相关模板: #\
关于xls:iggzj的make plan: sh/tips/run_xls_template.sh xx make_plan_xls_iggzj #\
\n\
\n\
生成对应的gene-qp: sh/codes/qp/gene/by_tips.sh xx silu_xls_iggzj --time_str $time_str

tips_plan={09:00:00,09:15:00}盘前的实现直接复用: \
sh/tips/run_xls_template.sh xx make_plan_xls_iggzj

tips_all={09:15:00,23:59:59}考虑手工对比日间强度: python realtime/stage/cli.py \
get xls:iggzj trend3.cross --mode zao2[09:30:01,09:48:00]

# 根据不同的强度 应该走不同的分支 比如silu_xls:iggzj_rup_alot.tips.properties?  TODO:    

# if xx*simple_code then xx*10cm*no30100->if2:eva-up0*filter:min=5,\
# if xx*simple_code then xx*10cm*no30200->if2:eva-up0*filter:min=5,\
# if xx*simple_code then xx*10cm*no40100->if2:eva-up0*filter:min=5

# xx*xls:ggzj->if2:eva-btw:min=1*filter:min=5,\
# zhushi:判断xls:ggzj+实时up1组合数据量是否>5,\

eva_all={09:15:00,23:59:59}xx->trend3.hist[09:25:00,],\
if xx*db51->rup2*filter:min=15 then xx*db51*eva:rup2==split_pool.ana[09:19:00,],\
zhushi:前排数据+db51做版块池分析 借助eva-str实现,\
if xx*db50->rup2*filter:min=15 then xx*db50*eva:rup2==split_pool.ana[09:19:00,],\
zhushi:前排数据+db50做版块池分析 借助eva-str实现,\
xx->stage:shape_fenbu:shizhi,\
xx->btw_fenbu,\
print_fenge,\
if xx->btw:min=2*filter:min=40 or xx->rup3*filter:min=25,\
zhushi:当前btw>2或者rup3的强度爆表了 说明存在结构性的热度机会,\
print_fenge,\
print:下面开始计算特定图形的数据,\
xx*BK0821->if2:eva-btw:min=1*filter:min=5,\
zhushi:判断叠加MSCI+实时up1组合数据量是否够用 够用可以考虑做买点,\
xx*BK1717->if2:eva-btw:min=3*filter:min=5,\
zhushi:判断叠加题材股+实时up3组合数据量是否够用 够用可以考虑做买点,\
xx*BK1633->if2:eva-btw:min=3*filter:min=5,\
zhushi:判断叠加BK1633高震幅股+实时up3组合数据量是否够用 够用可以考虑做买点,\
xx*10cm*no30000->if2:eva-rup2*filter:min=5,\
zhushi:判断基础xt 30000+实时rup2数据是否>5

# 在本文的最底端 加入一段收尾信息输出
jiewei=考虑根据本模板生成切片: \
sh/codes/qp/gene/by_tips.sh xx silu_xls_iggzj --time_str $time_str --action download


