#
#Fri Feb 14 15:36:12 CST 2025
juben=safe-buyer
title=在(考虑风控)的角度下给出股票池买点相关的临盘tips

replace=xls

qianyan=因为是考虑风控的角度 因此本模板会把很大的精力放在风控上


tips_plan={09:00:00,09:15:00}盘前的时候 可以先关注一下切片本身的数据,包括:#\
1 切片近期的强度#\
2 切片的题材和逻辑信息 比如是否一家独大 哪些题材占据主要的成分: \
sh/codes/analyze_pool.sh xx --day $day --mode plan

tips_jj={09:16:00,09:25:00}竞价的时候 需要关注以下信息#\
1 本身的大致走势 大致强度和波动性

####### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}对于开盘来说 判断整体的强度和波动是比较关键的#\
如果有跌停板的话 那么风险就很大了#\
如果波动很大的话 可以继续针对波动做一个计算: sh/buyer/run_qp_template.sh \
xx shake_alot info --mode open


eva_open={09:25:00,09:30:00}xx->if2:dstp,\
zhushi:判断是否存在跌停板,\
xx->if2:shake_alot.if,\
zhushi:判断波动是否alot




####### 早盘时区
tips_zao1={09:30:01,09:33:00}对于早盘时区来说 是判定风控最重要的时区之一 因此#\
1 通过对比头部数据来判断强度: python realtime/stage/cli.py get xx \
fronts_fenbu:jiasu.cross4#\
2 通过获取risk数据来判定风险: python realtime/stage/cli.py get xx risk_fenbu.cross#\
python realtime/stage/cli.py get xx risk_fenbu.hist#\
3 也可以调用更复杂的模板计算: sh/template/run_xls_template.sh xx trend#\
4 如果有跌停板出现的话 要更加注意风险

eva_zao1={09:30:01,09:45:00}xx->if2:dstp,\
zhushi:判断是否存在跌停板,\
xx->trend3.hist
