
# 监控题材的pull信息	TODO:
# 实现参考@xx_xls_trend_default.tips.properties 
# sh/eva/find_template.sh pull
# @engine/eva_str/export//trace/pull_tracing_evas.py

# sh/template/find_template.sh pull
# @xx_pull_info_094500.template.properties

# 文章<2026-04-05 搞定盘中快速上行的题材的买点>有一定的质量 可以一看

# 其实从纯买点的角度 单个pull的图形是不够的 必须还要上状态图eva才行...

