#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-cross-diwei
title=给出题材的日间地位分析

replace=xls+bk
enable_bkzj_df=0

try_save_to_chain=1
chain_node=analyze_xls

time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 1代表tips.properties 4代表xls(analyze-xls)
# 第4位和第5位数字组合代表了计算的类型
# no的说明 overall(no-xx)=99 cross-diwei=04
no=91404

qianyan=给出题材的日间地位分析 #\
分别会从以下角度来进行分析: #\
bkzj #\
xls:ggzj #\
db32代表的超短(超短可能会比较复杂) #\
BK1633代表的热度票 #\
\n\
\n\
\n\
\n\
一些实用的命令: #\
查看前日bkzj: python realtime/candi/cli.py get bkzj.zhuli --mode plan
\n\
\n\

eva_bkzj={00:00:00,23:59:59}print:bkzj角度进行分析,\
get_candi:bkzj.cdadan:limit=30*list:xx,\
zhushi:判断题材对应的bkzj数据是否在前日大单前30 如果非空 那么在,\
get_candi:bkzj.czhuli:limit=35*list:xx,\
zhushi:判断题材对应的zhuli数据是否在前日大单前30 如果非空 那么在,\
get_candi:BKZJ_HOT_3DAYS_1*list:xx,\
zhushi:判断题材是否在近3日热门题材池 如果非空 那么在,\
get_candi:BKZJ_ZHULI_2*list:xx,\
zhushi:判断题材是否在近5日主力题材池 如果非空 那么在

eva_ggzj={00:00:00,23:59:59}if not exist_ggzj then break,\
zhushi:走到了ggzj分支 但是不存在ggzj数据 break,\
print:ggzj角度进行分析,\
xls:ggzj:limit=50*xx->size:len=3,\
zhushi:在市场前50数据的变化值,\
xls:ggzj:limit=30*xx->get_codes,\
if xls:ggzj:limit=30*xx*filter:min=3 then \
xls:ggzj:limit=30->get_codes,back=append_xls:xx,\
zhushi:在市场ggzj前排的数据

eva_chaoduan={00:00:00,23:59:59}if not xx*db32*filter:min=1 and \
not xx*db21*filter:min=5 then break,\
zhushi:走到了chaoduan分支 但是不满足最基础的超短数量 break,\
print:chaoduan角度进行分析,\
xx*db32->size:len=4,\
xx*CODES_BAN->size:len=6,\
if db32*filter:max=30 then db32->get_codes,back=append_xls:xx,\
if db32*filter:min=31 then db43->get_codes,back=append_xls:xx,\
if db32*filter:min=31 then db22->get_codes,back=append_xls:xx

eva_other={00:00:00,23:59:59}print:一些其它角度,\
if new:BK1633*filter:min=5 then xx*BK1633->size:len=4,\
zhushi:BK1633的数量变化,\
if amount:limit=40*xx*filter:max=5 then amount:limit=40*xx->get_codes,\
zhushi:全市场前40amount的角度,\
if amount:limit=40*xx*filter:min=6 then \
amount:limit=40->get_codes,back=append_xls:xx,\
zhushi:全市场前40amount的角度



