#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给定一个未知的题材时 怎么给出买点方案思路

replace=xls
# 给定一个未知的题材时 怎么给出买点方案思路 -> 我近期最关心的问题之一
# 这种给定题材 实盘进行择时的 算是一种左侧方案了 是我必须一定要搞定的买点

start=09:16:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# buyer(第3位数字)的赋值规则见@engine/enum/buyer_enum.py
# 8代表buyer 1代表tips.properties 3代表buyer-silu
# 第4位和第5位数字组合代表了计算的类型 huizong=00 xls-buyer-silu=08
no=81308

qianyan=本tips解决一下给定一个未知的题材时 怎么给出买点方案思路难题 #\
\n\
从买点的角度 其实纯图形问题 (当然这里不考虑风控问题) 那么纯从买点的角度 有: #\
1 资金角度 也就是基于ggzj API来做买点 当然这个数据也不一定很准 #\
2 日内准度图形 #\
3 日间图形来提供准度 #\
4 如果是builded 那么还有builded+pool的角度 #\
\n\
其中 #\
1 资金的角度数据是比较有保障的 那么优先使用这个 #\
2 如果日内强度够用 那么先日内图形再日间图形 这个很好理解 如果题材开盘就上冲了 你却不冲 你就弱了 #\
3 如果日内强度不够 那么早盘的竞争结果 也是买点 前提是对这个题材看好 \
否则你去一个很弱的题材做竞争买点 也是不行的 #\
4 然后是日间图形买点 这个其实适用于题材没那么强 或者题材爆强的溢出效应 #\
总结上面的内容可知: #\
1 资金视角优先级高 但对不同的题材+eva:ggzj计算出的数据量 也要走不同的分支 #\
2 题材的日内强度or预估买点数量 是一个重要的数据 用于我判断使用哪个应对策略 #\
(上面2个数据是必须搞定的) #\
\n\
\n\
\n\
相关模板: #\
盘前需要对题材的图形有一个基本的认知: \
sh/tips/run_xls_template.sh xx xls_make_plan_overall#\
题材的trends,地位分析: \
sh/chain/gene/run_xls_template.sh xx fast_known_xls#\
\n\
*直接无脑走对应的买点chain: \
sh/chain/gene/run_xls_template.sh xx xls_buyer_default #\
\n\
缺买点太多时的应对策略 		TODO:


eva_all={00:00:00,23:59:59}xx->upstp*ban_size,\
xx->btw:limit=20:asc=0,\
zhushi:给一下最基础的前排数据,\
xx*10cm->btwed,\
xx*10cm->if2:rup2_alot.if,\
xx*10cm->if2:rup3_alot.if,\
xx*10cm->if2:rup5_alot.if,\
if exist_ggzj then xx->if:eva-ggzj2*filter:min=15,\
zhushi:给一下ggzj-eva的数据量 有一个基础认知


