#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-maoding-overall
title=给出题材锚定的总体论述(论述为主 少量计算)

replace=xls
enable_bkzj_df=0

qianyan=本文给一下给定题材后关于锚定的总体/一般论述#\
先阐述一些事实：#\
1* 题材的锚定和题材过去几个交易日的走势的状态有关->题材的内生性要素 #\
2 题材的锚定和市场的行情也强相关#\
3 正常行情下 比如震荡 普涨行情下 题材的锚定就是那几个标准的指标：\
涨停板 核心个股(可以是权重 也可以是弹性) bkzj流入数据 市场的竞争结果 \
20cm的锚定#\
4 特殊行情 比如弱势行情 能否形成逆势#\
\n\
\n\
相关的模板:
1 关于题材锚定(不给定题材)的一般论述: \
sh/tips/run_template.sh xls_maoding #\
2 手工计算一下题材的基础数据: \
sh/tips/run_xls_template.sh xx basic_xls

eva_quan={00:00:00,23:59:59}if xx->cross_days_zijin_dafu_liuru,\
zhushi:判断题材是否属于多日资金大幅流入,\
xx->if2:amount_codes_alot.if,\
zhushi:判断题材中的大成交股票池是否alot

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: #\
盘前时区对锚定来说还挺重要 这个时间可以对题材做大量的分析#\


eva_plan={09:00:00,09:15:00}xx->stage:zijin.days5,\
zhushi:计算一下资金流入数据

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区:

eva_jj={09:16:00,09:25:00}if xx==amount_codes_alot.if then \
xx*amount:limit=30->btw:limit=15,\
zhushi:如果大成交很多 看看对应的数据,\
xx->if2:has_upstp.if

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}xx->if2:has_upstp.if


############################### 早盘时区

tips_zao1={09:30:01,09:33:00}
