#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=拿到一个指定的未知的题材时 如何进行分析+make plan 

replace=xls

# 写死时间戳
time_str=09:00:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# gene(第3位数字)的赋值规则见@engine/enum/gene_enum.py 
# 7代表gene 1代表tips.properties 0代表plan 所以前3位是固定的
# 题材的plan 从数字40开始
# 第4位和第5位数字组合代表了计算的类型 overall=40 none=01 
no=71040

#functions=codes_shape
#before_func=init_codes_no_if($day)
functions=build_pool
before_func=init_codes_no_if($day),\
build_pool_codes(context,"list:BK1717,BK0821")

if=codes_no_recorder_inited

qianyan=本tips解决的问题是: 拿到一个指定的未知的题材时 如何进行分析+make plan#\
\n\
显然 当然可以对题材做trends分析 地位分析 但从买点的角度 没有什么比\
图形更重要 因此本文的侧重点 就是图形 #\
\n\
第一步 显然是对题材进行简单的剪裁(正常来说 题材的数据量对我来太大的) 剪裁的策略包括: #\
题材+xls:ggzj: 优先选择/甚至可以无脑选择 数据量太小另说 #\
题材+tover #\
题材+amount #\
题材+辨识度图形 #\
题材+BK0821(MSCI) #\
题材+BK1717(题材股) #\
题材+BK1633(昨日高震幅) #\
\n\
\n\
有了builded图形后 可以进行2次chain计算: \
sh/chain/gene/run_xls_template.sh xyz make_plan_builded_codes --mode plan#\
\n\
当然 如果觉得有必要 可以补一下对题材的trends,地位分析: \
sh/chain/gene/run_xls_template.sh xx fast_known_xls

eva_all={00:00:00,23:59:59}xx*xls:ggzj->size:len=1,\
xx*tover:min=5->size:len=1,\
xx*tover:min=3->size:len=1,\
xx*amount:min=3->size:len=1,\
xx*10cm*no30100->size:len=1,\
xx*10cm*no30200->size:len=1,\
xx*10cm*no40100->size:len=1,\
xx*BK1717->size:len=1,\
xx*BK0821->size:len=1

