#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-trend-default
title=监控xls trend的默认实现

replace=xls
enable_bkzj_df=0
open_index=xx
category=tracing

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 4代表trend 1代表tips.properties 1代表origin-xls
# 第4位和第5位数字组合代表了计算的类型 overall=00 none/default=01 
no=41101

# 参考@engine/observe/juben/template/xx_tracing_091600.template.properties

qianyan=本文给一下监控题材的默认实现#\
\n\
\n\
主要关注以下信息: #\
trend(hist) #\
涨停板 #\
跌停板 #\
opp/pull #\
rup3/rup5/rup7数据 #\
\n\
\n\
\n\
\n\
一些命令: #\
计算更详细的行情指标: sh/xls/analyze_hangqing.sh xx #\
旧的template实现: sh/template/run_xls_template.sh xx tracing #\
\n\
\n\
\n\
\n\
\n\
相关的模板: 


eva_quan={00:00:00,23:59:59}xx->stage:zijin_sum[09:33:00,],\
xx->stage:zijin.days5[09:20:00,],\
xx->stage:realtime[09:22:00,09:45:00],\
xx->if2:rup7_alot.if[09:23:00,],\
xx->if2:rup3_alot.if[09:23:00,],\
xx->upstps[09:33:00,09:50:00],\
if xx->dstp then xx->btw:max=-7:asc=1[09:23:00,],\
xx->trend3.hist:len=3[09:28:00,09:50:00],\
xx->opp_fenbu[09:31:00,09:45:00]


############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}


############################### 开盘时区
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}

############################### 早盘时区
tips_zao={09:30:01,09:45:00}早盘时区:


############################### 早盘时区
tips_zao2={09:38:01,09:45:00}早盘时区2(38分后):

eva_zao2={09:38:01,09:48:00}xx->npull:min=1.5:mode=m7,\
if xx->npull:min=1.5:mode=m7*alot then xx->npull:min=3.3:mode=m7


############################### 准盘中时区
tips_zpan={09:48:01,10:20:00}准盘中时区(48分后):

eva_zpan={09:48:01,10:20:00}xx->npull:min=1.5:mode=m7,\
xx->npull:min=1.5:mode=qt2


