juben=xls-trend-open
title=特地给开盘时区单独做一个实现

# 特地给开盘时区单独做一个实现

replace=xls
enable_bkzj_df=0
open_index=xx
category=tracing

start=09:15:00

try_save_to_chain=1
chain_node=analyze_xls

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 4代表trend 1代表tips.properties 1代表origin-xls
# 第4位和第5位数字组合代表了计算的类型 overall=00 none/default=01 open=03
no=41103

qianyan=特地给开盘时区单独做一个实现

eva_quan={00:00:00,23:59:59}xx->trend3.hist:len=3[09:20:00,],\
xx->btw_fenbu,\
xx->upstp.hist:len=4[09:22:00,],\
if xx->upstp then xx->upstp*ban_size,\
if xls:fenshi->upstp*filter:max=15 then xls:fenshi->upstp,back=append_xls:xx,\
zhushi:市场涨停板不多的话 判断一下题材的地位,\
if xx->jj_rzq:min=2*filter:max=40 then xx->if2:eva-jj_rzq:min=2,\
zhushi:计算jj-rzq的数据,\
if xx->jj_rzq:min=2*filter:min=41 then xx->if2:eva-jj_rzq:min=2*btw:min=-1,\
zhushi:计算jj-rzq的数据,\
if xx->jj_high:min=5*filter:max=40 then xx->if2:eva-jj_high:min=5,\
zhushi:计算jj-high5的数据,\
if xx->jj_high:min=5*filter:min=41 then xx->if2:eva-jj_high:min=5*up0,\
zhushi:计算jj-high5的数据,\
xx->btw:limit=15:asc=0,\
zhushi:显示基础的limit15数据
