#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-trend-fast
title=监控xls trend的fast实现(快速监控+判断能不能买入)

replace=xls
enable_bkzj_df=0
open_index=xx
category=tracing

start=09:16:00

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 4代表trend 1代表tips.properties 1代表origin-xls
# 第4位和第5位数字组合代表了计算的类型 overall=00 none/default=01 fast=02
no=41102

qianyan=监控xls trend的fast实现(快速监控+判断能不能买入)#\
\n\
\n\
\n\
\n\
相关的模板: 


eva_quan={00:00:00,23:59:59}xx->stage:zijin_sum[09:33:00,],\
xx->stage:realtime[09:22:00,09:45:00],\
xx->if2:rup7_alot.if,\
xx->if2:rup3_alot.if,\
xx->upstps[09:33:00,09:50:00],\
xx->trend3.hist:len=3[09:28:00,09:50:00],\
xx->opp_fenbu[09:31:00,09:45:00]

############################### 盘前时区
tips_plan={09:00:00,09:15:00}盘前时区: 

eva_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}


############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}

