#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-diwei-default
title=题材在市场中的地位的默认实现(日内版本)

replace=xls
enable_bkzj_df=0
category=tracing

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 4代表trend 1代表tips.properties 1代表origin-xls
# 第4位和第5位数字组合代表了计算的类型 这里地位相关的从60开始 default=61
no=41161


qianyan=本文给一下计算题材地位的默认实现(日内版本)#\
(实际本文的计算中 主要以涨停板为核心计算指标)#\
\n\
\n\
主要关注以下信息: #\
市场涨停板不多的话 涨停板#\
超短票(db31)中的涨停板#\
大成交个股中的前排数据#\
bkzj数据#\
\n\
\n\
\n\
(其实根据市场的不同环境 题材的不同的状态 应该走不同的实现->也就是状态图 TODO:)#\
\n\
\n\
\n\
相关的模板: 


eva_quan={00:00:00,23:59:59}if exist_t2 and \
xls:fenshi->upstp*filter:min=3:max=20 then \
xls:fenshi->upstp,back=append_xls:xx[09:23:00,],\
zhushi:如果市场涨停板不多 那么判断题材是否存在于数据,\
if exist_t2 then xls:fenshi->if2:upstp,\
zhushi:实时市场涨停板数量,\
xx->if2:upstp,\
zhushi:题材的涨停板数量,\
if exist_t2 and xls:fenshi->new:mode=inner:upstp*filter:min=3:max=20 \
then xls:fenshi->new:mode=inner:upstp,back=append_xls:xx[09:31:00,09:45:00],\
zhushi:如果市场新增涨停板不多 那么判断题材是否属于数据,\
if db31->upstp*filter:min=1:max=10 then \
db31->upstp,back=append_xls:xx[09:16:00,],\
zhushi:如果db31涨停板可控 那么判断题材是否存在于数据,\
print_fenge,\
if exist_t2 then \
xls:fenshi->amount:limit=35*btw:min=2,back=append_xls:xx[09:32:00,],\
zhushi:判断市场实时前排成交个股 是否存在题材的数据



############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区: 

eva_jj={09:16:00,09:25:00}


############################### 开盘时区
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}

############################### 早盘时区
tips_zao={09:30:01,09:45:00}早盘时区:


############################### 早盘时区
tips_zao2={09:38:01,09:45:00}早盘时区2(38分后):

eva_zao2={09:38:01,09:48:00}


############################### 准盘中时区
tips_zpan={09:48:01,10:20:00}准盘中时区(48分后):

eva_zpan={09:48:01,10:20:00}
