#
#Fri Feb 14 15:36:12 CST 2025
juben=yingzuo-buyer
title=根据我强悍的jpg数量能力+监控能力来硬做买点tips

replace=xls

qianyan=关于硬做买点的具体文章见<2026-06-16 绕过图形准度不够的方案之硬做+\
为什么可行>#\
总体来说 硬做买点本质提供了“准度图形70分”+监控数量70分+跟踪监控80分的买点方案#\
\n\
总体思路: 直接把实时的图形硬做 包括前排的shake 前排的btw 前排的amount等#\
\n\
一些特征: #\
1 不同的时区走不同的实现#\
2 单个买点尽量控制在15~20之间 来最大程度的放大自己的jpg优势#\
\n\
一些相关的模板:#\
1 sh/tips/run_xls_template.sh xx none_xls


tips_plan={09:00:00,09:15:00}

############################### 竞价时区
tips_jj={09:16:00,09:25:00}从买点的角度 竞价时区是有价值的 #\
1 直接分析图形: sh/codes/fronts/find_fronts.sh xx bsd #\
2 喜欢的jj-rzq: sh/buyer/run_simple_eva.sh xx jj_rzq:min=2 info --mode open#\
sh/buyer/run_simple_eva.sh xx jj_xt:min=3 info #\
3 暴力点 直接把前排数据拉出来 反正我跟踪能力强(最直接and有效的思路了): \
sh/eva/cli.sh xx btw:min=-2*ma_dis:min=2*btw:limit=20 --mode open

eva_jj={09:16:00,09:25:00}xx->btw:limit=15:asc=0,\
if xx->jj_rzq:min=1.8*filter:min=10 then xx->jj_rzq:min=2.0[09:23:00,]

############################### 开盘时区
# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区 很多操作可以复用竞价时区#\
买点的角度: 复用竞价#\
可以看看有没有baov的数据: sh/buyer/run_simple_eva.sh xx baov info

eva_open={09:25:00,09:30:00}xx->btw:limit=15:asc=0,\
xx->amount:limit=10,\
if xx->jj_rzq:min=1.8*filter:min=10 then xx->jj_rzq:min=2.0,\
zhushi:如果jj-rzq有一定的数据量 那么进行计算,\
if xx->baov*filter:min=8 then xx->baov,\
zhushi:如果baov有一定的数据量 那么进行计算


############################### 早盘时区

tips_zao1={09:30:01,09:45:00}早盘时区 可以尝试一下命令:#\
判断一下是否大批个股冲高: sh/if/check_if.sh "xx->opp2*alot" 如果是,\
那么走一下针对opp alot的特化: #\
\n\
判断一下在up2的数据是否alot: sh/if/check_if.sh "xx==if:rup2_alot.if" \
如果是 那么走一个针对up2 alot的特化分析:  \
sh/tips/run_xls_template.sh xx rup2_alot


eva_zao1={09:30:01,09:45:00}xx->stage:btw_fenbu,\
if xx->opp2*alot then xx->up0*opp2*rank:limit=18,\
zhushi:如果opp2-alot 那么直接暴力的走rank,\
xx->if2:rup2_alot.if,\
xx->if2:rup3_alot.if



