#
#Fri Feb 14 15:36:12 CST 2025
juben=zhendang
title=震荡行情的临盘tips

qianyan=对于震荡行情来说 主力是有多种玩法的 包括早盘可能会刻意压盘 \
因此不能因为开盘那几分就下判断#\
对震荡行情来说 和safe场景不同的是 全市场级别的指标会比市场核心股票池指标来的更准\
理由是震荡行情可能会发生剧烈的切换 靠单一股票池的指标判断可能会完全错过正确答案#\
因此从这个思路上看 震荡行情会更关注市场指标 以及一些头部指标

tips_plan={09:00:00,09:15:00}

tips_jj={09:16:00,09:25:00}对震荡行情来说 竞价时区的价值也有限 \
不过可以关注一下市场的涨停板 以及通过bkzj数据看看有没有新的题材出来


# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘的时候 可以关注以下数据#\
1 市场级别的指标(上面论述过最准确): sh/template/run_template.sh \
market --day $day #\
2 直接看bkzj数据: python realtime/candi/cli.py get bkzj.top:limit=40 #\
sh/hq/zhendang/bkzj_top.sh --mode open #\
3 市场核心题材的头部amount数据: sh/flush_cli.sh config:top_amount::amount20 trend3 --day $day #\
4 直接打开前日大单的指数k线(有一定的滞后性不推荐): sh/open/open_xls_list.sh bkzj.cdadan:limit=15 --day $day


tips_zao1={09:30:01,09:45:00}早盘时区是震荡行情比较重要的 因此要重视这个时区#\
1 依旧是市场指标第一位: sh/template/run_template.sh market --day $day #\
2 bkzj的数据第二位: sh/hq/zhendang/bkzj_top.sh --day $day #\
3 20cm的头部数据: sh/codes/analyze_pool.sh 20cm*eva:btw:min=9:limit=40 #\
4 刷新一下盘前定义的切片池: sh/flush_cli.sh qpc:plan trend3



