#
#Fri Feb 14 15:36:12 CST 2025
juben=zoushi
title=市场走势的tips

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 3代表advice 1代表tips.properties 0代表none
# 第4位和第5位数字组合代表了计算的类型 huizong=00 zoushi=01
no=31001

qianyan=本文给一下对于市场走势的预测/监控/临盘纠正相关的内容#\
\n\
一些零散的规律:#\
1 如果最近2个交易日波动极大(70个点以上) 如果早盘明显较弱 那么理智的把操作时区延后,\
因为大波动是会延续的 保不齐盘中甚至能直接v红#\
2 如果指数一直处于磨底的状态 然后突然因为外围利好高开 那么有一定的几率走成切换行情,\
背后的底层逻辑是 磨底的时候有很多左侧资金就等着兑现呢 然后切换到更低位的题材 一个现实\
的例子:2026-06-12 具体去看当日的数据

tips_plan={09:00:00,09:15:00}盘前部分:#\
盘前的时候 必然会有外围消息/走势的一些前置信息(这里特指波动较大的时候 波动小就无所谓了) \
但这里还是要提醒一下:#\
1 外围消息不会对市场的原本走势产生本质的影响 比如市场的原生动力就是向上趋势 而如果\
此时外围大跌 那么这只会影响市场的开盘前15min 最终还是会走成向上#\
2 外围消息会有钝化效应 同一个利空事件 必然是第一天对a股的走势影响最大 然后逐渐脱敏 \
只不过是需要考虑周期长度的问题,有的消息会影响半个月 有的消息只会影响2 3天

tips_jj={09:16:00,09:25:00}

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}

tips_zao1={09:30:01,09:33:00}
