#
#Fri Feb 14 15:36:12 CST 2025
juben=default(默认的剧本文件)
juben_tips=

open_index=index:fast

if=get_candi:qpc:plan

flush=qpc:plan->trend3[09:18:00,],\
if get_candi:qpc:plan::aa then qpc:plan::aa->trend3[09:18:00,]

eva0=market:amounts.cross7[09:26:00,09:39:00],\
market:emotion.hist4[09:23:00,09:39:00]

hand=
