#
#Fri Feb 14 15:36:12 CST 2025
juben=test
title=这是一个测试文件

# 参考@engine/caop/buyers/generate//template/test.gene.properties

replace=xls

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# qianyan
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息
# *qps: 核心组件 用于生成切片
# *on_result: 在计算获得了切片以后 如果指定了计算的func 那么再进行一次过滤 默认可以为空

if=
on_result=

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}xx->db51,\
if xx->db31*filter:min=10 then xx*db31

eva_all={00:00:00,23:59:59}db31->up7,db21->up5,\
zhushi:测试db21+up5

tips_jj={09:16:00,09:25:00}这是竞价时区的信息
tips_jj2={09:16:00,09:25:00}竞价2
eva_jj={09:16:00,09:25:00}

tips_all={00:00:00,23:59:59}

# 想要输出换行的消息 以#进行分割
tips_open={09:25:00,09:30:00}开盘时区的消息#\
开盘的时候需要关注什么呢

eva_open={09:25:00,09:30:00}db31->upstp,\
if db51->upstp then db51->up7,\
zhushi:测试if条件语句

tips_zao1={09:30:01,09:33:00}开盘前3min

# 无效的tips 因为没有指定有效的时间戳
tips_blank={}
