#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的[日内]辨识度买点策略
juben_tips=本模板专注于日内图形的买点策略 因此不会有锚定/子切片池等数据,\
可以说 就是一个纯粹的日内图形的策略\n

replace=xls
category=buyer

enable_realtime_pool=1

eva0=xx->btwed,\
if xx->jj_xt:min=2.5*alot2 then xx*eva:jj_xt:min=3->caop:find_fronts:rup[09:22:00,09:33:00],\
if not xx==rup3_alot.if then xx->caop:find_fronts:bsd[,09:45:00],\
if not xx->jj_xt:min=2.5*alot2 then xx->caop:find_fronts:bsd2[09:20:00,09:30:00],\
if xx*filter:max=100 then xx->caop:find_fronts:rup

eva=if xx->jj_xt:min=2.5*alot2 then xx->jj_xt:min=3:limit=10[09:22:00,09:38:00],\
if xx==rup2_alot.if then xx->rup:min=2.5:limit=15,\
if xx->opp:min=2.2*alot2 then xx->opp:min=3:limit=15[09:30:30,09:45:00]
