#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片强度为zhendang时的买点策略(会严格校验切片的强度->配置if条件校验)
juben_tips=

replace=xls
category=buyer

enable_realtime_pool=1

if=not xx==is_hot.if[09:25:00,]

flush=

eva0=xx->if2:has_upstp.if,\
xx->if2:lianghua_alot.if,\
xx->btwed,\
if not xx==rup3_alot.if then xx->caop:find_fronts:bsd[,09:45:00],\
if xx*filter:max=100 then xx->caop:find_fronts:rup

eva=if not xx==rup3_alot.if then xx->btw:min=1.5:limit=15,\
if not xx==rup2_alot.if then xx->btw:min=-3*wrap:trd_sum:len=3:min=4:max=14
