#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的早盘冲高买点策略
juben_tips=因为早盘冲高图形太重要了 我不得不单独出一个模板文件\n\
具体的买点来说 包括3个 冲的最猛的+水下冲的最猛的+水上冲的最猛的\n\

replace=xls
category=buyer

start_at=09:30:30
end_at=09:48:00

enable_realtime_pool=1

eva0=xx->if2:lianghua_opp_baozha.if,\
zhushi:判断是否量化爆炸,\
xx->if2:lianghua_opp_alot.if,\
zhushi:判断是否量化alot,\
print_fenge,\
xx->caop:find_fronts:opp,\
if xx->opp:min=2.5*alot then xx*eva:opp:min=2.2->caop:find_fronts:opp_alot,\
zhushi:如果符合opp>2.5满足alot 那么先计算opp>2.2 然后计算find-fronts:opp-alot,\
if xx->btw:max=0*alot then xx*eva:btw:max=0->caop:find_fronts:opp,\
zhushi:如果符合当前btw<0的数量alot 那么先计算btw<0 然后计算find-fronts:opp,\
if xx->opp:min=2*up0*alot then xx*eva:up0->caop:find_fronts:opp,\
zhushi:如果符合opp>2+up0(水上个股)的数量alot 那么先计算btw>0 然后计算find-fronts:opp


eva=if xx->opp:min=2:alot2 then xx->opp:min=2.5:limit=15,\
zhushi:如果符合opp>2满足alot2 那么计算opp>2.5的前排eva计算结果,\ 
if xx->opp:min=2*btw:max=0*alot2 then xx->btw:max=0*opp:min=2:limit=12,\
zhushi:如果符合opp>2+btw<0(水下个股)的数量alot 那么计算btw<0+opp>2的eva计算结果,\
if xx->opp:min=2*up0*alot then xx->up0*opp:min=2:limit=12,\
zhushi:如果符合opp>2+up0(水上个股)的数量alot 那么计算up0(水上)+opp>2的eva计算结果



