#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的买点策略
juben_tips=设计文件见<2026-05-06 单刷某个股票池/切片的买点>\n\
具体的说 就是锚定+日内图形+日间子图形

replace=xls
category=buyer

enable_realtime_pool=1

flush=

eva0=if xx*is_dapiao then xx->if:has_maoding2.if,\
xx->if:lianghua_alot.if,\
xx->btwed,\
if not xx==rup3_alot.if then xx->caop:find_fronts:bsd[,09:45:00],\
if xx*filter:max=100 then xx->caop:find_fronts:rup

eva=if not xx==rup3_alot.if then xx->btw:min=1.5:limit=15
