#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的基础的good数据
juben_tips=

replace=xls
category=buyer

enable_realtime_pool=1

eva0=xx->trend3.hist[09:22:00,],\
xx->if2:has_upstp.if,\
zhushi:判断是否包含{有效}涨停板,\
xx->if2:lianghua_alot.if,\
zhushi:判断是否量化alot,\
xx->if2:rup3_alot.if,\
xx->btwed,\
print_fenge,\
xx->fronts:good,\
xx->caop:find_fronts:good

#eva=if not xx==rup3_alot.if then xx->0zhou*filter:max=20,\
#zhushi:如果强度达不到rup3-alot 那么计算0zhou的eva计算结果(限制20)


