#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片日内弱转强的买点策略
juben_tips=日内弱转强也是和opp一样基础+重要+优先级高的买点策略,\
不过暂时没有想好切片强度为hot时的买点策略。。 TODO:

replace=xls
category=buyer

enable_realtime_pool=1

if=

eva0=xx->irzq

eva=
