#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片强度为hot时的买点策略(会严格校验切片的强度->配置if条件校验)
juben_tips=暂时没有想好切片强度为hot时的买点策略。。 TODO:

replace=xls
category=buyer

enable_realtime_pool=1

# 
if=xx==is_hot.if and xx*filter:min=35[09:25:00,]
if_msg=如果是一个小的切片+hot的话 并没有多少挖掘空间 这种情况下 不如走qp-btw模板实现

eva0=xx->caop:find_fronts:bsd[,09:45:00],\
xx->caop:find_fronts:rup

eva=
