#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的基础的btw数据
juben_tips=

replace=xls
category=buyer

enable_realtime_pool=1

eva0=xx->if2:has_upstp.if,\
xx->if2:lianghua_alot.if,\
xx->btwed,\
print_fenge,\
xx->fronts:btw,\
xx->caop:find_fronts:btw

eva=if not xx==rup3_alot.if then xx->0zhou,\
if not xx==rup3_alot.if then xx->2zhou,\
if not xx==rup5_alot.if then xx->btw:min=1:limit=12
