#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的[日内]辨识度买点策略
juben_tips=本模板专注于日内图形的买点策略 因此不会有锚定/子切片池等数据,\
可以说 就是一个纯粹的日内图形的策略\n

replace=xls
category=buyer

enable_realtime_pool=1

eva0=xx->btwed,\
if xx->jj_xt:min=2.5*alot2 then xx*eva:jj_xt:min=3->caop:find_fronts:rup[09:22:00,09:33:00],\
zhushi:判定jj-xt是否alot 如果满足 那么先jj-xt3 然后find-fronts:rup,\
if not xx==rup3_alot.if then xx->caop:find_fronts:bsd[,09:45:00],\
zhushi:如果强度{不}到rup3-alit 那么计算find-fronts:bsd,\
if not xx->jj_xt:min=2.5*alot2 then xx->caop:find_fronts:bsd2[09:20:00,09:30:00],\
zhushi:如果jj-xt>2.5{不}符合alot 那么计算find-fronts:bsd2,\
if xx*filter:max=100 then xx->caop:find_fronts:rup,\
zhushi:股票池数据量<100的话 计算最基础的find-fronts:rup

eva=if xx->jj_xt:min=2.5*alot2 then xx->jj_xt:min=3:limit=10[09:22:00,09:38:00],\
zhushi:如果jj-xt>2符合alot 那么计算jj-xt>3的eva结果,\
if xx==rup2_alot.if then xx->rup:min=2.5:limit=15,\
zhushi:如果符合rup2-alot 那么计算rup>2.5的eva结果,\
if xx->opp:min=2.2*alot2 then xx->opp:min=3:limit=15[09:30:30,09:45:00],\
zhushi:如果符合opp>2-alot 那么计算opp>3的eva结果

