#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的早盘zao特化买点策略
juben_tips=

replace=xls
category=buyer

enable_realtime_pool=1

start_at=09:30:20
end_at=09:49:00

eva0=xx->trend3.hist[09:22:00,],\
xx->if2:has_upstp.if,\
zhushi:判断是否包含{有效}涨停板,\
xx->if2:lianghua_alot.if,\
zhushi:判断是否量化alot,\
print_fenge,\
xx->fronts:zao,\
xx->caop:find_fronts:zao

eva=if xx->shake:min=3*alot*btw:max=1*filter:min=20 \
then xx->shake:min=3*up0*filter:max=20,\
zhushi:如果水下的shake>3的数据很多 那么反之计算水上shake3的数据的eva结果,\
if xx==rup3_alot.if then xx->newhigh:len=8*trd:min=1.5*filter:max=20,\
zhushi:如果满足rup3-alot 那么计算8日新高的eva结果




