#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的shake-alot的买点策略
juben_tips=

replace=xls
category=buyer

start_at=09:30:10
end_at=09:52:00

enable_realtime_pool=1

eva0=xx->trend3.hist[09:22:00,],\
xx->if2:shake_alot.if,\
xx->if2:lianghua_alot.if,\
xx->if2:rup2_alot.if,\
xx->btwed,\
print_fenge,\
xx->fronts:shake_alot,\
xx->caop:find_fronts:shake_alot,\
if xx*eva:btw:max=0==shake_alot.if then xx*eva:btw:max=0->shake*co:asc=1,\
zhushi:如果实时btw<0的数据符合shake-alot 那么计算一下btw<0所有数据的co数据(判定是否大量杀跌)

#eva=if not xx==rup3_alot.if then xx->0zhou*filter:max=20,\
#zhushi:如果强度达不到rup3-alot 那么计算0zhou的eva计算结果(限制20)


