#
#Fri Feb 14 15:36:12 CST 2025
juben=xx切片的早盘加速买点策略
juben_tips=

replace=xls
category=buyer

start_at=09:20:30
end_at=09:48:00

enable_realtime_pool=1

# 做一个最基础的校验
if=xx->ma_dis:min=2*btw:min=-1*alot2

eva0=xx->if2:lianghua_opp_alot.if[09:30:30,],\
print_fenge,\
xx->caop:find_fronts:jiasu


eva=
