#
#Fri Feb 14 15:36:12 CST 2025
juben=
juben_tips=分析一下特定的市场级别的大票的题材分布情况

enable_realtime_pool=0
enable_realtime_xls=0

flush=

eva0=if db31*shizhi:min=450*filter:min=5:max=25 \
 then db31*shizhi:min=450->get_codes,back=append_xls2,\
if shizhi:min=450*pos_pchg:min=25*10cm*filter:min=5:max=30 \
 then shizhi:min=450*pos_pchg:min=25*10cm->get_codes,back=append_xls2,\
if shizhi:min=450*10cm*tx:huoyue*filter:min=35 \
 then shizhi:min=450*10cm*tx:huoyue->get_codes,back=get_pool

