#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze_bkzj(基于bkzj类型的pool 继续深度分析挖掘)

juben_tips=

# 注意这里的replace=pool
replace=pool

if=get_candi:xx

eva0=get_candi:xx,\
get_candi:xx*stage:zijin,\
get_candi:xx*find_xls,\
get_candi:xx*stage2:if_size:min=3:if_zijin_alot.days4,\
get_candi:xx*stage2:if_size:min=2:if_zijin_alot.days3,\
get_candi:xx*stage2:if_size:max=1:if_zijin_alot.days3


