#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_analyze-codes-change(分析股票池的个股change信息)
juben_tips=

category=analyze
replace=xls

if=xx*simple_code and xx_new*filter:min=10


eva0=xx->stage:size:len=4,\
zhushi:直接给出股票池的数据变化,\
if xx_new*filter:max=40 then xx_new->get_codes,back=append_xls2,\
zhushi:给出new数据的直接题材池分析,\
xx_new*amount:limit=10->get_codes,back=append_xls2,\
zhushi:给出new+前排amount数据的题材池分析

