#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_analyze-pool(分析个股的版块池信息)
juben_tips=

category=tracing
replace=xls
sort=2

enable_realtime_xls=0

if=xx*filter:max=300

# 判断是否一家独大
eva0=if xx*filter:max=40*yijiaduda,\
if xx*filter:max=40 then xx->get_codes,back=append_xls2,\
if xx*filter:min=41 then xx*amount:limit=20->get_codes,back=append_xls2,\
if xx*filter:min=41 then xx*duoban:len=3:min=1:limit=30->get_codes,back=append_xls2,\
if xx*filter:min=41 then xx*trd:min=8:limit=20->get_codes,back=append_xls2,\
if xx*filter:min=41 then xx*shizhi:limit=20->get_codes,back=append_xls2

