#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_analyze_by_shape(从图形的角度分析股票池)
juben_tips=

category=analyze
replace=builded

enable_realtime_xls=0

# xx->get_codes,back=info,\
eva0=xx->stage:shape_fenbu:test_duan_xt,\
xx*newlow:len=7*trd:max=5->get_codes,\
xx->stage:pos_sum:len=18,\
xx->stage:pos_sum.days4,\
xx->stage:trends_sum:len=8,\
zhushi:给出股票池的8日trd-sum 能够看出来头部尾部数据的强度,\
xx->stage:trends_sum:len=3.days4,\
if xx*simple_code then xx->trend3.days6

