#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze_shape(分析题材中的切片分布)
juben_tips=从图形的角度 高辨识度票trd,3日trd-sum,pos-pchg等都是最基础的图形

replace=xls

#if xx*10cm*pos_pchg:min=15*alot,\
eva0=xx->zijin.days5,\
xx->trend3.days5,\
print_fenge,\
if xx*tx:huoyue*filter:min=40 then xx*tx:huoyue->stage:size:len=4,\
if xx*10cm*trd:min=2*baozha then xx*10cm*trd:min=7->get_codes,\
xx->if:10cm*trd:min=3*baozha,\
if xx*20cm*trd:min=7*alot2 then xx*20cm*trd:min=13->get_codes,\
xx->if:trd:max=-3*baozha,\
if xx*db21*filter:min=8 then xx*duoban:len=2:limit=10->get_codes,\
xx->if:db31*filter:min=15,\
xx->if:db81*filter:min=40,\
xx->if:db102*filter:min=15,\
xx->if:10cm*trd_sum:len=3:min=7*alot,\
xx->if:10cm*pos_pchg:min=15*alot,\
xx->if:10cm*pos_pchg:min=23*alot2,\
xx->if:amount:min=20*alot,\
if xx*amount:min=20*alot then xx*amount:min=20:limit=15->get_codes
