#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze_dadan(默认版块池为大单版块池的基础上 做对应的分析)
juben_tips=

# 注意这里的replace=pool
replace=pool
enable_bkzj_df=0

if=get_candi:xx

flush=xx->if:db21*filter:min=13,\
xx->if:trd:max=-3.3*baozha,\
xx->if:trd:min=4.5*baozha,\
xx->if:duo_trd:min=5:min_num=2:len=3*alot,\
xx->if:pos_pchg:len=7:min=22*alot2,\
xx->if_size:min=2:if_zijin_alot.days4

eva0=get_candi:xx*find_bk*append_xls,\
get_candi:xx*find_xls


