#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_analyze-pool(分析个股的版块池信息)
juben_tips=

category=tracing
replace=xls
sort=2

enable_realtime_xls=0

if=xx*filter:max=300

try_save_to_chain=1
chain_node=analyze_codes

# no的赋值规则见@engine/enum/no_rule_enum.py 
# analyze的赋值规则见@engine/enum/analyze_enum.py 
# 9代表analyze 2代表juben.properties 5代表qp
# 第4位和第5位数字组合代表了计算的类型
# no的说明 analyze-pool(plan版本实现)=062
no=925062

# 判断是否一家独大
eva0=if xx*filter:max=40*yijiaduda,\
if xx*filter:max=40 then xx->get_codes,back=append_xls2,\
zhushi:如果数据量比较小的话 那么直接进行append-xls计算,\
if xx*filter:min=20 then xx*amount:limit=10->get_codes,back=append_xls2,\
zhushi:截取前10成交量的个股 再进行append-xls计算,\
if xx*filter:min=41 then xx*amount:limit=20->get_codes,back=append_xls2,\
zhushi:对前20成交额的数据进行分析,\
if xx*filter:min=41 and xx*db31*filter:min=10 \
then xx*duoban:len=3:min=1:limit=30->get_codes,back=append_xls2,\
zhushi:如果db31的数据量满足大于10 那么进行分析,\
if xx*filter:min=41 and xx*trd:min=6*filter:min=10 \
then xx*trd:min=6:limit=20->get_codes,back=append_xls2,\
zhushi:如果trd>6的数据满足大于10 那么进行分析

flush=if xx*filter:min=41 then redu::xx->size:len=1
