#
#Fri Feb 14 15:36:12 CST 2025
juben=xx-amount-alot-xls
juben_tips=某个题材的成交额大的离谱时的处理方案

replace=origin_xls
category=analyze

if=xx*amount20*alot

eva0=if xx*amount50*alot,\
zhushi:判断是否amount50满足alot,\
if xx*amount30*alot,\
zhushi:判断是否amount30满足alot,\
if xx*amount30*baozha,\
zhushi:判断是否amount30满足baozha,\
xx*amount:limit=15->get_codes,\
zhushi:给出题材中前15大成交的股票池数据,\
xx*amount30*pc:yuanli_two123->stage:size:len=4,\
xx*amount30*pc:pos_high34->stage:size:len=4,\
xx->amount:limit=15*btw,\
zhushi:查看前日收盘时的前15成交额个股的数据,\
print_fenge,\
amount:limit=40->get_codes,back=append_xls:xx,\
zhushi:查看全市场成交额前40的个股中的对应占比数据


