#
#Fri Feb 14 15:36:12 CST 2025
juben=
juben_tips=寻找题材中的有效子股票池切片

replace=xls
sort=4

flush=if xx*tx:qushi2*filter:min=40 then xx;;qushi2->size:len=1,\
if xx*db31*filter:min=15 or xx*db51*filter:min=20 then xx;;db31->size:len=1

eva0=if xx*pure_xls then xx->zhuxians2:len=4
