#
#Fri Feb 14 15:36:12 CST 2025
juben=
juben_tips=寻找题材中的有效子股票池切片

replace=xls
sort=4

enable_realtime_pool=0
enable_realtime_xls=0

flush=if xx*tx:qushi2*filter:min=40 then xx;;qushi2->size:len=1,\
if xx*db31*filter:min=15 or xx*db51*filter:min=20 then xx;;db31->size:len=1

# if xx*pure_xls then xx->zhuxians2:len=4
eva0=if xx*tx:huoyue*filter:min=35 then xx*tx:huoyue->stage:size:len=4,\
if xx*db31*filter:min=15 then xx*db31->stage:size:len=4,\
if xx*pos_pchg:min=30*filter:min=10 then xx*pos_pchg:min=30->stage:size:len=4,\
if xx*shizhi:min=450*pos_pchg:min=15*filter:min=5 \
 then xx*shizhi:min=450*pos_pchg:min=15->stage:size:len=4,\
if xx*yz:zhusheng*filter:min=4 then xx*yz:zhusheng->stage:size:len=3,\
print_fenge,\
if xx*pure_xls then xx->stage:trend3.cross4 
