#
#Fri Feb 14 15:36:12 CST 2025
juben=
juben_tips=判定题材是否是量化深度介入的题材
replace=origin_xls
sort=4

open_index=

# 给出前日的db31的晋级数据
eva=xx->stage:if_zijin_alot2.days,\
xx->stage:realtime.days,\
xx->stage:tidui.days3,\
xx*db31->get_codes,\
xx*max_pchg:len=3:min=5->get_codes,\
xx*max_pchg:len=4:min=7->get_codes
