#
#Fri Feb 14 15:36:12 CST 2025
juben=pool_shuxing
juben_tips=计算输入的版块池的属性信息\n\
注意: 本剧本会进行replace操作,并且要求输入的是pool类型,会进行校验\
\n\

# 注意这里的replace=pool
replace=pool

open_index=xx

# xx::xls:shouban->size:len=3,\
flush=xx->if:cross_days_zijin_dafu_liuru,\
zhushi:判断是否资金在今日之前多次大幅流入(4天2次)(不过滤),\
xx->stage:zijin:mode=cross,\
zhushi:直接给出题材池的前日收盘bkzj数据,\
xx->stage:if:db31*alot,\
zhushi:判断超短票是否alot(不过滤)

eva0=