#
#Fri Feb 14 15:36:12 CST 2025
juben=pool_bkzj
juben_tips=计算输入的版块池的日间bkzj信息\n\

# 注意这里的replace=pool
replace=pool
enable_bkzj_df=0

open_index=xx

flush=xx->stage:if_zijin_alot2,\
xx->stage:if_size:if_zijin_alot1.days2,\
xx->stage:if_size:if_zijin_alot1.days4,\
xx->stage:zijin.days4

eva0=if get_candi:xx*is_bk then get_candi:xx,\
zhushi:直接获取最原始的数据,\
get_candi:xx*stage:zijin,\
zhushi:获取题材+bkzj的数据,\
get_candi:xx*stage2:if2:cross_days_zijin_dafu_liuru

