#
#Fri Feb 14 15:36:12 CST 2025
juben=pool-zhuli-maoding(分析题材中的主力子股票池的图形分布)
juben_tips=

replace=pool
code_category=

flush=xx->if:zhuli_codes_alot.if,\
xx::xls:zhuli->trend3

#if xx*10cm*pos_pchg:min=15*alot,\
eva0=
