#
#Fri Feb 14 15:36:12 CST 2025
juben=pool_duori-zijin-analyze
juben_tips=计算输入的版块池的多日主力资金表现属性信息\n\
注意: 本剧本会进行replace操作,并且要求输入的是pool类型,会进行校验\
\n\

# 注意这里的replace=pool
replace=pool

open_index=xx

# xx::xls:shouban->size:len=3,\
#flush=xx->stage:zijin:mode=cross,\
#zhushi:直接给出题材池的前日收盘bkzj数据,\
#xx->stage:if_zijin_hot:mode=cross,\
#zhushi:判断是否资金hot

eva0=get_candi:xx*stage2:if_zijin_hot:mode=cross,\
zhushi:给出最基础的前日收盘时hot的数据,\
get_candi:xx*stage2:if_size:max=1:if_zijin_hot2.days3*\
stage2:if_zijin_hot:mode=cross,\
zhushi:最近3个交易日只有1天资金大幅流入且刚好是昨天(新走强的题材 注意延续性),\
get_candi:xx*stage2:if2:cross_days_zijin_dafu_liuru*\
stage2:if_zijin_hot:mode=cross,\
zhushi:4天2日资金持续流入+前一天依旧在流入,\
print_fenge,\
get_candi:xx*stage2:if2:cross_days_zijin_dafu_liuru*\
stage2:not:if_zijin_hot:mode=cross,\
zhushi:4天2日资金持续流入+前一天没有流入了(可能要转空了),\
get_candi:xx*stage2:if2:cross_days_zijin_dafu_liuru,\
zhushi:标准的4天2日主力资金大幅流入,\
get_candi:xx*stage2:if2:cross_days_zijin_dafu_liuru:len=4:min=3,\
zhushi:要求比较高的4天3次主力资金大幅流入,\
print_fenge,\
get_candi:xx*stage2:zijin:mode=cross:min_idx=0.5,\
zhushi:给出基础的前日收盘idx>0.5的数据


