#
#Fri Feb 14 15:36:12 CST 2025
juben=
juben_tips=定位:给出热门题材在近几个交易日的核心数据

replace=origin_xls
enable_bkzj_df=0

open_index=xx

if=xx*tx:huoyue*filter:min=30

# 思考: 要不要上一些切片的数据?

eva0=xx->stage:zijin.days6,\
xx->stage:trend3.days4,\
if xx*tx:huoyue*filter:min=40 then xx*tx:huoyue->stage:size:len=4,\
xx*CODES_BAN->stage:redu:len=4,\
xx*trd:min=6.5->stage:redu:len=4,\
xx*shizhi:min=450*trd:min=3.5->stage:redu:len=4,\
xx->stage:fenbu2,\
xx->stage:zhuxians2:len=4,\
xx*db31->stage:jinji,\
if xx*CODES_BAN*filter:min=2 then xx*db31->jinji

