#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-good-shape(给出good的图形分布数据)
juben_tips=

replace=xls

if=xx*filter:min=1

flush=if xx*filter:min=25 then xx;;good->size:len=1,\
if xx*filter:min=25 then xx;;good2->size:len=1,\
print_fenge,\
if xx*amount20*alot*filter:min=40 then xx*amount20;;good2->size:len=1,\
if xx*10cm*pos_pchg:min=22*alot*filter:min=30 then xx*10cm*pos_pchg:min=22;;good2->size:len=1

# 股性 活跃 大成交 高位 超短 还有其他图形吗?
eva0=xx->trend3.days4,\
xx->size:len=4,\
print_fenge,\
if xx*amount20 and xx*amount20*alot,\
if xx*10cm*pos_pchg:min=22 and xx*10cm*pos_pchg:min=22*alot2,\
if xx*db41*filter:min=20 or xx*db21*filter:min=8



