#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-amount-shape
juben_tips=

replace=xls

if=xx*filter:min=10

flush=xx;;amount->size:len=1,\
if xx*trd:min=6*alot then xx*trd:min=6;;amount->size:len=1,\
if xx*trd:max=-4*alot then xx*trd:max=-4;;amount->size:len=1,\
if xx*not:break_ma:ma=3*alot then xx*not:break_ma:ma=3;;amount->size:len=1

eva0=



