#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-breakma-shape(给出break-ma的图形分布数据)
juben_tips=

replace=xls

if=xx*filter:min=20

flush=xx;;break_ma->size:len=1,\
if xx*pos_pchg:min=22*alot*filter:min=30 \
then xx*pos_pchg:min=22;;break_ma->size:len=1,\
if xx*xt2*alot*filter:min=30 \
then xx*xt2;;break_ma->size:len=1

# 股性 活跃 大成交 高位 超短 还有其他图形吗?
eva0=



