#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-fast-shape(在未知题材状态的时候 快速进行图形计算)
juben_tips=

replace=xls

# 在一个fast模板中 计算下面的数据实在过于耗cpu
#flush=if xx*db41*filter:min=20 or xx*db21*filter:min=8 then xx;;db31->size:len=1,\
#if xx*amount20*alot or xx*amount50*filter:min=12 then xx*amount20;;good->size:len=1,\
#if xx*10cm*tx:huoyue*alot2 then xx*10cm*tx:huoyue;;good->size:len=1,\
#if xx*10cm*tx:guxing2*alot2 then xx*10cm*tx:guxing2;;good->size:len=1,\
#if xx*10cm*db102*alot2 then xx*10cm*db102;;good->size:len=1,\
#if xx*10cm*pos_pchg:min=22*alot2 then xx*10cm*pos_pchg:min=22;;good->size:len=1

#flush=xx;;good->size:len=1,\
#xx;;good2->size:len=1

# 股性 活跃 大成交 高位 超短 还有其他图形吗?
eva0=xx*10cm->trend3.days4,\
xx*20cm->trend3.days4,\
if xx*pure_xls or xx*is_bk then xx->zijin.days4,\
zhushi:如果是原始类型或者bk类型 那么获取一下资金数据,\
print_fenge,\
if xx*tx:bsd and xx*tx:bsd*alot*filter:min=40 then xx*tx:bsd->stage:size:len=3,\
zhushi:如果tx:bsd的数据够多(>40) 那么计算一下tx:bsd的个股数量变化值,\
if xx*10cm*tx:guxing*filter:min=10 then xx*10cm*tx:guxing->stage:size:len=3,\
zhushi:如果tx:guxing的数据够多 那么计算一下tx:guxing的个股数量变化值,\
if xx*10cm*tx:guxing2 and xx*10cm*tx:guxing2*alot2 then xx*10cm*tx:guxing2->stage:size:len=3,\
zhushi:如果tx:guxing2的数据够多 那么计算一下tx:guxing2的个股数量变化值,\
if xx*10cm*tx:huoyue and xx*10cm*tx:huoyue*alot2 then xx*10cm*tx:huoyue->stage:size:len=3,\
zhushi:如果tx:huoyue的数据够多 那么计算一下tx:huoyue的个股数量变化值,\
if xx*amount20 and xx*amount20*alot then xx*amount20->stage:size:len=3,\
zhushi:如果amount20的数据够多 那么计算一下amount20的个股数量变化值,\
if xx*10cm*pos_pchg:min=22 and xx*10cm*pos_pchg:min=22*alot2 \
then xx*10cm*pos_pchg:min=22->stage:size:len=3,\
zhushi:如果pos-pchg>22的数据够多 那么计算一下pos-pchg>22的个股数量变化值,\
if xx*db41*filter:min=20 or xx*db21*filter:min=8,\
zhushi:判断是否满足db41数量>40 或者db21数量>8



