#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-xiangshang-shape(给出最近3个交易日向上的图形分布数据)
juben_tips=

replace=xls

if=xx*filter:min=1

flush=xx*ma_dis:min=2;;xiangshang->size:len=1,\
print_fenge,\
if xx*ma_dis:min=5*alot*filter:min=10 \
then xx*ma_dis:min=5;;xiangshang->size:len=1,\
if xx*upma*ma_dis:min=3*alot*filter:min=10 \
then xx*upma*ma_dis:min=3;;xiangshang->size:len=1

# 股性 活跃 大成交 高位 超短 还有其他图形吗?
eva0=



