#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-zhuli-shape(分析题材中的主力子股票池的图形分布)
juben_tips=

replace=xls
code_category=zhuli

#if xx*10cm*pos_pchg:min=15*alot,\
eva0=xx->stage:size:len=4,\
xx->trend3.days4,\
print_fenge,\
if xx*tx:bsd*alot then xx*tx:bsd->stage:size:len=3,\
if xx*10cm*tx:huoyue*filter:min=10 then xx*10cm*tx:huoyue->stage:size:len=3,\
if xx*pos_pchg:min=15*alot2 then xx*pos_pchg:min=15->stage:size:len=3,\
if xx*pos_pchg:len=10:min=7*baozha then xx*pos_pchg:len=10:min=7->stage:size:len=3,\
if xx*amount20*alot or xx*amount50*filter:min=15,\
if xx*db51*filter:min=3 then xx*db51->stage:size:len=3
