#
#Fri Feb 14 15:36:12 CST 2025
juben=sub-fast-shape(在未知题材状态的时候 快速进行图形计算)
juben_tips=

replace=xls

# 在一个fast模板中 计算下面的数据实在过于耗cpu
#flush=if xx*db41*filter:min=20 or xx*db21*filter:min=8 then xx;;db31->size:len=1,\
#if xx*amount20*alot or xx*amount50*filter:min=12 then xx*amount20;;good->size:len=1,\
#if xx*10cm*tx:huoyue*alot2 then xx*10cm*tx:huoyue;;good->size:len=1,\
#if xx*10cm*tx:guxing2*alot2 then xx*10cm*tx:guxing2;;good->size:len=1,\
#if xx*10cm*db102*alot2 then xx*10cm*db102;;good->size:len=1,\
#if xx*10cm*pos_pchg:min=22*alot2 then xx*10cm*pos_pchg:min=22;;good->size:len=1


# 股性 活跃 大成交 高位 超短 还有其他图形吗?
eva0=xx*10cm->trend3.days4,\
xx*20cm->trend3.days4,\
xx->zijin.days4,\
print_fenge,\
if xx*10cm*tx:guxing*filter:min=10 then xx*10cm*tx:guxing->stage:size:len=3,\
if xx*10cm*tx:guxing2 and xx*10cm*tx:guxing2*alot2 then xx*10cm*tx:guxing2->stage:size:len=3,\
if xx*10cm*tx:huoyue and xx*10cm*tx:huoyue*alot2 then xx*10cm*tx:huoyue->stage:size:len=3,\
if xx*amount20 and xx*amount20*alot then xx*amount20->stage:size:len=3,\
if xx*10cm*pos_pchg:min=22 and xx*10cm*pos_pchg:min=22*alot2 \
then xx*10cm*pos_pchg:min=22->stage:size:len=3,\
if xx*db41*filter:min=20 or xx*db21*filter:min=8



