#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_test-trends-good(分析股票池的trends-good子股票池分布数据)
juben_tips=

category=analyze
replace=xls

enable_realtime_xls=0

# xx->get_codes,back=info,\
eva0=xx->stage:shape_fenbu:test_trends_good,\
xx*tx:trends_good->get_codes,\
if xx->is_code then xx*trd_sum:len=4->get_codes

