#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_test-duan-xt(分析股票池的duan-xt子股票池分布数据)
juben_tips=

category=analyze
replace=xls

enable_realtime_xls=0

# xx->get_codes,back=info,\
eva0=xx->stage:shape_fenbu:test_duan_xt,\
if xx*simple_code then xx*duan_xt3->size:len=4,\
xx*suo_xt:max=0.8->get_codes


