#
#Fri Feb 14 15:36:12 CST 2025
juben=XX_test-dis(分析股票池的dis子股票池分布数据)
juben_tips=

category=analyze
replace=xls

enable_realtime_xls=0

# xx->get_codes,back=info,\
# xx->stage:shape_fenbu:test_dis:ma=10
eva0=xx->stage:shape_fenbu:test_dis


