#
#Fri Feb 14 15:36:12 CST 2025
juben=analyze-market-pull
title=本chain用于分析市场的整体pull的数据

need_xls=0
need_pool=0
enable_bkzj_df=0

start_at=09:43:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题(这里是@engine/enum/chain/market_node.py ) 这里就是19
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是10
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 analyze-market-pull=07 
no=191007

qianyan=本chain用于分析市场的整体pull的数据 用于后续给出买点方案 #\
主要是观察: #\
1 市场指数有没有明显的大幅拉升 涨跌家数是否明显变大 #\
2 题材有没有明显大幅拉升的机会(bkzj ggzj) #\
3 核心的股票池 市值100 市值200 zhz1000 zhz2000有没有明显的拉升 #\
\n\
\n\
对应的tip(但拆分的不如本chain细致): sh/tips/run_template.sh analyze_market_pull

start=本chain用于分析市场的整体pull的数据

chain_all={00:00:00,23:59:59}analyze_hq:juben:market_index_pull;\
zhushi:市场的指数拉升数据;\
analyze_hq:exist_pool_pull;\
zhushi:不走bkzj和ggzj分析市场上是否存在明显的版块机会;\
if exist_bkzj then analyze_hq:analyze_market_pull_by_bkzj;\
zhushi:bkzj视角分析版块池的波动

# 最后还缺一个ggzj的视角?        TODO:

end=

eva_all={00:00:00,23:59:59}market:emotion.hist4

