#
#Fri Feb 14 15:36:12 CST 2025
juben=fast-dig-pool
title=快速定位出当前实时/收盘可选的版块池

# 快速定位出当前实时/收盘可选的版块池

need_xls=0
need_pool=0
enable_bkzj_df=0

start_at=09:15:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是90
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是10
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 fast-dig=02
no=901002

qianyan=本chain用于快速定位出当前实时/收盘可选的版块池 #\
\n\
主要思路包括: #\
涨停板 #\
BK1633: sh/hand/run_template.sh tracing_BK1633 --time_str $time_str #\
iggzj: sh/hand/run_template.sh tracing_iggzj --time_str $time_str  #\
bkzj #\
\n\
直接打开: sh/open/open_xls_list.sh candi:BKZJ_ZHULI_2#\
sh/open/open_xls_list.sh bkzj.cdadan:limit=15#\
sh/open/open_xls_list.sh index:hp#\
\n\
\n\
更多

start=本chain用于快速定位出当前实时/收盘可选的版块池

chain_all={00:00:00,23:59:59}analyze_hq:upstp_to_pool;\
zhushi:通过涨停板来定位版块池

# 当前的chain node还远远不够            TODO:FIXME:

end=

eva_all={00:00:00,23:59:59}if exist_bkzj then get_candi:bkzj.zhuli:limit=15[09:30:01,]



