#
#Fri Feb 14 15:36:12 CST 2025
juben=handle-market-bad
title=本chain用于处理市场肉眼可见的差的行情

need_xls=0
need_pool=0
enable_bkzj_df=0

start_at=09:15:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题(这里是@engine/enum/chain/market_node.py ) 这里就是24
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是10
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 handle-bad=03
no=221003

qianyan=本chain用于处理市场肉眼可见的差的行情 #\
\n\
哪些情况能视作是市场很差呢? #\
黄白线同时无力 或者黄线大跌+白线0轴 #\
各种细节指标 比如iggzj BK1633都出现数据相比过去的数据的下滑甚至暴力走弱 #\
超短出现跌停板 #\
\n\
\n\
思考: 本chain需要给出应对策略 具体说买点方案吗? #\
(其实这个问题的回答 取决于对这个下跌的分类&理解 是下跌中继 还是大概率是下跌尾端 甚至日内就能v) #\
\n\
\n\
手工打开: sh/open/open_xls_list.sh candi:BKZJ_ZHULI_2#\
sh/open/open_xls_list.sh bkzj.cdadan:limit=15#\
sh/open/open_xls_list.sh index:hp#\
sh/bkzj/top.sh #\
\n\
一些手工指标: #\
直接手工计算下跌5%的数据: \
python realtime/stage/cli.py get xls:fenshi eva_size:eva_type=btw:max=-3.hist #\
python realtime/stage/cli.py get xls:fenshi eva_size:eva_type=btw:max=-3.cross #\
\n\


start=本chain用于处理市场肉眼可见的差的行情

# 注意: 当前受限于权重和时间精力 当前先尝试给出一个最基础的实现 
# 因此可能需要后续补充(基本确定要)  TODO:

# 可以指定多个chain 但在遍历的过程中 只要某一个计算成功 那么就直接结束 
# 也就是可以有多个chain 但最多只有1个结果
# 以;作为分隔符
chain_all={00:00:00,23:59:59}analyze_hq:juben:market_info[09:15:00,];\
zhushi:最基础的市场数据;\
if exist_ggzj then analyze_hq:analyze_risk_by_iggzj[09:30:01,],\
zhushi:如果存在ggzj数据 那么从ggzj的视角来分析

# 还缺BK1633和超短的视角        TODO:

# 是不是应该添加更多的node?

end=最后产出的是bkzj为主的数据 如果想要继续深究题材数据 可以:\
sh/bkzj/analyze_bkzj.sh list:aa,bb 

eva_all={00:00:00,23:59:59}market:emotion.hist4[09:23:00,],\
bkzj.top[09:30:01,]

