#
#Fri Feb 14 15:36:12 CST 2025
juben=hq-hot-dlb3-buyer
title=市场整体强势行情下 生成dlb3的策略(会配置if条件)

need_xls=0
need_pool=0

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# start_at
# end_at
# qianyan
# start: 开始节点
# chain: 实际的链路算子
# end: 输出一些end信息
# jcal:
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息

# 还缺行情的if条件 	TODO:
if=dlb3->upstp or dlb3->up5*filter:min=5

start_at=09:22:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是61
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是11
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 dlb3-buyer=03
no=611103

qianyan=强势的市场下(比如黄线行情 比如强震荡行情都命中) dlb3有可能(50%的比例)会出买点 #\
本chain给出一个实现

start=强势的市场下(比如黄线行情 比如强震荡行情都命中) dlb3有可能(50%的比例)会出买点 \
本chain比较简单 仅2个node

# 可以指定多个chain 但在遍历的过程中 只要某一个计算成功 那么就直接结束 
# 也就是可以有多个chain 但最多只有1个结果
# 以;作为分隔符
chain_all={00:00:00,23:59:59}analyze_hq:analyze_market_trend;\
zhushi:走一个analyze-market-trend算子 但仅作为数据记录 不参与条件判断;\
gene_qp:by_xls:dlb2->basic_eva;\
zhushi:简单的通过basic-eva进行切片生成策略

end=

eva_all={00:00:00,23:59:59}dlb3->trend3.hist[09:28:00,],\
zhushi:给出题材的基础走势数据,\
dlb3->trend3.days

