#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=市场确定性不足(比如大涨后一天需要分化)时的超短+ggzj提供确定性的买点

need_xls=0
need_pool=0
can_duplicate_regist=1
enable_bkzj_df=0

if=exist_ggzj[09:30:01,]

start_at=09:20:01

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是60
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是11
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 ggzj-chaoduan-buyer=05
no=601107

qianyan=市场确定性不足(比如大涨后一天需要分化)时 \
通过加强图形的辨识度(这里就是超短)+ggzj API提供确定性来解决确定性不足的问题

start=市场确定性不足(比如大涨后一天需要分化)时 \
通过加强图形的辨识度(这里就是超短)+ggzj API提供确定性来解决确定性不足的问题

# 可以指定多个chain 但在遍历的过程中 只要某一个计算成功 那么就直接结束 
# 也就是可以有多个chain 但最多只有1个结果
# 以;作为分隔符
# 设置next=read的时候 无论如何都只进行读取
chain_all={00:00:00,23:59:59}if exist_bkzj then \
analyze_hq:analyze_market_by_ZHULI_POOL[09:25:00,];\
zhushi:因为是混沌行情 所以会把最重要的zhuli-pool数据作为最重要的市场数据;\
gene_qp:by_xls:db81*no30200*10cm->sure_less_eva;\
zhushi:简单的通过sure-less-eva进行切片生成策略;\
if db152*10cm*filter:max=250 then \
gene_qp:by_xls:db152*10cm->sure_less_eva;\
zhushi:简单的通过sure-less-eva进行切片生成策略

end=

eva_all={00:00:00,23:59:59}db81*no30200*10cm->btwed.hist[09:28:00,],\
db152*no40100*10cm->btwed.hist[09:28:00,],\
market:emotion.hist4[09:23:00,]

