#
#Fri Feb 14 15:36:12 CST 2025
juben=test
title=这是一个测试文件

need_xls=1
need_pool=0

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# start_at
# end_at
# qianyan
# start: 开始节点
# chain: 实际的链路算子
# end: 输出一些end信息
# jcal:
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息

if=

# 这里做一下限制 因为analyze-xls-by-ggzj2是有时间限制的
start_at=09:31:00

qianyan=第一个测试链路算子 内容来自<2026-08-12 今天实战的chain案例>

start=本链路是一个测试链路,从指定的xls->analyze_xls开始,以生成redu-no切片终止

# 可以指定多个chain 但在遍历的过程中 只要某一个计算成功 那么就直接结束 
# 也就是可以有多个chain 但最多只有1个结果
# 以;作为分隔符
chain_all={00:00:00,23:59:59}analyze_hq:analyze_market_by_ggzj;\
zhushi:走一个analyze-hq算子 但仅作为数据记录 不参与条件判断;\
analyze_xls:tips:xx->analyze-xls-by-ggzj2;\
zhushi:走一下题材+ggzj分析;\
analyze_xls:tips:xx->analyze_xls_rup_alot;\
zhushi:走一下题材+rup分析;\
gene_qp:by_xls:xx->redu_no;\
zhushi:最后一步 生成redu-no的切片

chain_2={09:30:00,10:00:00}analyze_hq:analyze_market_by_ggzj;\
zhushi:最简单的只有1个node的chain 仅测试用

end=本链路以生成切片为最后一步 但很明显后续可以继续添加node(比如通过手工 sh/eva/cli.sh xx --chain abc)


eva_all={00:00:00,23:59:59}xx->trend3.hist[09:28:00,],\
zhushi:给出题材的基础走势数据

