#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=分析指定股票池的attack 包括和日间的对比数据/trend数据 和日内的实时指标

need_xls=1
need_pool=0
replace=xls
enable_realtime_df=0

can_duplicate_regist=1

# 最基础的数量限制
if=xx*filter:min=5

start=09:16:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是50
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是34
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 analyze-attack=15
no=503415

qianyan=分析指定股票池的attack数据 #\
\n\
主要分析的数据包括: #\
日内走势 #\
题材在市场中的地位(如果是origin) #\
attack指标 #\
\n\
\n\
相关的chain: 

start=分析指定股票池的attack数据

chain_all={09:15:00,23:59:59}analyze_xls:xx->xls_trend_fast;\
zhushi:计算基础的日内走势数据;\
if xx*has_origin then analyze_xls:xx*first->xls_diwei_default;\
zhushi:计算地位数据;\
analyze_codes:xx->analyze_attack;\
zhushi:计算进攻数据


end=

eva_all=
