#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=对大数据量的股票池做详细分析 包括图形属性 版块池 实时eva等

need_xls=1
need_pool=0
replace=xls
enable_realtime_df=0

can_duplicate_regist=1

# 最基础的数量限制
if=xx*filter:min=20

# 分析某个abc*xyz的实时股票池
# 包括 计算gene_qp:xx->spec_codes(图形属性分析) xx->split-pool(版块池分析) xx->realtime-eva/pan-eva(实时eva分析)

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是50
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是34
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 analyze-big-codes=12
no=503412

# 经过测试 本chain的表现勉强可以接受了

qianyan=对大数据量的股票池做详细分析(实际常常是abc*eva:xyz的实时股票池) #\
\n\
常见场景: 开盘黄线大幅拉升时的大量opp数据 #\
\n\
\n\
具体的计算包括: #\
图形属性: gene_qp:xx->spec_codes #\
版块分布: xx->split-pool #\
实时eva: xx->realtime_eva/pan_eva #\
\n\
\n\
\n\
本chain分别实现了日间和日内: #\
日间: sh/chain/gene/run_xls_template.sh xx fast_analyze_xls --mode plan #\
日内: sh/chain/gene/run_xls_template.sh xx fast_analyze_xls --mode now #\
\n\
\n\
更多?


start=对大数据量的股票池做详细分析

chain_plan={00:00:00,09:00:00}gene_qp:by_xls:xx->spec_codes;\
zhushi:属性分析;\
if not xx*has_origin then gene_qp:by_xls:xx->split_pool;\
zhushi:版块池分析;\
if xx*has_eva then gene_qp:by_xls:xx->realtime_eva;\
zhushi:实时eva分析

chain_all={09:15:00,23:59:59}gene_qp:by_xls:xx->spec_codes;\
zhushi:属性分析;\
if not xx*has_origin then gene_qp:by_xls:xx->split_pool;\
zhushi:版块池分析;\
gene_qp:by_xls:xx->realtime_eva;\
zhushi:实时eva分析;\
gene_qp:by_xls:xx->pan_eva[09:44:00,];\
zhushi:pan eva分析

end=

eva_all={00:00:00,23:59:59}xx->size:len=4[,14:59:59],\
xx->btw_fenbu.hist[09:22:00,],\
xx->trend3.hist[09:22:00,]

