#
#Fri Feb 14 15:36:12 CST 2025
juben=buyer-alot
title=指定的股票池的买点数量太多时的chain算子

need_xls=1
need_pool=0
replace=xls

# 至少要包含地位+rup alot算子

# 数量太大的话 我处理不了
if=xx*filter:max=150

start_at=09:16:00

can_duplicate_regist=1

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题(见@engine/enum/chain/handle_xls_enum.py  ) 这里就是71
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是41
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 buyer_alot=03
no=714103

qianyan=指定的股票池当前的买点数量爆炸的应对策略 #\
具体来说 包括: #\
确定题材在市场中的地位 #\
确定题材本身的rup-alot数据 #\
生成切片的策略

start=指定的股票池当前的买点数量爆炸的对应chain

chain_all={00:00:00,23:59:59}analyze_xls:tips:xx*first->xls_diwei_default;\
zhushi:计算题材的地位数据;\
if xx*pure_xls then analyze_xls:tips:xx->analyze_xls_rup_alot;\
zhushi:计算题材的rup数据;\
gene_qp:by_xls:xx->basic_eva;\
zhushi:简单的通过basic-eva进行切片生成策略

end=

eva_all={00:00:00,23:59:59}xx->btw:limit=20:asc=0,\
zhushi:给一下最基础的前排数据

