#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=通过组合算子来判定题材处于hot状态

need_xls=1
need_pool=0
replace=xls

if=

start_at=09:16:00

can_duplicate_regist=1

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是40
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是34
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 check-hot=02
no=403403

qianyan=通过组合算子来判定题材处于hot状态 #\
\n\
实际就是调用多个tips文件来共同验证 包括: #\
trend #\
diwei地位 #\
\n\

# ggzj API?		TODO:

#gene_qp:by_xls:xx*first->basic_chaoduan;\
#zhushi:计算一下basic-chaoduan切片

start=通过组合算子来判定题材处于hot状态的对应chain

chain_all={00:00:00,23:59:59}analyze_xls:tips:xx->xls_trend_fast;\
zhushi:计算题材的基础trend;\
analyze_xls:tips:xx*first->xls_diwei_default;\
zhushi:计算题材的地位数据;\
gene_qp:next=read:by_xls:xx->redu_no;\
zhushi:计算一下redu-no切片 且设置next标志位=read


end=

eva_all={00:00:00,23:59:59}xx->btw:limit=20:asc=0,\
zhushi:给一下最基础的前排数据,\
if exist_ggzj then xx->ggzj:limit=40[09:30:01,],\
zhushi:如果存在ggzj 看一下对应的数据

