#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=通过组合算子来对题材进行分析

need_xls=1
need_pool=0
replace=xls
enable_realtime_df=0

can_duplicate_regist=1

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是40
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是34
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 check-hot=02 fast-known=11 fast-analyze=12
no=403412

qianyan=通过组合算子来对题材进行分析 #\
\n\
对题材来说 我应该如何分析? #\
资金 #\
走势 #\
获利盘 #\
辨识度 #\
地位 #\
对实盘来说 还有进攻性 确定性 #\
最后一个是买点 #\
\n\
\n\
本chain分别实现了日间和日内: #\
日间: sh/chain/gene/run_xls_template.sh xx fast_analyze_xls --mode plan #\
日内: sh/chain/gene/run_xls_template.sh xx fast_analyze_xls --mode now #\
\n\
\n\
其实我还有很多分析工具: sh/tips/find_template.sh ana|grep xls

# 参考@engine/observe/chain//template/xx_fast_known_xls.chain.properties

start=通过组合算子来对题材进行分析

# 当前实现2个分支 日间+日内

# 日间分别会执行5次计算: 资金 走势 获利盘 辨识度票 地位
chain_plan={00:00:00,09:00:00}analyze_xls:next=read:xx->analyze_xls_cross_zijin;\
zhushi:计算题材资金;\
analyze_xls:next=read:xx->analyze_xls_cross_fast_trend;\
zhushi:计算题材走势;\
gene_qp:by_xls:xx->huoli_detail;\
zhushi:题材的获利盘数据;\
gene_qp:by_xls:xx->bianshidu_detail;\
zhushi:题材的辨识度数据;\
analyze_xls:next=read:xx->xls_cross_diwei;\
zhushi:分析题材的日间地位

# 下面是日内的分析
# 因为9点30分前的特殊性(比如缺少bkzj ggzj数据) 因此这里也走不同的分支实现

# =====================================================


# 9点30分 主要计算 走势+核心个股走势 实时前排 实时强度 进攻数据 在市场中的地位 + 日间地位(反正next=read) 
chain_open={09:15:00,09:30:00}analyze_xls:xx->xls_trend_open;\
zhushi:计算题材走势;\
gene_qp:by_xls:xx->open_attack_eva;\
zhushi:计算题材的进攻数据

# 开盘数据还差一个地位分析 TODO:


# =====================================================

# 30分后的实现
# 主要计算 走势 实时的进攻性 在市场中的地位 实时的波动(9点44分之后)
chain_all={09:30:01,23:59:59}analyze_xls:xx->xls_trend_fast;\
zhushi:计算题材走势;\
if exist_ggzj then analyze_xls:xx->analyze_xls_by_ggzj2;\
zhushi:ggzj指标来分析题材;\
gene_qp:by_xls:xx->realtime_eva;\
zhushi:计算题材的实时eva指标;\
gene_qp:by_xls:xx->pan_eva[09:44:00,];\
zhushi:计算题材的实时pan波动指标

# 30分后的实现 还缺地位分析 也还缺BK1633指标分析  TODO:

end=

eva_all={00:00:00,23:59:59}xx->trend3.days4

