#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=通过组合算子来版块池进行分析

need_xls=1
replace=pool
enable_realtime_df=0

can_duplicate_regist=1

start=09:15:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是41
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是34
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 fast-analyze=12
no=413412

qianyan=通过组合算子来对版块池进行分析 #\
\n\
对版块池来说 我应该如何分析? #\
实时走势第一位的 因为这个数据最准 #\
gg资金 #\
bkzj #\
\n\
\n\
本chain当前暂时只实现日内:        TODO:FIXME: #\
\n\
\n\

# 参考@engine/observe/chain//template/xx_fast_known_xls.chain.properties

start=通过组合算子来对题材池进行分析

# 当前实现2个分支 日间+日内

# 日间分别会执行5次计算: 资金 走势 获利盘 辨识度票 地位
chain_plan={00:00:00,09:00:00}

chain_all={09:15:00,23:59:59}analyze_xls:xx->analyze_pool_trend;\
zhushi:计算题材走势;\
if exist_ggzj then analyze_xls:xx->analyze_pool_by_ggzj;\
zhushi:ggzj指标来分析题材;\
if exist_bkzj then analyze_xls:xx->analyze_pool_by_bkzj;\
zhushi:ggzj指标来分析题材

# 30分后的实现 还缺地位分析 也还缺BK1633指标分析  TODO:

end=

eva_all={00:00:00,23:59:59}
