#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=通过组合算子来快速知道题材的一些基础信息

need_xls=1
need_pool=0
replace=xls

if=xx*is_bk or xx*pure_xls
if_err_msg=输入的不是原始类型或者bk类型

can_duplicate_regist=0

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是40
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是34
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 check-hot=02 fast-known=11
no=403411

qianyan=通过组合算子来快速知道题材的一些基础信息 #\
\n\
这里的快速信息就包括 #\
基础的trend信息 #\
基础的ggzj API的数据信息 #\
不自动计算图形信息 但可以手工: \
sh/tips/run_xls_template.sh xx analyze_cross_xls_by_shape#\
\n\

# ggzj API?		TODO:

#gene_qp:by_xls:xx*first->basic_chaoduan;\
#zhushi:计算一下basic-chaoduan切片

start=通过组合算子来快速知道题材的一些基础信息

chain_all={00:00:00,23:59:59}analyze_xls:next=read:xx->analyze_xls_cross_fast_trend;\
zhushi:计算题材的基础trend;\
if exist_ggzj then analyze_xls:next=read:xx->analyze_cross_xls_by_ggzj2;\
zhushi:计算题材的ggzj数据;\
if xx*is_bk then analyze_xls:next=read:xx->analyze_xls_cross_zijin;\
zhushi:计算bkzj的细节数据 比如是否属于大单级别的题材池


end=

eva_all={00:00:00,23:59:59}xx->trend3.days4

