#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=提供一个fast buyer实现(实际就是根据实盘数据来判断要不要走某个gene算子) 

# 	
# TODO:


need_xls=1
need_pool=0
replace=xls
enable_realtime_df=0

can_duplicate_regist=1

start=09:16:00

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题 这里就是30
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是33
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 fast-buyer=04
no=303304

qianyan=提供一个fast buyer实现(日内)(纯图形 假设对题材或股票池未知信息) #\
\n\
\n\
一些注意点: #\
追高的时候 想想下一日的市场行情是否允许你把利润带走(毕竟a股是t+1)(在a股永远别上头)!!!!! #\
\n\
\n\
相关工具: #\
注意点: sh/tips/run_template.sh buyer_tips

# 缺 如果outxt数据很大 走2次挖掘逻辑 TODO:
# 当前我在保守性的买点的优化上 还有极大空间 TODO:

chain_all={00:00:00,23:59:59}gene_qp:by_xls:xx->realtime_eva;\
zhushi:计算题材的实时eva指标;\
gene_qp:by_xls:xx->pan_eva[09:44:00,];\
zhushi:计算题材的实时pan波动指标


end=

eva_all={00:00:00,23:59:59}