#
#Fri Feb 14 15:36:12 CST 2025
juben=make-plan-builded-codes
title=对于builded的股票池进行make plan操作的chain算子

need_xls=1
need_pool=0
replace=builded

# 对数据量做一个基础限制
if=xx*filter:max=300

start_at=

can_duplicate_regist=1

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题(见@engine/enum/chain/handle_xls_enum.py) 这里就是52
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是41
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 buyer_alot=03 make_plan=07 make_plan_builded=08
no=524108

qianyan=在未知股票池信息的背景下 对于builded的股票池进行make plan操作的chain算子 #\
具体包括: #\
pool分析 #\
超短分布分析 #\
辨识度图形分析 #\
\n\
\n\
\n\
相关的模板: #\
列举预定义的股票池: sh/tips/run_template.sh codes_list#\
\n\
\n\
配置切片的信息: sh/codes/qp/add_qp.sh --rank --sort xx

start=在未知股票池信息的背景下 对于builded的股票池进行make plan操作的chain算子

# 盘前和实盘走不同的实现
chain_all={00:00:00,09:00:00}if not xx*pool_codes and not xx*xls_codes then \
analyze_codes:next=read:juben:xx->analyze_pool;\
zhushi:做基础的pool分析;\
if xx*db101*filter:min=22 then gene_qp:next=read:by_xls:xx->basic_chaoduan;\
zhushi:做基础的超短切割

# 还缺非盘前时区的实现 	TODO:
chain_all2={09:00:01,23:59:59}

eva_all={00:00:00,23:59:59}xx*10cm*no30100->get_codes,\
zhushi:基础的图形计算,\
xx*10cm*no30200->get_codes,\
zhushi:基础的图形计算,\
xx*10cm*no40100->get_codes,\
zhushi:基础的图形计算,\
if exist_ggzj then xx*xls:ggzj->get_codes[,09:00:00]

