#
#Fri Feb 14 15:36:12 CST 2025
juben=make-plan-core-codes
title=对于具有一定重要程度/权重的股票池进行make plan操作的chain算子

# 对于具有一定重要程度/权重的股票池进行make plan操作 TODO:

need_xls=1
need_pool=0
replace=xls

# 至少要包含地位+rup alot算子

# 注意这里对权重做了限制
if=rank>=3
if_err_msg=没有通过rank>=3条件 可以:sh/chain/gene/run_xls_template.sh xx \
make_plan_core_codes --rank 4

# 对数据量做一个基础限制
if2=xx*filter:max=300

start_at=

can_duplicate_regist=1

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题(见@engine/enum/chain/handle_xls_enum.py) 这里就是72
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是41
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 buyer_alot=03 make_plan=07
no=724107

start=对于具有一定重要程度/权重的股票池进行make plan操作的chain算子 这里不对权重做条件判定

chain_all={00:00:00,23:59:59}analyze_xls:tips:xx->analyze_cross_xls_by_shape[,09:00:00];\
zhushi:盘前时区做一下基础的图形分析;\
analyze_xls:tips:xx->xls_trend_fast[09:16:00,],\
zhushi:简单跟踪一下实盘数据;\
analyze_xls:tips:next=read:xx*first->xls_diwei_default[09:30:00,],\
zhushi:计算且仅计算一次地位数据;\
gene_qp:by_xls:xx->basic_eva;\
zhushi:简单的通过basic-eva进行切片生成策略(因为本身股票池已经有权重了 因此直接最基础的eva生成就行);\
gene_qp:by_xls:xx->sure_eva;\
zhushi:通过sure eva进行切片生成 这个图形的比重会更高一点


eva_all={00:00:00,23:59:59}xx->btw:limit=20:asc=0[09:15:00,],\
zhushi:给一下最基础的前排数据

