#
#Fri Feb 14 15:36:12 CST 2025
juben=xls-buyer-default
title=默认的买点chain 也是@xx_xls_buyer_silu.tips.properties 对应的chain

need_xls=1
need_pool=0
replace=xls

# 较宽的限制
if=xx*filter:max=500

start_at=09:16:00

can_duplicate_regist=1

# no的赋值规则见@engine/enum/chain/no_rule_enum.py  
# 第1位数字代表这个chain的主题 第2位数字代表次主题(见@engine/enum/chain/handle_xls_enum.py  ) 这里就是71
# 第3位数字表示开始的节点 第4位数字表示结束的节点 这里就是41
# 第5位和第6 7位数字组合代表了计算的类型
# no的说明 default-xls-buyer=02 buyer_alot=03
no=714102

qianyan=默认的买点chain #\
具体来说 会从以下点进行切入: #\
1 资金角度 也就是基于ggzj API来做买点 当然这个数据也不一定很准 #\
2 日内准度图形 #\
3 日间图形来提供准度 #\
4 如果是builded 那么还有builded+pool的角度 #\
\n\
回头查看对应的tips: sh/tips/run_xls_template.sh xx xls_buyer_silu

start=默认的买点chain 注意:实际计算的时候是过滤掉20cm的

chain_all={00:00:00,23:59:59}if exist_ggzj and xx->ggzj2*filter:min=5 then \
gene_qp:by_xls:xx->ggzj_eva[09:30:01,];\
zhushi:基础的根据ggzj eva进行的买点策略;\
gene_qp:by_xls:xx*10cm->basic_eva;\
zhushi:简单的通过basic-eva进行切片生成策略;\
if xx->rup2*up0*alot*filter:min=35 then \
gene_qp:by_xls:xx*10cm->sure_eva;\
zhushi:具备一定强度的时候 计算sure-eva进行切片生成策略

# 更多的策略 		TODO:

end=

eva_all={00:00:00,23:59:59}xx->upstp*ban_size,\
xx->btw:limit=20:asc=0,\
zhushi:给一下最基础的前排数据,\
xx*10cm->if2:rup2_alot.if,\
xx*10cm->if2:rup3_alot.if,\
xx*10cm->if2:rup5_alot.if


