#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=默认的模版文件

if=

qianyan=

# 最核心的周期调度命令在这里
eva=

# 动态测试多个eva写这里
eva2=

# 想要动态测试单个eva写这里
eva3=

# 包含时间戳的eva写这里
eva_zao={09:30:01,09:45:00}
eva_pan={09:45:00,15:00:00}

# manual-codes是一个买点文件中仅次于eva的命令
manual_codes=
manual_codes3=

# ============================================= 下面仅显示不计算
# 用于手工记录一些历史命令 
eva_history=

# 用于手工记录一些历史计算结果文件
files=

hand=这是一条手写的信息
