#
#Fri Feb 14 15:36:12 CST 2025
juben=test
title=这是一个测试文件

qianyan=测试一下前言

functions=codes_shape

before_func=init_codes_no_if($day)

if=db31*filter:min=10

tips_all={00:00:00,23:59:59}测试一下tips

single_codes=600371,000572

# eva命令是一个买点文件中最核心的命令
eva=db31->upstp
# 注意:eva3在刷新全模板的时候 只会显示不会实际计算
eva3=shizhi100->upstp

# 为了更丰富的计算/强大的买点能力 同样支持时间戳限制(tips格式)
eva_zao={09:30:01,09:45:00}db31->opp:min=5
eva_pan={09:45:00,15:00:00}db31->btw:max=-7

# 不下载数据的版本
eva0_zao={09:30:01,09:45:00}db32->upstp

# manual-codes是一个买点文件中仅次于eva的命令
manual_codes=
manual_codes3=

jcals_all={00:00:00,23:59:59}

# 用于手工记录一些历史命令 
eva_history=shizhi300->up3,dlb2->shake:min=5

# 用于手工记录一些历史计算结果文件
files=

hand=这是一条手写的信息
