#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=提供一个监控市场的默认模版文件

if=

open_index=fushi50,1gjd,zhz1000,zhz2000,wpg

enable_bkzj_df=1
start_at=09:18:00

qianyan=对市场的监控 本质就以下几个点: #\
判断市场风险 #\
判断市场热点/逻辑(如果存在的话) #\
判断市场风格(?) #\
\n\
\n\
\n\
判断市场热点有以下的方式(排名不分先后 按照不同的行情选择): #\
涨停板: sh/tips/run_template.sh analyze_market_by_upstp #\
超短: #\
ggzj/bkzj: sh/tips/run_template.sh analyze_market_by_ggzj2 #\
某个股票池的视角 比如BK1633: sh/tips/run_template.sh silu_BK1633

# 还可以继续往上加自己想关注的东西      TODO:

# 最核心的周期调度命令在这里
eva=

# 动态测试多个eva写这里
eva2=

# 想要动态测试单个eva写这里
eva3=

# 包含时间戳的eva写这里
eva0_jj={09:21:00,09:45:00}market:emotion.hist4,\
xls:fenshi->upstp.hist,\
if xls:fenshi->upstp*filter:max=22 then \
list:db62,db31->up7*ban_size,back=append_xls2,\
zhushi:如果实时涨停板不多 那么计算一下超短的前排分布数据,\
if exist_ggzj then xls:fenshi->ggzj:min_zhuli=0.5:limit=20,back=append_xls2[09:30:01,],\
if exist_bkzj then get_candi:bkzj.zhuli:limit=20[09:35:00,]

eva_pan={09:45:00,15:00:00}

# manual-codes是一个买点文件中仅次于eva的命令
manual_codes=
manual_codes3=

# ============================================= 下面仅显示不计算
# 用于手工记录一些历史命令 
eva_history=

# 用于手工记录一些历史计算结果文件
files=

hand=
