#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出跟踪实时iggzj 的hand模版默认实现

# 实时的iggzj太重要了 实现一下对应的tracing 

enable_bkzj_df=0

if=exist_ggzj
if_err_msg=当前不存在ggzj 也许应该:  \
open https://data.eastmoney.com/zjlx/detail.html

start=09:30:01

qianyan=给出跟踪实时iggzj 的hand模版默认实现 #\
本身实时的iggzj太重要了 因此给出一个默认实现  #\
\n\
\n\
[iggzj的重要性] #\
用做锚定版块/市场逻辑: 这个没什么说的 ggzj的确定性是更高的 #\
用于判定市场的风险 让我能够选择适用激进策略 还是保守策略 #\
\n\
\n\
相关的工具: #\
判断市场风险: sh/tips/run_template.sh analyze_risk_by_iggzj --time_str $time_str #\
分析市场: sh/tips/run_template.sh analyze_market_by_ggzj2 --time_str $time_str #\
sh/tips/run_xls_template.sh xls:iggzj silu_xls_iggzj #\
\n\
分析题材: sh/tips/run_xls_template.sh xx analyze_xls_by_ggzj2 #\
\n\
对应的gene qp: \
sh/codes/qp/gene/by_xls.sh xls:iggzj:limit=60 sub_iggzj --time_str $time_str #\
\n\
\n\
[一些偏好]: #\
市值300有偏好: sh/eva/cli.sh shizhi300*10cm ggzj2:min_zhuli=0 --time_str $time_str #\
\n\

tips_zao={09:30:01,09:50:00}实时打开叠加主力数据: sh/eva/cli.sh \
xls:iggzj:limit=40*stocks:zhuli ggzj2 --time_str $time_str --back append_xls2#\
叠加超短数据: sh/eva/cli.sh xls:iggzj:limit=40*stocks:chaoduan ggzj2 \
--time_str $time_str --back append_xls2

eva0_zao={09:30:01,09:45:00}xls:fenshi->if2:eva-ggzj2,\
zhushi:获取一下数量,\
xls:fenshi->if2:eva-ggzj2:min_zhuli=0.3,\
zhushi:获取实时主力>0.3的数量,\
xls:fenshi->ggzj2:limit=40,back=append_shape:stocks:zhuli,\
zhushi:判断是否存在主力级别的股票池 数据好的话 可以继续计算xls:iggzj:limit=40*stocks:zhuli,\
xls:fenshi->ggzj2:limit=40,back=append_shape:stocks:chaoduan,\
print:~~~~~~~~~~~~~~~~~~~~~~开始做版块锚定,\
xls:ggzj:limit=150->ggzj2:min_zhuli=0,back=append_xls2,\
zhushi:前日前排主力+实时又是主力 那么此时可以用做锚定,\
xls:fenshi->ggzj2:min_zhuli=0.3:limit=20,back=append_xls2,\
zhushi:全市场的前排数据 用做锚定


eva0_zao2={09:30:01,09:50:00}print:对比过往交易日来判定强度,\
xls:fenshi*eva.atzao2:ggzj:min_zhuli=\
0.3->eva_size:eva_type=rup.atzao2:min=2.5.days8[09:35:00,09:40:00],\
zhushi:根据min_zhuli=0.3和rup3数据来判断市场强度,\
xls:fenshi*eva.atzao:ggzj:min_zhuli=0.5->eva_size:\
eva_type=rup.atzao:min=2.5.days8[09:41:00,09:45:00],\
zhushi:根据min_zhuli=0.5和rup3数据来判断市场强度

# ============================================= 上面是模板生成 下面手工配置开始

# 允许再手工配置一下前言(前言2)
qianyan2=

# 手工监控的个股
single_codes=

# 最核心的周期调度命令在这里
eva=

# 动态测试多个eva写这里
eva2=

# 想要动态测试单个eva写这里
eva3=

# manual-codes是一个买点文件中仅次于eva的命令
manual_codes=
manual_codes3=

# ============================================= 下面仅显示不计算
# 用于手工记录一些历史命令 
eva_history=

# 用于手工记录一些历史计算结果文件
files=

hand=
