#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出一个未知股票池(盘前没有过多的分析)的默认实现


replace=xls
enable_bkzj_df=0
if=

qianyan=本文给出一个未知股票池(盘前没有过多的分析)的默认实现 #\
\n\
\n\
对股票池做版块池分析: #\
盘前: sh/codes/qp/gene/by_xls.sh xx split_pool #\
实盘: sh/codes/qp/gene/by_xls.sh xx*eva:rup2 split_pool #\
找到版块池后继续分析: sh/tips/run_xls_template.sh abc analyze_pool_cross_zijin #\
\n\
\n\
[日间]#\
显然图形分析是最重要的: sh/codes/qp/gene/by_xls.sh xx redu_detail #\
(可以在这个分析的结果上 进行2次选择) #\
资金分析: sh/tips/run_xls_template.sh xx analyze_xls_cross_zijin #\
\n\
\n\
[日内]#\
在市场中的地位: sh/tips/run_xls_template.sh xx xls_diwei_default #\
实时锚定: sh/template/run_xls_template.sh xx xls_maoding #\
直接根据up2数据进行计算: sh/codes/qp/gene/by_xls.sh xx up2_eva --action download #\
(up2的数据的多少 也能看出来版块的实际强度 可以在这个基础上 选择其它的应对方案) #\
sh/codes/qp/gene/by_xls.sh xx co2_eva --action download #\
计算进攻attack数据: sh/codes/qp/gene/by_xls.sh xx attack_eva --action download #\
\n\
根据ggzj数据进行判断: sh/tips/run_xls_template.sh xx analyze_xls_by_ggzj2 #\
\n\
\n\
跑一下对应的plan(比较有效): sh/tips/run_xls_template.sh xx make_plan_unknown_codes #\
\n\
\n\
\n\

# 更多的命令?
eva0_jj={09:20:00,09:30:00}xx->trend3.hist,\
xx->btw_fenbu.hist,\
xx->jj_rzq:min=2,xx->jj_high:min=4,xx->up2,\
xx*first->upstp*ban_size


tips_zao={09:30:01,09:45:00}早盘时区: #\
attack指标: sh/eva/cli.sh xx tx:attack --time_str $time_str --open 1 #\
计算up2: sh/codes/qp/gene/by_xls.sh xx up2_eva --time_str $time_str --action download #\
计算co2: sh/codes/qp/gene/by_xls.sh xx co2_eva --time_str $time_str --action download #\
计算attack: sh/codes/qp/gene/by_xls.sh xx attack_eva --time_str $time_str --action download #\
\n\
可以计算一下日间对比数据: python realtime/stage/cli.py get xx trend3.cross --mode zao1 #\
python realtime/stage/cli.py get xx eva_size:eva_type=tx:attack.cross --mode zao1 #\
\n\
\n\


eva0_zao={09:30:01,09:45:00}xx->trend3.hist,\
xx->btw_fenbu.hist,\
xx->opp_fenbu,\
if xx->upstp*filter:min=4 then xx->upstp*ban_size,\
if xx->upstp*filter:max=3 then xx->btw:limit=15:asc=0*co,\
if exist_bkzj then xx->stage:zijin,\
if exist_ggzj and xx->ggzj2*filter:max=20 then xx->ggzj2,\
if exist_ggzj and xx->ggzj2*filter:min=21 then xx->ggzj2*btwed

eva_pan={09:45:00,15:00:00}

tips_pan={09:45:00,15:00:00}盘中时区: #\
计算higher: sh/codes/qp/gene/by_xls.sh xx higher_eva --time_str $time_str --action download #\
计算ishake: sh/codes/qp/gene/by_xls.sh xx ishake_eva --time_str $time_str --action download #\
计算pull: sh/codes/qp/gene/by_xls.sh xx pull_eva --time_str $time_str --action download #\
计算co2: sh/codes/qp/gene/by_xls.sh xx co2_eva --time_str $time_str --action download #\

# ============================================= 上面是模板生成 下面手工配置开始

# 手工监控的个股
single_codes=

# 实盘中最重要的动态命令在这里
eva3=
manual_codes3=

# 最核心的周期调度命令在这里
eva=

# 动态测试多个eva写这里
eva2=

# manual-codes是一个买点文件中仅次于eva的命令
manual_codes=

# ============================================= 下面仅显示不计算
# 用于手工记录一些历史命令 
eva_history=

# 用于手工记录一些历史计算结果文件
files=

hand=
