#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出一个未知股票池(盘前没有过多的分析)的默认实现


replace=xls
if=

qianyan=本文给出一个未知股票池(盘前没有过多的分析)的默认实现 #\
\n\
\n\
对股票池做版块池分析: #\
盘前: sh/codes/qp/gene/by_xls.sh xx split_pool #\
实盘: sh/codes/qp/gene/by_xls.sh xx*eva:rup2 split_pool #\
\n\
\n\
跑一下对应的plan: sh/tips/run_xls_template.sh xx make_plan_unknown_codes

# 更多的命令?
eva0_jj={09:20:00,09:30:00}xx->trend3.hist,\
xx->jj_rzq:min=2,xx->jj_high:min=4,xx->up2

eva_zao={09:30:01,09:45:00}
eva_pan={09:45:00,15:00:00}

# 最核心的周期调度命令在这里
eva=

# 动态测试多个eva写这里
eva2=

# 想要动态测试单个eva写这里
eva3=

# manual-codes是一个买点文件中仅次于eva的命令
manual_codes=
manual_codes3=

# ============================================= 下面仅显示不计算
# 用于手工记录一些历史命令 
eva_history=

# 用于手工记录一些历史计算结果文件
files=

hand=
