#
#Fri Feb 14 15:36:12 CST 2025
juben=random
title=random(随机/硬做)测试

replace=xx


qianyan=本生成策略是硬做策略 一般用作保底策略 #\
虽然是保底策略 但还是会根据切片的实时特征来进行不同的计算#\
\n\
\n\
\n\
你可以选择打开对应的tips文件: sh/tips/run_xls_template.sh xx none_xls

# 兜底的策略
eva_all={00:00:00,23:59:59}xx->ma_dis:min=2*btw:min=-3*rank[09:15:00,]

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区:

eva_jj={09:16:00,09:25:00}

############################### 开盘时区
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}if xx==rup2_alot.if then xx->up0*rank,\
zhushi:如果数据很强 那么直接走rank,\
if not xx==rup2_alot.if then xx->btw:min=-1,\
if not xx==rup2_alot.if then xx*amount:limit=30->ma_dis:min=2

############################### 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区

eva_zao1={09:30:01,09:45:00}
