#
#Fri Feb 14 15:36:12 CST 2025
juben=rank-top
title=切片的rank属于top时的买点策略

category=generate
replace=xx

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 5代表gene.properties 9代表gene-buyers 这里前3位数字基本是固定的
# 第4位和第5位数字组合代表了计算的类型 rank-top=01 
no=75901

# 条件语句 rank-top 那么至少>=6
if=rank>=6
if2=xx*filter:max=50

qianyan=因为rank=top也就是股票池的权重极高 因此这里会尽可能的放松切片的限制#\
其实如果有切片的波动数据就更好了

# 兜底的策略
eva_all={00:00:00,23:59:59}xx->btw:min=-3*rank[09:15:00,]

############################### 竞价时区
tips_jj={09:16:00,09:25:00}竞价时区:

eva_jj={09:16:00,09:25:00}xx->jj_xt:min=2*filter:min=8

eva0_jj={09:16:00,09:25:00}xx->btw:max=-4:asc=1

############################### 开盘时区
tips_open={09:25:00,09:30:00}开盘时区:

eva_open={09:25:00,09:30:00}xx->jj_xt:min=2*filter:min=8,\
if xx==rup2_alot.if then xx->up0*rank,\
zhushi:如果数据很强 那么直接走rank,\
if not xx==rup2_alot.if then xx->btw:min=-1,\
if not xx==rup2_alot.if then xx*amount:limit=30->ma_dis:min=2

eva0_open={09:25:00,09:30:00}xx->btw:max=-4:asc=1,\
zhushi:做一下简单的风控

############################### 早盘时区
tips_zao1={09:30:01,09:45:00}早盘时区:

eva_zao1={09:30:01,09:45:00}xx->shake:min=2.2*filter:min=8:max=20[09:31:00,]

eva0_zao1={09:30:01,09:45:00}xx->btw:max=-4:asc=1*co*btw:asc=1,\
zhushi:做一下简单的风控

