#
#Fri Feb 14 15:36:12 CST 2025
juben=small
title=small股票池的默认实现

replace=xx

# no的赋值规则见@engine/enum/no_rule_enum.py 
# 7代表gene 5代表gene.properties 9代表gene-buyers 这里前3位数字基本是固定的
# 第4位和第5位数字组合代表了计算的类型 rank-top=01 small=02
no=75902

# 条件语句
if=risk>=2
if2=risk==-1

qianyan=这是small切片的默认实现 此时risk配置为>=2

eva_all={09:15:00,23:59:59}xx->btw
