#
#Fri Feb 14 15:36:12 CST 2025
juben=small+risk-low
title=small股票池+risk low的组合策略

replace=xx

# 条件语句
if=risk<=1
if2=not xx->dstp*filter:min=1[09:15:00,]

qianyan=这是风控最低的策略 因此这里限制切片不能出现跌停板

eva_all={09:15:00,23:59:59}if xx->rup2*filter:min=10 then xx->btw,\
if xx->rup2*filter:max=5 then xx->btw:limit=0
