#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=计算出实时的最强/进攻性最强的数据 也可以用做判断题材的进攻性

replace=xls

start=09:15:00

if=

on_result=

qianyan=计算出实时的最强/进攻性最强的数据 #\
也可以用做判断题材的进攻性(用于对比不同的版块池强度) #\
也可以用于判断某只个股在整个题材中的竞争位置 #\
也可以用做根据这些数据来说策略激进还是保守的选择 #\
\n\
正常来说 attack的数量超过18 那么进攻性就非常强了 此时考虑加强日间图形的比重 #\
(此时也可以考虑attack的溢出效应 即其它股票池也有机会) #\
\n\
\n\
对应的eva: @eva/tuxing/attacks_1.py

# 是不是应该做成对应的tips.properties文件?          TODO:

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:00}if xx->tx:attack*filter:max=18 then \
xx->tx:attack*filter:max=18,\
zhushi:attack的基础数据,\
if xx->tx:attack*filter:min=40 then break,\
zhushi:attack数据超出了正常范围的巨大 终止计算,\
if xx->tx:attack*filter:max=4 then break,\
zhushi:attack数据太小了 不需要继续计算,\
if xx->trd:min=4.6*filter:max=25 then xx->trd:min=4.6[,09:33:00],\
zhushi:trd>4.6,\
if xx->trd:min=6.3*filter:max=25 then xx->trd:min=6.3[09:33:00,],\
zhushi:实时trd>6.3,\
if xx->trd:min=3*ma_dis:min=9*filter:max=25 then \
xx->trd:min=3*ma_dis:min=9,\
zhushi:实时trd>3+ma-dis>9,\
if xx->trd:min=-2*max_pchg:len=4:min=23*filter:max=25 then \
xx->trd:min=-2*max_pchg:len=4:min=23,\
zhushi:实时max-pchg>23的 这个数据的进攻性是最强的 会包含一部分20cm数据,\
if xx*10cm->trd:min=0*max_pchg:len=4:min=15*filter:max=25 then \
xx*10cm->trd:min=0*max_pchg:len=4:min=15,\
zhushi:实时max-pchg>15的 10cm的数据 这个数据可以认为是决定性的,\
xx*10cm->trd:min=3*trd_sum:len=4:min=16:only_up0=1*filter:max=25 then \
xx*10cm->trd:min=3*trd_sum:len=4:min=16:only_up0=1,\
zhushi:trd-sum超标的

# 进攻性没那么强的数据
qps_all2={00:00:00,23:59:00}if xx*trd:max=3->trd_minus:min=4.5*filter:max=25 then \
xx*trd:max=3->trd_minus:min=4.5[,09:36:00],\
zhushi:趋势翻转>4.5的,\
if xx*trd:max=3->trd_minus:min=6.3*filter:max=25 then \
xx*trd:max=3->trd_minus:min=6.3[09:36:01,],\
zhushi:趋势翻转>6.3的,\
if xx->trd:min=2*newhigh:len=10*filter:max=25 then \
xx->trd:min=2*newhigh:len=10,\
zhushi:股价10日新高,\
if xx->rearch_btw:len=4*filter:max=25 then \
xx->rearch_btw:len=4,\
zhushi:btw股价4日新高


eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->if2:eva-tx:attack,\
xx->if2:eva-trd:min=4.6,\
xx->if2:eva-trd:min=2*max_pchg:len=4:min=15,\
xx->if2:eva-trd:min=2*trd_sum:len=4:min=16,\
xx->if2:eva-trd:min=2*newhigh:len=10,\
zhushi:最基础的数量,\
xx->btw_fenbu,\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识