#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=最基础的基于超短的图形

replace=xls

time_str=09:00:00

if=xx*db32*filter:max=20 and xx*db51*filter:max=100
if_err_msg=超短票不要过于夸张 比如db32>20 db51>100
on_result=

qianyan=给出最基础的基于超短的图形 比如db51_1,db102,db31等

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx*db32*filter:min=1 then xx*db32,\
xx*db31_1,\
xx*db51_1.bf3,\
zhushi:3日前的db51,\
if xx*db102*filter:max=50 then xx*db102,\
if xx*db102*filter:min=50 then xx*dlb2

eva_all={00:00:00,23:59:59}if not xx*is_bk and xx*simple_code \
then xx*CODES_BAN->size:len=6,\
if xx*has_eva and not xx*is_bk then xx*remove_eva*db31->stage:size:len=4,\
if xx*has_eva and not xx*is_bk then xx*remove_eva*db51_1.bf3->stage:size:len=4,\
if not xx*is_bk and xx*simple_code then xx->trend3.days6,\
zhushi:对数据有一个基本的认识


