#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=具备相当辨识度的箱体(比如箱体放大 箱体缩小 箱体持续了很久的波动)

# 当前的图形选择较差 最好不使用

replace=xls

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# qianyan
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息
# *qps: 核心组件 用于生成切片
# *on_result: 在计算获得了切片以后 如果指定了计算的func 那么再进行一次过滤 默认可以为空

time_str=09:00:00

functions=codes_shape
before_func=init_codes_no_if($day)
if=codes_no_recorder_inited
if2=xx*duanxt32_and*filter:max=70
if2_err_msg=duanxt32_and的数据量超标了 说明输入的xls本身极具辨识度 那么不适用本模板

on_result=

qianyan=本模板给出相对有辨识度(但不具备极致的辨识度)的xt图形

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx*suo_xt:max=0.6*filter:min=5:max=50 \
then xx*suo_xt:max=0.6,\
if xx*duanxt32_and*filter:min=5:max=50 then xx*duanxt32_and,\
zhushi:具备长期波动的箱体,\
if xx*duan_xt:min=8*no70701*filter:min=5:max=50 then xx*duan_xt:min=8*no70701,\
zhushi:2阴2阳

eva_all={00:00:00,23:59:59}if not xx*is_bk then xx*duanxt32_and->size:len=2,\
if not xx*is_bk then xx->trend3.days,\
zhushi:对数据有一个基本的认识


