#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=最基础的根据实时图形做切片生成

replace=xls

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# qianyan
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息
# *qps: 核心组件 用于生成切片
# *on_result: 在计算获得了切片以后 如果指定了计算的func 那么再进行一次过滤 默认可以为空

start=09:16:00

if=
if_err_msg=

on_result=

qianyan=最基础的根据实时图形做切片生成 包括: #\
轴2 #\
轴3 #\
轴5 #\
db31 #\
db51.bf3 

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx->zhou2*filter:min=3:max=30 then xx->zhou2,\
if xx->zhou3*filter:min=3:max=30 then xx->zhou3[,09:31:00],\
if xx->zhou5*filter:min=3:max=30 then xx->zhou5[,09:31:00],\
if xx*db31*filter:min=3:max=30 then xx*db31,\
if xx*db51.bf3*filter:min=3:max=30 then xx*db51.bf3,\
if xx->btw:min=2:filter:max=30 then xx->btw:min=2,\
if xx->btw:min=2:filter:min=31 and xx->btw:min=3*filter:max=30 then xx->btw:min=3

qps_all2={00:00:00,23:59:59}if xx->zhou3*filter:max=5 then xx->zhou3.hist[09:31:01,],\
if xx->zhou3*filter:min=6:max=30 then xx->zhou3[09:31:01,],\
if xx->zhou5*filter:max=5 then xx->zhou5.hist[09:31:01,],\
if xx->zhou5*filter:min=6:max=30 then xx->zhou5[09:31:01,]

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->btw_fenbu,\
xx->btw:limit=20:asc=0,\
zhushi:给出基础的前排数据,\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识


