#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=计算题材的辨识度相关的图形/子股票池数据

replace=xls+bk

time_str=09:00:00

functions=no_shape

# 设置一个比较小的过滤条件
if=
if_err_msg=

on_result=

jcals_all={00:00:00,23:59:59}

qianyan=计算题材的辨识度相关的图形/子股票池数据 用于判断题材的活跃度 以及后续用于给出买点方案设计 #\
\n\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}xx*db51,\
xx*db21,\
xx*db42,\
xx*10cm*duanxt:len=6:min=18,\
zhushi:箱体宽度大于18的全数据,\
xx*10cm*duanxt:len=6:min=16*db20,\
zhushi:箱体宽度大于16+db20的数据,\
xx*10cm*duanxt:len=6:min=9:max=16*db20,\
xx*10cm*no40001,\
xx*10cm*no30100,\
xx*10cm*no30200

qps_other_codes={00:00:00,23:59:59}xx*BK1633,\
xx*BK1717,\
xx*xls:ggzj


eva_all={00:00:00,23:59:59}