#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=以实时co2为主要图形的切片生成

replace=xls

basic_eva=tx:co2

start=09:30:01

if=xx->is_code or xx->tx:co2*filter:min=3
if_err_msg=不满足最小数据量的话 没必要计算了

on_result=

qianyan=以实时co2(tx:co2)为主要图形的切片生成

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定

# if xx->xyz*new:tx:ho3*filter:max=25 then xx->xyz*new:tx:ho3[09:44:00,],\
# zhushi:叠加new:tx:ho3

qps_all={00:00:00,23:59:59}if xx->xyz*filter:max=18 then xx->xyz,\
zhushi:最基础的co图形,\
if xx->xyz*ho:min=4.7*filter:max=25 then xx->xyz*ho:min=4.7,\
zhushi:叠加ho>4.7,\
if xx->xyz*btw:max=0*filter:max=25 then xx->xyz*btw:max=0,\
zhushi:叠加btw:max=0 即实时还在水下,\
if xx->xyz*btw:min=3.5*filter:max=25 then xx->xyz*btw:min=3.5,\
zhushi:叠加btw>3.5,\
if xx->xyz*higher*filter:max=25 then xx->xyz*higher[09:38:00,],\
zhushi:叠加higher

# new:xxx类型
qps_all2={00:00:00,23:59:59}if xx->new:mode=zao1:xyz*filter:max=25 then \
xx->new:mode=zao1:xyz[09:34:00,09:39:00],\
zhushi:new co计算,\
if xx->new:mode=zao2:xyz*filter:max=25 then \
xx->new:mode=zao2:xyz[09:39:00,09:46:00],\
zhushi:new co计算,\
if xx->new:xyz*filter:max=25 then xx->new:xyz[09:46:01,]

# 更多的图形?             TODO:

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->btw_fenbu,\
xx->if2:eva-xyz*btw:max=0,\
xx->if2:eva-xyz*btw:min=3.5,\
xx->if2:eva-xyz*higher[09:38:00,],\
xx->if2:eva-new:xyz[09:46:01,],\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识