#
#Fri Feb 14 15:36:12 CST 2025
juben=db51
title=第一个gene文件例子

replace=xls

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# qianyan
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息
# *qps: 核心组件 用于生成切片
# *on_result: 在计算获得了切片以后 如果指定了计算的func 那么再进行一次过滤 默认可以为空

time_str=09:00:00

if=xx*db51*filter:min=20
on_result=

qianyan=db51作为题材内的核心图形 因此很明显是需要出一个模板实现的#\
具体包括的内容: #\
db52 #\
db51_1 #\
trends数据的变化 #\
在市场中的地位 

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx*db52*filter:min=10 then xx*db52,\
if xx*db51_1*filter:max=45 then xx*db51_1

eva_all={00:00:00,23:59:59}if not xx*is_bk and xx*db52*filter:min=5 \
then xx*db52->stage:size:len=4,\
zhushi:db52的数据变化,\
if not xx*is_bk and xx*db51_1*filter:min=20 then xx*db51_1->stage:size:len=4,\
zhushi:db51_1的数据变化,\
if not xx*is_bk then xx*db51->trend3.days,\
zhushi:trend3的数据变化,\
print_fenge,\
db51->ban_total:limit=20,back=append_xls:xx,\
zhushi:在市场中的地位

