#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=db62详情分布实现

replace=xls

time_str=09:00:00

if=
on_result=

qianyan=本文给一下db62详情分布实现(毕竟db62)可以视作题材的超短的基本数据 #\
作用包括: #\
题材的情绪强度和变化 #\
用做买点 #\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if not xx*db62*filter:max=5 then break,\
zhushi:本分支是题材+db62<5的分支 不满足的话 终止,\
xx*db32,\
xx*db32*duoban:len=5:max_num=2,\
xx*db62*not:db32,\
xx*db51_1,\
xx*CODES_BAN,\
xx*db62

qps_db62_alot={00:00:00,23:59:59}if not xx*db62*filter:min=6 then break,\
zhushi:本分支是题材+db62>5的分支 不满足的话 终止,\
xx*db43,\
xx*db32*duoban:len=4:max_num=2,\
xx*db62*not:db32,\
xx*db31_1,\
xx*db31_1.bf2,\
xx*db62

eva_all={00:00:00,23:59:59}if not xx*simple_codes then break,\
xx*db22->size:len=4,\
xx*CODES_BAN->size:len=6,\
xx*db62->size:len=4,\
if xx*db62*filter:max=3 then break,\
if db43*filter:min=5 then db43->get_codes,back=append_xls:xx,\
if db32*duoban:len=4:max_num=2*filter:max=30 then \
db32*duoban:len=4:max_num=2->get_codes,back=append_xls:xx

