#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=ma-dis详情分布实现

replace=xls

time_str=09:00:00

if=
on_result=

qianyan=本文给一下ma-dis详情分布实现 #\
这个数据非常的有用 因为是比较细分的数据了 而且可以进而选择激进策略 还是保守策略 #\
\n\
\n\

qps_all={00:00:00,23:59:59}xx*sum_dis:min=7,\
xx*dis:min=5,\
xx*sum_dis:min=4:max=8,\
xx*dis:min=2:max=6,\
xx*sum_dis:min=-3:max=5,\
xx*dis:min=-3:max=3,\
xx*sum_dis:min=-8:max=-2,\
xx*dis:min=-6:max=-2,\
xx*sum_dis:max=-7,\
xx*dis:max=-5.5


# dis>5 alot
qps_dis5_alot={00:00:00,23:59:59}if xx*dis:min=5*filter:max=15 then break,\
zhushi:本分支是dis5 alot分支 也可以视作是激进分支,\
xx*sum_dis:min=12,\
xx*sum_dis:min=6.5:max=13,\
xx*dis:min=8,\
xx*dis:min=4.5:max=8.5

qps_dism5_alot={00:00:00,23:59:59}if xx*dis:max=-5*filter:max=15 then break,\
zhushi:本分支是dis<-5 alot分支,\
xx*dis:max=-7,\
xx*sum_dis:max=-10,\
xx*dis:min=-7.5:max=-4.5

