#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=以实时轴5(eva)为主要图形的切片生成(第一个实时eva的图形切片)

replace=xls

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# qianyan
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息
# *qps: 核心组件 用于生成切片
# *on_result: 在计算获得了切片以后 如果指定了计算的func 那么再进行一次过滤 默认可以为空

start=09:20:00

if=xx->zhou5*filter:max=30
if_err_msg=实时轴5(eva)图形的数据应该不会出现超过30 但却出现了

on_result=

qianyan=以实时轴5(eva)为主要图形的切片生成

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx->zhou5*filter:min=5:max=20 \
then xx->zhou5,\
if xx->zhou5*filter:max=4 then xx->zhou5.hist[09:33:00,],\
zhushi:如果实时的轴5数据过少 那么返回轴5.hist

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->btw_fenbu,\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识


