#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=最基础的根据实时ggzj eva结果生成切片

replace=xls

start=09:30:01

if=exist_ggzj

# 为什么要对数据做一个基础限制 因为?
if2=xx*filter:max=500
if_err_msg=

on_result=

qianyan=最基础的根据实时ggzj eva结果生成切片

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx->ggzj2*filter:max=20 then xx->ggzj2,\
if xx->ggzj2*rup2*filter:min=5 then xx->ggzj2*rup2

eva_all={00:00:00,23:59:59}xx*first->if2:upstp,\
xx->btw_fenbu,\
xx->ggzj2:asc=0


