#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=对股票池做活跃/波动分布分析/切割

replace=xls

time_str=09:00:00

if=
on_result=

qianyan=

qps_all={00:00:00,23:59:59}xx*tx:buhuoyue,\
xx*tx:huoyue_yidian,\
xx*tx:dabodong

qps_bodong_alot={00:00:00,23:59:59}if xx*tx:dabodong*filter:max=18 then break,\
zhushi:本分支是波动alot分支 如果不满足基本数量 那么不计算,\
xx*tx:dabodong*upbound:len=7:max=0.35,\
xx*tx:dabodong*upbound:len=7:min=0.65,\
xx*tx:dabodong*upbound:len=7:min=0.33:max=0.67

qps_huoyue_alot={00:00:00,23:59:59}if xx*tx:huoyue_yidian*filter:max=18 then break,\
zhushi:本分支是一点活跃alot分支 如果不满足基本数量 那么不计算,\
xx*tx:huoyue_yidian*upbound:len=7:max=0.35,\
zhushi:有点活跃 但是处于绝对的中下部 有一定风险,\
xx*tx:huoyue_yidian*upbound:len=7:min=0.65,\
zhushi:有点活跃 但是处于中部以上 如果环境ok的话 可以买入,\
xx*tx:huoyue_yidian*upbound:len=7:min=0.33:max=0.67

eva_all={00:00:00,23:59:59}
