#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=计算题材的获利盘相关的数据

replace=xls+bk

time_str=09:00:00

functions=no_shape

# 设置一个比较小的过滤条件
if=
if_err_msg=

on_result=

jcals_all={00:00:00,23:59:59}

qianyan=计算题材的获利盘相关的数据 用于判断题材的热度 以及后续用于给出买点方案设计 #\
\n\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}xx*tx:huoli_alot,\
xx*10cm*tx:huoli,\
xx*10cm*no40001,\
xx*db32,\
xx*pos_pchg:len=20:min=50,\
zhushi:从绝对的高度数据看,\
xx*db31*trd_sum:len=4:only_up0=1:min=16,\
xx*db30*10cm*trd_sum:len=5:only_up0=1:min=18


eva_all={00:00:00,23:59:59}if xx*simple_codes then \
xx*CODES_BAN->size:len=7,\
if xx*simple_codes then xx*10cm*trd:min=6->size:len=7


