#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=从attack进攻的角度 来评估股票池的开盘实时数据表现

replace=xls

start=09:15:01

if=

on_result=

qianyan=从attack进攻的角度 来评估股票池的开盘实时数据表现


qps_all={00:00:00,23:59:59}xx->up2,\
xx->outxt:len=6:out=up,\
zhushi:向上破箱体,\
xx->outxt:len=5:out=down,\
zhushi:向下破箱体,\
xx->reach_btw:len=3,\
zhushi:股价来到最近3个交易日的高点,\
xx*db31->trd_sum:len=4:only_up0=1:min=16*up0,\
xx*db30->trd_sum:len=4:only_up0=1:min=11,\
xx->jj_high:min=5*up0,\
xx->tx:attack[09:20:00,]

eva_all={00:00:00,23:59:59}xx->btw_fenbu
