#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=以实时outxt脱离箱体为主要图形的切片生成

replace=xls

basic_eva=outxt:len=6

start=09:18:0

if=xx->is_code or xx->outxt:len=6*filter:min=3
if_err_msg=不满足最小数据量的话 没必要计算了

on_result=

qianyan=以实时outxt脱离箱体为主要图形的切片生成 #\
\n\
对于脱离箱体的图形来说 比较适用于市场整体环境较好 进攻性较强的情况 \
否则 如果市场很弱 是没有多少资金愿意做这种比较激进的策略的 #\
\n\
\n\
比较适合BK1633这种有部分潜伏资金的个股(当然 也有一定的追高风险) #\
也适合做实时前排amount的投机(仅投机) 比如xx*eva:amount:limit=30*eva:xyz #\
如果数据量还是大 可以继续切割 比如: \
sh/codes/qp/gene/by_xls.sh xx*eva:high3 outxt --time_str $time_str #\
\n\
\n\
当前存在对应的思路文件: sh/tips/run_xls_template.sh xx silu_outxt_eva 

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定

# if xx->xyz*new:tx:ho3*filter:max=25 then xx->xyz*new:tx:ho3[09:44:00,],\
# zhushi:叠加new:tx:ho3

qps_all={00:00:00,23:59:59}if xx->xyz*filter:max=18 then xx->xyz,\
zhushi:最基础的outxt图形,\
if xx*xyz*filter:min=120 then break,\
zhushi:outxt的图形过大(>120) 认为无法处理这种数量级 终止计算,\
if xx->xyz*ho:min=4.7*filter:max=25 then xx->xyz*ho:min=4.7[09:30:01,],\
zhushi:叠加ho>5,\
if xx->xyz*btw:min=0:max=4*filter:max=25 then xx->xyz*btw:min=0:max=4,\
zhushi:叠加btw<4,\
if xx->xyz*btw:min=4*filter:max=25 then xx->xyz*btw:min=4,\
zhushi:叠加btw>4,\
if xx->xyz*btw:min=0:max=2.5*filter:max=25 then xx->xyz*btw:min=0:max=2.5,\
zhushi:叠加btw0~2.5,\
if xx->xyz*trd_sum:len=4:min=0:max=13*filter:max=25 then \
xx->xyz*trd_sum:len=4:min=0:max=13,\
zhushi:叠加trd-sum<13,\
if xx->xyz*trd_sum:len=4:min=3:max=9:only_up0=1*filter:max=25 then \
xx->xyz*trd_sum:len=4:min=3:max=9:only_up0=1,\
zhushi:叠加trd-sum<13,\
if xx->xyz*tx:co2*filter:max=25 then xx->xyz*tx:co2[09:30:01,]

qps_pan={09:46:00,23:59:59}if xx->xyz*new:tx:co2*filter:max=25 then \
xx->xyz*new:tx:co2

# 更多的图形?             TODO:

eva_all={00:00:00,23:59:59}xx->if2:eva-xyz,\
zhushi:基础图形数据,\
xx->xyz*btwed,\
zhushi:计算一下btw分布,\
xx->if2:eva-xyz*ho:min=4.7[09:30:01,],\
xx->if2:eva-xyz*btw:min=4,\
xx->if2:eva-xyz*btw:max=4,\
xx->if2:eva-xyz*trd_sum:len=4:min=0:max=13

