#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=@realtime_eva.gene对应的盘中时区的eva

replace=xls

# @realtime_eva.gene对应的盘中时区的gene
# TODO:

# 配置最早时间为9点42分
start=09:42:00

if=
on_result=

qianyan=给出@realtime_eva.gene对应的盘中时区的eva #\
但和@realtime_eva.gene 不同的是 本gene中的算子 都是纯eva #\
\n\
更多?

# 动态图形
qps_all={00:00:00,23:59:59}xx->tx:ishake10,\
zhushi:最基础的10min的波动,\
xx->new:tx:co2,\
xx->outside:len=10:max_xt=3.3,\
xx->outside:len=10:min_xt=3.3,\
xx->fenqi*npull:min=1.2,\
xx->npull:min=1.6,\
xx->higher:min=0.6


# 静态图形
qps_jingtai={00:00:00,23:59:59}xx->inside:min_xt=3.3*ho:min=2,\
zhushi:波动处于箱体内部+ho>2,\
xx->high5*bound40*btw:max=7,\
zhushi:对high5的数据 多一点尊敬,\
xx->inside*zhou5,\
xx->inside*zhou3,\
xx->inside*zhou2,\
xx->inside*zhou1

eva_all={00:00:00,23:59:59}if xx->is_code then \
xx->stage:eva_detail:eva_type=btw.hist
