#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=适用于大股票池的pull计算

# 对大数据量的股票池做pull计算 
# 因为数据量很大 因此pull只作为一个基础的图形 \
# 但是会叠加2次图形来进行计算 因此更准确的说 本文件更多的是挖掘pull+1的尝试
# 正常的计算流程中 本文件计算出某个图形后(其实就是yy*eva:pull*eva:zz) \
# 再进行2次计算才可以做买点

replace=xls


basic_eva=npull:mode=qt:min=1.2

start=09:44:00
enable_bkzj_df=0

# 设置一个最小数据量
if=xx*filter:min=100

qianyan=本文给出一种处理大股票池的pull方案 #\
因为是大数据量 因此从实际的角度 pull只作为一个基础的图形(而不是能直接拿去做买点) \
也就是说 需要叠加2次图形(eva)才有可能用做真正的买点 #\
\n\
从这个角度说 本文件提供的计算 其实退化成了形如fronts的eva图形组合挖掘计算 \
也就是说 本文计算出某个图形后 此时应该再把这个图形(形如yy*eva:pull*eva:zz) \
再做一次计算 #\
\n\
\n\
这里继续论述一下pull结果数据量很大时的几种应对策略: #\
叠加日内高shake #\
叠加reach_btw:len=4 #\
叠加日间辨识度图形 #\
叠加实时的ggzj_pull #\
叠加实时的前排amount #\
更多策略? #\
\n\
\n\
相关模板:

qps_all={00:00:00,23:59:59}if xx->xyz*filter:max=15 then xx->xyz,\
if xx->xyz*filter:max=15 then break,\
zhushi:计算出来的基础pull本身数据量太小 没有必要继续计算,\
if exist_t2:mode=m7 then xx->npull:mode=m7:min=1.2,\
zhushi:计算一下7min的数据,\
if xx->xyz*npull:min=2.2*filter:max=25 then xx->xyz*npull:min=2.2,\
zhushi:拉升超过2.2的数据,\
if xx->xyz*higher:min=0.5*filter:max=25 then xx->xyz*higher:min=0.5,\
zhushi:pull+higher,\
if xx->xyz*up2*filter:max=25 then xx->xyz*up2,\
zhushi:pull+up2 up2的数据的数量 一定程度上是能够代表强度的,\
if xx->xyz*upbound:min=0.8*shake:min=2.5*filter:max=25 then \
xx->xyz*upbound:min=0.8*shake:min=2.5,\
zhushi:实时股价处于日内箱体上部,\
if xx->xyz*shake:min=5.2*upbound:min=0.3*filter:max=25 then \
if xx->xyz*shake:min=5.2*upbound:min=0.3,\
zhushi:宽箱体+bound>0.3的拉升,\
if xx->xyz*up2*reach_btw:len=4*filter:max=25 then \
xx->xyz*up2*reach_btw:len=4,\
zhushi:股价拉升到4日btw新高,\
if xx->xyz*reach_shake:len=4*bound:min=0.3*filter:max=25 then \
xx->xyz*reach_shake:len=4*bound:min=0.3,\
zhushi:日内shake超过过去几日

# 看起来上面的pull挺多了 但能不能应对实盘的波动 还是犹未可知... TODO:

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->btw_fenbu,\
xx->npulled.hist:size=4,\
xx->stage:zijin.hist,\
xx->trend3.hist,\
print_fenge,\
print:开始计算一下各种eva,\
xx->if2:eva-xyz*npull:min=2.2,\
xx->if2:eva-xyz*higher:min=0.5,\
xx->if2:eva-xyz*up2,\
xx->if2:eva-xyz*upbound:min=0.8*shake:min=2.5,\
xx->if2:eva-xyz*shake:min=5.2*upbound:min=0.3,\
xx->if2:eva-xyz*up2*reach_btw:len=4,\
xx->if2:eva-xyz*reach_shake:len=4*bound:min=0.3


