#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=以实时pull为主要图形的切片生成

replace=xls

# update 2026-09-18: 第一次设计出basic_eva
basic_eva=npull:min=1.2

# 当前切片生成包括以下核心kv
# title
# if: 条件语句
# qianyan
# tips: 用于打印一些静态信息
# eva: 用于计算一些信息 主要用于打印一些动态信息
# *qps: 核心组件 用于生成切片
# *on_result: 在计算获得了切片以后 如果指定了计算的func 那么再进行一次过滤 默认可以为空

start=09:33:00

if=xx->pull_or_higher*filter:min=5
if_err_msg=不满足最小数据量的话 没必要计算了

on_result=

qianyan=以实时pull为主要图形的切片生成

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx->pull_or_higher*filter:min=5:max=20 \
then xx->pull_or_higher,\
if xx->pull_or_higher*filter:max=4 then break,\
zhushi:pull-or-higher的数据量太小了 不如直接返回 终止计算,\
if xx->pull_or_higher*filter:min=50 then break,\
zhushi:pull-or-higher的数据量太大了 超过了50 处理不了 建议切割成更小的股票池,\
if xx->xyz*up2*filter:max=20 then xx->xyz*up2,\
zhushi:最基础的叠加up2,\
if xx->xyz*btw:max=0.5*filter:max=20 then xx->xyz*btw:max=0.5,\
zhushi:水下拉升的数据,\
if xx->xyz*lpchg:max=-3*filter:max=25 then xx->xyz*lpchg:max=-3,\
zhushi:水下拉升2,\
if xx->xyz*trd_minus:min=5*filter:max=25 then xx->xyz*trd_minus:min=5,\
zhushi:股价走出了反转,\
if xx->xyz*upbound:min=0.7*up0*filter:max=25 then xx->xyz*upbound:min=0.7*up0,\
zhushi:股价处于实时的顶部,\
if xx->xyz*upbound:min=0.5*filter:max=25 then xx->xyz*upbound:min=0.5,\
zhushi:股价至少处于中部的数据

# 看起来上面给出的pull图形很多了 其实还远远不够             TODO:

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->if2:eva-pull_or_higher:min=1.8[,09:44:00],\
xx->if2:eva-pull_or_higher:min=1.4[09:44:01,],\
zhushi:最基础的pull_or_higher数量,\
xx->btw_fenbu,\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识