#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=redu-no(被编号的)图形

replace=xls

time_str=09:00:00

functions=no_shape

# 设置一个比较小的过滤条件
if=xx*no40100*filter:min=15
if_err_msg=基础的热度图形no40100的数据量没有满足最小的基础

on_result=

# 尝试读取statement文件
jcals_all={00:00:00,23:59:59}get_statement_msg_if("strategy.no.redu")

qianyan=redu图形生成策略(其实是@xx_analyze_codes_shape_redu_no\
.tips.properties对应的策略)

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx*no40100*filter:max=30 then xx*no40100,\
zhushi:如果2个周期的汇总图形数据量偏小 那么直接返回,\
if xx*no40100*filter:min=31 then xx*no40101,\
zhushi:2个周期的热度+高度股票池,\
if xx*no40100*filter:min=31 then xx*no40102,\
zhushi:2个周期的热度+箱体宽度股票池,\
if xx*no40100*filter:min=31 then xx*no40103,\
zhushi:2个周期的热度+高股性股票池,\
if xx*no40121*filter:min=5:max=40 then xx*no40121,\
zhushi:3个周期的热度+高度股票池,\
if xx*no40701*filter:min=5:max=40 then xx*no40701,\
zhushi:热度+高度为主的股票池



eva_all={00:00:00,23:59:59}if not xx*is_bk and xx*simple_code \
then xx*CODES_BAN->size:len=6,\
if not xx*is_bk and xx*simple_code then xx->trend3.days6,\
zhushi:对数据有一个基本的认识


