#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=对题材/股票池的热度数据 做一个深度计算

replace=xls+bk

time_str=09:00:00

functions=no_shape

# 设置一个比较小的过滤条件
if=
if_err_msg=

on_result=

# 尝试读取statement文件
# get_statement_msg_if("strategy.no.redu")
jcals_all={00:00:00,23:59:59}

qianyan=对题材/股票池的热度数据 做一个深度计算 #\
适合用做盘前的基础计算 #\
\n\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}xx*db32->size:len=1,\
zhushi:给出db32的基础数据 如果数据很大 那么可能要走其它实现,\
if xx*db32*filter:min=10 then break,\
zhushi:db32的数据过大 终止计算,\
xx*db31_1->size:len=1,\
xx*10cm*no40001->size:len=1,\
zhushi:5日长度的热度图形,\
xx*10cm*no40100->size:len=1,\
zhushi:10日长度的热度图形,\
xx*max_pchg:len=4:min_pchg=22->size:len=1,\
zhushi:从4日获利盘的角度查看数据,\
xx*10cm*max_pchg:len=4:min_pchg=13->size:len=1,\
xx*10cm*trd_sum:len=4:only_up0=1:min=19->size:len=1,\
zhushi:从4日trd-sum的角度看数据,\
xx*pos_pchg:len=20:min=50->size:len=1,\
zhushi:从绝对的高度数据看


eva_all={00:00:00,23:59:59}xx->stage:zijin_sum:can_has_empty=1:len=4,\
xx->stage:pos_sum:len=17,\
if not xx*is_bk and xx*simple_code \
then xx*CODES_BAN->size:len=6,\
if not xx*is_bk and xx*simple_code then xx*10cm*trd:min=6->size:len=8,\
if not xx*is_bk and xx*simple_code then xx->trend3.days6,\
zhushi:对数据有一个基本的认识

