#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出一些实用的realtime eva的计算结果

replace=xls

start=09:15:01

if=

on_result=

qianyan=给出一些实用的realtime eva的计算结果 #\
包括: #\
up2 #\
co2 #\
attack #\
\n\
\n\
\n\
[继续计算]: #\
如果attack数据很好: TODO: #\
如果outxt的数据很好: TODO: #\
\n\
更多?

qps_all={00:00:00,23:59:59}xx->up2,\
xx->tx:co2[09:30:01,],\
xx->tx:attack[09:20:00,],\
xx->outxt:len=6:out=up,\
zhushi:向上破箱体,\
xx->outxt:len=5:out=down,\
zhushi:向下破箱体,\
xx->shake:min=5*ho:min=3.5[09:30:01,09:45:00],\
zhushi:早盘上冲的数据

# 计算一些日间图形的分支
qps_has_eva_branch={00:00:00,23:59:59}if not xx->has_codes_str:eva then break,\
zhushi:如果不是包含eva的分支 那么无视本分支,\
xx*duanxt:len=6:min=21,\
zhushi:宽箱体,\
xx*duanxt:len=6:min=12,\
zhushi:宽箱体2号,\
xx*trd_sum:len=5:min=8,\
zhushi:过去5日总体走势良好

# 更多的分支? 比如 数据量不大的时候 计算reach-btw,reach-shake    TODO:
qps_small_codes={00:00:00,23:59:59}if xx*filter:min=101 then break,\
zhushi:如果不是小数据量股票池(<100) 那么走不到本分支,\
xx->jj_rzq:min=2[09:22:00,09:35:00],\
xx->jj_xt:min=3.5[09:22:00,09:35:00],\
xx->reach_btw:len=3,\
xx->reach_shake:min=0.55[09:30:01,09:38:00],\
xx->reach_shake:min=0.7[09:38:01,],\
xx->trd_minus:min=4.5

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->btw_fenbu,\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识

