#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=股票池本身已经有确定性的前提下 再加上日内图形+日间图形 上双重保险

# 看了20260818的数据 意识到sure eva其实也和股票池本身的图形强相关...
# open /Users/wuxian/Desktop/stk_daily/2026-08-18//xls_report//110048/xls:fenshi*eva.atzao2:ggzj:limit=40/EVA-btw/*

replace=xls

start=09:20:00

# 这里不对"股票池本身已经有确定性的前提下" 做验证
if=xx*filter:max=150
on_result=

qianyan=股票池本身已经有确定性的前提下 再加上日内图形+日间图形 \
上双重保险的图形切片生成 #\
\n\
如果xx*shizhi:min=500+reach-btw的数据很多 那么考虑直接走: \
sh/eva/cli.sh shizhi:min=500 ggzj:limit=40*rup2*rank #\
\n\
\n\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if exist_ggzj then xx->ggzj:limit=10,\
zhushi:直接给出ggzj API的切片,\
xx*shizhi:min=500->wrap:reach_btw,\
zhushi:市值>500+reach-btw 若数据很多 可以直接走市值500+ggzj+rup2的买点,\
xx->wrap:trd_minus:min=4*rup2,\
zhushi:股价相比前日走出反转,\
xx->newhigh:len=7,\
zhushi:股价走出新高,\
xx->jj_rzq:min=2.8[,09:35:00],\
zhushi:既然个股已经有确定了 那么叠加竞价弱转强也不错,\
xx->wrap:ma_dis:min=4*btw:min=1,\
zhushi:ma_dis数据很好


eva_all={00:00:00,23:59:59}xx->stage:btw_fenbu,\
xx->btw:limit=20:asc=0,\
xx*no30100->btw:asc=0,\
zhushi:基础的30100 5日基础辨识度箱体图形的数据,\
xx*no40100->btw:asc=0,\
zhushi:基础的10个交易日周期的热度图形的数据


