#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出某个股票池的基于股票池特征的2次计算

replace=xls

time_str=09:00:00

if=
on_result=

qianyan=给出某个股票池的基于股票池特征的2次计算 #\
比如一个形如abc*eva:xyz的股票池 本gene用于判断其中是否存在特殊股票池 #\
实际实盘也可以用于计算某只个股的属性 #\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}xx*db62,\
xx*db81,\
if new:BK1633*filter:min=10 and not xx->has_codes_str:BK1633 then xx*BK1633,\
xx*xls:jijin,\
xx*BK0821,\
xx*BK0535,\
xx*xls:zhz500,\
xx*xls:zhz1000,\
xx*xls:zhz2000,\
xx*shizhi100,\
xx*shizhi200,\
xx*shizhi300


eva_all={00:00:00,23:59:59}

