#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出ggzj类型股票池(比如xls:iggzj)的特化切片池图形

# 参考@xx_sub_BK1633.gene.properties

# 定位: 用于给出形如 abc*ggzj*eva:xyz 这种组合股票池的基于ggzj特征的子切片组合

replace=xls

time_str=09:00:00

if=xx->has_codes_str:ggzj
if_err_msg=输入的股票池不包含ggzj字符串

if2=xx*filter:min=5

qianyan=给出ggzj类型股票池(比如xls:iggzj)的特化切片池图形 #\
\n\
比较适用于震荡行情 或者偏弱的行情

qps_all={00:00:00,23:59:59}xx*stocks:zhuli,\
zhushi:叠加主力图形,\
xx*stocks:chaoduan,\
zhushi:叠加超短票,\
xx*db31,\
xx*shizhi100*db30,\
xx*shizhi200*db30,\
xx*shizhi300*db30,\
xx*shizhi:min=900,\
xx*shizhi:max=140,\
if xx*shizhi:max=140*filter:min=15 then xx*shizhi:max=140*eva:up5,\
zhushi:继续计算偏小市值 走出up5的数据,\
xx*eva:tx:outxt*db30,\
if xx*eva:tx:outxt*db30*filter:min=20 then xx*eva:tx:outxt*db30*shizhi:max=140,\
zhushi:继续计算outxt+市值<140的数据,\
zhushi:叠加outxt-eva,\
xx*BK1633*db30,\
zhushi:叠加BK1633 前日高震幅,\
xx*no40001*db30,\
zhushi:叠加5日热度图形

# 再做一下逻辑切割
qps_all2={00:00:00,23:59:59}xx*split_pool

eva_all={00:00:00,23:59:59}

