#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=市场的确定性不足的时候的切片生成策略(思路是通过加强日内图形+ggzj API来提供确定性)

replace=xls

start=09:20:00

# 稍微放宽数据量 -> 因为市场确定性不足的时候 买点的数量会变小 此时应该放宽数据量限制
if=xx*filter:max=250
on_result=

qianyan=市场的确定性不足的时候的切片生成策略(思路是通过加强日内图形+\
ggzj API来提供确定性) #\
\n\
\n\
\n\
\n\

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if exist_ggzj then xx->ggzj*rup3[09:30:01,],\
zhushi:通过ggzj API来提供确定性,\
xx*shizhi:min=300->wrap:reach_btw,\
zhushi:市值>500+reach-btw 若数据很多 可以直接走市值500+ggzj+rup2的买点,\
xx->wrap:trd_minus:min=4*rup2,\
zhushi:股价相比前日走出反转,\
xx->newhigh:len=7,\
zhushi:股价走出新高

eva_all={00:00:00,23:59:59}xx->stage:btw_fenbu,\
xx->btw:limit=20:asc=0


