#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=对实时up2的数据做深度分析 然后做切片生成

replace=xls

basic_eva=up2

start=09:15:00

if=xx->up2*filter:min=5
if_err_msg=不满足最小数据量的话 没必要计算了

on_result=

qianyan=对实时up2的数据做深度分析 然后做切片生成

# 核心组件
# 1,直接指定
# 2,通过一个if then条件语句判定
qps_all={00:00:00,23:59:59}if xx->xyz*filter:min=80 then break,\
zhushi:up2的数据量太大了 超过了80 处理不了 建议切割成更小的股票池,\
if xx->up4*filter:max=20 then xx->up4,\
zhushi:btw>4的数据 显然是更强的维度,\
if xx->xyz*shake:min=4.8*filter:max=20 then xx->xyz*shake:min=4.8,\
zhushi:up2叠加shake>5,\
if xx->btw:min=1.5:max=4*rup:min=3.5*filter:max=20 then \
xx->btw:min=1.5:max=4*rup:min=3.5,\
zhushi:股价处于1.5~4 但是rup>3.5,\
if xx->btw:min=1.5:max=4*upbound:min=0.5*filter:max=20 then \
xx->btw:min=1.5:max=4*upbound:min=0.5,\
zhushi:股价处于1.5~4 且股价处于中部以上,\
if xx->xyz*btw:max=4.8*reach_btw:len=4*filter:max=25 then \
xx->xyz*btw:max=4.8*reach_btw:len=4,\
zhushi:股价来到4日btw新高,\
if xx->xyz*newhigh:len=8*filter:max=25 then xx->xyz*newhigh:len=8,\
zhushi:叠加newhigh

eva_all={00:00:00,23:59:59}xx->if2:upstp,\
xx->if2:eva-up2,\
zhushi:最基础的数量,\
xx->btw_fenbu,\
xx->trend3.hist[09:28:00,],\
zhushi:对数据有一个基本的认识