#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出早盘时区最实用的eva的计算结果

replace=xls

start_at=09:15:01
end_at=09:50:00


if=

on_result=

qianyan=

qps_all={00:00:00,23:59:59}xx->up2,\
xx->up3,\
xx->tx:co2[09:30:01,],\
xx->opp:min=3[09:30:01,],\
xx->opp:min=2*bound50[09:30:01,],\
xx->shake:min=4*ho:min=3[09:30:01,],\
xx->bs:good,\
xx->outxt:len=6:out=up,\
xx->trd_sum:len=3:min=7*trd:min=-2,\
xx->sum_dis:min=5*trd:min=-2

# dis相关的分支
qps_dis_rela={00:00:00,23:59:59}xx->minus_dis:min=3.5,\
if xx->minus_dis:min=3.5*filter:min=20 then xx->minus_dis:min=3.5:max_dis=5,\
zhushi:如果数据量偏大 那么限制一下dis,\
xx->sum_dis:min=4.5,\
if xx->sum_dis:min=4.5*filter:min=20 then xx->sum_dis:min=4.5:max=8.5,\
xx->trd:min=3*sum_dis:max=3,\
zhushi:日内走的好 但是当前的sum dis代表的位置是不高的 是偏保守的策略,\
xx->trd_sum:min=4.5*sum_dis:max=3,\
zhushi:连续2日走的好 但是当前的sum dis代表的位置是不高的 是偏保守的策略

# update: 发现sum-dis这个指标 其实比我想的更重要 准度更高

# 更多的算子??

eva_all=xx->trend3.hist,\
xx->btw_fenbu
