#
#Fri Feb 14 15:36:12 CST 2025
juben=
title=给出早盘时区最实用的eva的计算结果

replace=xls

start_at=09:30:01
end_at=09:50:00


if=

on_result=

qianyan=

qps_all={00:00:00,23:59:59}xx->up2,\
xx->up3,\
xx->tx:co2,\
xx->opp:min=3,\
xx->opp:min=2*bound50,\
xx->shake:min=4*ho:min=3,\
xx->bs:good,\
xx->outxt:len=6:out=up,\
xx->trd_sum:len=3:min=7*trd:min=-2,\
xx->sum_dis:min=5*trd:min=-2

# 更多的算子??

eva_all=
